remove @NS_PROGRAM_INSERT_CMBD_STAGE/;
COPY INTO @NS_PROGRAM_INSERT_CMBD_STAGE/UH_AH_P_Program_Insert_NS.csv FROM 
(select ALTRUISTA_ID,LOB,BENEFIT_PLAN,PROGRAM_NAME,START_DATE,END_DATE,PROGRAM_REFERRAL_SOURCE,
PROGRAM_STATUS,PROGRAM_STATUS_DESC from NORTHSTAR.NS_PROGRAM_INSERT_CMBD) 
file_format = (TYPE = CSV compression = none
              FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' 
              FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE') HEADER = TRUE SINGLE=TRUE OVERWRITE=TRUE;
get @NS_PROGRAM_INSERT_CMBD_STAGE/ file:///obhdp/NorthStar;⁩
