CREATE TASK IF NOT EXISTS ETL.CMPCT_IMDM_EDW_INDV_KEY_LD
  WAREHOUSE = ECT_STG_OBH_DP_LOAD_WH
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  USER_TASK_TIMEOUT_MS = 36000000
  COMMENT = 'Task to Trigger COMPACT IMDM_EDW_INDV_KEY table load'
  AFTER ETL.ETL_IMDM_INDV_CHNG_LD
AS
  call ETL.DBA_MERGE_IMDM_EDW_INDV_KEY('ETL.IMDM_INDV_CHNG', 'COMPACT.IMDM_EDW_INDV_KEY', 'Historical Load');



ALTER TASK ETL.CMPCT_IMDM_EDW_INDV_KEY_LD RESUME ;