create or replace procedure OBH_DP_CLM_TRANS_SRVC_LN_IMDM_ID_UPDT()
  returns varchar
  language sql
  as
  $$
  
  declare
  unique_id varchar;
  load_strt_ts timestamp;
  load_end_ts timestamp;
  updt_cnt number;
  result varchar;
  
  begin
  
  SELECT UUID_STRING() into unique_id;
  SELECT CURRENT_TIMESTAMP() INTO load_strt_ts ;
  
  CREATE or REPLACE TEMPORARY TABLE IMDMID_NOMATCH as 
  SELECT distinct CLM_TRANS_SYS_ID,IMDM_ID, SRC_MBR_ID 
  FROM OBH_DP.CLM_TRANS_SRVC_LN WHERE IMDM_ID IS NULL AND SRC_MBR_ID <> '-1' ;
  
  CREATE or REPLACE TEMPORARY TABLE IMDMID_NOMATCH_MBR AS 
  SELECT CLM.CLM_TRANS_SYS_ID,CLM.IMDM_ID, CLM.SRC_MBR_ID, MBR.MEMB_DIM_ID,MBR.MEMB_FIRST_NAME, MBR.MEMB_LAST_NAME, MBR.DOB,
  MBR.SOCIAL_SEC_NO,MBR.MEDICARE_NO, MBR.MEDICAID_NO FROM 
  IMDMID_NOMATCH CLM INNER JOIN 
  (SELECT DISTINCT MEMB_DIM_ID,MEMB_FIRST_NAME,MEMB_LAST_NAME,DOB,SOCIAL_SEC_NO,MEDICARE_NO,MEDICAID_NO 
   from COMPACT.DIM_MEMBER ) MBR 
  ON CLM.src_mbr_id=MBR.MEMB_DIM_ID ;
  
  CREATE or REPLACE TEMPORARY TABLE IMDMID_GEN AS 
  SELECT DISTINCT A.CLM_TRANS_SYS_ID , A.SRC_MBR_ID, C.IMDM_ID FROM 
  IMDMID_NOMATCH_MBR A,COMPACT.IMDM_EDW_INDV_KEY B,  compact.IMDM_INDV C WHERE B.INDV_SRC_ID = C.IMDM_ID AND TO_CHAR(B.indv_key_val) =    TO_CHAR(A.MEMB_DIM_ID) 
  AND (A.MEMB_FIRST_NAME) = UPPER(C.FST_NM) AND A.DOB = C.BTH_DT AND (A.MEDICARE_NO = C.MDCRID OR A.MEDICAID_NO = C.MDCDID) ;
  
  UPDATE IMDMID_NOMATCH X SET X.IMDM_ID = Y.IMDM_ID FROM (SELECT * FROM IMDMID_GEN) Y WHERE 
  X.CLM_TRANS_SYS_ID = Y.CLM_TRANS_SYS_ID AND X.SRC_MBR_ID = Y.SRC_MBR_ID ;
  
  CREATE or REPLACE TEMPORARY TABLE IMDMID_NOMATCH_1 as 
  SELECT distinct CLM_TRANS_SYS_ID,IMDM_ID, SRC_MBR_ID 
  FROM IMDMID_NOMATCH WHERE IMDM_ID IS NULL ;
  
  CREATE or REPLACE TEMPORARY TABLE IMDMID_NOMATCH_MBR_1 AS 
  SELECT CLM.CLM_TRANS_SYS_ID,CLM.IMDM_ID, CLM.SRC_MBR_ID, MBR.MEMB_DIM_ID,MBR.MEMB_FIRST_NAME, MBR.MEMB_LAST_NAME, MBR.DOB,
  MBR.SOCIAL_SEC_NO,MBR.MEDICARE_NO, MBR.MEDICAID_NO FROM 
  IMDMID_NOMATCH_1 CLM INNER JOIN 
  (SELECT DISTINCT MEMB_DIM_ID,MEMB_FIRST_NAME,MEMB_LAST_NAME,DOB,SOCIAL_SEC_NO,MEDICARE_NO,MEDICAID_NO 
   from COMPACT.DIM_MEMBER WHERE SOCIAL_SEC_NO IS NOT NULL) MBR 
  ON CLM.src_mbr_id=MBR.MEMB_DIM_ID ;
  
  CREATE or REPLACE TEMPORARY TABLE IMDMID_GEN_1 AS 
  SELECT DISTINCT A.CLM_TRANS_SYS_ID , A.SRC_MBR_ID, C.IMDM_ID FROM 
  IMDMID_NOMATCH_MBR_1 A,COMPACT.IMDM_EDW_INDV_KEY B,  compact.IMDM_INDV C WHERE B.INDV_SRC_ID = C.IMDM_ID AND TO_CHAR(B.indv_key_val) =    TO_CHAR(A.MEMB_DIM_ID) 
  AND A.SOCIAL_SEC_NO = C.SSN AND A.DOB = C.BTH_DT AND (A.MEDICARE_NO = C.MDCRID OR A.MEDICAID_NO = C.MDCDID) ;
  
  UPDATE IMDMID_NOMATCH X SET X.IMDM_ID = Y.IMDM_ID FROM (SELECT * FROM IMDMID_GEN_1) Y WHERE 
  X.CLM_TRANS_SYS_ID = Y.CLM_TRANS_SYS_ID AND X.SRC_MBR_ID = Y.SRC_MBR_ID ;
  
  UPDATE OBH_DP.CLM_TRANS_SRVC_LN X SET SF_PROCESS_ID = 'IMDM_ID_UPDT' , 
  X.IMDM_ID = Y.IMDM_ID FROM (SELECT * FROM IMDMID_NOMATCH) Y WHERE 
  X.CLM_TRANS_SYS_ID = Y.CLM_TRANS_SYS_ID AND X.SRC_MBR_ID = Y.SRC_MBR_ID ;
  
  SELECT $1+$2 into updt_cnt FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
  
  SELECT CURRENT_TIMESTAMP() INTO load_end_ts ;
  
  INSERT INTO ETL.DBA_PROCESS_LOG VALUES (:unique_id,'OBH_DP.CLM_TRANS_SRVC_LN','OBH_DP.CLM_TRANS_SRVC_LN','IMDM_ID_UPDATE',0,0,:load_strt_ts,:load_end_ts,CURRENT_TIMESTAMP,0,:updt_cnt,0) ;
   
  result:='OBH_DP_CLM_TRANS_SRVC_LN_IMDM_ID_UPDT completed successfully';
  return result;
  
  exception
    when statement_error then
      raise;
    when other then
      raise;
 
   end;
    
   $$
   ;
  
