create or replace task FOUNDATION.OCM_DIM_CLM_TRANS_HIS_TASK
warehouse=ECT_DEV_OBH_DP_LOAD_WH
COMMENT='Historical Loads the data to intermediate OCM_DIM_CLM_TRANS FOUNDATION table'
after ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_FCT_CLM_TRANS_HIS_TASK
AS CALL FOUNDATION.OCM_DIM_CLM_TRANS_HIS_LOAD_PROC();

create or replace task FOUNDATION.OCM_FCT_CLM_TRANS_HIS_TASK
warehouse=ECT_DEV_OBH_DP_LOAD_WH
COMMENT='Historical Loads the data to intermediate OCM_FCT_CLM_TRANS FOUNDATION table'
schedule='USING CRON 0 0 * * FRI UTC'
AS CALL FOUNDATION.OCM_FCT_CLM_TRANS_HIS_LOAD_PROC();

create or replace task FOUNDATION.OCM_CLM_TRANS_SRVC_LN_HIS_TASK
warehouse=ECT_DEV_OBH_DP_LOAD_WH
COMMENT='Historical Loads the data to final OCM_CLM_TRANS_SRVC_LN FOUNDATION table'
after ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_DIM_CLM_TRANS_HIS_TASK
AS CALL FOUNDATION.OCM_CLM_TRANS_SRVC_LN_HIS_LOAD_PROC();

create or replace task FOUNDATION.OCM_DIM_CLM_TRANS_INC_TASK
warehouse=ECT_DEV_OBH_DP_LOAD_WH
COMMENT='Incremental Loads the data to intermediate OCM_DIM_CLM_TRANS FOUNDATION table'
after ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_FCT_CLM_TRANS_INC_TASK
AS CALL FOUNDATION.OCM_DIM_CLM_TRANS_INC_LOAD_PROC();

create or replace task FOUNDATION.OCM_FCT_CLM_TRANS_INC_TASK
warehouse=ECT_DEV_OBH_DP_LOAD_WH
COMMENT='Incremental Loads the data to intermediate OCM_FCT_CLM_TRANS FOUNDATION table'
schedule='USING CRON 0 */8 * * * UTC'
AS CALL FOUNDATION.OCM_FCT_CLM_TRANS_INC_LOAD_PROC();

create or replace task FOUNDATION.OCM_CLM_TRANS_SRVC_LN_INC_TASK
warehouse=ECT_DEV_OBH_DP_LOAD_WH
COMMENT='Incremental Loads the data to final OCM_CLM_TRANS_SRVC_LN FOUNDATION table'
after ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_DIM_CLM_TRANS_INC_TASK
AS CALL FOUNDATION.OCM_CLM_TRANS_SRVC_LN_INC_LOAD_PROC();

ALTER TASK FOUNDATION.OCM_DIM_CLM_TRANS_HIS_TASK RESUME;
ALTER TASK FOUNDATION.OCM_FCT_CLM_TRANS_HIS_TASK RESUME;
ALTER TASK FOUNDATION.OCM_CLM_TRANS_SRVC_LN_HIS_TASK RESUME;

ALTER TASK FOUNDATION.OCM_DIM_CLM_TRANS_INC_TASK RESUME;
ALTER TASK FOUNDATION.OCM_FCT_CLM_TRANS_INC_TASK RESUME;
ALTER TASK FOUNDATION.OCM_CLM_TRANS_SRVC_LN_INC_TASK RESUME;