CREATE TABLE IF NOT EXISTS COMPACT.DIM_REASON_CODE
    (
        REASON_DIM_ID INTEGER NOT NULL,
        REASON_CODE VARCHAR(12) NOT NULL,
        REASON_CODE_TYPE VARCHAR(2) NOT NULL,
        COMPANY_DIM_ID INTEGER NOT NULL,
        REASON_DESC VARCHAR(60),
        REASON_STANDARD_FLAG VARCHAR(1),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        REASON_GROUP_DIM_ID INTEGER DEFAULT -1 NOT NULL,
        CONVERTED_FROM_DIM_ID INTEGER DEFAULT -1 NOT NULL,
        REASON_CODE_TYPE_DIM_ID INTEGER DEFAULT -1 NOT NULL,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_RSN_CD PRIMARY KEY (REASON_DIM_ID),
        CONSTRAINT FK_DIM_RSN_CD_GRP FOREIGN KEY (REASON_GROUP_DIM_ID) REFERENCES COMPACT.DIM_REASON_CODE_GROUP(REASON_GROUP_DIM_ID),
        CONSTRAINT FK_DIM_RSN_CD_CMPNY FOREIGN KEY (COMPANY_DIM_ID) REFERENCES COMPACT.DIM_COMPANY(COMPANY_DIM_ID),
        CONSTRAINT UK_F_DIM_RSN_CD UNIQUE (REASON_CODE, REASON_CODE_TYPE,COMPANY_DIM_ID, CONVERTED_FROM_DIM_ID)
    );
