CREATE TABLE IF NOT EXISTS COMPACT.TB_PRV_PROV_ALT (
	PROV_ALT_SYS_ID NUMBER(10) NOT NULL,
	PRAC_SYS_ID NUMBER(10) NOT NULL,
	PROV_SYS_ID NUMBER(10) NOT NULL,
	PROV_ALT_ID varchar(20) NULL,
	SRC_REC_CRT_DTTM DATETIME NULL,
	SRC_REC_CRT_USER_ID VARCHAR(15) NULL,
	SRC_REC_UPDT_DTTM DATETIME NULL,
	SRC_REC_UPDT_USER_ID VARCHAR(15) NULL,
	REC_CRT_DTTM DATETIME NOT NULL,
	REC_UPDT_DTTM DATETIME NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
	BTCH_LOAD_DT DATETIME NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_TB_PRV_PROV_ALT_SYS_ID PRIMARY KEY (PROV_ALT_SYS_ID)
);