CREATE TABLE IF NOT EXISTS COMPACT.TB_AMA_POS (
	POS_SYS_ID VARCHAR(10) NOT NULL,
	POS_ID VARCHAR(2) NULL,
	POS_DESC VARCHAR(50) NULL,
	POS_DERIV_CATGY VARCHAR(64) NULL,
	SRC_REC_USER_ID VARCHAR(15) NULL,
	REC_DEL_FLG VARCHAR(1) NULL,
	REC_CRT_DTTM DATETIME NOT NULL,
	REC_UPD_DTTM DATETIME NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
	BTCH_LOAD_DT DATE NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_TB_AMA_POS_POS_SYS PRIMARY KEY (POS_SYS_ID)
);