CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_FLAG_INDICATOR (
    FLAG_DIM_ID NUMBER NOT NULL,
    FLAG_IND VARCHAR(3) NOT NULL,
    FLAG_IND_DESCRIPTION VARCHAR(30),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    FLAG_TYPE VARCHAR(50),
    CONSTRAINT PK_FLAG_DIM_ID PRIMARY KEY (FLAG_DIM_ID),
    CONSTRAINT UK_FLAG_IND_FLAG_TYP UNIQUE (FLAG_IND, FLAG_TYPE)
);
COMMENT ON COLUMN COMPACT.DIM_RX_FLAG_INDICATOR.FLAG_DIM_ID IS 'This column is auto generated and it gets incremented for every value being added and mainly used in fact tables';
COMMENT ON COLUMN COMPACT.DIM_RX_FLAG_INDICATOR.FLAG_IND IS 'This column represents  flag indicator for ex lets say for benefit_max_flag as below BLANK = NOT USED and also for b = batch ,m = manual ,t = electronic';
COMMENT ON COLUMN COMPACT.DIM_RX_FLAG_INDICATOR.FLAG_IND_DESCRIPTION IS 'This column represents the description for FLAG_IND field for ex:m = manual';
COMMENT ON COLUMN COMPACT.DIM_RX_FLAG_INDICATOR.DW_INSERT_DATETIME IS 'This table represents the date value as when the record got updated';
