CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROV_AGREEMENT (
	PROV_AGREEMENT_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_PROV_AGREEMENT_DIM_ID PRIMARY KEY,
	PROV_AGREEMENT_ID VARCHAR(20),
	EFFECTIVE_DATE DATE,
	TERM_DATE DATE,
	AGREEMENT_DESC VARCHAR(70),
	AGREEMENT_TYPE VARCHAR(4),
	DW_INSERT_DATETIME DATE NOT NULL,
	DW_UPDATE_DATETIME DATE NOT NULL,
	RECORD_STATUS_DIM_ID NUMBER NOT NULL DEFAULT -1,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT UK_F_DIM_PROV_AGREEMENT_AGREEMENT_ID_EFFECTIVE_DATE UNIQUE (PROV_AGREEMENT_ID,EFFECTIVE_DATE)
);
