CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_OTHER_COVERAGE_CODE (
    OTHER_COVERAGE_CODE_DIM_ID NUMBER NOT NULL,
    OTHER_COVERAGE_CODE VARCHAR(3) NOT NULL,
    OTHER_COVERAGE_CODE_DESC VARCHAR(60),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT PK_OTHER_COVERAGE_CODE_DIM_ID PRIMARY KEY (OTHER_COVERAGE_CODE_DIM_ID),
    CONSTRAINT UK_OTHER_COVERAGE_CODE UNIQUE (OTHER_COVERAGE_CODE)
);
COMMENT ON TABLE COMPACT.DIM_RX_OTHER_COVERAGE_CODE IS 'This table stores attributes that describe the pharmacy other carrier coverage.';
COMMENT ON COLUMN COMPACT.DIM_RX_OTHER_COVERAGE_CODE.OTHER_COVERAGE_CODE_DIM_ID IS 'Represents the link to the DIM_RX_OTHER_COVERAGE_CODE table describing the pharmacy other carrier coverage. i.e. 1 = 01 no other coverage identified or 8 = 08 claim is billing for copay. ';
COMMENT ON COLUMN COMPACT.DIM_RX_OTHER_COVERAGE_CODE.OTHER_COVERAGE_CODE IS 'Code that represents the pharmacy other carrier coverage. i.e. 1 = 01 no other coverage identified or 8 = 08 claim is billing for copay. ';
COMMENT ON COLUMN COMPACT.DIM_RX_OTHER_COVERAGE_CODE.OTHER_COVERAGE_CODE_DESC IS 'Describes the pharmacy other carrier coverage. i.e. 1 = 01 no other coverage identified or 8 = 08 claim is billing for copay. ';
COMMENT ON COLUMN COMPACT.DIM_RX_OTHER_COVERAGE_CODE.DW_INSERT_DATETIME IS 'Date the record was added to the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_RX_OTHER_COVERAGE_CODE.DW_UPDATE_DATETIME IS 'Date the record was updated in the Data Warehouse.';
