CREATE TABLE IF NOT EXISTS COMPACT.DIM_BILL_TYPE_CAT_LVL_2 (
BILL_TYPE_CAT_LVL_2_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_BILL_TYPE_CAT_LVL_2_DIM_ID PRIMARY KEY,
BILL_TYPE_CAT_LVL_2_DESC VARCHAR(50),
BILL_TYPE_CAT_LVL_2_SHORT_DESC VARCHAR(25),
BILL_TYPE_CAT_LVL_1_DIM_ID NUMBER NOT NULL DEFAULT -1,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT FK_DIM_BILL_TYPE_CAT_LVL_2_CAT_LVL_1_DIM_ID FOREIGN KEY (BILL_TYPE_CAT_LVL_1_DIM_ID) REFERENCES COMPACT.DIM_BILL_TYPE_CAT_LVL_1(BILL_TYPE_CAT_LVL_1_DIM_ID)
);
