CREATE TABLE IF NOT EXISTS COMPACT.DIM_ADMIT_SOURCE (
	ADMIT_SOURCE_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_ADMIT_SOURCE_DIM_ID PRIMARY KEY,
	ADMIT_SOURCE_CODE VARCHAR(6) NOT NULL,
	ADMIT_SOURCE_DESC VARCHAR(30),
	ADMIT_CLASS VARCHAR(1),
	DW_INSERT_DATETIME DATE,
	DW_UPDATE_DATETIME DATE,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT UK_F_DIM_ADMIT_SOURCE_SOURCE_CODE_ADMIT_CLASS UNIQUE (ADMIT_SOURCE_CODE,ADMIT_CLASS)
);
