CREATE TABLE IF NOT EXISTS COMPACT.DIM_GROUP (
	GROUP_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_GROUP_DIM_ID PRIMARY KEY,
	GROUP_ID VARCHAR(10) NOT NULL CONSTRAINT UK_F_DIM_GROUP_DIM_GROUP_ID UNIQUE,
	GROUP_SHORT_NAME VARCHAR(80),
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	SEQ_GROUP_ID INTEGER,
	COMPANY_DIM_ID INTEGER,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT UK_F_DIM_GROUP_SEQ_GROUP_ID_COMPANY_DIM_ID UNIQUE (SEQ_GROUP_ID,COMPANY_DIM_ID)
);
