CREATE TABLE IF NOT EXISTS COMPACT.DIM_DATE (
	FULL_DATE DATE NOT NULL,
	DAY_NBR INTEGER,
	MONTH_NBR INTEGER,
	QUARTER_NBR INTEGER,
	YEAR_NBR INTEGER,
	WEEK_NBR_YR INTEGER,
	WEEK_BEGIN_DT DATE,
	WEEK_END_DT DATE,
	DAY_WEEK_NBR INTEGER,
	DAY_MONTH_NBR INTEGER,
	CAL_YEAR_MONTH INTEGER,
	CAL_YEAR_QUARTER INTEGER,
	WEEKDAY_INDI VARCHAR(7),
	NBR_DAYS_IN_MONTH INTEGER,
	NBR_DAYS_IN_QUARTER INTEGER,
	CAL_YEAR_WEEK INTEGER,
	FIRST_DAY_MONTH DATE,
	PREV_FULL_DATE DATE,
	PREV_MONTH_FULL_DATE DATE,
	PREV_QTR_FULL_DATE DATE,
	PREV_YEAR_FULL_DATE DATE,
	MONTH_DESC VARCHAR(10),
	PREV_MONTH_CY INTEGER,
	PREV_MONTH_QTR_CY INTEGER,
	PREV_MONTH_YEAR_CY INTEGER,
	QUARTER_FULL_DATE DATE,
	QUARTER_DESC VARCHAR(8),
	PREV_QTR_CY INTEGER,
	PREV_QTR_YEAR_CY INTEGER,
	YEAR_DATE DATE,
	NUM_DAYS_YEAR INTEGER,
	PREV_YEAR INTEGER,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	MONTH_DIM_ID INTEGER NOT NULL,
	QUARTER_DIM_ID INTEGER NOT NULL,
	YEAR_DIM_ID INTEGER NOT NULL,
	UHG_HOLIDAYS_FLAG VARCHAR2(1),
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_DIM_DATE PRIMARY KEY (FULL_DATE),
	CONSTRAINT FK_DIM_DT_MNTH_DIM_ID FOREIGN KEY (MONTH_DIM_ID) REFERENCES COMPACT.DIM_DATE_MONTH(MONTH_DIM_ID),
	CONSTRAINT FK_DIM_DT_QTR_DIM_ID FOREIGN KEY (QUARTER_DIM_ID) REFERENCES COMPACT.DIM_DATE_QUARTER(QUARTER_DIM_ID),
	CONSTRAINT FK_DIM_DT_YEAR_DIM_ID FOREIGN KEY (YEAR_DIM_ID) REFERENCES COMPACT.DIM_DATE_YEAR(YEAR_DIM_ID)
);
COMMENT ON TABLE COMPACT.DIM_DATE IS 'This table stores attributes that describe multiple ways for selecting dates for reporting.';
COMMENT ON COLUMN COMPACT.DIM_DATE.FULL_DATE IS 'Full date format mm/dd/yyyy. i.e. 4/12/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.DAY_NBR IS 'The number of the day on the current calendar from the full date. i.e. 103';
COMMENT ON COLUMN COMPACT.DIM_DATE.MONTH_NBR IS 'Number of the month from the full date 1 - 12. i.e. 4/12/2012 = 4';
COMMENT ON COLUMN COMPACT.DIM_DATE.QUARTER_NBR IS 'Quarter number 1 - 4 from the full date. i.e. 4/12/2012 = 2';
COMMENT ON COLUMN COMPACT.DIM_DATE.YEAR_NBR IS 'Year number format yyyy from the full date. i.e. 2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.WEEK_NBR_YR IS 'Week number of the full date i.e. 4/12/2012 week 15.';
COMMENT ON COLUMN COMPACT.DIM_DATE.WEEK_BEGIN_DT IS 'Week begin date from Sunday. i.e. 4/8/2012 - 4/14/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.WEEK_END_DT IS 'Week end date thru Saturday. i.e. 4/8/2012 - 4/14/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.DAY_WEEK_NBR IS 'Day of the week number from the full date 1 - 7. i.e. Thursday = 5';
COMMENT ON COLUMN COMPACT.DIM_DATE.DAY_MONTH_NBR IS 'Day of the month number from the full date. i.e. 4/12/2012 = 12';
COMMENT ON COLUMN COMPACT.DIM_DATE.CAL_YEAR_MONTH IS 'Year and month format from the full date. i.e. 201204';
COMMENT ON COLUMN COMPACT.DIM_DATE.CAL_YEAR_QUARTER IS 'Year and quarter number from the full date. i.e. 20122';
COMMENT ON COLUMN COMPACT.DIM_DATE.WEEKDAY_INDI IS 'Weekday indicator values Weekday or Weekend.';
COMMENT ON COLUMN COMPACT.DIM_DATE.NBR_DAYS_IN_MONTH IS 'Number of days in the full date month. i.e. 4/12/2012 = 30';
COMMENT ON COLUMN COMPACT.DIM_DATE.NBR_DAYS_IN_QUARTER IS 'Number of days in the quarter of the full date. i.e. April thru June = 91 days.';
COMMENT ON COLUMN COMPACT.DIM_DATE.CAL_YEAR_WEEK IS 'Year and week number from the full date. i.e. 4/12/2012 = 201215';
COMMENT ON COLUMN COMPACT.DIM_DATE.FIRST_DAY_MONTH IS 'First day of the month from the full date. i.e. 4/1/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_FULL_DATE IS 'Previous full date from the full date. i.e. 4/12/2012 = 4/11/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_MONTH_FULL_DATE IS 'Previous month from the full date.i.e. 4/12/2012 = 3/12/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_QTR_FULL_DATE IS 'Previous quarter from the full date. i.e. 4/12/2012 = 1/12/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_YEAR_FULL_DATE IS 'Previous Year from the full date. i.e. 4/12/2012 = 4/12/2011';
COMMENT ON COLUMN COMPACT.DIM_DATE.MONTH_DESC IS 'Month description from the full date. i.e. 4/12/2012 = APR 12';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_MONTH_CY IS 'Previous month year from full date. i.e. 4/12/2012 = 201203';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_MONTH_QTR_CY IS 'Previous month quarter from full date. i.e. 4/12/2012 = 201201';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_MONTH_YEAR_CY IS 'Previous month year from full date. i.e. 4/12/2012 = 201104';
COMMENT ON COLUMN COMPACT.DIM_DATE.QUARTER_FULL_DATE IS 'Quarter first date from full date. i.e. 4/12/2012 = 4/1/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.QUARTER_DESC IS 'Quarter description from full date. i.e. 4/12/2012 = QTR 2 12';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_QTR_CY IS 'Previous quarter from the full date. i.e. 4/12/2012 = 20121';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_QTR_YEAR_CY IS 'Previous quarter year from the full date. i.e. 4/12/2012 = 20112';
COMMENT ON COLUMN COMPACT.DIM_DATE.YEAR_DATE IS 'Year of the full date. i.e. 1/1/2012';
COMMENT ON COLUMN COMPACT.DIM_DATE.NUM_DAYS_YEAR IS 'Number of days in the year. i.e. 365 or 366';
COMMENT ON COLUMN COMPACT.DIM_DATE.PREV_YEAR IS 'Previous Year from the full date. i.e. 4/12/2012 = 2011';
COMMENT ON COLUMN COMPACT.DIM_DATE.DW_INSERT_DATETIME IS 'Date the record was added to the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_DATE.DW_UPDATE_DATETIME IS 'Date the record was updated in the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_DATE.MONTH_DIM_ID IS 'Represents the link to the DIM_DATE_MONTH table listing the month by INTEGER, quarter, year quarter, year INTEGER, begin and end dates for month, quarter and year, LMO, LYR and current month indicator.';
COMMENT ON COLUMN COMPACT.DIM_DATE.QUARTER_DIM_ID IS 'Represents the link to the DIM_DATE_QUARTER table listing the quarter, year quarter, year INTEGER, begin and end dates for quarter and year.';
COMMENT ON COLUMN COMPACT.DIM_DATE.YEAR_DIM_ID IS 'Represents the link to the DIM_DATE_YEAR table listing the year INTEGER, begin and end dates.';
