CREATE TABLE IF NOT EXISTS COMPACT.DIM_EOB_IND (
	EOB_IND_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_EOB_IND_DIM_ID PRIMARY KEY,
	EOB_IND_DESC VARCHAR(20),
	DW_INSERT_DATETIME DATE,
	DW_UPDATE_DATETIME DATE,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);
