CREATE TABLE IF NOT EXISTS COMPACT.DIM_CLAIM_TYPE (
CLAIM_TYPE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_CLAIM_TYPE_DIM_ID PRIMARY KEY,
CLAIM_TYPE VARCHAR(8) NOT NULL CONSTRAINT UK_F_DIM_CLAIM_TYPE_CLAIM_TYPE UNIQUE,
CLAIM_TYPE_DESC VARCHAR(30),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
