CREATE TABLE IF NOT EXISTS COMPACT.PATIENT_INDEX (
	INDEX_VALUE VARCHAR2(200)  NOT NULL,
	INDEX_ID NUMBER NOT NULL,
	PATIENT_ID NUMBER NOT NULL,
	DISPLAY_VALUE VARCHAR2(200) NOT NULL,
	CREATED_ON DATETIME  NOT NULL,
	CREATED_BY NUMBER,
	UPDATED_BY NUMBER,
	UPDATED_ON DATETIME,
	DELETED_BY NUMBER,
	DELETED_ON DATETIME,
	PATIENT_INDEX_IDNTY NUMBER NOT NULL CONSTRAINT PK_PATIENT_INDX_ID PRIMARY KEY ,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);