CREATE TABLE IF NOT EXISTS COMPACT.DIM_NETWORK (
NETWORK_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_NETWORK_DIM_ID PRIMARY KEY,
NETWORK_ID VARCHAR(15),
NETWORK_DESC VARCHAR(20),
COMPANY_DIM_ID NUMBER NOT NULL,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT FK_DIM_NETWORK_DIM_COMPANY FOREIGN KEY (COMPANY_DIM_ID) REFERENCES COMPACT.DIM_COMPANY(COMPANY_DIM_ID)
);

