create TABLE IF NOT EXISTS COMPACT.IMDM_EDW_INDV_KEY cluster by (INDV_KEY_VAL,INDV_KEY_TYP_REF_DESC,CREAT_SYS_REF_CD)(
	INDV_KEY_VAL VARCHAR(250) NOT NULL,
	INDV_KEY_TYP_REF_DESC VARCHAR(300) NOT NULL,
	CREAT_DTTM TIMESTAMP_NTZ(3),
	CHG_DTTM TIMESTAMP_NTZ(3),
	CREAT_SYS_REF_CD VARCHAR(30) NOT NULL,
	CHG_SYS_REF_CD VARCHAR(30),
	DATA_SECUR_RULE_LIST VARIANT,
	IMDM_SURRG_KEY VARCHAR(250) NOT NULL,
	INDV_SRC_ID VARCHAR(250) NOT NULL,
	DW_SYS_REF_CD VARCHAR(30) NOT NULL,
	DW_CREAT_DTTM TIMESTAMP_NTZ(9),
	DW_CHG_DTTM TIMESTAMP_NTZ(9),
	SF_INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SF_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SF_PROCESS_ID VARCHAR(36),
	CDC_FLG VARCHAR(5),
	constraint IMDM_EDW_INDV_KEY_PK primary key (INDV_KEY_VAL, INDV_KEY_TYP_REF_DESC, CREAT_SYS_REF_CD, IMDM_SURRG_KEY, INDV_SRC_ID, DW_SYS_REF_CD)
);