CREATE TABLE IF NOT EXISTS COMPACT.DIM_RATECELL_REGION
    (
        RTCL_REGION_DIM_ID INTEGER NOT NULL,
        COMPANY_DIM_ID INTEGER NOT NULL,
        RTCL_STATE VARCHAR(2) NOT NULL,
        RTCL_REGION_CODE VARCHAR(20),
        RTCL_REGION_NAME VARCHAR(30),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_RATECELL_REGION_DIM_ID PRIMARY KEY (RTCL_REGION_DIM_ID)
    );
