CREATE TABLE IF NOT EXISTS COMPACT.TB_MEM_MBR_ALT (
MBR_ALT_SYS_ID int NOT NULL,
MBR_SYS_ID int NULL,
MBR_ALT_ID VARCHAR(50) NULL,
MBR_ALT_ID_SRC_FLG VARCHAR(1) NOT NULL,
SRC_REC_CRT_DTTM DATETIME NULL,
SRC_REC_CRT_USER_ID VARCHAR(15) NULL,
SRC_REC_UPDT_DTTM DATETIME NULL,
SRC_REC_UPDT_USER_ID VARCHAR(15) NULL,
REC_CRT_DTTM DATETIME NOT NULL,
REC_UPDT_DTTM DATETIME NOT NULL,
REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
BTCH_LOAD_DT DATE NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT TB_MEM_MBR_ALT_SYS PRIMARY KEY (MBR_ALT_SYS_ID)
);