CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_PROVIDER_QUALIFIER (
    PROV_QUALIFIER_DIM_ID NUMBER NOT NULL,
    PROV_ID_QUALIFIER VARCHAR(3) NOT NULL,
    PROV_ID_QUALIFIER_DESC VARCHAR(50),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT PK_PROV_QUALIFIER_DIM_ID PRIMARY KEY (PROV_QUALIFIER_DIM_ID),
    CONSTRAINT UK_PROV_ID_QUALIFIER UNIQUE (PROV_ID_QUALIFIER)
);
