CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROCEDURE_MODIFIER (
MODIFIER_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_PROCEDURE_MODIFIER_DIM_ID PRIMARY KEY,
MODIFIER_CODE VARCHAR(3) NOT NULL CONSTRAINT UK_F_DIM_PROCEDURE_MODIFIER_MODIFIER_CODE UNIQUE,
PROCEDURE_MODIFIER_DESC VARCHAR(60),
ANESTHESIA_IND VARCHAR(1),
INFORMATIONAL_FLAG VARCHAR(1),
PROCEDURE_MODIFIER_EFF_DATE DATE,
PROCEDURE_MODIFIER_TERM_DATE DATE,
PRMO_REV_INP_OUTP_IND VARCHAR(1),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
FINANCIAL_FLAG VARCHAR(1) DEFAULT 'N',
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
