CREATE TABLE IF NOT EXISTS COMPACT.UNET_PLACE_OF_SERVICE_CODE
    (
        PL_OF_SRVC_SYS_ID NUMBER NOT NULL CONSTRAINT PK_PLACE_OF_SERVICE_CODE PRIMARY KEY,
        AMA_PL_OF_SRVC_CD VARCHAR(2) NOT NULL,
        AMA_PL_OF_SRVC_DESC VARCHAR(50) NOT NULL,
        CLM_PL_OF_SRVC_CD VARCHAR(2) NOT NULL,
        CLM_PL_OF_SRVC_DESC VARCHAR(50) NOT NULL,
        COS_PL_OF_SRVC_CD VARCHAR(2) NOT NULL,
        PL_OF_SRVC_SUM_CD VARCHAR(1) NOT NULL,
        PL_OF_SRVC_SUM_DESC VARCHAR(40) NOT NULL,
        PL_OF_SRVC_CATGY_TXT VARCHAR(10) NOT NULL,
        SRC_MAP_CD VARCHAR(2) NOT NULL,
        UNET_PL_OF_SRVC_CD VARCHAR(2) NOT NULL,
        UPDT_USER_ID VARCHAR(8) NOT NULL,
        LOAD_DT DATE NOT NULL,
        UPDT_DT DATE NOT NULL,
		SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_PROCESS_ID VARCHAR(36)
    );