CREATE TABLE IF NOT EXISTS  COMPACT.T_AUTH_CLAIM_INFO (SERVICE_ID VARCHAR,                
AUTH_NBR VARCHAR,                  
TYPE_CODE VARCHAR,                 
AUTH_TRANS_STATUS_CODE NUMBER(38,0),
CLAIM_AUTH_ID VARCHAR,             
CLAIM_AUTH_SUB_ID VARCHAR,         
SUBMIT_DATE TIMESTAMP_NTZ(9),          
TIMES_SENT NUMBER(38,0),            
FAIL_REASON VARCHAR,            
HAS_AUTH_EVER_PASSED BOOLEAN,       
IS_ARCHIVED BOOLEAN,                
CREATE_USER_ID VARCHAR,            
CREATE_DATE TIMESTAMP_NTZ(9),          
UPDATE_USER_ID VARCHAR,            
UPDATE_DATE TIMESTAMP_NTZ(9),          
XREF_TYPE_CODE VARCHAR,            
XREF_ID VARCHAR,
SF_INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),

SF_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),

SF_PROCESS_ID VARCHAR(36),
constraint PK_T_AUTH_CLAIM_INFO primary key (SERVICE_ID, AUTH_NBR, TYPE_CODE)  );
            