CREATE TABLE IF NOT EXISTS COMPACT.DIM_PLACE_OF_SVC (
PLACE_OF_SVC_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_PLACE_OF_SVC_DIM_ID PRIMARY KEY,
PLACE_OF_SVC_CODE VARCHAR(6) NOT NULL CONSTRAINT UK_F_DIM_PLACE_OF_SVC_PLACE_OF_SVC_CODE UNIQUE,
PLACE_OF_SVC_DESC VARCHAR(60),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
PLACE_OF_SVC_SUMM_CD VARCHAR(1) NOT NULL DEFAULT 'K',
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
