CREATE TABLE IF NOT EXISTS COMPACT.INTERNAL_PROGRAM_REASON (
	PROGRAM_REASON_ID NUMBER NOT NULL,
	REASON_DESCRIPTION VARCHAR(5000),
	PROGRAM_STATUS_ID NUMBER,
	CREATED_ON DATETIME,
	CREATED_BY NUMBER,
	IS_ACTIVE NUMBER,
	DELETED_BY NUMBER,
	DELETED_ON DATETIME,
	UPDATED_BY NUMBER,
	UPDATED_ON DATETIME,
	REASON_TYPE VARCHAR(100),
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36)
);