CREATE TABLE IF NOT EXISTS COMPACT.DIM_COS_STL_2 (
COS_STL_2_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_COS_STL_2_DIM_ID PRIMARY KEY,
COS_STL_2_DESC VARCHAR(20),
COS_STL_1_DIM_ID NUMBER NOT NULL,
COS_STL_1_DESC VARCHAR(20),
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT FK_DIM_COS_STL_2_DIM_COS_STL_1 FOREIGN KEY (COS_STL_1_DIM_ID) REFERENCES COMPACT.DIM_COS_STL_1(COS_STL_1_DIM_ID)
);
