CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_PAYMENT_TYPE (
    PAYMENT_TYPE_DIM_ID NUMBER NOT NULL,
    PAYMENT_TYPE VARCHAR(3) NOT NULL,
    PAYMENT_TYPE_DESC VARCHAR(30),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT PK_PAYMENT_TYPE_DIM_ID PRIMARY KEY (PAYMENT_TYPE_DIM_ID),
    CONSTRAINT UK_PAYMENT_TYPE UNIQUE (PAYMENT_TYPE)
);
COMMENT ON TABLE COMPACT.DIM_RX_PAYMENT_TYPE IS 'This table stores attributes that describe the Pharmacy payment type.';
COMMENT ON COLUMN COMPACT.DIM_RX_PAYMENT_TYPE.PAYMENT_TYPE_DIM_ID IS 'Represents the link to the DIM_RX_PAYMENT_TYPE table describing the payment type. Values are 1 = P Pharmacy, 2 = M Member, 3 = A Medical provider, 0 = UNK UNKNOWN and -1 = N/A N/A.';
COMMENT ON COLUMN COMPACT.DIM_RX_PAYMENT_TYPE.PAYMENT_TYPE IS 'Code that represents the payment type. Values are P = Pharmacy, M = Member, A = Medical provider, UNK = UNKNOWN and N/A = N/A.';
COMMENT ON COLUMN COMPACT.DIM_RX_PAYMENT_TYPE.PAYMENT_TYPE_DESC IS 'Describes the payment type. Values are Pharmacy, Member, Medical provider, UNKNOWN and N/A.';
COMMENT ON COLUMN COMPACT.DIM_RX_PAYMENT_TYPE.DW_INSERT_DATETIME IS 'Date the record was added to the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_RX_PAYMENT_TYPE.DW_UPDATE_DATETIME IS 'Date the record was updated in the Data Warehouse.';
