CREATE TABLE IF NOT EXISTS COMPACT.DIM_COMPANY (
COMPANY_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_COMPANY_DIM_ID PRIMARY KEY,
COMPANY_CODE VARCHAR(5) NOT NULL CONSTRAINT UK_F_DIM_COMPANY_COMPANY_CODE UNIQUE,
COMPANY_DESC VARCHAR(30),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
CORPORATE_DIM_ID INTEGER,
DIVISION_DIM_ID INTEGER,
REGION_DIM_ID INTEGER,
GEOGRAPHY_STATE_DIM_ID INTEGER,
RECORD_STATUS_DIM_ID INTEGER,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
