CREATE TABLE IF NOT EXISTS COMPACT.DIM_REVENUE_CAT_LVL_2 (
REVENUE_CAT_LVL_2_DIM_ID NUMBER  NOT NULL CONSTRAINT PK_F_DIM_REVENUE_CAT_LVL_2_DIM_ID PRIMARY KEY,
REVENUE_CAT_LVL_2_DESC VARCHAR(100),
REVENUE_CAT_LVL_2_SHORT_DESC VARCHAR(25),
REVENUE_CAT_LVL_1_DIM_ID NUMBER NOT NULL DEFAULT -1,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT FK_DIM_REVENUE_CAT_LVL_2_CAT_LVL_1 FOREIGN KEY (REVENUE_CAT_LVL_1_DIM_ID) REFERENCES COMPACT.DIM_REVENUE_CAT_LVL_1(REVENUE_CAT_LVL_1_DIM_ID)
);
