CREATE TABLE IF NOT EXISTS COMPACT.DIM_DATE_QUARTER (
    QUARTER_DIM_ID NUMBER NOT NULL,
	QUARTER_DESC VARCHAR2(8),
	CAL_YEAR_QUARTER NUMBER,
	YEAR_DIM_ID NUMBER NOT NULL,
	YEAR_NBR NUMBER,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	QUARTER_BEGIN_DATE DATE,
	QUARTER_END_DATE DATE,
	YEAR_BEGIN_DATE DATE,
	YEAR_END_DATE DATE,
	CURR_QUARTER_IND NUMBER,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_DIM_DATE_QUARTER PRIMARY KEY (QUARTER_DIM_ID),
	CONSTRAINT FK_DIM_DATE_QUARTER_YEAR_DIM_ID FOREIGN KEY (YEAR_DIM_ID) REFERENCES COMPACT.DIM_DATE_YEAR(YEAR_DIM_ID)
);

COMMENT ON TABLE COMPACT.DIM_DATE_QUARTER IS 'This table stores attributes that describe multiple ways for selecting quarter dates for reporting.';