CREATE TABLE IF NOT EXISTS COMPACT.DIM_CARE_LEVEL (
CARE_LEVEL_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_CARE_LELVEL_DIM_ID PRIMARY KEY,
CARE_LEVEL_CODE VARCHAR(17) NOT NULL,
CARE_LEVEL_DESC VARCHAR(32) NOT NULL,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
