CREATE TABLE IF NOT EXISTS COMPACT.UNET_MHSA_CODE
    (
        MHSA_CD VARCHAR(1) NOT NULL,
        MHSA_DESC VARCHAR(25) NOT NULL,
        UPDT_USER_ID VARCHAR(8) NOT NULL,
        LOAD_DT DATE NOT NULL,
        UPDT_DT DATE NOT NULL,
		SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_PROCESS_ID VARCHAR(36),
		CONSTRAINT PK_MHSA_CD PRIMARY KEY (MHSA_CD) not enforced
    );