CREATE TABLE IF NOT EXISTS COMPACT.UNET_ZIP
    (
        ZIP_CD VARCHAR(5) NOT NULL CONSTRAINT PK_ZIP PRIMARY KEY,
        ZIP_ROW_EFF_DT DATE NOT NULL CONSTRAINT UK_ZIP UNIQUE,
        ZIP_FST_3_CD VARCHAR(3) NOT NULL,
        ZIP_LST_2_CD VARCHAR(2) NOT NULL,
        ZIP_TYP_CD VARCHAR(1) NOT NULL,
        ZIP_TYP_SRC_CD VARCHAR(1) NOT NULL,
        CTY_NM VARCHAR(28) NOT NULL,
        ST_NUM_CD VARCHAR(2) NOT NULL,
        ST_ABBR_CD VARCHAR(2) NOT NULL,
        PST_CNTY_CD VARCHAR(3) NOT NULL,
        PST_CNTY_NM VARCHAR(25) NOT NULL,
        HCFA_CNTY_CD VARCHAR(4) NOT NULL,
        HCFA_CNTY_NM VARCHAR(30) NOT NULL,
        ZIP_ROW_END_DT DATE NOT NULL,
        LOAD_DT DATE NOT NULL,
        UPDT_DT DATE NOT NULL,
		SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_PROCESS_ID VARCHAR(36)
    );