CREATE TABLE IF NOT EXISTS
    COMPACT.DIM_ETHNIC_CODE
    (
       ETHNIC_DIM_ID NUMBER NOT NULL CONSTRAINT PK_DIM_ETHNIC_DIM_ID PRIMARY KEY,
        ETHNIC_CODE VARCHAR2(10) NOT NULL,
        ETHNIC_CODE_DESC VARCHAR2(100),
        CONVERTED_FROM_DIM_ID NUMBER NOT NULL,
        DW_INSERT_DATETIME DATETIME,
        DW_UPDATE_DATETIME DATETIME,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
      CONSTRAINT UK_DIM_ETHNIC_CODE_CONVERTED_FROM UNIQUE (ETHNIC_CODE, CONVERTED_FROM_DIM_ID)
    );