CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_THERAPEUTIC_GROUP (
    RX_THERAPEUTIC_GROUP_DIM_ID NUMBER NOT NULL,
    RX_THERAPEUTIC_GROUP_IND VARCHAR(3) NOT NULL,
    RX_THERAPEUTIC_GROUP_IND_DESC VARCHAR(30),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT PK_RX_THERAPEUTIC_GROUP_DIM_ID PRIMARY KEY (RX_THERAPEUTIC_GROUP_DIM_ID),
    CONSTRAINT UK_RX_THERAPEUTIC_GROUP_IND UNIQUE (RX_THERAPEUTIC_GROUP_IND)
);
COMMENT ON TABLE COMPACT.DIM_RX_THERAPEUTIC_GROUP IS 'This table is a one time load and it DETERMINES WHICH CLAIM SITUATIONS ARE REPORTED ON A PLANS REPORTS.';
COMMENT ON COLUMN COMPACT.DIM_RX_THERAPEUTIC_GROUP.RX_THERAPEUTIC_GROUP_DIM_ID IS 'This column is auto generated and it gets incremented for every value being added and mainly used in fact tables';
COMMENT ON COLUMN COMPACT.DIM_RX_THERAPEUTIC_GROUP.RX_THERAPEUTIC_GROUP_IND IS 'This column represents  WHICH CLAIM SITUATIONS ARE REPORTED ON A PLANS REPORTS as below BLANK = UNASSIGNED ,A= ANTIDEPRESSANTS ,B= BETA BLOCKERS ,C= CONTRACEPTIVES ,D= DURABLE MEDICAL EQUIPMENT (DME) ,G= ORGAN TRANSPLANT MEDS ,J = NSAID ';
COMMENT ON COLUMN COMPACT.DIM_RX_THERAPEUTIC_GROUP.RX_THERAPEUTIC_GROUP_IND_DESC IS 'This column represents the description for RX_THERAPEUTIC_GROUP_IND field for ex:A= ANTIDEPRESSANTS';
COMMENT ON COLUMN COMPACT.DIM_RX_THERAPEUTIC_GROUP.DW_INSERT_DATETIME IS 'This table represents the date value as when the record got updated';
