CREATE TABLE IF NOT EXISTS COMPACT.DIM_MEDICARE_TYPE (
	MEDICARE_TYPE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_MEDICARE_TYPE_DIM_ID PRIMARY KEY,
	MEDICARE_TYPE VARCHAR(3) NOT NULL,
	MEDICARE_IND VARCHAR(1),
	MEDICARE_TYPE_DESC VARCHAR(100),
	MEDICARE_GROUP_DIM_ID INTEGER NOT NULL,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	GROUP_DIM_ID INTEGER NOT NULL DEFAULT -1,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT UK_F_DIM_MEDICARE_TYPE_MEDICARE_TYPE_GROUP_DIM_ID UNIQUE (MEDICARE_TYPE,GROUP_DIM_ID)
);
