CREATE TABLE IF NOT EXISTS COMPACT.DIM_GL_TAG (
	GL_TAG_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_GL_TAG_DIM_ID PRIMARY KEY,
	GL_TAG_CODE VARCHAR(6),
	GL_TAG_DESC VARCHAR(25),
	DW_INSERT_DATE DATETIME,
	DW_UPDATE_DATE DATETIME,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36)
);
