CREATE TABLE IF NOT EXISTS COMPACT.DIM_SDA (
    SDA_DIM_ID INTEGER NOT NULL CONSTRAINT PK_DIM_SDA PRIMARY KEY,
	SDA_CODE VARCHAR(100),
	SDA_DESC VARCHAR(100),
	COMPANY_DIM_ID INTEGER,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	CONVERTED_FROM_DIM_ID INTEGER DEFAULT -1 ,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);
