CREATE TABLE IF NOT EXISTS COMPACT.DIM_RATE_TYPE
    (
        RATE_TYPE_DIM_ID INTEGER NOT NULL,
        RATE_TYPE_CODE VARCHAR(4) NOT NULL,
        RATE_TYPE_DESC VARCHAR(255) NOT NULL,
        CONVERTED_FROM_DIM_ID INTEGER NOT NULL,
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_DIM_RATE_TYPE PRIMARY KEY (RATE_TYPE_DIM_ID),
        CONSTRAINT UK_F_DIM_RATE_TYPE_CODE_CONVERTED UNIQUE (RATE_TYPE_CODE,CONVERTED_FROM_DIM_ID),
        CONSTRAINT FK_DIM_RATE_TYPE FOREIGN KEY (CONVERTED_FROM_DIM_ID) REFERENCES COMPACT.DIM_CONVERTED_FROM(CONVERTED_FROM_DIM_ID)
    );
