CREATE TABLE IF NOT EXISTS COMPACT.PROGRAM_STATUS (
    PROGRAM_STATUS_ID NUMBER NOT NULL CONSTRAINT PK_PROGRAM_STATUS_ID PRIMARY KEY,
	PROGRAM_STATUS_NAME VARCHAR(1000) NOT NULL,
	IS_ACTIVE NUMBER,
	CREATED_BY NUMBER,
	CREATED_ON DATETIME,
	UPDATED_BY NUMBER,
	UPDATED_ON DATETIME,
	DELETED_BY NUMBER,
	DELETED_ON DATETIME,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);