CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROVIDER_TYPE (
PROV_TYPE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_PROVIDER_TYPE_DIM_ID PRIMARY KEY,
TYPE_OR_SPEC_CODE VARCHAR(10) NOT NULL,
TYPE_OR_SPECIALTY VARCHAR(1),
PROV_TYPE_SHORT_DESC VARCHAR(15),
PROV_TYPE_DESC VARCHAR(60),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
TYPE_OF_SERVICE VARCHAR(3),
PROV_SPEC_CAT_CODE INTEGER,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT UK_F_DIM_PROVIDER_TYPE_TYPE_OR_SPEC_CODE_SPECIALTY UNIQUE (TYPE_OR_SPEC_CODE,TYPE_OR_SPECIALTY)
);
