CREATE TABLE IF NOT EXISTS COMPACT.STAR_EXCLUSION_RULE_FAILURES (
	CLINICAL_REVIEW_ID NUMBER(11) NOT NULL,
	REASON_CODE varchar(3) NOT NULL,
	CREATE_DATE_TIME DATETIME NOT NULL,
	UPDATE_DATE_TIME DATETIME NOT NULL,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	    SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_STAR_EXCLUSION_RULE_FAILURES PRIMARY KEY (CLINICAL_REVIEW_ID,REASON_CODE)
);