CREATE TABLE IF NOT EXISTS COMPACT.DIM_CPT_CAT_LVL_2 (
CPT_CAT_LVL_2_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_CPT_CAT_LVL_2_DIM_ID PRIMARY KEY,
CPT_CAT_LVL_2_DESC VARCHAR(500),
CPT_CAT_LVL_2_SHORT_DESC VARCHAR(25),
CPT_CAT_LVL_1_DIM_ID INTEGER NOT NULL DEFAULT -1,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT FK_DIM_CPT_CAT_LVL_2_DIM_CPT_CAT_LVL_1 FOREIGN KEY (CPT_CAT_LVL_1_DIM_ID) REFERENCES COMPACT.DIM_CPT_CAT_LVL_1(CPT_CAT_LVL_1_DIM_ID)
);
