CREATE TABLE IF NOT EXISTS COMPACT.DIM_CLAIM_STATUS (
CLAIM_STATUS_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_CLAIM_STATUS_DIM_ID PRIMARY KEY,
CLAIM_STATUS VARCHAR(1) NOT NULL CONSTRAINT UK_F_DIM_CLAIM_STATUS_CLAIM_STATUS UNIQUE,
CLAIM_STATUS_DESC VARCHAR(30),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
CLAIM_STATUS_TYPE_DIM_ID INTEGER NOT NULL,
CLAIM_STATUS_TYPE VARCHAR(1) NOT NULL,
CLAIM_STATUS_TYPE_DESC VARCHAR(20),
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);

