CREATE TABLE IF NOT EXISTS COMPACT.TB_CUST_ACCT_ORG_SALE_CHNL_XREF (
	SALE_CHNL_SYS_ID NUMBER(10) NOT NULL,
	ACCT_SYS_ID NUMBER(10) NOT NULL,
	REC_ACTV_FLG VARCHAR(1) NOT NULL,
	REC_CRT_DTTM DATETIME NOT NULL,
	REC_UPDT_DTTM DATETIME NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_TB_CUST_ACCT_ORG_SALE_CHNL_XREF_SALE PRIMARY KEY (SALE_CHNL_SYS_ID,ACCT_SYS_ID)
);
