CREATE TABLE IF NOT EXISTS COMPACT.DIM_BILL_TYPE (
BILL_TYPE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_BILL_TYPE_DIM_ID PRIMARY KEY,
BILL_TYPE VARCHAR(3) NOT NULL CONSTRAINT UK_F_DIM_BILL_TYPE_BILL_TYPE UNIQUE,
BILL_TYPE_DESC VARCHAR(60),
INP_OUTP_IND VARCHAR(1),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
BILL_TYPE_CAT_LVL_2_DIM_ID INTEGER NOT NULL DEFAULT -1,
BILL_TYPE_CAT_LVL_1_DIM_ID INTEGER NOT NULL DEFAULT -1,
PLACE_OF_SVC_DIM_ID INTEGER NOT NULL DEFAULT -1,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
