CREATE TABLE IF NOT EXISTS COMPACT.DIM_RATECELL_CATEGORY
    (
        RTCL_CATEGORY_DIM_ID INTEGER NOT NULL,
        RTCL_CATEGORY_CODE VARCHAR(10),
        RTCL_CATEGORY_DESC VARCHAR(50),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_RATECELL_CATEGORY_RTCL_CATEGORY_DIM_ID PRIMARY KEY (RTCL_CATEGORY_DIM_ID)
    );
