CREATE TABLE IF NOT EXISTS COMPACT.DIM_CLASS (
CLASS_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_CLASS_DIM_ID PRIMARY KEY,
CLASS_ID VARCHAR(10) NOT NULL,
CLASS_DESC VARCHAR(200) NOT NULL,
GROUP_CODE VARCHAR(8) NOT NULL,
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT UK_F_DIM_CLASS_ID_CLASS_ID_GROUP_CODE UNIQUE (CLASS_ID, GROUP_CODE)
);
