CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROVIDER_SPECIALTY (
PROV_DIM_ID NUMBER NOT NULL,
PRIMARY_SPECIALTY_FLAG VARCHAR(1),
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
PROV_SPEC_DIM_ID NUMBER NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT PK_F_DIM_PROVIDER_SPECIALTY_DIM_ID PRIMARY KEY (PROV_DIM_ID,PROV_SPEC_DIM_ID),
CONSTRAINT FK_DIM_PROVIDER_SPECIALTY_DIM_PROVIDER FOREIGN KEY (PROV_DIM_ID) REFERENCES COMPACT.DIM_PROVIDER(PROV_DIM_ID),
CONSTRAINT FK_DIM_PROVIDER_SPECIALTY_DIM_PROVIDER_TYPE FOREIGN KEY (PROV_SPEC_DIM_ID) REFERENCES COMPACT.DIM_PROVIDER_TYPE(PROV_TYPE_DIM_ID)
);

