CREATE TABLE IF NOT EXISTS COMPACT.TB_SYS_DERIV_LVL_OF_CARE_CATGY_XREF (
	LVL_OF_CARE_DERIV_TXT VARCHAR(25) NOT NULL,
	LVL_OF_CARE_RLLP_CATGY_TXT VARCHAR(30) NULL,
	LVL_OF_CARE_SEQ_NBR NUMBER(10) NULL,
	REC_CRT_DTTM DATETIME NOT NULL,
	REC_UPDT_DTTM DATETIME NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
	BTCH_LOAD_DT DATE NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT PK_TB_SYS_DERIV_LVL_OF_CARE_CATGY_XREF_DERIV_TXT PRIMARY KEY (LVL_OF_CARE_DERIV_TXT));