CREATE TABLE IF NOT EXISTS COMPACT.DIM_SOURCE_PRODUCT (
	SOURCE_PRODUCT_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_SOURCE_PRODUCT_DIM_ID PRIMARY KEY,
	SOURCE_PRODUCT_CODE VARCHAR(20) NOT NULL,
	SOURCE_PRODUCT_DESC VARCHAR(70) NOT NULL,
	CONVERTED_FROM_DIM_ID NUMBER NOT NULL,
	DW_INSERT_DATETIME DATE NOT NULL,
	DW_UPDATE_DATETIME DATE NOT NULL,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT UK_F_DIM_SOURCE_PRODUCT_CODE_CONVERTED_FROM UNIQUE (SOURCE_PRODUCT_CODE,CONVERTED_FROM_DIM_ID)
);
