CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_APPROVED_COST_SOURCE (
    APPROVED_COST_SOURCE_DIM_ID NUMBER NOT NULL,
    APPROVED_COST_SOURCE VARCHAR(15) NOT NULL,
    APPROVED_COST_SOURCE_DESC VARCHAR(50),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT PK_APPROVED_COST_SOURCE_DIM_ID PRIMARY KEY (APPROVED_COST_SOURCE_DIM_ID),
    CONSTRAINT UK_APPROVED_COST_SOURCE UNIQUE (APPROVED_COST_SOURCE)
);
COMMENT ON TABLE COMPACT.DIM_RX_APPROVED_COST_SOURCE IS 'This table stores attributes that describe Pharmacy approved cost source like maximum allowed cost list 01 or avgerage generic cost. ';
COMMENT ON COLUMN COMPACT.DIM_RX_APPROVED_COST_SOURCE.APPROVED_COST_SOURCE_DIM_ID IS 'Represents the link to the DIM_RX_APPROVED_COST_SOURCE table describing the Pharmacy approved cost source. i.e. 27 = MAC01 maximum allowed cost list 01 or 3 = AVGGENERIC avg.generic cost. ';
COMMENT ON COLUMN COMPACT.DIM_RX_APPROVED_COST_SOURCE.APPROVED_COST_SOURCE IS 'Code that represents Pharmacy approved cost source. i.e. MAC01 = maximum allowed cost list 01 or AVGGENERIC = avg.generic cost. ';
COMMENT ON COLUMN COMPACT.DIM_RX_APPROVED_COST_SOURCE.APPROVED_COST_SOURCE_DESC IS 'Describes Pharmacy approved cost source. i.e. maximum allowed cost list 01 or avg.generic cost. ';
COMMENT ON COLUMN COMPACT.DIM_RX_APPROVED_COST_SOURCE.DW_INSERT_DATETIME IS 'Date the record was added to the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_RX_APPROVED_COST_SOURCE.DW_UPDATE_DATETIME IS 'Date the record was updated in the Data Warehouse.';
