CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROVIDER_PAR_STAT (
PROVIDER_PAR_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_PROVIDER_PAR_STAT_DIM_ID PRIMARY KEY,
PROVIDER_PAR_STAT VARCHAR(1) NOT NULL,
PROVIDER_DESC VARCHAR(20),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
