CREATE TABLE IF NOT EXISTS COMPACT.DIM_DIAG_CAT_LVL_2 (
	DIAG_CAT_LVL_2_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_DIAG_CAT_LVL_2_DIM_ID PRIMARY KEY,
	DIAG_CAT_LVL_2_DESC VARCHAR(200),
	DIAG_CAT_LVL_2_SHORT_DESC VARCHAR(25),
	DIAG_CAT_LVL_1_DIM_ID INTEGER NOT NULL DEFAULT -1,
	DW_INSERT_DATETIME DATE,
	DW_UPDATE_DATETIME DATE,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT FK_DIM_DIAG_CAT_LVL_2_DIM_DIAG_CAT_LVL_1 FOREIGN KEY (DIAG_CAT_LVL_1_DIM_ID) REFERENCES COMPACT.DIM_DIAG_CAT_LVL_1(DIAG_CAT_LVL_1_DIM_ID)
);
