CREATE TABLE IF NOT EXISTS COMPACT.DIM_COS_STL_4 (
COS_STL_4_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_COS_STL_4_DIM_ID PRIMARY KEY,
COS_STL_4_DESC VARCHAR(40),
COS_STL_3_DIM_ID INTEGER NOT NULL,
COS_STL_3_DESC VARCHAR(20),
COS_STL_2_DIM_ID INTEGER NOT NULL,
COS_STL_2_DESC VARCHAR(20),
COS_STL_1_DIM_ID INTEGER NOT NULL,
COS_STL_1_DESC VARCHAR(20),
COS_CODE VARCHAR(4) NOT NULL CONSTRAINT UK_F_DIM_COS_STL_4_COS_CODE UNIQUE,
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
COS_PRIORITY NUMBER(6,3),
UNIT_TYPE VARCHAR(1),
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
