CREATE TABLE IF NOT EXISTS COMPACT.DIM_REVENUE_CAT_LVL_1 (
REVENUE_CAT_LVL_1_DIM_ID NUMBER  NOT NULL CONSTRAINT PK_F_DIM_REVENUE_CAT_LVL_1_DIM_ID PRIMARY KEY,
REVENUE_CAT_LVL_1_DESC VARCHAR(50),
REVENUE_CAT_LVL_1_SHORT_DESC VARCHAR(25),
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
