CREATE TABLE IF NOT EXISTS COMPACT.DIM_PLAN_LOB (
	PLAN_LOB_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_PLAN_LOB_DIM_ID PRIMARY KEY,
	LINE_OF_BUSINESS_DIM_ID INTEGER NOT NULL DEFAULT -1 ,
	PLAN_DIM_ID INTEGER NOT NULL DEFAULT -1 ,
	PLAN_PROGRAM_DIM_ID INTEGER NOT NULL DEFAULT -1,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	PPC_FLAG VARCHAR(1),
	SOURCE_PRODUCT_DIM_ID INTEGER NOT NULL DEFAULT -1 ,
	CLASS_DIM_ID INTEGER NOT NULL DEFAULT -1 ,
	CLASS_PLAN_DIM_ID INTEGER NOT NULL DEFAULT -1 ,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT UK_F_DIM_PLAN_LOB_PLAN_BUSINESS_CLASS_PROD UNIQUE (PLAN_DIM_ID,LINE_OF_BUSINESS_DIM_ID,CLASS_PLAN_DIM_ID,CLASS_DIM_ID,SOURCE_PRODUCT_DIM_ID),
	CONSTRAINT FK_DIM_PLAN_LOB_CLASS_DIM_ID FOREIGN KEY (CLASS_DIM_ID) REFERENCES COMPACT.DIM_CLASS(CLASS_DIM_ID),
	CONSTRAINT FK_DIM_PLAN_LOB_LINE_OF_BUSINESS_DIM_ID FOREIGN KEY (LINE_OF_BUSINESS_DIM_ID) REFERENCES COMPACT.DIM_LINE_OF_BUSINESS(LINE_OF_BUSINESS_DIM_ID),
	CONSTRAINT FK_DIM_PLAN_LOB_PLAN_DIM_ID FOREIGN KEY (PLAN_DIM_ID) REFERENCES COMPACT.DIM_PLAN(PLAN_DIM_ID)
);
