CREATE TABLE IF NOT EXISTS COMPACT.DIM_FEE_SCHEDULE (
	FEE_SCHEDULE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_FEE_SCHEDULE_DIM_ID_ PRIMARY KEY,
	FEE_SCHEDULE_CODE VARCHAR(70) NOT NULL CONSTRAINT UK_F_DIM_FEE_SCHEDULE_FEE_SCHEDULE_CODE UNIQUE,
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36)
);
