CREATE TABLE IF NOT EXISTS COMPACT.DIM_CONVERTED_FROM
    (
       CONVERTED_FROM_DIM_ID INTEGER NOT NULL,
        CONVERTED_FROM VARCHAR(8) NOT NULL,
        CONVERTED_FROM_DESC VARCHAR(60),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        CONVERTED_FROM_TYPE VARCHAR(1),
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_CNVRTD_FRM PRIMARY KEY (CONVERTED_FROM_DIM_ID)
    );
