CREATE TABLE IF NOT EXISTS COMPACT.FACT_CLAIM_RX_ADDITION (
COMPANY_DIM_ID NUMBER NOT NULL,
SEQ_CLAIM_ID VARCHAR(50) NOT NULL,
LINE_NUMBER NUMBER NOT NULL,
SUB_LINE_CODE VARCHAR(1) NOT NULL,
APPROVED_NET_PATIENT_PAY_AMT NUMBER(9,2),
PLAN_COPAY_AMT NUMBER(9,2),
PRODUCT_SELECTION_DIFF_AMT NUMBER(9,2),
PROF_SVC_FEE_CONTRACT_AMT NUMBER(9,2),
INCENTIVE_BILLED_AMT NUMBER(9,2),
OTHER_ADJUSTMENT_AMT NUMBER(9,2),
OTHER_BILLED_AMT NUMBER(9,2),
PATIENT_DEDUCTIBLE_AMT NUMBER(9,2),
INGREDIENT_COST_CALCULATED_AMT NUMBER(9,2),
USUAL_BILLING_AMT NUMBER(18,2),
DRUG_UNIT_COST_AMT NUMBER(13,5),
OUT_OF_NETWORK_PENALTY_AMT NUMBER(9,2),
ALLOWED_SALES_TAX_AMT NUMBER(9,2),
REFILLS_AUTHORIZED NUMBER(3,0),
REFILL_CODE_DIM_ID NUMBER NOT NULL DEFAULT -1,
PAYMENT_TYPE_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_OTC_CODE_DIM_ID NUMBER NOT NULL DEFAULT -1,
DISPENSE_AS_WRITTEN_DIM_ID NUMBER NOT NULL DEFAULT -1,
OTHER_COVERAGE_CODE_DIM_ID NUMBER NOT NULL DEFAULT -1,
COMPOUND_CODE_DIM_ID NUMBER NOT NULL DEFAULT -1,
REIMBURSEMENT_BASIS_DIM_ID NUMBER NOT NULL DEFAULT -1,
COST_DETERMIN_BASIC_DIM_ID NUMBER NOT NULL DEFAULT -1,
APPROVED_COST_SOURCE_DIM_ID NUMBER NOT NULL DEFAULT -1,
PLAN_DRUG_STATUS_DIM_ID NUMBER NOT NULL DEFAULT -1,
PLAN_QUALIFIER_CODE_DIM_ID NUMBER NOT NULL DEFAULT -1,
SYS7 VARCHAR(24),
SYS8 VARCHAR(24),
SYS9 VARCHAR(24),
DETAIL_SVC_DATE DATE,
POST_DATE DATE,
RX_ORIGINATION_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
SVC_PROV_REL_CODE VARCHAR(6),
SVC_PROV_DISPENSER_CLASS VARCHAR(3),
SVC_PROV_DISPENSER_TYPE VARCHAR(3),
RX_PRODUCT_QUALIFIER_DIM_ID NUMBER NOT NULL DEFAULT -1,
DRUG_LABLE_NAME VARCHAR(13),
DRUG_DOSAGE_FORM VARCHAR(4),
DRUG_STRENGTH_OR_UNITS VARCHAR(13),
PRODUCT_MANUFACTURER VARCHAR(10),
DRUG_STRENGTH_IN_METRIC VARCHAR(11),
ROUTE_OF_ADMINISTRATION VARCHAR(2),
DOSAGE_FORM_MEDI_SPAN VARCHAR(4),
RX_MEMB_CARDHOLDER_REL_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_PRIORAUTH_QUALIFIER_DIM_ID NUMBER NOT NULL DEFAULT -1,
PRIOR_AUTH_REASON_CODE VARCHAR(2),
CARDHOLDER_ID VARCHAR(20),
CARDHOLDER_INFO_1 VARCHAR(100),
CARDHOLDER_INFO_2 VARCHAR(100),
RX_THIRD_PARTY_RESTRIC_DIM_ID NUMBER NOT NULL DEFAULT -1,
UNIT_DOSE_IND VARCHAR(1),
GENERIC_CODE_NUMBER VARCHAR(5),
GENERIC_CODE_SEQ VARCHAR(6),
TRANSACTION_CODE VARCHAR(2),
CLAIM_MESSAGE VARCHAR(40),
RX_BENEFIT_MAX_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_CLIENT_TYPE_DIM_ID NUMBER NOT NULL DEFAULT -1,
BENEFIT_MAX_APPLIED_AMT NUMBER(9,2),
RX_THERAPEUTIC_GROUP_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_FORMULARY_CLAIM_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_MEDICAL_CLAIM_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_PRIORAUTH_CLAIM_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_TRANSPLANT_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_INJECTABLE_PROD_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RXSOL_FORMULARY_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_HALF_TAB_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
DRUG_PRICING_TIER VARCHAR(2),
RX_ALT_INSURANCE_FLAG_DIM_ID NUMBER NOT NULL DEFAULT -1,
ADMIN_FEE NUMBER(9,2),
SYS15 VARCHAR(60),
SYS16 VARCHAR(60),
DRUG_LBL_NAM_DSG_FRM_STNGTH VARCHAR(30),
CARDHOLDER_INFO_3 VARCHAR(50),
RX_ORIGIN VARCHAR(1),
PATIENT_RESIDENCE_DIM_ID NUMBER NOT NULL DEFAULT -1,
RX_SOURCE_PLAN_CODE VARCHAR(10),
RX_SUBMIT_TIME VARCHAR(16),
OOP_MAX_AMT NUMBER(9,2),
REMITTANCE_TYPE_DIM_ID NUMBER NOT NULL DEFAULT -1,
REG_DISASTER_OVERRIDE VARCHAR(1),
CLIENT_COPAY NUMBER(9,2),
RX_SOURCE_PLAN_TYPE VARCHAR(10),
REJECT_1_REASON_DIM_ID NUMBER NOT NULL DEFAULT -1,
REJECT_2_REASON_DIM_ID NUMBER NOT NULL DEFAULT -1,
REJECT_3_REASON_DIM_ID NUMBER NOT NULL DEFAULT -1,
GROSS_AMT_DUE NUMBER(13,2),
REJECT_MESSAGE1 VARCHAR(40),
REJECT_MESSAGE2 VARCHAR(40),
REJECT_MESSAGE3 VARCHAR(40),
PROV_QUALIFIER_DIM_ID NUMBER NOT NULL DEFAULT -1,
PRESC_QUALIFIER_DIM_ID NUMBER NOT NULL DEFAULT -1,
PRESCRIPTION_SERIAL_NO VARCHAR(12),
SUBMISSION_CLARIFICATION_CODE NUMBER,
MAIL_ORDER_RX_INDICATOR VARCHAR(1),
SDA VARCHAR(4),
RISKGROUP VARCHAR(4),
HICN VARCHAR(20),
RSN_FOR_SVC_CODE VARCHAR(2),
PERSONAL_SVC_CODE VARCHAR(2),
RESULT_OF_SVC_CODE VARCHAR(2),
OTH_PAYER_REJ_COUNT NUMBER,
OTH_PAYER_REJ_CODE1 VARCHAR(3),
OTH_PAYER_REJ_CODE2 VARCHAR(3),
OTH_PAYER_REJ_CODE3 VARCHAR(3),
BENEFIT_STAGE_COUNT NUMBER,
BENEFIT_STAGE_QLFR1 NUMBER,
BENEFIT_STAGE_AMT1 NUMBER(11,2),
SPL_PACKAGING_IND NUMBER,
RX_SVC_TYPE NUMBER,
OTH_PAYER_SALES_TAX NUMBER(11,2),
OTH_PAYER_ID VARCHAR(10),
FLAT_TAX_SUBMITTED NUMBER(11,2),
DISPENSING_FEE_SUBMITTED NUMBER(11,2),
OTH_PAYER1_BIN NUMBER,
OTH_PAYER1_PAID_AMT NUMBER(11,2),
OTH_PAYER1_SALES_TAX_AMT NUMBER(11,2),
OTH_PAYER1_COMP_PREP_AMT NUMBER(11,2),
OTH_PAYER2_BIN NUMBER,
OTH_PAYER2_PAID_AMT NUMBER(11,2),
OTH_PAYER2_SALES_TAX_AMT NUMBER(11,2),
OTH_PAYER2_COMP_PREP_AMT NUMBER(11,2),
QUANTITY_PRESCRIBED NUMBER(15,1) DEFAULT 0,
SUBMISSION_CLARIFICATION_CD_1 VARCHAR(2),
SUBMISSION_CLARIFICATION_CD_2 VARCHAR(2),
SUBMISSION_CLARIFICATION_CD_3 VARCHAR(2),
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT PK_F_FACT_CLAIM_RX_ADDITION PRIMARY KEY (COMPANY_DIM_ID,SEQ_CLAIM_ID,LINE_NUMBER,SUB_LINE_CODE),
CONSTRAINT FK_FACT_CLAIM_RX_PLACE_OF_SVC FOREIGN KEY (PATIENT_RESIDENCE_DIM_ID) REFERENCES COMPACT.DIM_PLACE_OF_SVC(PLACE_OF_SVC_DIM_ID),
CONSTRAINT FK_FACT_CLAIM_RX_REASON_CODE_1 FOREIGN KEY (REJECT_1_REASON_DIM_ID) REFERENCES COMPACT.DIM_REASON_CODE(REASON_DIM_ID),
CONSTRAINT FK_FACT_CLAIM_RX_REASON_CODE_2 FOREIGN KEY (REJECT_2_REASON_DIM_ID) REFERENCES COMPACT.DIM_REASON_CODE(REASON_DIM_ID),
CONSTRAINT FK_FACT_CLAIM_RX_REASON_CODE_3 FOREIGN KEY (REJECT_3_REASON_DIM_ID) REFERENCES COMPACT.DIM_REASON_CODE(REASON_DIM_ID)
);
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.COMPANY_DIM_ID IS 'Represents the link to DIM_COMPANY table that describes UHC Community and State Company created codes for every plan used in the Data Warehouse. Queries should be restricting or grouping by COMPANY_DIM_ID. This table is linked to several tables describing the company and state information. i.e. AC Pennsylvania with corporation UnitedHealthGroup under the AmeriChoice division from the NorthEast region is from the state of Pennsylvania.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SEQ_CLAIM_ID IS 'Sequential unique claim id created when claims are inserted into the source system.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.LINE_NUMBER IS 'Claims can contain several detail lines and are given a line number.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SUB_LINE_CODE IS 'A single character code identifying if the claim detail line has been ''A''djusted or ''R''eversed. If the claim line has not been adjusted or reversed the field will have a blank value '' '' (space), -1 = N/A or 0 = UNK. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.APPROVED_NET_PATIENT_PAY_AMT IS 'Patient net amount for the pharmacy claim.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PLAN_COPAY_AMT IS 'Copayment amount from the patient''splan program. A copayment (or copay) is a fixed-dollar amount that you pay each time for certain services. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PRODUCT_SELECTION_DIFF_AMT IS 'The difference amount between the Generic or Brand name prescriptions.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PROF_SVC_FEE_CONTRACT_AMT IS 'Provider contract service fee amount.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.INCENTIVE_BILLED_AMT IS 'Incentive billed amount.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.OTHER_ADJUSTMENT_AMT IS 'Other adjustment amounts.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.OTHER_BILLED_AMT IS 'Other billed amounts.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PATIENT_DEDUCTIBLE_AMT IS 'The Member''s out of pocket amount paid towards deductible.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.INGREDIENT_COST_CALCULATED_AMT IS 'Pharmacy claim prescription ingredient calculated cost amount.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.USUAL_BILLING_AMT IS 'Usual or customary billing amount as submitted';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.DRUG_UNIT_COST_AMT IS 'Unit cost per prescription drug.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.OUT_OF_NETWORK_PENALTY_AMT IS 'Provider out of network penalty fee amount.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.ALLOWED_SALES_TAX_AMT IS 'Sales tax amount.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REFILLS_AUTHORIZED IS 'Prescription Solutions Inc (PSI) Pharmacy authorized refills on the prescription. i.e. 15 refills.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REFILL_CODE_DIM_ID IS 'Represents the link to the DIM_RX_REFILL_CODE table describing how many refills are on the prescription. i.e. 100 = 00 New Prescription or 15 = 15 15 refills.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PAYMENT_TYPE_DIM_ID IS 'Represents the link to the DIM_RX_PAYMENT_TYPE table describing the payment type. Values are 1 = P Pharmacy, 2 = M Member, 3 = A Medical provider, 0 = UNK UNKNOWN and -1 = N/A N/A.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.RX_OTC_CODE_DIM_ID IS 'Represents the link to the DIM_RX_OTC_CODE describing the pharmacy over the counter medication code. i.e. 1 = O OTC,single source or 4 = S RX, multi source.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.DISPENSE_AS_WRITTEN_DIM_ID IS 'Represents the link to the DIM_RX_DISPENSE_AS_WRITTEN table describing if the pharmacy prescription was substituted or dispensed as written. i.e. 1 = 1 substitution not allowed by prescriber or 2 = 2 substitution allowed patient requested product dispensed.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.OTHER_COVERAGE_CODE_DIM_ID IS 'Represents the link to the DIM_RX_OTHER_COVERAGE_CODE table describing the pharmacy other carrier coverage. i.e. 1 = 01 no other coverage identified or 8 = 08 claim is billing for copay. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.COMPOUND_CODE_DIM_ID IS 'Represents the link to the DIM_RX_COMPOUND_CODE describing if the pharmacy makes and sells prescription medications. A compounding pharmacy can often concoct drug formulas that are specially tailored to patients. Values are 1 = 0 not specified, 2 = 1 not a compound, 3 = 2 compound, 0 = UNK UNKNOWN and -1 = N/A N/A. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REIMBURSEMENT_BASIS_DIM_ID IS 'Represents the link to the DIM_RX_REIMBURSEMENT_BASIS table describing the code used in pharmacy reimbursement formula from the state. i.e. 6 = 6 mac (Maximum Allowable Cost) or 2 = 2 awp (Average Wholesale Price) reduced to awp.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.COST_DETERMIN_BASIC_DIM_ID IS 'Represents the link to the DIM_RX_COST_DETERMIN_BASIC table that describes the basic cost determinate for the pharmacy prescription. i.e. 4 = 04 usual and customary paid as submitted or 7 = 07 mac pricing ingredient cost reduced to mac pricing.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.APPROVED_COST_SOURCE_DIM_ID IS 'Represents the link to the DIM_RX_APPROVED_COST_SOURCE table describing the Pharmacy approved cost source. i.e. 27 = MAC01 maximum allowed cost list 01 or 3 = AVGGENERIC avg.generic cost. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PLAN_DRUG_STATUS_DIM_ID IS 'Represents the link to the DIM_RX_PLAN_DRUG_STATUS table describing the plan or program prescription status. The prescription drug might be on the list or formulary. Values are 1 = C non-formulary, 2 = F Formulary, 3 = G non-formulary, 4 = K formulary, non-max benefit, 5 = L non-formulary, non-max benefit, 6 = S S, 7 = 5 5, 0 = UNK UNKNOWN and -1 = N/A N/A.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PLAN_QUALIFIER_CODE_DIM_ID IS 'Represents the link to the DIM_RX_PLAN_QUALIFIER_CODE table describing the pharmacy prescription pricing plan or program that they qualify for. i.e. 1 = 1 open formulary or 8 = 8 6 tier pricing. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SYS7 IS 'For system use only. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SYS8 IS 'For system use only. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SYS9 IS 'For system use only. ';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.DRUG_LBL_NAM_DSG_FRM_STNGTH IS 'drug label name, dosage form, and strength/units of product identified by ndc';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.CARDHOLDER_INFO_3 IS 'Card holder City,State,Zip';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.RX_ORIGIN IS 'rx origin code';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PATIENT_RESIDENCE_DIM_ID IS 'patient residence as submitted by pharmacy it represents dim_place_of_svc table';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.RX_SOURCE_PLAN_CODE IS 'plan code or alternate plan code underwhich prescriptionwas processed';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.RX_SUBMIT_TIME IS 'time rx was received for processing';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.OOP_MAX_AMT IS 'amount from this claim applied to the member or familys periodic out-of-pocket max.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REMITTANCE_TYPE_DIM_ID IS 'remittance format C - check E - electronic fund transfer M - journal entry it represents DIM_RX_FLAG_INDICATOR table';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REG_DISASTER_OVERRIDE IS 'regional disaster override populate with y if source field in extract is not blank.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.CLIENT_COPAY IS 'sum of copay and co-insurance';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.RX_SOURCE_PLAN_TYPE IS 'type code taken from plan code detail.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REJECT_1_REASON_DIM_ID IS 'The Reason for rejecting the claim reason code1 it represents DIM_REASON_CODE table reason_Code_type is RX';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REJECT_2_REASON_DIM_ID IS 'The Reason for rejecting the reason code2 it represents DIM_REASON_CODE table reason_Code_type is RX';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REJECT_3_REASON_DIM_ID IS 'The Reason for rejecting the claim message3 it represents DIM_REASON_CODE table reason_Code_type is RX';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.GROSS_AMT_DUE IS 'Gross Amount Due';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REJECT_MESSAGE1 IS 'The descriptive inforamtion for rejecting the claim message1';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REJECT_MESSAGE2 IS 'The descriptive inforamtion for rejecting the claim message2';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.REJECT_MESSAGE3 IS 'The descriptive inforamtion for rejecting the claim message3';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PROV_QUALIFIER_DIM_ID IS 'qualifier used to define code set that identifies the service/provider';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.PRESC_QUALIFIER_DIM_ID IS 'qualifier used to define,which code set, is being used to identify the prescriber.';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.QUANTITY_PRESCRIBED IS 'Quantity prescribed by Physician, used for Scheduled drugs';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SUBMISSION_CLARIFICATION_CD_1 IS 'Submission clarification code 1 for quantity_prescribed';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SUBMISSION_CLARIFICATION_CD_2 IS 'Submission clarification code 2 for quantity_prescribed';
COMMENT ON COLUMN COMPACT.FACT_CLAIM_RX_ADDITION.SUBMISSION_CLARIFICATION_CD_3 IS 'Submission clarification code 3 for quantity_prescribed';
