CREATE TABLE IF NOT EXISTS COMPACT.UNET_PROCEDURE_MODIFIER_CODE
    (
        PROC_MOD_SYS_ID NUMBER NOT NULL CONSTRAINT PK_PROCEDURE_MODIFIER_CODE PRIMARY KEY,
        PROC_MOD_CD VARCHAR(2),
        PROC_MOD_DESC VARCHAR(80) NOT NULL,
        PROC_MOD_GRP_CD VARCHAR(2) NOT NULL,
        PROC_MOD_GRP_DESC VARCHAR(25) NOT NULL,
        PROC_MOD_PROV_SPCL_NM VARCHAR(10) NOT NULL,
        UPDT_USER_ID VARCHAR(8) NOT NULL,
        LOAD_DT DATE NOT NULL,
        UPDT_DT DATE NOT NULL,
		SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_PROCESS_ID VARCHAR(36)
    );