CREATE TABLE IF NOT EXISTS COMPACT.DIM_LANGUAGE (
LANGUAGE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_LANGUAGE_DIM_ID PRIMARY KEY,
LANGUAGE_CODE VARCHAR(5) NOT NULL,
LANGUAGE_DESC VARCHAR(30),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
CONVERTED_FROM_DIM_ID INTEGER NOT NULL DEFAULT -1,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT UK_F_DIM_LANGUAGE_LANGUAGE_CODE_CONV_FROM UNIQUE (LANGUAGE_CODE,CONVERTED_FROM_DIM_ID),
CONSTRAINT FK_DIM_LANGUAGE_LANGUAGE_CODE_CONV_FROM FOREIGN KEY (CONVERTED_FROM_DIM_ID) REFERENCES COMPACT.DIM_CONVERTED_FROM(CONVERTED_FROM_DIM_ID) 
);
