CREATE TABLE IF NOT EXISTS COMPACT.DIM_DRG_CODE (
DRG_CODE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_DRG_CODE_DIM_ID PRIMARY KEY,
DRG_CODE VARCHAR(6) NOT NULL,
DRG_CODE_SHORT_DESC VARCHAR(30),
DRG_CODE_MDC_CODE VARCHAR(2),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
DRG_CODE_CLASS VARCHAR(4),
DRG_CODE_TYPE VARCHAR(10),
DRG_CODE_LONG_DESC VARCHAR(300),
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT UK_F_DIM_DRG_CODE_DRG_CODE_CODE_TYPE UNIQUE(DRG_CODE,DRG_CODE_TYPE)
);
