CREATE TABLE IF NOT EXISTS COMPACT.DIM_WHOLE_CLAIM_STATUS
    (
        WHOLE_CLAIM_STATUS_DIM_ID INTEGER NOT NULL,
        WHOLE_CLAIM_STATUS VARCHAR(1) NOT NULL,
        WHOLE_CLAIM_STATUS_DESC VARCHAR(20),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_WHLE_CLM_STS PRIMARY KEY (WHOLE_CLAIM_STATUS_DIM_ID)
    );
