CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROVIDER_IDENT (
PROV_DIM_ID NUMBER NOT NULL,
IDENT_TYPE_DIM_ID NUMBER NOT NULL,
IDENT_VALUE VARCHAR(100) NOT NULL,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT PK_F_DIM_PROVIDER_IDENT_DIM_ID PRIMARY KEY (PROV_DIM_ID,IDENT_TYPE_DIM_ID)
);
