CREATE TABLE IF NOT EXISTS COMPACT.DIM_CPT_CAT_LVL_1 (
    CPT_CAT_LVL_1_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_CPT_CAT_LVL_1_DIM_ID PRIMARY KEY,
    CPT_CAT_LVL_1_DESC VARCHAR(50),
    CPT_CAT_LVL_1_SHORT_DESC VARCHAR(25),
    DW_INSERT_DATETIME DATE,
    DW_UPDATE_DATETIME DATE,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);
