CREATE TABLE IF NOT EXISTS COMPACT.UNET_CLAIM_ORIGINATION_CODE
    (
        CLM_ORIG_CD VARCHAR(2) NOT NULL,
        CLM_ORIG_DESC VARCHAR(50) NOT NULL,
        UPDT_USER_ID VARCHAR(8) NOT NULL,
        LOAD_DT DATE NOT NULL,
        UPDT_DT DATE NOT NULL,
		SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_PROCESS_ID VARCHAR(36),
		CONSTRAINT PK_CLM_ORIG_CD PRIMARY KEY (CLM_ORIG_CD) not enforced
    );