CREATE TABLE IF NOT EXISTS COMPACT.DIM_RX_CLIENT_TYPE (
    RX_CLIENT_TYPE_DIM_ID NUMBER NOT NULL,
    RX_CLIENT_TYPE VARCHAR(3) NOT NULL,
    RX_CLINET_TYPE_DESC VARCHAR(40),
    DW_INSERT_DATETIME DATETIME NOT NULL,
    DW_UPDATE_DATETIME DATETIME NOT NULL,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36),
    CONSTRAINT PK_RX_CLIENT_TYPE_DIM_ID PRIMARY KEY (RX_CLIENT_TYPE_DIM_ID)
);
