create TABLE IF NOT EXISTS COMPACT.IMDM_INDV cluster by (IMDM_ID,SSN,SBSCRID,MDCDID,MDCRID,URSLID,RXCL1_CAGMID,RXCL2_CAGMID,RXCC_CAGMID,EDWPRSID,SMRTPRSID)(
	IMDM_ID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique Identifier assigned to an individual by enterprise individual master data management [iMDM EID] ',
	SRC_CD VARCHAR(100) COMMENT 'Code relating to specific source of the record',
	SSN VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Social Security Number is a numerical identifier assigned to U.S. citizens and some residents to track their income and determine benefits.',
	MDCDID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Medicaid number also known as a recipient number [MRN] or individual number is a 9-digit number than is assigned by CMS on the State Beneift card. Doctors and pharmacies use this number for billing.',
	SBSCRID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique Identifier assigned by the insurance company to a person who pays for health insurance premiums or whose employment is the basis for membership in the insurance plan during the coverage period.',
	MDCRID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique Identifier assigned by Federal Govt to individuals who qualify for Medicare Benefits. This is also called as HICN used to be SSN followed by a letter which is replaced by Medical Beneficiary Number [MBI]',
	URSLID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique identifier assigned by Galaxy system to an individual with in UHG',
	RXCL1_CAGMID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique identifier assigned by Optum Rx[BOOK 1]system [CARRIER,GROUP,MEMBER]',
	RXCL2_CAGMID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique identifier assigned by Optum Rx system [BOOK 2] [CARRIER,GROUP,MEMBER]',
	RXCC_CAGMID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique identifier assigned by Optum Rx [CATAMARAN] system [CARRIER,GROUP,MEMBER,INSTANCE]',
	EDWPRSID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique Identifier- EDW Person ID assigned by Optum Behavioral Eneterprise Data Warehouse to an individual',
	SMRTPRSID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Unique Identifier -Diamond ID assigned by SMART/BASIS to an individual who is having a Community and State Plan',
	BH_IND VARCHAR(1) COMMENT 'Indicates if individual ever had Behavioral plan with UHG',
	FST_NM VARCHAR(100) COMMENT 'First/Given name of the individual',
	LST_NM VARCHAR(100) COMMENT 'Last/Surname/Family name of the individual',
	BTH_DT DATE COMMENT 'Date of birth of the individual',
	DCSD_DT DATE COMMENT 'Deceased Date of the individual',
	GDR_CD VARCHAR(3) COMMENT 'Gender Code of the individual',
	ADDR_LN_1 VARCHAR(100) COMMENT 'Street address for primary address of the individual',
	ADDR_LN_2 VARCHAR(100) COMMENT 'The apartment/suite number for primary address of the individual',
	ADDR_LN_3 VARCHAR(100) COMMENT 'The apartment/suite number for primary address of the individual',
	CTY_NM VARCHAR(200) COMMENT 'Name of the city for primary address of the individual',
	ST_CD VARCHAR(100) COMMENT 'State Code for primary address of the individual',
	PST_CD VARCHAR(100) COMMENT 'Postal/Zip code for primary address of the individual',
	CNTY_NM VARCHAR(200) COMMENT 'Name of the county for primary address of the individual',
	CNTRY_CD VARCHAR(100) COMMENT 'Name of the country for primary address of the individual',
	LAT NUMBER(15,8) COMMENT 'Latitude for primary address of the individual',
	LONG NUMBER(15,8) COMMENT 'Longitude for primary address of the individual',
	ADDR_STD_IND VARCHAR(5) COMMENT 'Indicates if the address was standarized in iMDM',
	ADDR_PRF_IND VARCHAR(5) COMMENT 'Indicates if the address is indicated as preferred in iMDM',
	ADDR_VLD_IND VARCHAR(5) COMMENT 'Indicates if the address was validated in iMDM',
	EML_ADDR VARCHAR(275) COMMENT 'Primary Electronical mail address provided by the indiviual',
	EML_ADDR_PRF_IND VARCHAR(5) COMMENT 'Indicates if the email address is indicated as preferred in iMDM',
	EML_ADDR_VLD_IND VARCHAR(5) COMMENT 'Indicates if the email address was validated in iMDM',
	PH_NBR VARCHAR(50) COMMENT 'Primary Phone number provider by the individual',
	PH_NBR_TYP VARCHAR(15) COMMENT 'Primary Phone number type [home/work/mobile] provider by the individual',
	PH_NBR_PRF_IND VARCHAR(5) COMMENT 'Indicates if the phone number is indicated as preferred in iMDM',
	PH_NBR_VLD_IND VARCHAR(5) COMMENT 'Indicates if the phone number was validated in iMDM',
	CDC_FLAG VARCHAR(1) COMMENT 'Indicates if record is inserted/updated/split/merge/delete from iMDM in OBHDP',
	SF_INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Indicates the timestamp when the record is inserted/updated/split/merge/delete from iMDM in OBHDP',
	SF_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Indicates the timestamp when the record is inserted/updated/split/merge/delete from iMDM in OBHDP',
	SF_PROCESS_ID VARCHAR(36) COMMENT 'Indicates the process through which the record is inserted/updated/split/merge/delete from iMDM in OBHDP',
	constraint INDV_DEM_PK primary key (IMDM_ID, SSN, SBSCRID, MDCDID, MDCRID, URSLID, RXCL1_CAGMID, RXCL2_CAGMID, RXCC_CAGMID, EDWPRSID, SMRTPRSID)
);