CREATE TABLE IF NOT EXISTS COMPACT.DIM_AUTO_ADJUD_FLAG (
	AUTO_ADJUD_FLAG_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_AUTO_ADJUD_FLAG_DIM_ID PRIMARY KEY,
	AUTO_ADJUD_FLAG_DESC VARCHAR(30),
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36)
);
