CREATE TABLE IF NOT EXISTS COMPACT.DIM_LINE_OF_BUSINESS (
	LINE_OF_BUSINESS_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_LINE_OF_BUSINESS_DIM_ID PRIMARY KEY,
	LINE_OF_BUSINESS VARCHAR(5) NOT NULL CONSTRAINT UK_F_DIM_LINE_OF_BUSINESS_BUSINESS UNIQUE,
	LINE_OF_BUSINESS_DESC VARCHAR(30),
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	LINE_OF_BUSINESS_TYPE_DIM_ID INTEGER,
	RECORD_STATUS_DIM_ID INTEGER,
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);
