CREATE TABLE IF NOT EXISTS COMPACT.DIM_PRODUCT (
PRODUCT_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_PRODUCT_DIM_ID PRIMARY KEY,
PRODUCT_CODE VARCHAR(7) NOT NULL CONSTRAINT UK_F_DIM_PRODUCT_PRODUCT_CODE UNIQUE,
PRODUCT_DESC VARCHAR(35),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
