CREATE TABLE IF NOT EXISTS COMPACT.DIM_LINE_OF_BUSINESS_TYPE (
	LINE_OF_BUSINESS_TYPE_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_LINE_OF_BUSINESS_TYPE_DIM_ID PRIMARY KEY,
	LINE_OF_BUSINESS_TYPE_DESC VARCHAR(8),
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
    SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    SF_PROCESS_ID VARCHAR(36)
);
