CREATE TABLE IF NOT EXISTS COMPACT.DIM_COSMOS_CUST_SEG (
	COSMOS_CUST_SEG_DIM_ID INTEGER NOT NULL CONSTRAINT PK_F_DIM_COSMOS_CUST_SEG_DIM_ID PRIMARY KEY,
	COSMOS_CUST_SEG VARCHAR(9) NOT NULL CONSTRAINT UK_F_DIM_COSMOS_CUST_SEG_COSMOS_CUST_SEG UNIQUE,
	COSMOS_CUST_SEG_DESC VARCHAR(120),
	DW_INSERT_DATETIME DATETIME,
	DW_UPDATE_DATETIME DATETIME,
	COMPANY_DIM_ID INTEGER NOT NULL DEFAULT -1 ,
	LEGAL_ENTITY VARCHAR(10),
	FIN_PRODUCT VARCHAR(10),
	SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	SF_PROCESS_ID VARCHAR(36),
	CONSTRAINT FK_DIM_COSMOS_CUST_SEG_COMPANY_DIM_ID FOREIGN KEY (COMPANY_DIM_ID) REFERENCES COMPACT.DIM_COMPANY(COMPANY_DIM_ID)
);
