CREATE TABLE IF NOT EXISTS COMPACT.DIM_REASON_CODE_GROUP
    (
        REASON_GROUP_DIM_ID INTEGER NOT NULL,
        REASON_GROUP_CODE VARCHAR(10),
        REASON_GROUP_TYPE VARCHAR(2),
        REASON_CODE_GROUP_DESC VARCHAR(30),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_RSN_CD_GRP PRIMARY KEY (REASON_GROUP_DIM_ID),
        CONSTRAINT UK_F_DIM_RSN_CD_GRP UNIQUE (REASON_GROUP_CODE, REASON_GROUP_TYPE)
    );
