CREATE TABLE IF NOT EXISTS COMPACT.TB_PRD_PKG_ALT (
PKG_ALT_SYS_ID NUMBER(10) NOT NULL,
PKG_SYS_ID NUMBER(10) NULL,
PKG_ALT_ID VARCHAR(60) NULL,
SRC_REC_CRT_DTTM DATETIME NULL,
SRC_REC_UPDT_DTTM DATETIME NULL,
SRC_REC_CRT_USER_ID varchar(15) NULL,
SRC_REC_UPDT_USER_ID varchar(15) NULL,
REC_CRT_DTTM DATETIME NOT NULL,
REC_UPDT_DTTM DATETIME NOT NULL,
REC_XTRCT_SRC_CD varchar(4) NOT NULL,
REC_INPUT_SRC_CD varchar(4) NOT NULL,
BTCH_LOAD_DT DATE NOT NULL,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT PK_TB_PRD_PKG_ALT PRIMARY KEY (PKG_ALT_SYS_ID)
);