CREATE TABLE IF NOT EXISTS COMPACT.DIM_PLAN_PROGRAM_TYPE (
PLAN_PROGRAM_TYPE_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_PLAN_PROGRAM_TYPE_DIM_ID PRIMARY KEY,
PROGRAM_TYPE_CODE VARCHAR(6) NOT NULL,
PROGRAM_TYPE_DESC VARCHAR(30),
DW_INSERT_DATETIME DATETIME,
DW_UPDATE_DATETIME DATETIME,
MEDICARE_DUAL_FLAG_DIM_ID NUMBER,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT UK_F_DIM_PLAN_PROGRAM_TYPE_CODE UNIQUE (PROGRAM_TYPE_CODE),
CONSTRAINT FK_DIM_PLAN_PROGRAM_TYPE_DIM_MEDICARE_DUAL_FLAG FOREIGN KEY (MEDICARE_DUAL_FLAG_DIM_ID) REFERENCES COMPACT.DIM_MEDICARE_DUAL_FLAG (MEDICARE_DUAL_FLAG_DIM_ID)
);
COMMENT ON TABLE COMPACT.DIM_PLAN_PROGRAM_TYPE IS 'This table stores attributes that describe program types like Dual or Non Dual.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.PLAN_PROGRAM_TYPE_DIM_ID IS 'Represents the link to DIM_PLAN_PROGRAM_TYPE table describing a list of program types and if the types are Medicare Dual eligible 1 = Non-Dual and 2 = Dual. i.e. MCRD = MCR dual (Medicare Dual eligible) or HCB = Home/Comm-based program.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.PROGRAM_TYPE_CODE IS 'Codes that represent the program type that a plan may have, specified by company. i.e. TANF, CMS, CHP and SSI.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.PROGRAM_TYPE_DESC IS 'Describes the program type that a plan may have, specified by company. i.e. TANF, San Diego CMS, CHP and SSI without MCR.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.DW_INSERT_DATETIME IS 'Date the record was added to the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.DW_UPDATE_DATETIME IS 'Date the record was updated in the Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.MEDICARE_DUAL_FLAG_DIM_ID IS 'Represents the link to DIM_MEDICARE_DUAL_FLAG table describing if the program types are Medicare Dual eligible. Values are 1 = Non-Dual, 2 = Dual, 0 = Unknown and -1 = N/A.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.SF_INSERT_DATETIME IS 'Date the record was updated in the OBHDP Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.SF_UPDATE_DATETIME IS 'Date the record was updated in the OBHDP Data Warehouse.';
COMMENT ON COLUMN COMPACT.DIM_PLAN_PROGRAM_TYPE.SF_PROCESS_ID IS 'GUID of the process when the record was inserted or updated in the OBHDP Data Warehouse.';

