CREATE TABLE IF NOT EXISTS COMPACT.DIM_RATECELL_RATE
    (
        RTCL_RATE_DIM_ID INTEGER NOT NULL,
        RTCL_DIM_ID INTEGER NOT NULL,
        RTCL_MONTH DATE NOT NULL,
        RATE NUMBER(15,2) NOT NULL,
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        RTCL_GME NUMBER(15,2),
        RTCL_PAE NUMBER(15,1),
        RTCL_RISK_ADJ_RATE_SCORE NUMBER(15,4),
        MONTH_DIM_ID INTEGER NOT NULL DEFAULT -1,
        RTCL_CODE_DESC VARCHAR(200),
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_RATECELL_RATE PRIMARY KEY (RTCL_RATE_DIM_ID),
        CONSTRAINT UK_F_DIM_RATECELL_RATE_RTCL_DIM_ID_MNTH UNIQUE (RTCL_DIM_ID, RTCL_MONTH)
    );
