CREATE TABLE IF NOT EXISTS COMPACT.DIM_PROV_CRED_TYPE (
PROV_CRED_TYPE_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_PROV_CRED_TYPE_DIM_ID PRIMARY KEY,
PROV_CRED_TYPE VARCHAR(10) NOT NULL,
PROV_CRED_TYPE_DESC VARCHAR(100) NOT NULL,
CONVERTED_FROM_DIM_ID NUMBER NOT NULL,
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36),
CONSTRAINT UK_F_DIM_PROV_CRED_TYPE_CONV_FROM UNIQUE (PROV_CRED_TYPE,CONVERTED_FROM_DIM_ID),
CONSTRAINT FK_DIM_PROV_CRED_TYPE_DIM_CONVERTED_FROM FOREIGN KEY (CONVERTED_FROM_DIM_ID) REFERENCES COMPACT.DIM_CONVERTED_FROM(CONVERTED_FROM_DIM_ID)
);
