CREATE TABLE IF NOT EXISTS COMPACT.DIM_EDI_FLAG (
EDI_FLAG_DIM_ID NUMBER NOT NULL CONSTRAINT PK_F_DIM_EDI_FLAG_DIM_ID PRIMARY KEY,
EDI_FLAG_DESC VARCHAR(30),
DW_INSERT_DATETIME DATE,
DW_UPDATE_DATETIME DATE,
SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
SF_PROCESS_ID VARCHAR(36)
);
