CREATE TABLE IF NOT EXISTS COMPACT.DIM_UNCLEAN_FLAG
    (
        UNCLEAN_FLAG_DIM_ID INTEGER NOT NULL,
        UNCLEAN_FLAG_DESC VARCHAR(30),
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_UNCLN_FLG PRIMARY KEY (UNCLEAN_FLAG_DIM_ID)
    );
