CREATE TABLE IF NOT EXISTS COMPACT.UNET_ADJUDICATION_OFFICE
    (
		ADJD_OFC_SYS_ID NUMBER NOT NULL CONSTRAINT PK_ADJUDICATION_OFFICE PRIMARY KEY,
		        ADJD_OFC_CD VARCHAR(3) NOT NULL,
		        MBR_SITE_CD VARCHAR(3) NOT NULL,
		        ADJD_OFC_TXT VARCHAR(35) NOT NULL,
		        ENG_CD VARCHAR(1) NOT NULL,
		        CLM_SRC_CD VARCHAR(3) NOT NULL,
		        CLM_SRC_DESC VARCHAR(30) NOT NULL,
		        SRC_SYS_CD VARCHAR(2) NOT NULL,
		        UPDT_USER_ID VARCHAR(8) NOT NULL,
		        LOAD_DT DATE NOT NULL,
		        UPDT_DT DATE NOT NULL,
		SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
		SF_PROCESS_ID VARCHAR(36)
    );