CREATE TABLE ETL.SMART_DIM_RATECELL_PLAN_XWALK_L
(       RTCL_DIM_ID VARCHAR(50) NOT NULL,
        PLAN_DIM_ID VARCHAR(50) NOT NULL,
        COMPANY_DIM_ID VARCHAR(50) NOT NULL,
        RTCL_STATE VARCHAR(2) NOT NULL,
        GEOGRAPHY_COUNTY_DIM_ID VARCHAR(50) NOT NULL,
        GENDER_DIM_ID VARCHAR(50) NOT NULL,
        RTCL_AGE_BEGIN VARCHAR(50),
        RTCL_AGE_END VARCHAR(50),
        RTCL_AGE_TYPE VARCHAR(1),
        LINE_OF_BUSINESS_DIM_ID VARCHAR(50) NOT NULL,
        PLAN_PROGRAM_DIM_ID VARCHAR(50) NOT NULL,
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_RTCL_PLN_XWLK_XMULTI PRIMARY KEY (COMPANY_DIM_ID, PLAN_DIM_ID,
        GEOGRAPHY_COUNTY_DIM_ID, GENDER_DIM_ID, RTCL_AGE_BEGIN, RTCL_AGE_TYPE,
        LINE_OF_BUSINESS_DIM_ID)
);