CREATE TABLE FOUNDATION.DIM_RATECELL_PLAN_XWALK
    (
        RTCL_DIM_ID INTEGER NOT NULL,
        PLAN_DIM_ID INTEGER NOT NULL,
        COMPANY_DIM_ID INTEGER NOT NULL,
        RTCL_STATE VARCHAR(2) NOT NULL,
        GEOGRAPHY_COUNTY_DIM_ID INTEGER NOT NULL,
        GENDER_DIM_ID INTEGER NOT NULL,
        RTCL_AGE_BEGIN INTEGER,
        RTCL_AGE_END INTEGER,
        RTCL_AGE_TYPE VARCHAR(1),
        LINE_OF_BUSINESS_DIM_ID INTEGER NOT NULL,
        PLAN_PROGRAM_DIM_ID INTEGER NOT NULL,
        DW_INSERT_DATETIME DATETIME ,
        DW_UPDATE_DATETIME DATETIME ,
        SF_INSERT_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_UPDATE_DATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        SF_PROCESS_ID VARCHAR(36),
        CONSTRAINT PK_F_DIM_RATECELL_PLAN_XWLK PRIMARY KEY (COMPANY_DIM_ID, PLAN_DIM_ID,
        GEOGRAPHY_COUNTY_DIM_ID, GENDER_DIM_ID, RTCL_AGE_BEGIN, RTCL_AGE_TYPE,
        LINE_OF_BUSINESS_DIM_ID)
    );