COPY INTO SMART_DIM_RATECELL_PLAN_XWALK_L
 (
 RTCL_DIM_ID	,
 PLAN_DIM_ID	,
 COMPANY_DIM_ID	,
 RTCL_STATE	,
 GEOGRAPHY_COUNTY_DIM_ID	,
 GENDER_DIM_ID	,
 RTCL_AGE_BEGIN	,
 RTCL_AGE_END	,
 RTCL_AGE_TYPE	,
 LINE_OF_BUSINESS_DIM_ID	,
 PLAN_PROGRAM_DIM_ID	,
 DW_INSERT_DATETIME	,
 DW_UPDATE_DATETIME
 )FROM
 ( SELECT STG.$1,
          STG.$2,
          STG.$3,
          STG.$4,
          STG.$5,
          STG.$6,
          STG.$7,
          STG.$8,
          STG.$9,
          STG.$10,
          STG.$11,
          STG.$12,
          STG.$13 FROM
 @SMART_DIM_STAGE/DIM_RATECELL_PLAN_XWALK/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
