-- BBalboa 2022-01-07
-- Instructions:
-- 1 - Load to ETL, all tables
-- 2 - Load to FOUNDATION, all tables
-- 3 - Load to common format
-- 4 - Execute this script in SNOWFLAKE all at once
SELECT
   TBL.SRC_NAME SOURCE_TABLE, TBL.ETL_COUNT SOURCE_TABLE_COUNT, TBL.TRG_NAME TARGET_TABLE, TBL.FOUND_COUNT TARGET_TABLE_COUNT,
   NVL(SMRT.VAL_TBL,'N/A') SMART_TABLE, NVL(SMRT.VAL_CNTS,0) SMART_TABLE_COUNT,
   ELOG.VAL_CNTS SOURCE_LOG_TABLE_COUNT,
   FLOG.VAL_CNTS TARGET_LOG_TABLE_COUNT
FROM (
SELECT 'ETL.EDW_TB_DIM_MBR_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.EDW_TB_DIM_MBR_L ) ETL_COUNT, 'COMPACT.IMDM_EDW_INDV_KEY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.IMDM_EDW_INDV_KEY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_ADMIT_SOURCE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_ADMIT_SOURCE_L ) ETL_COUNT, 'COMPACT.DIM_ADMIT_SOURCE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_ADMIT_SOURCE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_AHFS_THER_CLASS_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_AHFS_THER_CLASS_CODE_L ) ETL_COUNT, 'COMPACT.DIM_AHFS_THER_CLASS_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_AHFS_THER_CLASS_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_AUTO_ADJUD_FLAG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_AUTO_ADJUD_FLAG_L ) ETL_COUNT, 'COMPACT.DIM_AUTO_ADJUD_FLAG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_AUTO_ADJUD_FLAG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_BILL_TYPE_CAT_LVL_1_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_BILL_TYPE_CAT_LVL_1_L ) ETL_COUNT, 'COMPACT.DIM_BILL_TYPE_CAT_LVL_1' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_BILL_TYPE_CAT_LVL_1) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_BILL_TYPE_CAT_LVL_2_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_BILL_TYPE_CAT_LVL_2_L ) ETL_COUNT, 'COMPACT.DIM_BILL_TYPE_CAT_LVL_2' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_BILL_TYPE_CAT_LVL_2) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_BILL_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_BILL_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_BILL_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_BILL_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CARE_LEVEL_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CARE_LEVEL_L ) ETL_COUNT, 'COMPACT.DIM_CARE_LEVEL' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CARE_LEVEL) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CASE_EVENT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CASE_EVENT_L ) ETL_COUNT, 'COMPACT.DIM_CASE_EVENT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CASE_EVENT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CLAIM_STATUS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CLAIM_STATUS_L ) ETL_COUNT, 'COMPACT.DIM_CLAIM_STATUS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CLAIM_STATUS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CLAIM_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CLAIM_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_CLAIM_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CLAIM_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CLASS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CLASS_L ) ETL_COUNT, 'COMPACT.DIM_CLASS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CLASS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CLASS_PLAN_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CLASS_PLAN_L ) ETL_COUNT, 'COMPACT.DIM_CLASS_PLAN' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CLASS_PLAN) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COA_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COA_L ) ETL_COUNT, 'COMPACT.DIM_COA' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COA) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COB_CARRIER_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COB_CARRIER_CODE_L ) ETL_COUNT, 'COMPACT.DIM_COB_CARRIER_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COB_CARRIER_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COMPANY_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COMPANY_L ) ETL_COUNT, 'COMPACT.DIM_COMPANY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COMPANY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CONVERTED_FROM_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CONVERTED_FROM_L ) ETL_COUNT, 'COMPACT.DIM_CONVERTED_FROM' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CONVERTED_FROM) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COSMOS_CUST_SEG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COSMOS_CUST_SEG_L ) ETL_COUNT, 'COMPACT.DIM_COSMOS_CUST_SEG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COSMOS_CUST_SEG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COS_STL_1_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COS_STL_1_L ) ETL_COUNT, 'COMPACT.DIM_COS_STL_1' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COS_STL_1) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COS_STL_2_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COS_STL_2_L ) ETL_COUNT, 'COMPACT.DIM_COS_STL_2' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COS_STL_2) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COS_STL_3_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COS_STL_3_L ) ETL_COUNT, 'COMPACT.DIM_COS_STL_3' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COS_STL_3) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_COS_STL_4_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_COS_STL_4_L ) ETL_COUNT, 'COMPACT.DIM_COS_STL_4' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_COS_STL_4) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CPT_CAT_LVL_1_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CPT_CAT_LVL_1_L ) ETL_COUNT, 'COMPACT.DIM_CPT_CAT_LVL_1' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CPT_CAT_LVL_1) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CPT_CAT_LVL_2_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CPT_CAT_LVL_2_L ) ETL_COUNT, 'COMPACT.DIM_CPT_CAT_LVL_2' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CPT_CAT_LVL_2) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_CPT_CAT_LVL_3_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_CPT_CAT_LVL_3_L ) ETL_COUNT, 'COMPACT.DIM_CPT_CAT_LVL_3' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_CPT_CAT_LVL_3) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_DIAGNOSIS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_DIAGNOSIS_L ) ETL_COUNT, 'COMPACT.DIM_DIAGNOSIS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_DIAGNOSIS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_DIAG_CAT_LVL_1_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_DIAG_CAT_LVL_1_L ) ETL_COUNT, 'COMPACT.DIM_DIAG_CAT_LVL_1' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_DIAG_CAT_LVL_1) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_DIAG_CAT_LVL_2_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_DIAG_CAT_LVL_2_L ) ETL_COUNT, 'COMPACT.DIM_DIAG_CAT_LVL_2' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_DIAG_CAT_LVL_2) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_DRG_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_DRG_CODE_L ) ETL_COUNT, 'COMPACT.DIM_DRG_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_DRG_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_EDI_FLAG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_EDI_FLAG_L ) ETL_COUNT, 'COMPACT.DIM_EDI_FLAG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_EDI_FLAG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_ELIG_STATUS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_ELIG_STATUS_L ) ETL_COUNT, 'COMPACT.DIM_ELIG_STATUS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_ELIG_STATUS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_EOB_IND_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_EOB_IND_L ) ETL_COUNT, 'COMPACT.DIM_EOB_IND' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_EOB_IND) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_FEE_SCHEDULE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_FEE_SCHEDULE_L ) ETL_COUNT, 'COMPACT.DIM_FEE_SCHEDULE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_FEE_SCHEDULE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_GEOGRAPHY_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_GEOGRAPHY_L ) ETL_COUNT, 'COMPACT.DIM_GEOGRAPHY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_GEOGRAPHY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_GL_TAG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_GL_TAG_L ) ETL_COUNT, 'COMPACT.DIM_GL_TAG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_GL_TAG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_GNRC_THER_CLASS_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_GNRC_THER_CLASS_CODE_L ) ETL_COUNT, 'COMPACT.DIM_GNRC_THER_CLASS_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_GNRC_THER_CLASS_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_GROUP_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_GROUP_L ) ETL_COUNT, 'COMPACT.DIM_GROUP' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_GROUP) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_IDENT_TYPES_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_IDENT_TYPES_L ) ETL_COUNT, 'COMPACT.DIM_IDENT_TYPES' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_IDENT_TYPES) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_IO_FLAG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_IO_FLAG_L ) ETL_COUNT, 'COMPACT.DIM_IO_FLAG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_IO_FLAG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_LANGUAGE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_LANGUAGE_L ) ETL_COUNT, 'COMPACT.DIM_LANGUAGE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_LANGUAGE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_LINE_OF_BUSINESS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_LINE_OF_BUSINESS_L ) ETL_COUNT, 'COMPACT.DIM_LINE_OF_BUSINESS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_LINE_OF_BUSINESS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_LINE_OF_BUSINESS_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_LINE_OF_BUSINESS_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_LINE_OF_BUSINESS_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_LINE_OF_BUSINESS_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_LTC_IND_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_LTC_IND_L ) ETL_COUNT, 'COMPACT.DIM_LTC_IND' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_LTC_IND) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_MEDCO_THER_CLASS_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_MEDCO_THER_CLASS_CODE_L ) ETL_COUNT, 'COMPACT.DIM_MEDCO_THER_CLASS_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_MEDCO_THER_CLASS_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_MEDICARE_DUAL_FLAG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_MEDICARE_DUAL_FLAG_L ) ETL_COUNT, 'COMPACT.DIM_MEDICARE_DUAL_FLAG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_MEDICARE_DUAL_FLAG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_MEDICARE_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_MEDICARE_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_MEDICARE_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_MEDICARE_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_MEMBER_ADDRESS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_MEMBER_ADDRESS_L ) ETL_COUNT, 'COMPACT.DIM_MEMBER_ADDRESS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_MEMBER_ADDRESS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_MEMBER_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_MEMBER_L ) ETL_COUNT, 'COMPACT.DIM_MEMBER' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_MEMBER) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_NDC_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_NDC_CODE_L ) ETL_COUNT, 'COMPACT.DIM_NDC_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_NDC_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_NETWORK_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_NETWORK_L ) ETL_COUNT, 'COMPACT.DIM_NETWORK' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_NETWORK) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PLACE_OF_SVC_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PLACE_OF_SVC_L ) ETL_COUNT, 'COMPACT.DIM_PLACE_OF_SVC' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PLACE_OF_SVC) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PLAN_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PLAN_L ) ETL_COUNT, 'COMPACT.DIM_PLAN' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PLAN) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PLAN_LOB_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PLAN_LOB_L ) ETL_COUNT, 'COMPACT.DIM_PLAN_LOB' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PLAN_LOB) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PLAN_PROGRAM_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PLAN_PROGRAM_L ) ETL_COUNT, 'COMPACT.DIM_PLAN_PROGRAM' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PLAN_PROGRAM) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PLAN_PROGRAM_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PLAN_PROGRAM_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_PLAN_PROGRAM_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PLAN_PROGRAM_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROCEDURE_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROCEDURE_CODE_L ) ETL_COUNT, 'COMPACT.DIM_PROCEDURE_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROCEDURE_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROCEDURE_MODIFIER_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROCEDURE_MODIFIER_L ) ETL_COUNT, 'COMPACT.DIM_PROCEDURE_MODIFIER' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROCEDURE_MODIFIER) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PRODUCT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PRODUCT_L ) ETL_COUNT, 'COMPACT.DIM_PRODUCT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PRODUCT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROGRAM_STATUS_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROGRAM_STATUS_CODE_L ) ETL_COUNT, 'COMPACT.DIM_PROGRAM_STATUS_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROGRAM_STATUS_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_ADDRESS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_ADDRESS_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_ADDRESS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_ADDRESS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_CONTRACT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_CONTRACT_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_CONTRACT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_CONTRACT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_CONTRACT_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_CONTRACT_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_CONTRACT_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_CONTRACT_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_CREDENTIAL_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_CREDENTIAL_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_CREDENTIAL' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_CREDENTIAL) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_FACILITY_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_FACILITY_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_FACILITY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_FACILITY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_FACILITY_XWALK_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_FACILITY_XWALK_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_FACILITY_XWALK' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_FACILITY_XWALK) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_IDENT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_IDENT_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_IDENT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_IDENT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_PAR_STAT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_PAR_STAT_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_PAR_STAT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_PAR_STAT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_SPECIALTY_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_SPECIALTY_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_SPECIALTY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_SPECIALTY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROVIDER_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROVIDER_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_PROVIDER_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROVIDER_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROV_ADDR_INFO_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROV_ADDR_INFO_L ) ETL_COUNT, 'COMPACT.DIM_PROV_ADDR_INFO' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROV_ADDR_INFO) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROV_AGREEMENT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROV_AGREEMENT_L ) ETL_COUNT, 'COMPACT.DIM_PROV_AGREEMENT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROV_AGREEMENT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_PROV_CRED_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_PROV_CRED_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_PROV_CRED_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_PROV_CRED_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RATECELL_CATEGORY_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RATECELL_CATEGORY_L ) ETL_COUNT, 'COMPACT.DIM_RATECELL_CATEGORY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RATECELL_CATEGORY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RATECELL_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RATECELL_L ) ETL_COUNT, 'COMPACT.DIM_RATECELL' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RATECELL) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RATECELL_RATE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RATECELL_RATE_L ) ETL_COUNT, 'COMPACT.DIM_RATECELL_RATE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RATECELL_RATE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RATECELL_REGION_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RATECELL_REGION_L ) ETL_COUNT, 'COMPACT.DIM_RATECELL_REGION' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RATECELL_REGION) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RATE_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RATE_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_RATE_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RATE_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_REASON_CODE_GROUP_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_REASON_CODE_GROUP_L ) ETL_COUNT, 'COMPACT.DIM_REASON_CODE_GROUP' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_REASON_CODE_GROUP) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_REASON_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_REASON_CODE_L ) ETL_COUNT, 'COMPACT.DIM_REASON_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_REASON_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_REASON_CODE_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_REASON_CODE_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_REASON_CODE_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_REASON_CODE_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_REVENUE_CAT_LVL_1_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_REVENUE_CAT_LVL_1_L ) ETL_COUNT, 'COMPACT.DIM_REVENUE_CAT_LVL_1' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_REVENUE_CAT_LVL_1) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_REVENUE_CAT_LVL_2_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_REVENUE_CAT_LVL_2_L ) ETL_COUNT, 'COMPACT.DIM_REVENUE_CAT_LVL_2' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_REVENUE_CAT_LVL_2) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_REVENUE_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_REVENUE_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_REVENUE_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_REVENUE_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_APPROVED_COST_SOURCE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_APPROVED_COST_SOURCE_L ) ETL_COUNT, 'COMPACT.DIM_RX_APPROVED_COST_SOURCE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_APPROVED_COST_SOURCE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_BILLING_ACCT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_BILLING_ACCT_L ) ETL_COUNT, 'COMPACT.DIM_RX_BILLING_ACCT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_BILLING_ACCT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_CLIENT_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_CLIENT_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_RX_CLIENT_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_CLIENT_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_COMPOUND_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_COMPOUND_CODE_L ) ETL_COUNT, 'COMPACT.DIM_RX_COMPOUND_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_COMPOUND_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_COST_DETERMIN_BASIC_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_COST_DETERMIN_BASIC_L ) ETL_COUNT, 'COMPACT.DIM_RX_COST_DETERMIN_BASIC' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_COST_DETERMIN_BASIC) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_DISPENSE_AS_WRITTEN_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_DISPENSE_AS_WRITTEN_L ) ETL_COUNT, 'COMPACT.DIM_RX_DISPENSE_AS_WRITTEN' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_DISPENSE_AS_WRITTEN) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_FLAG_INDICATOR_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_FLAG_INDICATOR_L ) ETL_COUNT, 'COMPACT.DIM_RX_FLAG_INDICATOR' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_FLAG_INDICATOR) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_FORMULARY_IND_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_FORMULARY_IND_L ) ETL_COUNT, 'COMPACT.DIM_RX_FORMULARY_IND' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_FORMULARY_IND) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_GENERIC_BRAND_IND_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_GENERIC_BRAND_IND_L ) ETL_COUNT, 'COMPACT.DIM_RX_GENERIC_BRAND_IND' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_GENERIC_BRAND_IND) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_GPI_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_GPI_L ) ETL_COUNT, 'COMPACT.DIM_RX_GPI' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_GPI) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_OTC_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_OTC_CODE_L ) ETL_COUNT, 'COMPACT.DIM_RX_OTC_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_OTC_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_OTHER_COVERAGE_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_OTHER_COVERAGE_CODE_L ) ETL_COUNT, 'COMPACT.DIM_RX_OTHER_COVERAGE_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_OTHER_COVERAGE_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_PAYMENT_TYPE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_PAYMENT_TYPE_L ) ETL_COUNT, 'COMPACT.DIM_RX_PAYMENT_TYPE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_PAYMENT_TYPE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_PLAN_DRUG_STATUS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_PLAN_DRUG_STATUS_L ) ETL_COUNT, 'COMPACT.DIM_RX_PLAN_DRUG_STATUS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_PLAN_DRUG_STATUS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_PLAN_QUALIFIER_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_PLAN_QUALIFIER_CODE_L ) ETL_COUNT, 'COMPACT.DIM_RX_PLAN_QUALIFIER_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_PLAN_QUALIFIER_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_PRIORAUTH_QUALIFIER_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_PRIORAUTH_QUALIFIER_L ) ETL_COUNT, 'COMPACT.DIM_RX_PRIORAUTH_QUALIFIER' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_PRIORAUTH_QUALIFIER) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_PRODUCT_QUALIFIER_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_PRODUCT_QUALIFIER_L ) ETL_COUNT, 'COMPACT.DIM_RX_PRODUCT_QUALIFIER' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_PRODUCT_QUALIFIER) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_PROVIDER_QUALIFIER_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_PROVIDER_QUALIFIER_L ) ETL_COUNT, 'COMPACT.DIM_RX_PROVIDER_QUALIFIER' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_PROVIDER_QUALIFIER) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_REFILL_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_REFILL_CODE_L ) ETL_COUNT, 'COMPACT.DIM_RX_REFILL_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_REFILL_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_RX_THERAPEUTIC_GROUP_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_RX_THERAPEUTIC_GROUP_L ) ETL_COUNT, 'COMPACT.DIM_RX_THERAPEUTIC_GROUP' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_RX_THERAPEUTIC_GROUP) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_SOURCE_PRODUCT_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_SOURCE_PRODUCT_L ) ETL_COUNT, 'COMPACT.DIM_SOURCE_PRODUCT' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_SOURCE_PRODUCT) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_SPEC_THER_CLASS_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_SPEC_THER_CLASS_CODE_L ) ETL_COUNT, 'COMPACT.DIM_SPEC_THER_CLASS_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_SPEC_THER_CLASS_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_STD_THER_CLASS_CODE_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_STD_THER_CLASS_CODE_L ) ETL_COUNT, 'COMPACT.DIM_STD_THER_CLASS_CODE' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_STD_THER_CLASS_CODE) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_UNCLEAN_FLAG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_UNCLEAN_FLAG_L ) ETL_COUNT, 'COMPACT.DIM_UNCLEAN_FLAG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_UNCLEAN_FLAG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_VENDOR_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_VENDOR_L ) ETL_COUNT, 'COMPACT.DIM_VENDOR' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_VENDOR) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_DIM_WHOLE_CLAIM_STATUS_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_DIM_WHOLE_CLAIM_STATUS_L ) ETL_COUNT, 'COMPACT.DIM_WHOLE_CLAIM_STATUS' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_WHOLE_CLAIM_STATUS) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_FACT_CLAIM_DELETED_LOG_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_FACT_CLAIM_DELETED_LOG_L ) ETL_COUNT, 'COMPACT.FACT_CLAIM_DELETED_LOG' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_CLAIM_DELETED_LOG) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_FACT_CLAIM_EXTN_PROV_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_FACT_CLAIM_EXTN_PROV_L ) ETL_COUNT, 'COMPACT.FACT_CLAIM_EXTN_PROV' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_CLAIM_EXTN_PROV) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_FACT_CLAIM_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_FACT_CLAIM_L ) ETL_COUNT, 'COMPACT.FACT_CLAIM' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_CLAIM) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_FACT_CLAIM_RX_ADDITION_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_FACT_CLAIM_L L INNER JOIN ETL.SMART_FACT_CLAIM_RX_ADDITION_L R ON  L.SEQ_CLAIM_ID = R.SEQ_CLAIM_ID AND L.COMPANY_DIM_ID = R.COMPANY_DIM_ID AND L.LINE_NUMBER = R.LINE_NUMBER AND L.SUB_LINE_CODE = R.SUB_LINE_CODE ) ETL_COUNT, 'COMPACT.FACT_CLAIM_RX_ADDITION' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_CLAIM_RX_ADDITION) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_FACT_MEMBER_ELIG_HISTORY_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_FACT_MEMBER_ELIG_HISTORY_L ) ETL_COUNT, 'COMPACT.FACT_MEMBER_ELIG_HISTORY' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_MEMBER_ELIG_HISTORY) FOUND_COUNT UNION ALL
SELECT 'ETL.SMART_FACT_MEMBER_REVENUE_DETAIL_L' SRC_NAME, (SELECT COUNT(1) FROM ETL.SMART_FACT_MEMBER_REVENUE_DETAIL_L ) ETL_COUNT, 'COMPACT.FACT_MEMBER_REVENUE_DETAIL' TRG_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_MEMBER_REVENUE_DETAIL) FOUND_COUNT UNION ALL
SELECT 'FOUNDATION.CLM_TRANS_SRVC_LN' SRC_NAME, (SELECT COUNT(1) FROM FOUNDATION.CLM_TRANS_SRVC_LN ) ETL_COUNT, 'OBH_DP.CLM_TRANS_SRVC_LN' TRG_NAME, (SELECT COUNT(1) FROM OBH_DP.CLM_TRANS_SRVC_LN) FOUND_COUNT UNION ALL
SELECT 'COMPACT.DIM_NDC_CODE' SRC_NAME, (SELECT COUNT(1) FROM COMPACT.DIM_NDC_CODE ) ETL_COUNT, 'OBH_DP.DIM_PHRM_NDC_DRG' TRG_NAME, (SELECT COUNT(1) FROM OBH_DP.DIM_PHRM_NDC_DRG) FOUND_COUNT UNION ALL
SELECT 'COMPACT.FACT_CLAIM' SRC_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_CLAIM WHERE CLAIM_TYPE_DIM_ID NOT IN (3, 8)) ETL_COUNT, 'FOUNDATION.CLM_TRANS_SRVC_LN' TRG_NAME, (SELECT COUNT(1) FROM FOUNDATION.CLM_TRANS_SRVC_LN) FOUND_COUNT  UNION ALL
SELECT 'COMPACT.FACT_CLAIM_RX_ADDITION' SRC_NAME, (SELECT COUNT(1) FROM COMPACT.FACT_CLAIM WHERE CLAIM_TYPE_DIM_ID IN (3, 8)) ETL_COUNT, 'FOUNDATION.PHRM_DRG_CLM' TRG_NAME, (SELECT COUNT(1) FROM FOUNDATION.PHRM_DRG_CLM) FOUND_COUNT UNION ALL
SELECT 'FOUNDATION.PHRM_DRG_CLM' SRC_NAME, (SELECT COUNT(1) FROM FOUNDATION.PHRM_DRG_CLM) ETL_COUNT, 'OBH_DP.PHRM_DRG_CLM' TRG_NAME, (SELECT COUNT(1) FROM OBH_DP.PHRM_DRG_CLM) FOUND_COUNT
) TBL
LEFT JOIN (SELECT
CONCAT('COMPACT.',SRC_TABLE) VAL_TBL,
SRC_COUNT VAL_CNTS,
ROW_NUMBER() OVER(PARTITION BY SRC_SCHEMA,SRC_TABLE ORDER BY EXTRACT_DT DESC) ROWNBR
FROM ETL.DBA_VALIDATION_COUNTS WHERE SRC_SCHEMA = 'DW') SMRT ON TBL.TRG_NAME = SMRT.VAL_TBL AND SMRT.ROWNBR = 1
LEFT JOIN(SELECT
CONCAT(SRC_SCHEMA,'.',SRC_TABLE) VAL_TBL,
SRC_COUNT VAL_CNTS,
ROW_NUMBER() OVER(PARTITION BY SRC_SCHEMA,SRC_TABLE ORDER BY EXTRACT_DT DESC) ROWNBR
FROM ETL.DBA_VALIDATION_COUNTS WHERE SRC_SCHEMA <> 'DW') ELOG ON TBL.SRC_NAME = ELOG.VAL_TBL AND ELOG.ROWNBR = 1
LEFT JOIN (SELECT
CONCAT(SRC_SCHEMA,'.',SRC_TABLE) VAL_TBL,
SRC_COUNT VAL_CNTS,
ROW_NUMBER() OVER(PARTITION BY SRC_SCHEMA,SRC_TABLE ORDER BY EXTRACT_DT DESC) ROWNBR
FROM ETL.DBA_VALIDATION_COUNTS WHERE SRC_SCHEMA <> 'DW') FLOG ON TBL.TRG_NAME = FLOG.VAL_TBL AND FLOG.ROWNBR = 1;
