COPY INTO EDW_TB_FCT_MBR_ELIG_L (
    SALE_CHNL_SYS_ID,
    GRP_SYS_ID,
    PKG_SYS_ID,
    MBR_SYS_ID,
    PERS_SYS_ID,
    CARE_MGT_MKT_SYS_ID,
    ZIP_CD_SYS_ID,
    MBR_ELIG_SYS_ID,
    CAL_DT_SYS_ID,
    RPT_CUST_SYS_ID,
    MBR_ELIG_OCCUR_CNT,
    REC_CRT_DTTM,
    REC_UPDT_DTTM)
  FROM (
    SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
           STG.$11,  STG.$12,  STG.$13
    FROM @EDW_TB_FCT_MBR_ELIG_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
