COPY INTO ETL.EDW_STG_GALA_MEMBER_L (
BTCH_LOAD_DT,MBR_SYS_ID,MBR_ROW_EFF_DT,CUST_SEG_NBR,SBSCR_NBR,DEPN_NBR,GRP_CUST_NBR,REL_CD,SRC_SYS_GRP_CD,ADLT_DEPN_CD,BTH_DT,CES_SSN,CUST_SEG_SYS_ID,ENRLEE_ID,ER_GRP_ID,FAM_ID,FAM_NBR,FST_NM,GDR_CD,INDV_ID,INDV_ID_MTCH_CD,LST_NM,MBR_ALT_ID,MBR_ID,MBR_SSN,MIDL_INIT,ORIG_EFF_DT,NON_UHG_EE_IND,SITE_CD,SRC_SYS_CD,SRC_SYS_UPDT_DT,TOPS_REL_CD,LOGC_DEL_IND,MBR_ROW_END_DT,CURR_IND,LOAD_DT,UPDT_DT,CES_MBR_CPIN,IS_ACTIVE,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,DIR_READ_SEQ_NBR
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
         STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
         STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29,  STG.$30,
         STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39,  STG.$40,
         STG.$41,  STG.$42,  STG.$43,  STG.$44
FROM @ETL.EDW_STG_GALA_MEMBER_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;