COPY INTO ETL.EDW_TB_AUT_AUTH_L (
AUTH_SYS_ID,MBR_SYS_ID,CASE_SYS_ID,PROC_CD_SYS_ID,AUTH_NBR,AUTH_SRVC_CD,LVL_OF_SRVC_CD,LVL_OF_CARE_TXT,MH_SA_CD,AUTH_EFF_DT,AUTH_EXPIR_DT,APRV_UNITS_QTY,SRC_REC_CRT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_DTTM,SRC_REC_UPDT_USER_ID,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT,REQ_BY,LINK_AUTH,AUTH_STS_RSN_CD)
FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24
   FROM @ETL.EDW_TB_AUT_AUTH_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;