COPY INTO ETL.EDW_STM_FCET_CMC_MCTN_TAX_NAME_L (
BTCH_LOAD_DT,MCTN_ID,MCTN_TYPE,MCTN_NAME,MCTN_LST_NAME,MCTN_FIRST_NAME,MCTN_MID_INIT,MCTN_TITLE,MCTN_STATUS,MCTN_ADDR1,MCTN_ADDR2,MCTN_ADDR3,MCTN_CITY,MCTN_STATE,MCTN_ZIP,MCTN_COUNTY,MCTN_CTRY_CD,MCTN_PHONE,MCTN_PHONE_EXT,MCTN_FAX,MCTN_FAX_EXT,MCTN_EMAIL,MCTN_LOCK_TOKEN,ATXR_SOURCE_ID,REC_CRT_DTTM,REC_UPD_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28
FROM @ETL.EDW_STM_FCET_CMC_MCTN_TAX_NAME_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;