COPY INTO ETL.EDW_TB_PRV_PROV_L (
PROV_SYS_ID,PROV_CLSS_CD,PROV_FULL_NM,PROV_REIMB_CATGY_NM,PROV_TAX_ID,PROV_NPI_ID,PROV_SSN_NBR,PROV_DEA_NBR,PROV_MEDCD_NBR,PROV_MEDCR_NBR,PROV_UPIN_NBR,SRC_REC_CRT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_DTTM,SRC_REC_UPDT_USER_ID,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT,PROV_MPIN,PROV_TXNMY_CD)
FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22
   FROM @ETL.EDW_TB_PRV_PROV_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE FORCE = TRUE;