COPY INTO ETL.EDW_TB_AMA_POS_L (
POS_SYS_ID,POS_ID,POS_DESC,POS_DERIV_CATGY,SRC_REC_USER_ID,REC_DEL_FLG,REC_CRT_DTTM,REC_UPD_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT
) FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8,
   STG.$9, STG.$10, STG.$11
   FROM @ETL.EDW_TB_AMA_POS_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;