COPY INTO ETL.EDW_STAR_EXCLUSION_RULE_FAILURES_L (
CLINICAL_REVIEW_ID,REASON_CODE,CREATE_DATE_TIME,UPDATE_DATE_TIME
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4
FROM @ETL.EDW_STAR_EXCLUSION_RULE_FAILURES_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;