COPY INTO ETL.EDW_TB_PRV_PROVIDER_ALT_L (
PROV_ALT_SYS_ID,PROV_SYS_ID,SRC_PROV_TAX_ID,SRC_REC_CRT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_DTTM,SRC_REC_UPDT_USER_ID,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT,PROV_ALT_ID)
FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8,
   STG.$9, STG.$10, STG.$11, STG.$12, STG.$13
   FROM @ETL.EDW_TB_PRV_PROVIDER_ALT_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;