COPY INTO ETL.EDW_TB_DIM_ORG_SALE_CHNL_L (
    SALE_CHNL_SYS_ID,
    SALE_CHNL_NM,
    REC_CRT_DTTM,
    REC_UPDT_DTTM)
  FROM (
    SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4
    FROM @ETL.EDW_TB_DIM_ORG_SALE_CHNL_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
