COPY INTO ETL.EDW_STG_GALA_REASON_CODE_L (
BTCH_LOAD_DT,RSN_CD_SYS_ID,RSN_CD,RSN_CD_DESC,TRANS_CATGY_NM,SRC_SYS_CD,ADJ_CAUS_CD,RSN_CD_ROW_EFF_DT,RSN_CD_ROW_END_DT,FINC_CD,FINC_DESC,FINC_SUM_CD,FINC_SUM_DESC,PAYO_CD,PAYO_DESC,PAYO_SUM_CD,PAYO_SUM_DESC,VLD_SRVC_TXT,XCLS_LAG_CD,RECON_IND,RPT_INFO_CD,UPDT_USER_ID,LOAD_DT,UPDT_DT,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28
FROM @ETL.EDW_STG_GALA_REASON_CODE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;