COPY INTO ETL.EDW_TB_DIM_MBR_UNMASK_UHC_L (
    MBR_SYS_ID,
    ELIG_ADR_LN_1_TXT,
    ELIG_ADR_LN_2_TXT,
    MAIL_ADR_LN_1_TXT,
    MAIL_ADR_LN_2_TXT,
    MBR_NM_FST_TXT,
    MBR_NM_LST_TXT,
    SBSCR_NM_FST_TXT,
    SBSCR_NM_LST_TXT)
  FROM (
    SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9
    FROM @ETL.EDW_TB_DIM_MBR_UNMASK_UHC_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

