COPY INTO ETL.EDW_TB_SYS_DERIV_LVL_OF_CARE_XREF_L (
 	MH_SA_CD,
 	PROC_TYP_CD,
 	PROC_CD,
 	LVL_OF_CARE_DERIV_TXT,
 	LVL_OF_SRVC_DERIV_CD,
 	UNIT_TYP_CD,
 	SRC_REC_CRT_DTTM,
 	SRC_REC_CRT_USER_ID,
 	SRC_REC_UPDT_DTTM,
 	SRC_REC_UPDT_USER_ID,
 	REC_CRT_DTTM,
 	REC_UPDT_DTTM,
 	REC_XTRCT_SRC_CD,
 	REC_INPUT_SRC_CD,
 	BTCH_LOAD_DT )
 FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8,
   STG.$9, STG.$10, STG.$11, STG.$12, STG.$13, STG.$14, STG.$15
   FROM @ETL.EDW_TB_SYS_DERIV_LVL_OF_CARE_XREF_STAGE/ STG)
 FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
