COPY INTO ETL.EDW_STAR_EPISODE_OF_CARE_L (
EPISODE_OF_CARE_ID,ADMIT_STATUS_REF_SYS_ID,MEMBER_ID,MEMBER_CDB_XREF_ID,MEMBER_SYSTEM_CODE,MEMBER_PARTITION_ID,MEMBER_GROUP_NBR,MEMBER_PRODUCT_TYPE,COVERAGE_EFF_DATE,COVERAGE_EXP_DATE,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,MEMBER_LAST_NAME_MASKED,ACE_SECURE_ITEM,MEMBER_GENDER,MEMBER_STATE,SITUS_STATE,SUBSCRIBER_NBR,ALT_SUBSCRIBER_NBR,FACILITY_ID,FACILITY_NAME,FACILITY_TIN,FACILITY_MPIN,FACILITY_ADDRESS_SEQ_NBR,FACILITY_STATE,LINX_SERVICE_ID,ICUE_SRN,IS_HIGH_NEED_MEMBER,CREATE_USER_ID,CREATE_DATE_TIME,UPDATE_USER_ID,UPDATE_DATE_TIME,IS_PRE_CLINICAL_EXCLUSION
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29,  STG.$30,
        STG.$31,  STG.$32,  STG.$33
FROM @ETL.EDW_STAR_EPISODE_OF_CARE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;