COPY INTO ETL.EDW_TB_AUT_AUTH_DEV_L (
AUTH_SYS_ID,SRVC_SYS_ID,RFR_SYS_ID,CAC_SUBDIV_SYS_ID,AUTH_NBR,AUTH_EFF_DT,AUTH_EXPIR_DT,AUTH_COMMT_CD,AUTH_CLM_RMRK_TXT,AUTH_ECT_FLG,AUTH_AMB_FLG,AUTH_DISCLM_GIV_FLG,AUTH_LTR_SND_FLG,AUTH_CLM_SND_FLG,AUTH_TYP_CD,AUTH_REAS_SEL_CD,AUTH_CONTR_STS_CD,SRC_ELIG_STS_CD,LVL_OF_SRVC_CD,LVL_OF_CARE_TXT,AUTH_SRVC_CD,SRC_RFR_ID,SRC_SRVC_ID,SRC_AUTH_NBR,SRC_AUTH_CURR_STS_CD,SRC_AUTH_HIST_ID,SRC_RFR_PROF_ID,SRC_AUTH_CLM_NBR,SRC_AUTH_CLM_SUB_NBR,SRC_AUTH_UNIT_QTY,SRC_AUTH_TRT_REQ_ID,SRC_AUTH_TRT_REQ_DTL_ID,SRC_AUTH_CUST_ID,SRC_AUTH_GROUP_ID,SRC_AUTH_SUBDIV_ID,SRC_AUTH_DIV_NM,SRC_PTNT_ID,SRC_CLM_GRP_NBR,CMG_TYP_CD,SRC_REC_CRT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_DTTM,SRC_REC_UPDT_USER_ID,REC_DEL_FLG,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT,AUTH_AXIS1A_CD,AUTH_AXIS1B_CD,AUTH_DIAG_DTTM,AUTH_AXIS1A_DESC,AUTH_AXIS1B_DESC,ICD_DIAG_TYP_CD,DSM_TYP_CD,REQ_DTTM,REQ_DT_TM_ZONE,DTRM_DTTM,DTRM_DT_TM_ZONE,REV_TYP_CD,AUTH_STS_CHG_CD,AUTH_STS_CHG_DTTM,AUTH_STS_CHG_DT_TM_ZONE,ALRT_REL_CD,AUTH_REQ_DT,REQ_BY,LINK_AUTH,AUTH_STS_RSN_CD,AUTH_MBR_ALRDY_ADMT_FLG,UM_PROC_CD,ICUE_PROV_SEQ_NBR,REV_PRR_TYP,DECN_SEQ_NBR,SRVC_SEQ_NBR,DECN_SUB_TYP,DECN_RSN_TYP,DECN_OTCOME_TYP,DECN_ENTR_BY_USER_ID,DECN_MADE_BY_USER_ID,GAP_REV_OTCOME_TYP,DECN_SRC_CMMT_TXT,PEER_TO_PEER_REV_DT,DECN_MBR_COV_SEQ_NBR,INAC_IND,SYS_CLM_RMRK_CD,OVRD_CLM_RMRK_CD,DECN_PROV_CMNCT_DTTM,DECN_PROV_CMNCT_TO_ROLE,DECN_MBR_CMNCT_DTTM,DECN_MBR_CMNCT_TO_ROLE,WRT_DECN_CMNCT_DTTM,DECN_MADE_BY_USER_PSTN_ID,DECN_MADE_BY_USER_DEPT_ID,DECN_MADE_BY_USER_COMPLOC_ID,CLM_BEN_LVL_CD,DECN_PROV_SEQ_NBR,AUTH_DNY_FLG,ATD_RFR_SYS_ID,REQ_RFR_SYS_ID,AUTH_APRV_UNIT_QTY,AUTH_EXPT_USE_QTY,SRC_AUTH_ID,SRC_AUTH_SYS_CD
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29,  STG.$30,
        STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39,  STG.$40,
        STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49,  STG.$50,
        STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57,  STG.$58,  STG.$59,  STG.$60,
        STG.$61,  STG.$62,  STG.$63,  STG.$64,  STG.$65,  STG.$66,  STG.$67,  STG.$68,  STG.$69,  STG.$70,
        STG.$71,  STG.$72,  STG.$73,  STG.$74,  STG.$75,  STG.$76,  STG.$77,  STG.$78,  STG.$79,  STG.$80,
        STG.$81,  STG.$82,  STG.$83,  STG.$84,  STG.$85,  STG.$86,  STG.$87,  STG.$88,  STG.$89,  STG.$90,
        STG.$91,  STG.$92,  STG.$93,  STG.$94,  STG.$95,  STG.$96,  STG.$97,  STG.$98,  STG.$99,  STG.$100,
        STG.$101, STG.$102, STG.$103, STG.$104
FROM @ETL.EDW_TB_AUT_AUTH_DEV_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;