COPY INTO ETL.EDW_TB_DIAG_DSM_L (
    DSM_SYS_ID,
    DSM_CD,
    DSM_TYP_CD,
    DSM_EFF_DT,
    DSM_EXPR_DT,
    DSM_DESC,
    DSM_CATGY,
    ICD_CD,
    ICD_TYP_CD,
    ASSOC_EFF_DT,
    ASSOC_EXPR_DT,
    SRC_REC_CRT_DTTM,
    SRC_REC_CRT_USER_ID,
    SRC_REC_UPDT_DTTM,
    SRC_REC_UPDT_USER_ID,
    REC_CRT_DTTM,
    REC_UPDT_DTTM,
    REC_XTRCT_SRC_CD,
    REC_INPUT_SRC_CD,
    BTCH_LOAD_DT)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20
    FROM @ETL.EDW_TB_DIAG_DSM_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
  