COPY INTO EDW_TB_DIM_MBR_ELIG_L (
    MBR_ELIG_SYS_ID,
    BEN_PLN_VAR_CD,
    BEN_RPT_CD,
    BEN_SET_CD,
    BHVN_CD,
    ELIG_COV_DESC,
    ENRL_TYP_DESC,
    GRP_ELIG_TMLN_EFF_DT,
    GRP_ELIG_TMLN_EXPIR_DT,
    MBR_ELIG_TMLN_EFF_DT,
    MBR_ELIG_TMLN_EXPIR_DT,
    RES_MKT_SITE_CD,
    SOLD_MKT_SITE_CD,
    SRC_AREA_TYP_NM,
    SRVC_AREA_NM,
    MEDCD_RT_CELL_CD,
    REC_CRT_DTTM,
    REC_UPDT_DTTM,
    BH_DMHC_IND,
    EAP_DMHC_IND,
    CES_POL_NBR,
    CES_LGL_ENTY,
    MBR_ELIG_SRC_KEY_ID,
    SRC_REC_CD)
  FROM (
    SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
           STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
           STG.$21,  STG.$22,  STG.$23,  STG.$24
    FROM @EDW_TB_DIM_MBR_ELIG_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
