COPY INTO ETL.EDW_TB_CUS_GRP_L (
   GRP_SYS_ID,ACCT_SYS_ID,GRP_NM,GRP_TMLN_EFF_DTTM,GRP_TMLN_EXPIR_DTTM,SRC_REC_CRT_DTTM,SRC_REC_UPDT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_USER_ID,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT)
FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8,
   STG.$9, STG.$10, STG.$11, STG.$12, STG.$13, STG.$14
   FROM @ETL.EDW_TB_CUS_GRP_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;