COPY INTO ETL.EDW_TB_DIAG_L (
   DIAG_SYS_ID, DIAG_CATGY_DERIV_DESC, DIAG_CD, DIAG_DERIV_TYP_CD, DSM_DIAG_CATGY_DESC,
   MH_SA_CD, SRC_REC_CRT_DTTM, SRC_REC_CRT_USER_ID, SRC_REC_UPDT_DTTM, SRC_REC_UPDT_USER_ID,
   REC_CRT_DTTM, REC_UPDT_DTTM, REC_XTRCT_SRC_CD, REC_INPUT_SRC_CD, BTCH_LOAD_DT,
   BH_DIAG_CATGY_DESC, BH_DIAG_DESC, DIAG_DERIV_DESC, DSM_DIAG_DESC, EAP_DIAG_CATGY_DESC,
   EAP_DIAG_DESC, ICD9_DIAG_CATGY_DESC, ICD9_DIAG_DESC, DIAG_EFF_DT, DIAG_EXPR_DT,
   DSM_TYP_CD, ICD_DIAG_TYP_CD)
 FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8,
   STG.$9, STG.$10, STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16,
   STG.$17, STG.$18, STG.$19, STG.$20, STG.$21, STG.$22, STG.$23, STG.$24,
   STG.$25, STG.$26, STG.$27
   FROM @ETL.EDW_TB_DIAG_STAGE/ STG)
 FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
