COPY INTO ETL.EDW_TB_PROC_L (
PROC_CD_SYS_ID,CLM_FM_TYP_CD,PROC_EFF_DT,PROC_END_DT,PROC_TYP_CD,SRC_REC_CRT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_DTTM,SRC_REC_UPDT_USER_ID,
REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT,PROC_CD,PROC_DESC,PROC_CPT_TYP_CD,PROC_CPT_TYP_DESC)
FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8,
   STG.$9, STG.$10, STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16,
   STG.$17, STG.$18
   FROM @ETL.EDW_TB_PROC_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
