COPY INTO ETL.EDW_TB_SYS_DERIV_LVL_OF_CARE_CATGY_XREF_L (
LVL_OF_CARE_DERIV_TXT,
LVL_OF_CARE_RLLP_CATGY_TXT,
LVL_OF_CARE_SEQ_NBR,
REC_CRT_DTTM,
REC_UPDT_DTTM,
REC_XTRCT_SRC_CD,
REC_INPUT_SRC_CD,
BTCH_LOAD_DT )
 FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8
   FROM @ETL.EDW_TB_SYS_DERIV_LVL_OF_CARE_CATGY_XREF_STAGE/ STG)
 FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
