COPY INTO ETL.EDW_MBC_CUSTOMER_L (
    MBR_NM_FST_TXT,
    MBR_NM_LST_TXT,
    BTH_DT,
    MBR_SYS_ID,
    PERS_SYS_ID,
    ACCT_NM,
    SBSCR_SRC_ID,
    RPT_CUST_CUST_NM,
    RPT_CUST_LOB_NM,
    UHG_SEG_NM,
    BH_PRDCT_TYP_DESC,
    BH_PRDCT_BRND_DESC,
    BH_UBH_FUND_DESC,
    BH_PRDCT_BRND_DESC_DTL,
    MBR_ELIG_TMLN_EFF_DT,
    MBR_ELIG_TMLN_EXPIR_DT,
    REL_DESC,
    MBI,
    MARKET_SEGMENT)
  FROM (
     SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
            STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19
     FROM @ETL.EDW_MBC_CUSTOMER_STAGE STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
