COPY INTO ETL.EDW_STAR_CLINICAL_REVIEW_L (
CLINICAL_REVIEW_ID,EPISODE_OF_CARE_ID,CASE_STATUS_REF_SYS_ID,OUTCOME_OPENED,FACILITY_ADDR,FACILITY_EMAIL,FACILITY_PHONE,FACILITY_ID,FACILITY_MEDICARE_NBR,FACILITY_NAME,MEMBER_DOB,MEMBER_FIRSTNAME,MEMBER_ID,MEMBER_LASTNAME,FORM_TYPE,INITIAL_REVIEW_ID,CONCURRENT_FORM_SEQUENCE,FACILITY_ADDRESS_EFFECTIVE_DATE,FACILITY_ADDRESS_ID,FACILITY_ADDRESS_SUB_ID,TREATMENT_MILESTONE,MANUAL_AUTH_UNITS,AUTH_START_DATE,AUTH_EXP_DATE,CREATE_USER_ID,CREATE_DATE_TIME,UPDATE_USER_ID,UPDATE_DATE_TIME,MEMBER_PHONE,MEMBER_PHONE_EXT,MEMBER_ADDRESS,IS_ACE_PLATINUM,LINX_AUTH_NUMBER,LINX_PROCEDURE_PROGRAM_CODE,COHORT,COHORT2,SUBCOHORT,COHORT_CHANGED,IS_SUD,ELAPSED_TIME,SERVICE_SETTING_TYPE,STEP_NUMBER,RETRY_NUMBER,KVP_JSON,MEMBER_EXHAUSTED_MEDICARE,UNCOVERED_DAYS,SOURCE_OF_INFO_ID,COMPLETED_PROVIDER_AUTH,COMPLETED_MEMBER_AUTH,PROVIDER_AUTH_NUMBER,MEMBER_AUTH_NUMBER,IS_TELEPHONIC,NOTES,CALLER_NAME,CALLER_PHONE,CALLER_PHONE_EXT,CALLING_FACILITY_NAME,MEMBER_NOT_ACTIVE,ELIGIBILITY_FOLLOW_UP,ADDITIONAL_COMMENTS,PROCEDURE_PROGRAM,BENEFIT_CONFIRM,BENEFIT_QUOTED,ENTERED_BY,ICUE_ASSESSMENT_ID
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29,  STG.$30,
        STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39,  STG.$40,
        STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49,  STG.$50,
        STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57,  STG.$58,  STG.$59,  STG.$60,
        STG.$61,  STG.$62,  STG.$63,  STG.$64,  STG.$65
FROM @ETL.EDW_STAR_CLINICAL_REVIEW_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
