COPY INTO ETL.EDW_TB_PRV_PROVIDER_L (
PROV_SYS_ID,PRAC_SYS_ID,PROV_ENTY_CD,CRDNTL_ID,PROV_SVRC_CATGY_CD,PROV_CLM_PAY_COMB_CHK_CD,PROV_TYPE_CD,PROV_FACL_TYP_DESC,PROV_PRAC_TYPE_CD,PROV_SPCL_CD_1,PROV_SPCL_CD_2,PROV_NPI_ID,PROV_PRI_ADR_SYS_ID,PROV_REMIT_ADR_SYS_ID,PROV_TAX_ID,PROV_STS_CD,PROV_REV_TYPE_CD,PROV_PREAUTH_IND_CD,PROV_PAY_HOLD_DTTM,PROV_SECUR_LVL_CD,PROV_EFT_TYPE_CD,PROV_CPTATN_EFT_TYPE_CD,PROV_LST_CHNL_DTTM,PROV_LANG_IND_CD,PROV_EXTR_ADR_CD,PROV_BANK_REL_SYS_ID,PROV_TRM_DTTM,PROV_TRM_RSN_CD,PROV_CLHS_ID,PROV_OVPAY_RECOV_CD,PROV_LST_ASGN_DTTM,SRC_ATTCH_SYS_ID,SRC_CMN_PRAC_ID,SRC_PROV_ADR_ID,SRC_PROV_ADR_REMIT_TYPE_CD,SRC_PROV_ADR_PRI_TYPE_CD,PROV_IN_NTWK_FLG,PROV_UBH_PREF_PRV_FLG,PROV_MEDCD_NBR,PROV_MEDCR_NBR,PROV_DEA_NBR,SRC_REC_CRT_DTTM,SRC_REC_CRT_USER_ID,SRC_REC_UPDT_DTTM,SRC_REC_UPDT_USER_ID,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD,BTCH_LOAD_DT,PROV_REIM_CATGY_NM,MPIN,PROV_TAXONOMY_CD,PROV_NM,SRC_PROV_ID,PROV_CHK_NM,PROV_UPIN_NBR)
FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29,  STG.$30,
        STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39,  STG.$40,
        STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49,  STG.$50,
        STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57
   FROM @ETL.EDW_TB_PRV_PROVIDER_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;