COPY INTO ETL.EDW_AUTH_EXTRACT_L (
    MBR_SYS_ID,
    PERS_SYS_ID,
    AUTH_EFF_DT,
    AUTH_CRT_DT,
    AUTH_PRSD_EFF_DT,
    ELIG_ST_ABBR_CD,
    ACSS_DESC,
    CHRT_TYP_DESC)
  FROM (
    SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8
    FROM @ETL.ETL.EDW_AUTH_EXTRACT_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
