COPY INTO ETL.EDW_STG_GALA_PROVIDER_L (
BTCH_LOAD_DT,	PROV_SYS_ID,	PROV_ROW_EFF_DT,	SITE_CD,	PROV_NBR,	MPIN,	COS_PROV_SPCL_CD,	PROV_SPCL_CATGY_CD,	GDR_CD,	SRC_SYS_CD,	ADR_LN_1_TXT,	ADR_LN_2_TXT,	ADR_TYP_CD,	ALL_PAYR_IND,	ALT_PAYE_NBR,	CLIN_NM,	CLIN_TYP_CD,	CRDNTL_DESC,	CTY_NM,	DEA_ALPH_NBR,	DEA_NBR,	END_RSN_CD,	END_RSN_DESC,	EPD_PROV_SPCL_CD,	FACL_CD,	FACL_DESC,	FEE_SCHED_SRC_CD,	FST_NM,	FULL_NM,	GRP_PRAC_NBR,	HCFA_CNTY_CD,	INVSTGT_CD,	IRS_B_NTC_ISS_IND,	LST_NM,	MEDCD_ID_NBR,	MEDCR_ID_NBR,	MEDCR_RCIPR_PGM_IND,	MULT_LOC_IND,	NAT_ASSOC_BD_PHRM_NBR,	NAT_FEE_SCHED_ZIP_CD,	NPRTCP_FEE_SCH_NBR,	OUT_AREA_IND,	PAY_AS_BIL_IND,	PROF_LIC_ST_CD,	PROF_ST_LIC_NBR,	PROV_ADMIN_HLD_EFF_DT,	PROV_ADMIN_HLD_END_DT,	PROV_ADMIN_HLD_RSN_CD,	PROV_CATGY_CD,	PROV_CLSS_CD,	PROV_DEG_CD,	PROV_DEG_DESC,	PROV_ORIG_EFF_DT,	PROV_ROW_END_DT,	PRSC_NBR,	PRSC_PRVL_CD,	PR_NON_WTHLD_TAX_IND,	SPCL_GRP_CD,	SPCL_GRP_DESC,	SSN,	ST_ABBR_CD,	SURCHRG_TAX_IND,	TIN,	UNIV_PROV_ID_NBR,	UTLZ_REV_CATGY,	ZIP_CD,	ZIP_PLS_4_CD,	ZIP_FST_3_CD,	CURR_IND,	LOAD_DT,	UPDT_DT,	REC_CRT_DTTM,	REC_UPDT_DTTM,	REC_XTRCT_SRC_CD,	REC_INPUT_SRC_CD
  )FROM (
   SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29,  STG.$30,
        STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39,  STG.$40,
        STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49,  STG.$50,
        STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57,  STG.$58,  STG.$59,  STG.$60,
        STG.$61,  STG.$62,  STG.$63,  STG.$64,  STG.$65,  STG.$66,  STG.$67,  STG.$68,  STG.$69,  STG.$70,
        STG.$71,  STG.$72,  STG.$73,  STG.$74,  STG.$75
   FROM @ETL.EDW_STG_GALA_PROVIDER_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;