COPY INTO ETL.EDW_TB_CUST_ACCT_ORG_SALE_CHNL_XREF_L (
SALE_CHNL_SYS_ID,ACCT_SYS_ID,REC_ACTV_FLG,REC_CRT_DTTM,REC_UPDT_DTTM,REC_XTRCT_SRC_CD,REC_INPUT_SRC_CD)
FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7
   FROM @ETL.EDW_TB_CUST_ACCT_ORG_SALE_CHNL_XREF_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;