COPY INTO SMART_DIM_CPT_CAT_LVL_2_L (
	CPT_CAT_LVL_2_DIM_ID,
	CPT_CAT_LVL_2_DESC,
	CPT_CAT_LVL_2_SHORT_DESC,
	CPT_CAT_LVL_1_DIM_ID,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6
    FROM @SMART_DIM_CPT_CAT_LVL_2_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
