COPY INTO ETL.SMART_DIM_MEMBER_ADDRESS_L (
    MEMB_ADDR_DIM_ID,
    COMPANY_DIM_ID,
    MEMB_DIM_ID,
    SEQ_MEMB_ID,
    ADDR_TYPE,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    ADDRESS_LINE_3,
    CITY, STATE,
    ZIP,
    COUNTY,
    COUNTRY_CD,
    PHONE,
    PHONE_EXT,
    FAX,
    FAX_EXT,
    EMAIL,
    CONVERTED_FROM_DIM_ID,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20,
           STG.$21
    FROM @SMART_DIM_MEMBER_ADDRESS_STAGE/ STG)
    FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
