COPY INTO ETL.SMART_DIM_SDA_L(
SDA_DIM_ID,
SDA_CODE,
SDA_DESC,
COMPANY_DIM_ID,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME,
CONVERTED_FROM_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7
    FROM @SMART_DIM_SDA_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

