COPY INTO ETL.SMART_DIM_PROVIDER_SPECIALTY_L (
   PROV_DIM_ID,
   PRIMARY_SPECIALTY_FLAG,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME,
   PROV_SPEC_DIM_ID)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
   FROM @SMART_DIM_PROVIDER_SPECIALTY_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
