COPY INTO ETL.SMART_DIM_PROVIDER_CONTRACT_L (
   PROV_DIM_ID	,
   SEQ_PROV_CONTRACT	,
   CONTRACT_TYPE	,
   PROV_CONTRACT_LINE_OF_BUSINESS	,
   PANEL_ID	,
   PROV_CONTRACT_EFFECTIVE_DATE	,
   PROV_CONTRACT_TERM_DATE	,
   TERM_REASON	,
   PCP_FLAG	,
   TAX_ID	,
   DW_INSERT_DATETIME	,
   DW_UPDATE_DATETIME	,
   VEND_DIM_ID	,
   CONTRACT_TYPE_DIM_ID	,
   CONTRACT_TYPE_DESC	,
   CONT_LINE_OF_BUSINESS_DIM_ID	,
   PROVIDER_PAR_DIM_ID	,
   CONTRACT_DIM_ID	,
   PROV_CONTRACT_ID	,
   NETWORK_DIM_ID	,
   CONVERTED_FROM_DIM_ID	,
   RECORD_STATUS_DIM_ID	,
   ACC_NEW_PAT_IND	,
   PROV_AGREEMENT_DIM_ID)
FROM (
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8, STG.$9, STG.$10, STG.$11, STG.$12, STG.$13,
   STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20, STG.$21, STG.$22, STG.$23, STG.$24
   FROM @SMART_DIM_PROVIDER_CONTRACT_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;