COPY INTO SMART_DIM_RX_GENERIC_BRAND_IND_L
 (
 RX_GENERIC_BRAND_IND_DIM_ID	,
 RX_GENERIC_BRAND_IND	,
 RX_GENERIC_BRAND_IND_DESC	,
 DW_INSERT_DATETIME	,
 DW_UPDATE_DATETIME
 )FROM
 (SELECT
 STG.$1,
 STG.$2,
 STG.$3,
 STG.$4,
 STG.$5 FROM
 @SMART_DIM_RX_GENERIC_BRAND_IND_STAGE/ STG)
 FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
