COPY INTO SMART_DIM_PROCEDURE_MODIFIER_L
 (
 MODIFIER_DIM_ID	,
 MODIFIER_CODE	,
 PROCEDURE_MODIFIER_DESC	,
 ANESTHESIA_IND	,
 INFORMATIONAL_FLAG	,
 PROCEDURE_MODIFIER_EFF_DATE	,
 PROCEDURE_MODIFIER_TERM_DATE	,
 PRMO_REV_INP_OUTP_IND	,
 DW_INSERT_DATETIME	,
 DW_UPDATE_DATETIME	,
 FINANCIAL_FLAG
 )FROM
 ( SELECT
 STG.$1,
 STG.$2,
 STG.$3,
 STG.$4,
 STG.$5,
 STG.$6,
 STG.$7,
 STG.$8,
 STG.$9,
 STG.$10,
 STG.$11 FROM
 @SMART_DIM_PROCEDURE_MODIFIER_STAGE/ STG ) FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
