COPY INTO SMART_DIM_COMPANY_L (
    COMPANY_DIM_ID,
    COMPANY_CODE,
    COMPANY_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    CORPORATE_DIM_ID,
    DIVISION_DIM_ID,
    REGION_DIM_ID,
    GEOGRAPHY_STATE_DIM_ID,
    RECORD_STATUS_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10
    FROM @SMART_DIM_COMPANY_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
