COPY INTO ETL.SMART_PROGRAM_STATUS_L (
PROGRAM_STATUS_ID,
PROGRAM_STATUS_NAME,
IS_ACTIVE,
CREATED_BY,
CREATED_ON,
UPDATED_BY,
UPDATED_ON,
DELETED_BY,
DELETED_ON,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11
            FROM @SMART_PROGRAM_STATUS_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;