COPY INTO SMART_DIM_PROCEDURE_CODE_L
 (
 PROCEDURE_DIM_ID	,
 PROCEDURE_CODE	,
 PROCEDURE_CODE_SHORT_DESC	,
 PRIMARY_GROUPING	,
 SECONDARY_GROUPING	,
 PRCD_REV_INP_OUTP_IND	,
 ER_FLAG	,
 DW_INSERT_DATETIME	,
 DW_UPDATE_DATETIME	,
 ASC_GROUPER	,
 REVENUE_CAT_LVL_2_DIM_ID	,
 REVENUE_CAT_LVL_1_DIM_ID	,
 CPT_CAT_LVL_3_DIM_ID	,
 CPT_CAT_LVL_2_DIM_ID	,
 CPT_CAT_LVL_1_DIM_ID	,
 PROCEDURE_CODE_LONG_DESC	,
 PROCEDURE_CODE_EFF_DATE	,
 PROCEDURE_CODE_TERM_DATE	,
 CODE_TYPE
 )FROM
 (
 SELECT
 STG.$1,
 STG.$2,
 STG.$3,
 STG.$4,
 STG.$5,
 STG.$6,
 STG.$7,
 STG.$8,
 STG.$9,
 STG.$10,
 STG.$11,
 STG.$12,
 STG.$13,
 STG.$14,
 STG.$15,
 STG.$16,
 STG.$17,
 STG.$18,
 STG.$19
 FROM
 @SMART_DIM_PROCEDURE_CODE_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
