COPY INTO ETL.SMART_DIM_DATE_QUARTER_L(
QUARTER_DIM_ID,
QUARTER_DESC,
CAL_YEAR_QUARTER,
YEAR_DIM_ID,
YEAR_NBR,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME,
QUARTER_BEGIN_DATE,
QUARTER_END_DATE,
YEAR_BEGIN_DATE,
YEAR_END_DATE,
CURR_QUARTER_IND
)
                   FROM (
                        SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
                               STG.$11, STG.$12
                     FROM @SMART_DIM_DATE_QUARTER_STAGE/ STG)
                   FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;