COPY INTO SMART_DIM_PROVIDER_FACILITY_L (
	PROV_FACILITY_DIM_ID,
	PROV_FACILITY_ID,
	PROV_FACILITY_NAME,
	PROV_FACILITY_NAME_ALIAS,
	SYSTEM,
	NATIONAL_SYSTEM,
	REGION,
	MARKET,
	SUB_MARKET,
	UNET_MARKET,
	STATE,
	COUNTY,
	ZIP,
	MPIN,
	TIN,
	DUPLICATE,
	CLOSED,
	BLOCKED,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20
    FROM @SMART_DIM_PROVIDER_FACILITY_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
