COPY INTO ETL.SMART_ACO_TIN_LIST_L (
ACCOUNT_ID,
GROUP_NAME,
REGION,
STATE,
TIN,
VENDOR_NAME,
TIN_EFF_DATE,
TIN_END_DATE,
TIN_EFF_DATE_CIP,
TIN_END_DATE_CIP,
TIN_STATUS,
IMPACT_ACCOUNT_ID,
ADDITIONAL_COMMENTS,
INSERTED_DATETIME,
UPDATED_DATETIME,
QFR_TIN_FLAG
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,   STG.$12,   STG.$13,   STG.$14,   STG.$15,   STG.$16
            FROM @SMART_ACO_TIN_LIST_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;