COPY INTO SMART_DIM_RATECELL_RATE_L (
RTCL_RATE_DIM_ID	,
RTCL_DIM_ID	,
RTCL_MONTH	,
RATE	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME	,
RTCL_GME	,
RTCL_PAE	,
RTCL_RISK_ADJ_RATE_SCORE	,
MONTH_DIM_ID	,
RTCL_CODE_DESC
) FROM
(
SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5,
STG.$6,
STG.$7,
STG.$8,
STG.$9,
STG.$10,
STG.$11 FROM
@SMART_DIM_RATECELL_RATE_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
