COPY INTO SMART_DIM_AUTO_ADJUD_FLAG_L (
    AUTO_ADJUD_FLAG_DIM_ID,
	AUTO_ADJUD_FLAG_DESC,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4
    FROM @SMART_DIM_AUTO_ADJUD_FLAG_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
