COPY INTO SMART_DIM_CPT_CAT_LVL_3_L (
	CPT_CAT_LVL_3_DIM_ID,
	CPT_CAT_LVL_3_DESC,
	CPT_CAT_LVL_2_DIM_ID,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME,
	CPT_CAT_LVL_3_SHORT_DESC)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6
    FROM @SMART_DIM_CPT_CAT_LVL_3_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
