COPY INTO ETL.SMART_DIM_CASE_EVENT_L (
    CASE_EVENT_DIM_ID,
    CAS_EVT, CAS_INT_NUM,
    CAS_LAST_SEQ,
    TREATMENT_SETTING_DIM_ID,
    PATIENT_NO,
    MEDT,
    CASE_CLOSE_DATE,
    CASE_CLOSE_REASON_TYPE_DIM_ID,
    TRANS_DATE,
    FIRST_TRANS_DATE,
    CASE_STAGE_DIM_ID,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4, STG.$5, STG.$6, STG.$7, STG.$8, STG.$9, STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14
    FROM @SMART_DIM_CASE_EVENT_STAGE/ STG)
    FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
