COPY INTO ETL.DBA_VALIDATION_COUNTS (
SRC_SYSTEM,
SRC_SCHEMA,
SRC_TABLE,
SRC_COUNT)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4
    FROM @SMART_DBA_VALIDATION_COUNTS_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

