COPY INTO SMART_DIM_LANGUAGE_L (
    LANGUAGE_DIM_ID,
    LANGUAGE_CODE,
    LANGUAGE_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    CONVERTED_FROM_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5, STG.$6
    FROM @SMART_DIM_LANGUAGE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

