COPY INTO SMART_DIM_RATECELL_REGION_L (
RTCL_REGION_DIM_ID	,
COMPANY_DIM_ID	,
RTCL_STATE	,
RTCL_REGION_CODE	,
RTCL_REGION_NAME	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME
)FROM
(
SELECT STG.$1,
       STG.$2,
       STG.$3,
       STG.$4,
       STG.$5,
       STG.$6,
       STG.$7
FROM
 @SMART_DIM_RATECELL_REGION_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
