COPY INTO SMART_DIM_RX_PROVIDER_QUALIFIER_L (
    PROV_QUALIFIER_DIM_ID,
    PROV_ID_QUALIFIER,
    PROV_ID_QUALIFIER_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_PROVIDER_QUALIFIER_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
