COPY INTO ETL.SMART_DIM_PROVIDER_IDENT_L (
    PROV_DIM_ID,
    IDENT_TYPE_DIM_ID,
    IDENT_VALUE,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
   FROM @SMART_DIM_PROVIDER_IDENT_STAGE/ STG )
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
