COPY INTO SMART_DIM_PROVIDER_PAR_STAT_L
 (
PROVIDER_PAR_DIM_ID	,
PROVIDER_PAR_STAT	,
PROVIDER_DESC	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME
 )
 FROM
 (
 SELECT
 STG.$1,
 STG.$2,
 STG.$3,
 STG.$4,
 STG.$5 FROM
 @SMART_DIM_PROVIDER_PAR_STAT_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
