COPY INTO ETL.SMART_INDEX_NAME_L (
INDEX_ID,
INDEX_NAME,
INDEX_TYPE,
SOURCE_TYPE,
SOURCE_ID,
SOURCE_NAME,
NOTES,
INDEX_DESCRIPTION,
IS_ACTIVE,
REPORT_INDEX_ID,
IS_DEFAULT,
IS_MEMBER_MERGE_CONFIGURED,
INDEX_ORDER_ID,
CRM_IS_ACTIVE,
CREATED_BY,
CREATED_ON,
UPDATED_BY,
UPDATED_ON,
DELETED_BY,
DELETED_ON,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19,  STG.$20,
        STG.$21,  STG.$22
            FROM @SMART_INDEX_NAME_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
