 COPY INTO ETL.SMART_ACO_PRODUCTS_L (
ACCOUNT_ID,
GROUP_NAME,
REGION,
STATE,
LINE_OF_BUSINESS,
LINE_OF_BUSINESS_DESC,
PROGRAM_TYPE_CODE,
PROGRAM_TYPE_DESC,
PRODUCT_ROLLUP,
PRODUCT_DETAIL,
STATUS,
IMPACT_ACCOUNT_ID,
ADDITIONAL_COMMENTS,
INSERTED_DATETIME,
UPDATED_DATETIME,
PLAN_CODE,
PLAN_DESC
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17
 FROM @SMART_ACO_PRODUCTS_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;