COPY INTO ETL.SMART_DIM_COS_STL_2_L (
   COS_STL_2_DIM_ID,
   COS_STL_2_DESC,
   COS_STL_1_DIM_ID,
   COS_STL_1_DESC,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6
   FROM @SMART_DIM_COS_STL_2_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
