COPY INTO SMART_DIM_PLAN_L
(
PLAN_DIM_ID	,
PLAN_CODE	,
PLAN_DESC	,
PLAN_STANDARD_FLAG	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME	,
ETL_COMPANY_DIM_ID	,
PLAN_GEOGRAPHY_COUNTY_DIM_ID	,
COUNTY	,
COUNTY_DESC	,
STATE	,
STATE_DESC	,
HCFA_COUNTY	,
HCFA_COUNTY_DESC	,
STATE_PROGRAM_CODE_1_DIM_ID	,
STATE_PROGRAM_CODE_2_DIM_ID
)
FROM
( SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5,
STG.$6,
STG.$7,
STG.$8,
STG.$9,
STG.$10,
STG.$11,
STG.$12,
STG.$13,
STG.$14,
STG.$15,
STG.$16 FROM
@SMART_DIM_PLAN_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
