COPY INTO SMART_DIM_COB_CARRIER_CODE_L (
    COB_CARRIER_CODE_DIM_ID,
	COMPANY_DIM_ID,
	COB_CARRIER_CODE,
	SHORT_NAME,
	FULL_NAME_1,
	FULL_NAME_2,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	CITY,
	STATE,
	ZIP_CODE,
	COUNTY,
	CONTACT_NAME,
	CONTACT_TITLE,
	CARRIER_TYPE,
	PHONE_NUMBER,
	EXTENSION,
	FAX_NUMBER,
	CONVERTED_FROM_DIM_ID,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20,
           STG.$21
    FROM @SMART_DIM_COB_CARRIER_CODE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
