COPY INTO SMART_DIM_BILL_TYPE_L (
    BILL_TYPE_DIM_ID,
    BILL_TYPE,
    BILL_TYPE_DESC,
    INP_OUTP_IND,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    BILL_TYPE_CAT_LVL_2_DIM_ID,
    BILL_TYPE_CAT_LVL_1_DIM_ID,
    PLACE_OF_SVC_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9
    FROM @SMART_DIM_BILL_TYPE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
