COPY INTO ETL.SMART_DIM_RX_COST_DETERMIN_BASIC_L (
    COST_DETERMIN_BASIC_DIM_ID,
    COST_DETERMIN_BASIC,
    COST_DETERMIN_BASIC_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_COST_DETERMIN_BASIC_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
