COPY INTO SMART_DIM_FEE_SCHEDULE_L (
	FEE_SCHEDULE_DIM_ID,
	FEE_SCHEDULE_CODE,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4
    FROM @SMART_DIM_FEE_SCHEDULE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

