COPY INTO ETL.SMART_DIM_RX_BILLING_ACCT_L (
    RX_BILLING_ACCT_DIM_ID,
    LINE_OF_BUSINESS_DIM_ID,
    ACCOUNT_NO,
    COMPANY_DIM_ID,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6
FROM @SMART_DIM_RX_BILLING_ACCT_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
