COPY INTO ETL.SMART_LOB_BENF_PLAN_L (
LOB_BEN_ID,
LOB_ID,
BENEFIT_PLAN_ID,
START_DATE,
END_DATE,
HAS_EXPIRED,
IS_ACTIVE,
CREATED_ON,
DELETED_BY,
DELETED_ON,
CREATED_BY,
UPDATED_BY,
UPDATED_ON,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15
            FROM @SMART_LOB_BENF_PLAN_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;