COPY INTO ETL.SMART_DIM_STD_THER_CLASS_CODE_L (STD_THER_CLASS_DIM_ID, STD_THER_CLASS_CODE, STD_THER_CLASS_DESC, DW_INSERT_DATETIME, DW_UPDATE_DATETIME) 
FROM 
( SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5 FROM @SMART_DIM_STD_THER_CLASS_CODE_STAGE/ STG)  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
