COPY INTO SMART_DIM_UNCLEAN_FLAG_L
(
UNCLEAN_FLAG_DIM_ID	,
UNCLEAN_FLAG_DESC	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME
)
FROM
(
SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4
FROM
@SMART_DIM_UNCLEAN_FLAG_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
