COPY INTO SMART_DIM_CLAIM_STATUS_L (
    CLAIM_STATUS_DIM_ID,
    CLAIM_STATUS,
    CLAIM_STATUS_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    CLAIM_STATUS_TYPE_DIM_ID,
    CLAIM_STATUS_TYPE,
    CLAIM_STATUS_TYPE_DESC)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8
    FROM @SMART_DIM_CLAIM_STATUS_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
