COPY INTO ETL.SMART_DIM_RX_DISPENSE_AS_WRITTEN_L (
    DISPENSE_AS_WRITTEN_DIM_ID,
    DISPENSE_AS_WRITTEN,
    DISPENSE_AS_WRITTEN_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_DISPENSE_AS_WRITTEN_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
