COPY INTO SMART_DIM_DIAGNOSIS_L (
    DIAGNOSIS_DIM_ID,
    DIAGNOSIS_CODE,
    DIAGNOSIS_SHORT_DESC,
    DX_CLASS_1,
    FROM_AGE,
    TO_AGE,
    PATIENT_GENDER,
    TRAUMA_FLAG,
    PROCEDURE_CLASS,
    DIAGNOSIS_MDC_CODE,
    OPER_PROCEDURE_FLAG,
    DIAGNOSIS_EFFECTIVE_DATE,
    DIAGNOSIS_TERM_DATE,
    PRODUCT_SERVICE_ID_QUALIFIER,
    DIAGNOSIS_NODECM_CODE,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    DIAG_FIRSTN_DIM_ID,
    DIAG_FIRSTN_CODE,
    DIAG_FIRSTN_DESC,
    DIAG_CAT_LVL_2_DIM_ID,
    DIAG_CAT_LVL_1_DIM_ID,
    ICD_VER_IND,
    CODE_TYPE,
    DIAGNOSIS_LONG_DESC)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20,
           STG.$21, STG.$22, STG.$23, STG.$24, STG.$25
    FROM @SMART_DIM_DIAGNOSIS_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

