COPY INTO SMART_DIM_REASON_CODE_GROUP_L (
REASON_GROUP_DIM_ID	,
REASON_GROUP_CODE	,
REASON_GROUP_TYPE	,
REASON_CODE_GROUP_DESC	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME
) FROM
(
SELECT STG.$1,
       STG.$2,
       STG.$3,
       STG.$4,
       STG.$5,
       STG.$6 FROM
@SMART_DIM_REASON_CODE_GROUP_STAGE/ STG )
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
