COPY INTO SMART_DIM_ADMIT_SOURCE_L (
	ADMIT_SOURCE_DIM_ID,
	ADMIT_SOURCE_CODE,
	ADMIT_SOURCE_DESC,
	ADMIT_CLASS,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6
    FROM @SMART_DIM_ADMIT_SOURCE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
