COPY INTO ETL.SMART_DIM_RX_COMPOUND_CODE_L (
    COMPOUND_CODE_DIM_ID,
    COMPOUND_CODE,
    COMPOUND_CODE_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_COMPOUND_CODE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
