COPY INTO ETL.SMART_DIM_PROVIDER_ADDRESS_L (
   PROV_ADDR_DIM_ID,
   COMPANY_DIM_ID,
   PROV_DIM_ID,
   PROV_ADDR_ID,
   PROV_ADDR_SUB_ID,
   EFFECTIVE_DATE,
   TERM_DATE,
   TERM_REASON_DIM_ID,
   ADDRESS_LINE_1,
   ADDRESS_LINE_2,
   ADDRESS_LINE_3,
   CITY, STATE,
   ZIP, COUNTY,
   COUNTRY_CD,
   PHONE,
   PHONE_EXT,
   FAX,
   FAX_EXT,
   EMAIL,
   HD_IND,
   SVC_LOC_IND,
   MAIL_IND,
   PRIM_ADDR_IND,
   CONVERTED_FROM_DIM_ID,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8, STG.$9, STG.$10, STG.$11, 
   STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20, STG.$21, STG.$22, 
   STG.$23, STG.$24, STG.$25, STG.$26, STG.$27, STG.$28 
   FROM @SMART_DIM_PROVIDER_ADDRESS_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
