COPY INTO ETL.SMART_DIM_PROV_CRED_TYPE_L (
   PROV_CRED_TYPE_DIM_ID,
   PROV_CRED_TYPE,
   PROV_CRED_TYPE_DESC,
   CONVERTED_FROM_DIM_ID,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6
   FROM @SMART_DIM_PROV_CRED_TYPE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
