COPY INTO ETL.SMART_DIM_PLAN_PROGRAM_TYPE_L (
    PLAN_PROGRAM_TYPE_DIM_ID,
    PROGRAM_TYPE_CODE,
    PROGRAM_TYPE_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    MEDICARE_DUAL_FLAG_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6
    FROM @ETL.SMART_DIM_PLAN_PROGRAM_TYPE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
