COPY INTO SMART_DIM_PROV_AGREEMENT_L (
	PROV_AGREEMENT_DIM_ID,
	PROV_AGREEMENT_ID,
	EFFECTIVE_DATE,
	TERM_DATE,
	AGREEMENT_DESC,
	AGREEMENT_TYPE,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME,
	RECORD_STATUS_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9
    FROM @SMART_DIM_PROV_AGREEMENT_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
