COPY INTO ETL.SMART_DIM_RX_FLAG_INDICATOR_L (
    FLAG_DIM_ID,
    FLAG_IND,
    FLAG_IND_DESCRIPTION,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    FLAG_TYPE)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6
FROM @SMART_DIM_RX_FLAG_INDICATOR_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
