COPY INTO ETL.SMART_DIM_DATE_YEAR_L(
YEAR_DIM_ID,
YEAR_NBR,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME,
YEAR_BEGIN_DATE,
YEAR_END_DATE,
CURR_YEAR_IND
)
                   FROM (
                        SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7
                     FROM @SMART_DIM_DATE_YEAR_STAGE/ STG)
                   FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;