COPY INTO ETL.SMART_DIM_RX_APPROVED_COST_SOURCE_L (
    APPROVED_COST_SOURCE_DIM_ID,
    APPROVED_COST_SOURCE,
    APPROVED_COST_SOURCE_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_APPROVED_COST_SOURCE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
