COPY INTO SMART_DIM_RATE_TYPE_L
 (
RATE_TYPE_DIM_ID	,
RATE_TYPE_CODE	,
RATE_TYPE_DESC	,
CONVERTED_FROM_DIM_ID	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME
 )FROM
 ( SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5,
STG.$6
FROM @SMART_DIM_RATE_TYPE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
