COPY INTO SMART_DIM_EOB_IND_L (
	EOB_IND_DIM_ID,
	EOB_IND_DESC,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4
    FROM @SMART_DIM_EOB_IND_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
