COPY INTO SMART_DIM_RX_PAYMENT_TYPE_L (
    PAYMENT_TYPE_DIM_ID,
    PAYMENT_TYPE,
    PAYMENT_TYPE_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_PAYMENT_TYPE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
