COPY INTO SMART_DIM_GEOGRAPHY_L (
	ZIP_CODE,
    AREA,
    COUNTY,
    STATE,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    GEOGRAPHY_DIM_ID,
    GEOGRAPHY_STATE_DIM_ID,
    STATE_DESC,
    GEOGRAPHY_COUNTY_DIM_ID,
    COUNTY_DESC,
    CITY_DESC,
    AREA_DESC,
    GEOGRAPHY_REGION_DIM_ID,
    REGION,
    REGION_DESC,
    GEOGRAPHY_AREA_DIM_ID,
    ZIP_LATITUDE,
    ZIP_LONGITUDE)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19
    FROM @SMART_DIM_GEOGRAPHY_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

