COPY INTO SMART_DIM_DRG_CODE_L (
    DRG_CODE_DIM_ID,
    DRG_CODE,
    DRG_CODE_SHORT_DESC,
    DRG_CODE_MDC_CODE,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    DRG_CODE_CLASS,
    DRG_CODE_TYPE,
    DRG_CODE_LONG_DESC)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9
    FROM @SMART_DIM_DRG_CODE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

