COPY INTO ETL.SMART_DIM_DATE_MONTH_L(
MONTH_DIM_ID,
MONTH_DESC,
MONTH_NBR,
QUARTER_DIM_ID,
QUARTER_DESC,
CAL_YEAR_QUARTER,
YEAR_DIM_ID,
YEAR_NBR,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME,
MONTH_BEGIN_DATE,
MONTH_END_DATE,
QUARTER_BEGIN_DATE,
QUARTER_END_DATE,
YEAR_BEGIN_DATE,
YEAR_END_DATE,
CAL_YEAR_MONTH,
LMO_MONTH_DIM_ID,
LYR_LMO_MONTH_DIM_ID,
LYR_MONTH_DIM_ID,
MONTH_NAME,
CURR_MONTH_IND
)
                   FROM (
                        SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
                               STG.$11, STG.$12, STG.$13, STG.$14, STG.$15, STG.$16, STG.$17, STG.$18, STG.$19, STG.$20,
                               STG.$21, STG.$22
                     FROM @SMART_DIM_DATE_MONTH_STAGE/ STG)
                   FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;