COPY INTO SMART_DIM_GROUP_L (
	GROUP_DIM_ID,
	GROUP_ID,
	GROUP_SHORT_NAME,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME,
	SEQ_GROUP_ID,
	COMPANY_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5, STG.$6,  STG.$7
    FROM @SMART_DIM_GROUP_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

