COPY INTO ETL.SMART_DIM_PLAN_PROGRAM_L (
    PLAN_PROGRAM_DIM_ID,
    PROGRAM_CODE,
    PROGRAM_DESC,
    COMPANY_DIM_ID,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    PLAN_PROGRAM_TYPE_DIM_ID,
    PROGRAM_TYPE_CODE,
    PROGRAM_TYPE_DESC)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9
    FROM @ETL.SMART_DIM_PLAN_PROGRAM_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
