COPY INTO ETL.SMART_DIM_PROVIDER_CREDENTIAL_L (
	PROV_CRED_DIM_ID,
	COMPANY_DIM_ID,
	PROV_DIM_ID,
	PROV_CRED_TYPE_DIM_ID,
	CRED_SEQ_NO,
	CRED_VALUE_1,
	CRED_VALUE_2,
	EFFECTIVE_DATE,
	TERM_DATE,
	CRED_STATE,
	CRED_PAR_IND,
	CONVERTED_FROM_DIM_ID,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8, STG.$9, STG.$10, STG.$11, STG.$12, STG.$13, STG.$14 
   FROM @SMART_DIM_PROVIDER_CREDENTIAL_STAGE/ STG)  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
