COPY INTO SMART_DIM_PROGRAM_STATUS_CODE_L
    (
        PROGRAM_STATUS_DIM_ID ,
        PROGRAM_STATUS_CODE ,
        PROGRAM_STATUS_CODE_DESC ,
        DW_INSERT_DATE ,
        DW_UPDATE_DATE
    )FROM
(
SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5
FROM @SMART_DIM_PROGRAM_STATUS_CODE_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
