COPY INTO SMART_DIM_ELIG_STATUS_L (
ELIG_STATUS_DIM_ID	,
ELIG_STATUS	,
ELIG_STATUS_DESC	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME	
)FROM
(
SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5
FROM @SMART_DIM_ELIG_STATUS_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
