COPY INTO SMART_DIM_RX_OTHER_COVERAGE_CODE_L (
    OTHER_COVERAGE_CODE_DIM_ID,
    OTHER_COVERAGE_CODE,
    OTHER_COVERAGE_CODE_DESC,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME)
FROM (
SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
FROM @SMART_DIM_RX_OTHER_COVERAGE_CODE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;