COPY INTO SMART_DIM_PROVIDER_TYPE_L
(
PROV_TYPE_DIM_ID	,
TYPE_OR_SPEC_CODE	,
TYPE_OR_SPECIALTY	,
PROV_TYPE_SHORT_DESC	,
PROV_TYPE_DESC	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME	,
TYPE_OF_SERVICE	,
PROV_SPEC_CAT_CODE
)
FROM
(SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5,
STG.$6,
STG.$7,
STG.$8,
STG.$9
FROM @SMART_DIM_PROVIDER_TYPE_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
