COPY INTO ETL.SMART_DIM_REVENUE_CAT_LVL_1_L (
   REVENUE_CAT_LVL_1_DIM_ID,
   REVENUE_CAT_LVL_1_DESC,
   REVENUE_CAT_LVL_1_SHORT_DESC,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME)
FROM ( SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5 
   FROM @SMART_DIM_REVENUE_CAT_LVL_1_STAGE/ STG)
   FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
