COPY INTO SMART_DIM_REASON_CODE_L (
REASON_DIM_ID	,
REASON_CODE	,
REASON_CODE_TYPE	,
COMPANY_DIM_ID	,
REASON_DESC	,
REASON_STANDARD_FLAG	,
DW_INSERT_DATETIME	,
DW_UPDATE_DATETIME	,
REASON_GROUP_DIM_ID	,
CONVERTED_FROM_DIM_ID	,
REASON_CODE_TYPE_DIM_ID
)FROM
(
SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5,
STG.$6,
STG.$7,
STG.$8,
STG.$9,
STG.$10,
STG.$11
FROM @SMART_DIM_REASON_CODE_STAGE/ STG) FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
