COPY INTO ETL.SMART_INTERNAL_PROGRAM_REASON_L (
PROGRAM_REASON_ID,
REASON_DESCRIPTION,
PROGRAM_STATUS_ID,
CREATED_ON,
CREATED_BY,
IS_ACTIVE,
DELETED_BY,
DELETED_ON,
UPDATED_BY,
UPDATED_ON,
REASON_TYPE,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13
            FROM @SMART_INTERNAL_PROGRAM_REASON_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;