COPY INTO SMART_DIM_LINE_OF_BUSINESS_L (
    LINE_OF_BUSINESS_DIM_ID,
	LINE_OF_BUSINESS,
	LINE_OF_BUSINESS_DESC,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME,
	LINE_OF_BUSINESS_TYPE_DIM_ID,
	RECORD_STATUS_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4, STG.$5, STG.$6, STG.$7
    FROM @SMART_DIM_LINE_OF_BUSINESS_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

