COPY INTO SMART_DIM_MEDICARE_TYPE_L (
    MEDICARE_TYPE_DIM_ID,
	MEDICARE_TYPE,
	MEDICARE_IND,
	MEDICARE_TYPE_DESC,
	MEDICARE_GROUP_DIM_ID,
	DW_INSERT_DATETIME,
	DW_UPDATE_DATETIME,
	GROUP_DIM_ID)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4, STG.$5,  STG.$6,  STG.$7,  STG.$8
    FROM @SMART_DIM_MEDICARE_TYPE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;

