COPY INTO ETL.SMART_PATIENT_INDEX_L (
INDEX_VALUE,
INDEX_ID,
PATIENT_ID,
DISPLAY_VALUE,
CREATED_ON,
CREATED_BY,
UPDATED_BY,
UPDATED_ON,
DELETED_BY,
DELETED_ON,
PATIENT_INDEX_IDNTY,
DW_INSERT_DATETIME,
DW_UPDATE_DATETIME
)FROM
(SELECT STG.$1,   STG.$2,   STG.$3,   STG.$4,   STG.$5,   STG.$6,   STG.$7,   STG.$8,   STG.$9,   STG.$10,
        STG.$11,  STG.$12,  STG.$13
FROM @SMART_PATIENT_INDEX_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;