COPY INTO SMART_DIM_COS_STL_4_L (
    COS_STL_4_DIM_ID,
    COS_STL_4_DESC,
    COS_STL_3_DIM_ID,
    COS_STL_3_DESC,
    COS_STL_2_DIM_ID,
    COS_STL_2_DESC,
    COS_STL_1_DIM_ID,
    COS_STL_1_DESC,
    COS_CODE,
    DW_INSERT_DATETIME,
    DW_UPDATE_DATETIME,
    COS_PRIORITY,
    UNIT_TYPE)
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9,  STG.$10,
           STG.$11, STG.$12, STG.$13
    FROM @SMART_DIM_COS_STL_4_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
