COPY INTO ETL.SMART_DIM_PROV_ADDR_INFO_L (
   PROV_ADDR_INFO_DIM_ID,
   COMPANY_DIM_ID,
   PROV_DIM_ID,
   PROV_ADDR_DIM_ID,
   PROV_ADDR_ID,
   PROV_ADDR_SUB_ID,
   EFFECTIVE_DATE,
   INFO_CODE_TYPE_DIM_ID,
   INFO_CODE_DIM_ID,
   INFO_VALUE,
   CONVERTED_FROM_DIM_ID,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5, STG.$6, STG.$7, STG.$8, STG.$9, STG.$10,
   STG.$11, STG.$12, STG.$13
   FROM @SMART_DIM_PROV_ADDR_INFO_STAGE/ STG)
    FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
