COPY INTO ETL.SMART_DIM_CARE_LEVEL_L (
   CARE_LEVEL_DIM_ID,
   CARE_LEVEL_CODE,
   CARE_LEVEL_DESC,
   DW_INSERT_DATETIME,
   DW_UPDATE_DATETIME)
FROM ( 
   SELECT STG.$1, STG.$2, STG.$3, STG.$4, STG.$5
   FROM @SMART_DIM_CARE_LEVEL_STAGE/ STG)
FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
