COPY INTO SMART_DIM_MEDICARE_DUAL_FLAG_L
    (
        MEDICARE_DUAL_FLAG_DIM_ID ,
        MEDICARE_DUAL_FLAG ,
        MEDICARE_DUAL_FLAG_DESC,
        DW_INSERT_DATETIME ,
        DW_UPDATE_DATETIME
)FROM
(
SELECT
STG.$1,
STG.$2,
STG.$3,
STG.$4,
STG.$5
FROM @SMART_DIM_MEDICARE_DUAL_FLAG_STAGE/ STG) FILE_FORMAT= SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;
