COPY INTO UNET_GALAXY_ADJUDICATION_OFFICE_L (
	ADJD_OFC_SYS_ID,
	ADJD_OFC_CD,
	MBR_SITE_CD,
	ADJD_OFC_TXT,
	ENG_CD,
	CLM_SRC_CD,
	CLM_SRC_DESC,
	SRC_SYS_CD,
	UPDT_USER_ID,
	LOAD_DT,
	UPDT_DT
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11
	FROM @UNET_GALAXY_ADJUDICATION_OFFICE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		