COPY INTO UNET_GALAXY_PLACE_OF_SERVICE_CODE_L (
	PL_OF_SRVC_SYS_ID,
	AMA_PL_OF_SRVC_CD,
	AMA_PL_OF_SRVC_DESC,
	CLM_PL_OF_SRVC_CD,
	CLM_PL_OF_SRVC_DESC,
	COS_PL_OF_SRVC_CD,
	PL_OF_SRVC_SUM_CD,
	PL_OF_SRVC_SUM_DESC,
	PL_OF_SRVC_CATGY_TXT,
	SRC_MAP_CD,
	UNET_PL_OF_SRVC_CD,
	UPDT_USER_ID,
	LOAD_DT,
	UPDT_DT
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11, STG.$12, STG.$13, STG.$14
	FROM @UNET_GALAXY_PLACE_OF_SERVICE_CODE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		