COPY INTO UNET_GALAXY_CUSTOMER_SEGMENT_GROUP_STRUCTURE_L (
    CUST_SEG_GRP_STRCT_SYS_ID,
    CUST_SEG_GRP_STRCT_ROW_EFF_DT,
    CUST_SEG_SYS_ID,
    CUST_SEG_GRP_STRCT_ROW_END_DT,
    CONTR_PLN_COV_SYS_ID,
    PAR_CUST_NBR,
    CUST_PLN_ID,
    CUST_SEG_GRP_ID,
    MKT_TYP_CD,
    MKT_NBR,
    PLN_VAR_SUBDIV_CD,
    RPT_CD_BR_CD,
    CUST_SEG_NBR,
    PRDCT_CD,
    CUST_SPEC_NTWK_IND,
    ER_GRP_ID,
    FINC_ARNG_CD,
    HMO_ACCT_DIV_CD,
    PAR_CUST_SYS_ID,
    SITUS_ST_ABBR_CD,
    SUBGRP_1_CD,
    SUBGRP_2_CD,
    SRC_SYS_CD,
    SRC_SYS_GRP_CD,
    LOAD_DT,
    UPDT_DT,
    LD_PRTN_CD,
    UNTD_WTH_ME_IND
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19, STG.$20,
	STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28
	FROM @UNET_GALAXY_CUSTOMER_SEGMENT_GROUP_STRUCTURE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		