COPY INTO UNET_GALAXY_MEMBER_L (
			MBR_SYS_ID,
	        MBR_ROW_EFF_DT,
	        CUST_SEG_NBR,
	        SBSCR_NBR,
	        DEPN_NBR,
	        GRP_CUST_NBR,
	        REL_CD,
	        SRC_SYS_GRP_CD,
	        ADLT_DEPN_CD,
	        ALT_ID,
	        BENFY_1_NM,
	        BENFY_2_NM,
	        BTH_DT,
	        CES_SSN,
	        COB_IND,
	        CONT_CNFN_END_DT,
	        CUST_SEG_SYS_ID,
	        DEPN_STS_CD,
	        DEPN_STS_VERF_DT,
	        ELIG_EFF_DT,
	        ENRLEE_ID,
	        ER_GRP_ID,
	        FAM_ID,
	        FAM_NBR,
	        FST_NM,
	        GDR_CD,
	        INDV_ID,
	        INDV_ID_MTCH_CD,
	        LANG_CD,
	        LST_NM,
	        MEDCR_ELIG_EFF_DT,
	        MEDCR_ELIG_END_DT,
	        MEDCR_ELIG_IND,
	        MEDCR_PRI_IND,
	        MBR_ADMIN_HLD_EFF_DT,
	        MBR_ADMIN_HLD_END_DT,
	        MBR_ADMIN_HLD_RSN_CD,
	        MBR_ALT_ID,
	        MBR_CHG_RSN_CD,
	        MBR_ID,
	        MBR_SSN,
	        MIDL_INIT,
	        ORIG_EFF_DT,
	        PRXST_COND_BEGN_DT,
	        PRXST_COND_END_DT,
	        SBSCR_ADMIN_HLD_EFF_DT,
	        SBSCR_ADMIN_HLD_END_DT,
	        SBSCR_ADMIN_HLD_RSN_CD,
	        SBSCR_CHG_RSN_CD,
	        SBSCR_COBRA_QUAL_EVNT_CD,
	        SBSCR_DEPT_NBR,
	        SBSCR_HCFA_RPLY_CD,
	        SBSCR_HCFA_STS_CD,
	        SBSCR_HIR_DT,
	        SBSCR_MRTL_STS_CD,
	        SBSCR_MEDCD_CSE_NBR,
	        SBSCR_MEDCD_RT_CELL_CD,
	        SBSCR_MEDCD_RCIP_NBR,
	        SBSCR_MEDCR_NBR,
	        SBSCR_MEDCR_PND_DT,
	        SBSCR_MEDCR_PND_IND,
	        SBSCR_PERS_SRVC_SPCL_NBR,
	        SBSCR_SALRY_AMT,
	        SBSCR_SALRY_TYP_CD,
	        SBSCR_SUB_DEPT_NBR,
	        SBSCR_TYP_CD,
	        NON_UHG_EE_IND,
	        SITE_CD,
	        SRC_SYS_CD,
	        SRC_SYS_UPDT_DT,
	        STDNT_ELIG_THRU_DT,
	        DIR_READ_SEQ_NBR,
	        TOPS_REL_CD,
	        UTIL_FLD_TXT,
	        LOGC_DEL_IND,
	        MBR_ROW_END_DT,
	        CURR_IND,
	        UP_MBR_CONV_IND,
	        LOAD_DT,
	        UPDT_DT,
	        COB_VERF_DT,
	        MEDCR_COB_CD,
	        COB_CD,
	        CES_MBR_CPIN,
	        CPIN_MTCH_IND,
	        SBSCR_FAM_ID,
	        EE_ACCT_ID,
	        UTIL_FLD_4_TXT
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19, STG.$20,
	STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29, STG.$30,
	STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39, STG.$40,
	STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49, STG.$50,
	STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57,  STG.$58,  STG.$59, STG.$60,
	STG.$61,  STG.$62,  STG.$63,  STG.$64,  STG.$65,  STG.$66,  STG.$67,  STG.$68,  STG.$69, STG.$70,
	STG.$71,  STG.$72,  STG.$73,  STG.$74,  STG.$75,  STG.$76,  STG.$77,  STG.$78,  STG.$79, STG.$80,
	STG.$81,  STG.$82,  STG.$83,  STG.$84,  STG.$85,  STG.$86,  STG.$87,  STG.$88
	FROM @UNET_GALAXY_MEMBER_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		