COPY INTO UNET_GALAXY_PROCEDURE_MODIFIER_CODE_L (
	PROC_MOD_SYS_ID,
	PROC_MOD_CD,
	PROC_MOD_DESC,
	PROC_MOD_GRP_CD,
	PROC_MOD_GRP_DESC,
	PROC_MOD_PROV_SPCL_NM,
	UPDT_USER_ID,
	LOAD_DT,
	UPDT_DT
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9
	FROM @UNET_GALAXY_PROCEDURE_MODIFIER_CODE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		