COPY INTO UNET_GALAXY_UNET_CLAIM_HEADER_L (
			UNET_CLM_HEAD_SYS_ID,
	        MBR_SYS_ID,
	        CLM_AUD_NBR,
	        SYS_ENT_SEQ_NBR,
	        SYS_ENT_DT,
	        TRANS_CD,
	        CLM_DUP_KEY_BRK_NBR,
	        ADJ_LFTM_MED_BEN_AMT,
	        ADJ_NBR,
	        ASGN_ADJD_OFC_SYS_ID,
	        BEN_COV_TYP_CD,
	        BEN_LVL_CAUS_CD,
	        BEN_STRCT_1_CD,
	        BEN_STRCT_2_CD,
	        BIL_RECV_DT,
	        CAI_RPRCNG_CD,
	        CPTATN_PAY_MDL_CD,
	        CLM_LOC_CD,
	        CO_CD,
	        COV_TYP_CD,
	        CLM_ORIG_CD,
	        CUST_SEG_NBR,
	        CUST_SEG_SYS_ID,
	        CUST_SEG_ROW_EFF_DT,
	        DEPN_NBR,
	        DERIV_MBR_MKT_NBR,
	        DIAG_1_CD,
	        DIAG_2_CD,
	        DIAG_3_CD,
	        DIAG_4_CD,
	        DIAG_5_CD,
	        DIR_READ_SEQ_NBR,
	        DSCHRG_STS_CD,
	        ERLY_SRVC_DT,
	        ENG_CD,
	        ENT_DRG_CD,
	        FAM_OOP_YTD_AMT,
	        FLM_LOC_NBR,
	        FLM_LOC_OFC_NBR,
	        FIDC_TYP_CD,
	        FM_TYP_CD,
	        FRANCH_1_CD,
	        FRANCH_2_CD,
	        GEO_AREA_NBR,
	        GEO_AREA_NBR_MKT_ROW_EFF_DT,
	        HLTHCAR_ECON_MBR_MKT_NBR,
	        HI_RISK_CLM_CLSS_CD,
	        HMO_ACCT_DIV_CD,
	        JOB_INJ_CD,
	        LT_SRVC_DT,
	        MDCR_PAYR_ID,
	        MEDCR_COB_TYP_CD,
	        MEDCR_ELIG_CD,
	        MEDCR_PRI_IND,
	        MBR_AGE,
	        MBR_BTH_DT,
	        MBR_FST_NM,
	        MBR_GDR_CD,
	        MBR_LST_NM,
	        MBR_MKT_NBR,
	        MBR_MKT_ROW_EFF_DT,
	        MBR_MKT_TYP_CD,
	        MBR_OOP_YTD_AMT,
	        MBR_PRI_PHYSN_MPIN,
	        MBR_PRI_PHYSN_PROV_SYS_ID,
	        MBR_PRI_PHYSN_PROV_ROW_EFF_DT,
	        MBR_ZIP_CD,
	        MBR_ZIP_ROW_EFF_DT,
	        MKT_SEG_CD,
	        MNNRP_PCT,
	        PD_CLSS_CD,
	        PD_DIV_CD,
	        PD_POL_NBR,
	        PTNT_ACCT_NBR,
	        PLN_CD,
	        PLN_VAR_SUBDIV_CD,
	        PRI_PHYSN_IPA_NBR,
	        PRI_PHYSN_TIN,
	        PRI_PHYSN_TIN_PRFX_CD,
	        PRI_PHYSN_TIN_SUFX_CD,
	        PROC_1_CD,
	        PROC_2_CD,
	        PROC_3_CD,
	        PROC_ADJD_OFC_SYS_ID,
	        PRDCT_CD,
	        PRTCTD_HLTH_INFO_CD,
	        REIM_POL_CD,
	        REL_CD,
	        RPRCNG_STS_CD,
	        RPRCNG_VEND_CD,
	        RPT_CD_BR_CD,
	        NON_UHG_EE_IND,
	        SRC_SYS_CD,
	        SRC_SYS_GRP_CD,
	        STD_COB_TYP_CD,
	        SUBGRP_1_CD,
	        SUBGRP_2_CD,
	        SBSCR_BTH_DT,
	        SBSCR_EMPMT_STS_CD,
	        SBSCR_GDR_CD,
	        SBSCR_NBR,
	        SBSCR_ST_ABBR_CD,
	        SBSCR_ZIP_CD,
	        SBSCR_ZIP_ROW_EFF_DT,
	        SYS_DRG_CD,
	        TOPS_REL_CD,
	        LOAD_DT,
	        UPDT_DT,
	        REF_PROV_UNIV_PROV_ID_NBR,
	        REF_PROV_AUTH_NBR,
	        MULT_PROC_1_PCT,
	        MULT_PROC_2_PCT,
	        MULT_PROC_3_PCT,
	        MULT_PROC_PRCSNG_CONT_CD,
	        ULIST_MULT_PROC_IND,
	        CHK_SPRS_IND,
	        SHR_ARNG_CD,
	        OBLIG_CD,
	        WRK_COMP_IND,
	        PAY_ENRLEE_IND,
	        WRKFLW_ID,
	        INT_IND,
	        CLN_NON_CLN_CD,
	        NON_CLN_ELEM_1_CD,
	        NON_CLN_ELEM_2_CD,
	        NON_CLN_ELEM_3_CD,
	        MORE_NON_CLN_ELEM_IND,
	        RESBMT_CD,
	        RESBMT_DT,
	        ORIG_FLN_DT,
	        SBMT_VEND_CD,
	        SBMT_SRC_CD,
	        UB92_TOT_CLM_CALC_IND,
	        PROV_WRTOFF_AMT,
	        PTNT_RESP_AMT,
	        MEDCR_PART_D_CUST_ELEC_CD,
	        BIL_DRG_CD,
	        MULT_IMAG_RDUC_XCPT_IND,
	        PRDCT_BUS_TYP_CD,
	        INVC_VAL_CD,
	        INVC_VAL_AMT,
	        ORIG_INVC_VAL_AMT,
	        DOL_RESBMT_STS_CD,
	        CROS_REF_ICN_CD,
	        GRPR_SFTWE_VER_NBR,
	        CLM_LVL_RTN_CD,
	        CLM_LVL_NTWK_MGT_FEE_AMT,
	        POA_1_CD,
	        POA_2_CD,
	        POA_3_CD,
	        POA_4_CD,
	        POA_5_CD,
	        MCR_LTR_DT,
	        MCR_REVR_ID,
	        MCR_STS_CD,
	        PYMT_PRDCT_CD,
	        EMRG_IND,
	        NON_EMRG_IND,
	        NON_EMRG_PCT,
	        PRC_SRC_CD,
	        PRC_ALLW_AMT,
	        ICD_VER_CD,
	        PRVNTIVE_BEN_CD,
	        ADJ_ORIG_ICN,
	        ORIG_DRFT_NBR,
	        UPDT_BY_PROC_IND,
	        LBM_CLM_TYP_CD,
	        LBM_TRNSMS_STS_CD,
	        LBM_LAB_AFFIL_CD,
	        ENRP_FACL_ER_IND,
	        ENRP_CLM_CMS_PCT,
	        SSP_PHYSN_CD,
	        SSP_FACL_GRP_CD,
	        XCHG_RCUP_ST_CD,
	        UNET_OOP_CLM_HEAD_IND,
	        ORIG_CLOS_CLM_AUD_NBR,
	        ORIG_CLOS_CLM_FILM_LOC_NBR,
	        PTNT_RSN_FOR_VST_1_CD,
	        PTNT_RSN_FOR_VST_2_CD,
	        PTNT_RSN_FOR_VST_3_CD,
	        RNDR_PROV_ST_CD,
	        SRVC_PROV_ST_CD,
	        CIRE_CRIT_CD,
	        CLM_PRC_DT,
	        TOT_ALLW_AMT,
	        CLM_LVL_PRC_ENG,
	        ENRP_DFLT_PCT,
	        MNRP_DFLT_PCT,
	        TIER_1_PREM_PRFRM_IND,
	        TIER_1_IND,
	        NPT_TIER_OTCOME_CD,
	        NPT_TIER_TYP_CD,
	        PLN_FTUR_PL_OF_SRVC,
	        PLN_FTUR_HOSP_TIER,
	        PLN_FTUR_POS_LAB,
	        PLN_FTUR_POS_SCOPIC,
	        PLN_FTUR_POS_MAJ_DIAG,
	        PLN_FTUR_POS_OPTNT_SURG,
	        PLN_FTUR_PREM_DESG,
	        PLN_FTUR_PREM_DESG_PCP,
	        PLN_FTUR_PREM_DESG_SPCL,
	        PLN_FTUR_HI_VAL_PCP,
	        PLN_FTUR_HI_VAL_SPCL,
	        PLN_FTUR_HI_VAL_FACL,
	        PLN_FTUR_HI_VAL_HOSP,
	        PROV_DEMOT_IND,
	        PROV_PL_OF_SRVC_ZIP_CD,
	        LEG_ENTY_NBR,
	        CONTR_ST_SITUS,
	        BIL_TYP_FREQ_CD,
	        SMB_TYP_APPL_CD,
	        SMB_POL_CD,
	        SMB_CLM_CATG,
	        SMB_GRP_SIZE_CD,
	        SMB_ST_CD
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19, STG.$20,
	STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29, STG.$30,
	STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39, STG.$40,
	STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49, STG.$50,
	STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57,  STG.$58,  STG.$59, STG.$60,
	STG.$61,  STG.$62,  STG.$63,  STG.$64,  STG.$65,  STG.$66,  STG.$67,  STG.$68,  STG.$69, STG.$70,
	STG.$71,  STG.$72,  STG.$73,  STG.$74,  STG.$75,  STG.$76,  STG.$77,  STG.$78,  STG.$79, STG.$80,
	STG.$81,  STG.$82,  STG.$83,  STG.$84,  STG.$85,  STG.$86,  STG.$87,  STG.$88,  STG.$89, STG.$90,
	STG.$91,  STG.$92,  STG.$93,  STG.$94,  STG.$95,  STG.$96,  STG.$97,  STG.$98,  STG.$99, STG.$100,
		STG.$101,  STG.$102,  STG.$103,  STG.$104,  STG.$105,  STG.$106,  STG.$107,  STG.$108,  STG.$109, STG.$110,
		STG.$111,  STG.$112,  STG.$113,  STG.$114,  STG.$115,  STG.$116,  STG.$117,  STG.$118,  STG.$119, STG.$120,
		STG.$121,  STG.$122,  STG.$123,  STG.$124,  STG.$125,  STG.$126,  STG.$127,  STG.$128,  STG.$129, STG.$130,
		STG.$131,  STG.$132,  STG.$133,  STG.$134,  STG.$135,  STG.$136,  STG.$137,  STG.$138,  STG.$139, STG.$140,
		STG.$141,  STG.$142,  STG.$143,  STG.$144,  STG.$145,  STG.$146,  STG.$147,  STG.$148,  STG.$149, STG.$150,
		STG.$151,  STG.$152,  STG.$153,  STG.$154,  STG.$155,  STG.$156,  STG.$157,  STG.$158,  STG.$159, STG.$160,
		STG.$161,  STG.$162,  STG.$163,  STG.$164,  STG.$165,  STG.$166,  STG.$167,  STG.$168,  STG.$169, STG.$170,
		STG.$171,  STG.$172,  STG.$173,  STG.$174,  STG.$175,  STG.$176,  STG.$177,  STG.$178,  STG.$179, STG.$180,
		STG.$181,  STG.$182,  STG.$183,  STG.$184,  STG.$185,  STG.$186,  STG.$187,  STG.$188,  STG.$189, STG.$190,
		STG.$191,  STG.$192,  STG.$193,  STG.$194,  STG.$195,  STG.$196,  STG.$197,  STG.$198,  STG.$199, STG.$200,
	    	STG.$201,  STG.$202,  STG.$203,  STG.$204,  STG.$205,  STG.$206,  STG.$207,  STG.$208,  STG.$209, STG.$210,
			STG.$211,  STG.$212,  STG.$213,  STG.$214,  STG.$215
	FROM @UNET_GALAXY_UNET_CLAIM_HEADER_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		