COPY INTO UNET_GALAXY_MHSA_CODE_L (
	MHSA_CD,
	MHSA_DESC,
	UPDT_USER_ID,
	LOAD_DT,
	UPDT_DT
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5
	FROM @UNET_GALAXY_MHSA_CODE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		