COPY INTO UNET_GALAXY_UNET_CLAIM_STATISTICAL_SERVICE_L (
	UNET_CLM_SRVC_SYS_ID,
	        MBR_SYS_ID,
	        CLM_AUD_NBR,
	        SYS_ENT_SEQ_NBR,
	        SYS_ENT_DT,
	        TRANS_CD,
	        CLM_DUP_KEY_BRK_NBR,
	        DTL_LN_NBR,
	        UNET_CLM_HEAD_SYS_ID,
	        ADJD_DT,
	        ADJ_HCCC_CD,
	        ASGN_ADJD_OFC_CD,
	        BNK_DESG_CD,
	        BEN_LVL_SYS_ID,
	        CHRG_STS_CD,
	        CLM_CLSS_CD,
	        CLM_LOC_CD,
	        CLM_LVL_RSN_CD_SYS_ID,
	        CLM_PD_DT,
	        CLOS_CLM_IND,
	        COB_CML_PROC_TYP_CD,
	        COB_MEDCR_PROC_TYP_CD,
	        COB_NON_DUP_EXPN_IND,
	        CPTATD_IPA_NBR,
	        CPTATN_FUND_CD,
	        CPTATN_TYP_CD,
	        CONT_MKT_IND,
	        COS_HCCC_CD,
	        CUST_SEG_NBR,
	        CUST_SEG_SYS_ID,
	        CUST_SEG_ROW_EFF_DT,
	        DEPN_NBR,
	        DIAG_1_CD,
	        DIAG_2_CD,
	        DIAG_3_CD,
	        DIAG_4_CD,
	        DRFT_NBR,
	        ENCTR_CD,
	        FNL_RSN_CD_SYS_ID,
	        FNL_RSN_LVL_CD,
	        FNL_RCNSD_RSN_CD_SYS_ID,
	        FNL_RCNSD_RSN_LVL_CD,
	        FST_SRVC_DT,
	        LST_SRVC_DT,
	        MAJ_MED_PCT,
	        OPT_OUT_IND,
	        ORIG_ADJD_DT,
	        ORIG_PD_DT,
	        ORIG_PCT,
	        ORIG_SRVC_CD,
	        ORIG_SRVC_LVL_RSN_CD_SYS_ID,
	        ORIG_SYS_ENT_SEQ_NBR,
	        OTHR_INS_CD,
	        OOP_INCR_AMT,
	        OVRIDE_CD,
	        PARS_AUTH_NBR,
	        PART_RCNSD_IND,
	        PAYE_ASGN_CD,
	        PL_OF_SRVC_SYS_ID,
	        POOL_LGR_CD,
	        POS_TRANS_IND,
	        PST_DT,
	        PRS_FNL_RECOM_CD,
	        PRS_INIT_DISP_CD,
	        PREF_PROV_CD,
	        PREF_PROV_IND,
	        PREF_PROV_REIM_CD,
	        PREF_PROV_SCHED_NBR,
	        PRI_PHYSN_IND,
	        PROC_CD,
	        PROC_MOD_1_SYS_ID,
	        PROC_RVNU_CD,
	        PSA_SYS_ID,
	        PSA_ROW_EFF_DT,
	        PROV_APRV_REF_CD,
	        PROV_COV_PHYSN_CD,
	        PROV_CONTR_MKT_NBR,
	        PROV_CONTR_MKT_ROW_EFF_DT,
	        PROV_LOC_MKT_NBR,
	        PROV_LOC_MKT_ROW_EFF_DT,
	        PROV_MKT_TYP_CD,
	        PROV_PRTCP_STS_CD,
	        PROV_SANCTION_IND,
	        PROV_ST_ABBR_CD,
	        PROV_TIN,
	        PROV_TIN_PRFX_CD,
	        PROV_TIN_SUFX_CD,
	        PROV_ZIP_CD,
	        PROV_ZIP_ROW_EFF_DT,
	        RAD_ANES_PTH_IND,
	        RSTRC_PROV_CD,
	        RVNU_CD,
	        RISK_SHR_ELIG_CD,
	        NON_UHG_EE_IND,
	        SRVC_CD_CHG_IND,
	        SRVC_LVL_RSN_CD_SYS_ID,
	        SRC_CPTATN_CD,
	        SRVC_TYP_MOD_GRP_CD,
	        SRVC_PROV_CATGY_CD,
	        SRVC_PROV_IPA_NBR,
	        SRVC_PROV_SYS_ID,
	        SRVC_PROV_ROW_EFF_DT,
	        SRC_CHRG_AMT,
	        SRC_CONTR_AMT,
	        SRC_DED_AMT,
	        SRC_NOT_COV_AMT,
	        SRC_PD_AMT,
	        SRC_SYS_CD,
	        SRC_SYS_GRP_CD,
	        SBSCR_NBR,
	        SURCHRG_TAX_ELIG_IND,
	        SURCHRG_TAX_STS_CD,
	        TRANS_TYP_SYS_ID,
	        TOPS_DEPN_NBR,
	        TOPS_REL_CD,
	        TOPS_PROV_TYP_CD,
	        TOPS_SBSCR_NBR,
	        TRUE_PL_OF_SRVC_SYS_ID,
	        SRVC_CURR_IND,
	        ADJ_SRVC_UNIT_CNT,
	        ALLW_AMT,
	        BEN_LMT_AMT,
	        BEN_PAY_AMT,
	        CALC_PD_AMT,
	        COB_SV_AMT,
	        COB_RDUC_AMT,
	        COINS_AMT,
	        COV_AMT,
	        CONTR_WTHLD_CNTNGY_RSRV_AMT,
	        COPAY_AMT,
	        DED_AMT,
	        DSCNT_AMT,
	        DSCNT_TYP_CD,
	        DUP_CHRG_AMT,
	        ELIG_AMT,
	        ENCTR_PRC_AMT,
	        LIAB_CHRG_AMT,
	        NET_PD_AMT,
	        NON_DUP_CHRG_AMT,
	        OPT_SRVC_CNT_IND,
	        PAY_RDUC_AMT,
	        PHYSN_FINC_ALLW_AMT,
	        PROV_SANCTION_AMT,
	        PROV_WTHLD_AMT,
	        RCNSD_RDUC_AMT,
	        RDUC_AMT,
	        SPCL_NEGOT_DSCNT_AMT,
	        SBMT_CHRG_AMT,
	        SRVC_UNIT_CNT,
	        VST_CNT,
	        PROC_MOD_2_SYS_ID,
	        PROC_MOD_3_SYS_ID,
	        PROC_MOD_4_SYS_ID,
	        PROC_MOD_5_SYS_ID,
	        LOAD_DT,
	        UPDT_DT,
	        ORIG_SRVC_MOD_CD,
	        REIM_RSN_CD_SYS_ID,
	        MNNRP_REIM_CD,
	        BIL_PROC_CD,
	        NDC,
	        BIL_PL_OF_SRVC_SYS_ID,
	        FACL_CONTR_METH_CD,
	        NEW_FACL_CONTR_METH_IND,
	        ANES_PRORT_CD,
	        ANES_MN_UNIT_CD,
	        OPTNT_SURG_COMPAT_CD,
	        ANES_PYMT_METH_CD,
	        TIER_1_BEN_IND,
	        THREE_TIER_BEN_CD,
	        SRC_BASE_DED_CD,
	        SRC_MAJ_MED_DED_CD,
	        PYMT_PROC_MOD_2_SYS_ID,
	        PYMT_PROC_MOD_3_SYS_ID,
	        PYMT_PROC_MOD_4_SYS_ID,
	        PYMT_PROC_MOD_5_SYS_ID,
	        CRDNTL_STS_CD,
	        SRVC_LN_SPLT_IND,
	        ORIG_FACL_CONTR_METH_CD,
	        ORIG_DTL_LN_NBR,
	        SHR_ARNG_CD,
	        OBLIG_CD,
	        PTI_VAL_CD,
	        DERIV_PTI_CONTR_ORG_ID,
	        SEL_PTI_CONTR_ORG_ID,
	        MULT_IMAG_PROC_RDUC_RNK_CD,
	        MDLTY_CD,
	        MULT_IMAG_RDUC_FAM_GRP_CD,
	        EBD_RDLGY_PROC_CD,
	        UB92_RVNU_CD_STAT_SRVC_IND,
	        HCT_ORIG_LVL_NBR,
	        HCT_LVL_NBR,
	        MHSA_VEND_CD,
	        SRVC_LVL_NTWK_MGT_FEE_AMT,
	        BIL_PROV_NPI_NBR,
	        SRVC_PROV_NPI_NBR,
	        REF_PROV_NPI_NBR,
	        ATD_PROV_NPI_NBR,
	        BIL_PROV_DESG_STS_IND,
	        BIL_PROV_EFNCY_RT_CD,
	        BIL_PROV_QLTY_RT_CD,
	        UHP_SRVC_ELIG_PROV_NO_DESG_IND,
	        UHP_DED_CR_AMT,
	        UHP_TIER_1_PROC_IND,
	        RAPL_NOBLX_RCAL_IND,
	        CLIN_REV_RSLT_CD,
	        REL_SRVC_CD,
	        REL_SRVC_RULE_NBR,
	        REL_SRVC_RULE_EFF_DT,
	        REL_SRVC_RULE_GRP_CD,
	        REL_SRVC_AUTH_PROC_CD,
	        REL_SRVC_CLM_LVL_IND,
	        PYMT_TIER_CD,
	        EOC_RSN_CD,
	        PRC_SRC_CD,
	        PRC_ALLW_AMT,
	        ICD_VER_CD,
	        PROMPT_PAY_ST_CD,
	        ERISA_CD,
	        PRVNTIVE_BEN_CATGY_NM,
	        PRVNTIVE_BEN_CATGY_RULE_TYP_CD,
	        PRVNTIVE_BEN_CATGY_INCL_XCLD_CD,
	        LBM_IN_SCOPE_SRVC_LN_CD,
	        LBM_IN_SCOPE_PROC_CD,
	        LBM_ALLW_AMT,
	        LBM_EDT_RSN_CD,
	        W500_ADD_NTWK_BEN_IND,
	        PART_RCNSD_MTCH_IND,
	        UNET_OOP_CLM_SRVC_IND,
	        BEN_LVL_CAUS_CD,
	        FACL_CD,
	        IMMED_RLSE_IND,
	        PHYS_MEDCN_SRC_CD,
	        PHYS_MEDCN_CNT,
	        PHYS_MEDCN_CATGY_CD,
	        CLM_RECPT_DT,
	        PYMT_TYP,
	        DAY_TYP,
	        PROMPT_PAY_RSN_CD,
	        PROMPT_PAY_PRDCT_CD,
	        UNIT_OF_MSR_CD,
	        NAT_DRG_CD_QTY,
	        EPSD_OF_PYMT_SRVC_ID,
	        EPSD_OF_PYMT_MNL_INTRVTN_CD,
	        EPSD_OF_PYMT_BUNDLE_ID,
	        EPSD_OF_PYMT_PRC_AMT,
	        EDC_835_RPT_CD,
	        ICES_PRS_EDC_MNEM_TXT,
	        REF_PROV_SYS_ID,
	        RNDR_PROV_SYS_ID,
	        PROV_GRP_TBL_NBR,
	        ONLN_SPCL_PROC_INSTR_TBL_ID,
	        FRONT_END_SPCL_PROC_INSTR_TBL_ID,
	        ONLN_SPCL_PROC_INSTR_CATGY,
	        SRVC_BEN_SET_CD,
	        MBR_BAS_PCT,
	        MBR_NEW_COINS_APPL_CD,
	        MBR_INCNT_COINS_APPL_CD,
	        TRNSL_PL_OF_SRVC_SYS_ID,
	        PRC_SEL_CD,
	        TOPS_SRVC_CATGY_CD,
	        SRVC_PTNT_RESP_AMT,
	        AUTH_SRC_ID_CD,
	        UCI_RULE_PROC_CD,
	        SITE_OF_CARE_CD,
	        GENETIC_TST_CD,
	        ONCOLOGY_TST_CD,
	        UNET_CLM_CALC_CD,
	        RPT_TIER_CD,
	        INCNT_BEN_CD,
	        PHYS_MEDCN_MSKEL_IND,
	        PHYS_MEDCN_MSKEL_CNT,
	        TM_PRD_CD,
	        CLM_SPCL_RX_CD,
	        PHRM_CPN_STS_CD,
	        PHRM_CPN_AMT,
	        PHRM_CPN_PTNT_RESP_AMT,
	        DED_AFT_CPN_AMT,
	        PTNT_RESP_AFT_CPN_AMT,
	        COINS_AFT_CPN_AMT,
	        PHRM_CRE_ELIG_IND
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11,  STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16,  STG.$17,  STG.$18,  STG.$19, STG.$20,
	STG.$21,  STG.$22,  STG.$23,  STG.$24,  STG.$25,  STG.$26,  STG.$27,  STG.$28,  STG.$29, STG.$30,
	STG.$31,  STG.$32,  STG.$33,  STG.$34,  STG.$35,  STG.$36,  STG.$37,  STG.$38,  STG.$39, STG.$40,
	STG.$41,  STG.$42,  STG.$43,  STG.$44,  STG.$45,  STG.$46,  STG.$47,  STG.$48,  STG.$49, STG.$50,
	STG.$51,  STG.$52,  STG.$53,  STG.$54,  STG.$55,  STG.$56,  STG.$57,  STG.$58,  STG.$59, STG.$60,
	STG.$61,  STG.$62,  STG.$63,  STG.$64,  STG.$65,  STG.$66,  STG.$67,  STG.$68,  STG.$69, STG.$70,
	STG.$71,  STG.$72,  STG.$73,  STG.$74,  STG.$75,  STG.$76,  STG.$77,  STG.$78,  STG.$79, STG.$80,
	STG.$81,  STG.$82,  STG.$83,  STG.$84,  STG.$85,  STG.$86,  STG.$87,  STG.$88,  STG.$89, STG.$90,
	STG.$91,  STG.$92,  STG.$93,  STG.$94,  STG.$95,  STG.$96,  STG.$97,  STG.$98,  STG.$99, STG.$100,
		STG.$101,  STG.$102,  STG.$103,  STG.$104,  STG.$105,  STG.$106,  STG.$107,  STG.$108,  STG.$109, STG.$110,
		STG.$111,  STG.$112,  STG.$113,  STG.$114,  STG.$115,  STG.$116,  STG.$117,  STG.$118,  STG.$119, STG.$120,
		STG.$121,  STG.$122,  STG.$123,  STG.$124,  STG.$125,  STG.$126,  STG.$127,  STG.$128,  STG.$129, STG.$130,
		STG.$131,  STG.$132,  STG.$133,  STG.$134,  STG.$135,  STG.$136,  STG.$137,  STG.$138,  STG.$139, STG.$140,
		STG.$141,  STG.$142,  STG.$143,  STG.$144,  STG.$145,  STG.$146,  STG.$147,  STG.$148,  STG.$149, STG.$150,
		STG.$151,  STG.$152,  STG.$153,  STG.$154,  STG.$155,  STG.$156,  STG.$157,  STG.$158,  STG.$159, STG.$160,
		STG.$161,  STG.$162,  STG.$163,  STG.$164,  STG.$165,  STG.$166,  STG.$167,  STG.$168,  STG.$169, STG.$170,
		STG.$171,  STG.$172,  STG.$173,  STG.$174,  STG.$175,  STG.$176,  STG.$177,  STG.$178,  STG.$179, STG.$180,
		STG.$181,  STG.$182,  STG.$183,  STG.$184,  STG.$185,  STG.$186,  STG.$187,  STG.$188,  STG.$189, STG.$190,
		STG.$191,  STG.$192,  STG.$193,  STG.$194,  STG.$195,  STG.$196,  STG.$197,  STG.$198,  STG.$199, STG.$200,
	    	STG.$201,  STG.$202,  STG.$203,  STG.$204,  STG.$205,  STG.$206,  STG.$207,  STG.$208,  STG.$209, STG.$210,
			STG.$211,  STG.$212,  STG.$213,  STG.$214,  STG.$215,  STG.$216,  STG.$217,  STG.$218,  STG.$219, STG.$220,
	STG.$221,  STG.$222,  STG.$223,  STG.$224,  STG.$225,  STG.$226,  STG.$227,  STG.$228,  STG.$229, STG.$230,
	STG.$231,  STG.$232,  STG.$233,  STG.$234,  STG.$235,  STG.$236,  STG.$237,  STG.$238,  STG.$239, STG.$240,
	STG.$241,  STG.$242,  STG.$243,  STG.$244,  STG.$245,  STG.$246,  STG.$247,  STG.$248,  STG.$249, STG.$250,
	STG.$251,  STG.$252,  STG.$253,  STG.$254,  STG.$255,  STG.$256,  STG.$257,  STG.$258,  STG.$259, STG.$260,
	STG.$261,  STG.$262,  STG.$263,  STG.$264,  STG.$265,  STG.$266,  STG.$267,  STG.$268,  STG.$269, STG.$270,
	STG.$271,  STG.$272,  STG.$273,  STG.$274,  STG.$275,  STG.$276,  STG.$277,  STG.$278,  STG.$279, STG.$280,
	STG.$281
	FROM @UNET_GALAXY_UNET_CLAIM_STATISTICAL_SERVICE_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		