COPY INTO UNET_GALAXY_ZIP_L (
	ZIP_CD,
	ZIP_ROW_EFF_DT,
	ZIP_FST_3_CD,
	ZIP_LST_2_CD,
	ZIP_TYP_CD,
	ZIP_TYP_SRC_CD,
	CTY_NM,
	ST_NUM_CD,
	ST_ABBR_CD,
	PST_CNTY_CD,
	PST_CNTY_NM,
	HCFA_CNTY_CD,
	HCFA_CNTY_NM,
	ZIP_ROW_END_DT,
	LOAD_DT,
	UPDT_DT
    )
  FROM (
    SELECT STG.$1,  STG.$2,  STG.$3,  STG.$4,  STG.$5,  STG.$6,  STG.$7,  STG.$8,  STG.$9, STG.$10,
	STG.$11, STG.$12,  STG.$13,  STG.$14,  STG.$15,  STG.$16
	FROM @UNET_GALAXY_ZIP_STAGE/ STG)
  FILE_FORMAT = SMART_FILE_FORMAT ON_ERROR = SKIP_FILE;		