create or replace table FACT_CLAIM_M
as
select
SPLIT_PART(ADJUD_DATE,'T',1) as ADJUD_DATE,
ALLOWED_AMT,
AUTH_NUMBER,
cast(round(BILL_TYPE_DIM_ID) as integer) as BILL_TYPE_DIM_ID,
BILLED_AMT,
case when CALC_ADMITS='0E-10' then '0' else CALC_ADMITS end as CALC_ADMITS,
case when CALC_DAYS='0E-10' then '0' else CALC_DAYS end as CALC_DAYS,
case when CALC_PROCEDURES='0E-10' then '0' else CALC_PROCEDURES end as CALC_PROCEDURES,
case when CALC_UNITS='0E-10' then '0' else CALC_UNITS end as CALC_UNITS,
case when CALC_VISITS='0E-10' then '0' else CALC_VISITS end as CALC_VISITS,
CLAIM_NUMBER,
cast(CLAIM_STATUS_DIM_ID as integer) as CLAIM_STATUS_DIM_ID,
SPLIT_PART(CLAIM_THRU_DATE,'T',1) as CLAIM_THRU_DATE,
cast(CLAIM_TYPE_DIM_ID as integer) as CLAIM_TYPE_DIM_ID,
cast(CLASS_DIM_ID as integer) as CLASS_DIM_ID,
cast(COMPANY_DIM_ID as integer) as COMPANY_DIM_ID,
cast(CONVERTED_FROM_DIM_ID as integer) as CONVERTED_FROM_DIM_ID,
COPAYMENT_1_AMT ,
COPAYMENT_2_AMT,
cast(COS_STL_4_DIM_ID as integer) as COS_STL_4_DIM_ID,
cast(CPT_CODE_DIM_ID as integer) as CPT_CODE_DIM_ID,
cast(CPT_MODIFIER_DIM_ID as integer) as CPT_MODIFIER_DIM_ID,
SPLIT_PART(DETAIL_SVC_DATE,'T',1) as DETAIL_SVC_DATE,
cast(DIAGNOSIS_1_DIM_ID as integer) as DIAGNOSIS_1_DIM_ID,
cast(DRG_CODE_DIM_ID as integer) as DRG_CODE_DIM_ID,
cast(LINE_NUMBER as integer) as LINE_NUMBER,
cast(MEMB_DIM_ID as integer) as MEMB_DIM_ID,
MEMBER_AGE,
NET_AMT,
NOT_COVERED_AMT,
OTHER_CARRIER_AMT,
PAID_NET_AMT,
cast(PLACE_OF_SVC_1_DIM_ID as integer) as PLACE_OF_SVC_1_DIM_ID,
cast(PLAN_DIM_ID as integer) as PLAN_DIM_ID,
SPLIT_PART(POST_DATE,'T',1) as POST_DATE,
SPLIT_PART(PRIMARY_SVC_DATE,'T',1) as  PRIMARY_SVC_DATE,
cast(PROV_DIM_ID as integer) as PROV_DIM_ID,
cast(PROV_SPEC_DIM_ID as integer) as PROV_SPEC_DIM_ID,
cast(PROV_TYPE_DIM_ID as integer) as PROV_TYPE_DIM_ID,
cast(PROVIDER_PAR_DIM_ID as integer) as PROVIDER_PAR_DIM_ID,
QUANTITY,
cast(REVENUE_CODE_DIM_ID as integer) as REVENUE_CODE_DIM_ID,
cast(SEQ_CLAIM_ID as integer) as SEQ_CLAIM_ID,
SUB_LINE_CODE,
SPLIT_PART(SVC_TO_DATE,'T',1) as SVC_TO_DATE,
cast (VEND_DIM_ID as integer) as VEND_DIM_ID,
cast (WHOLE_CLAIM_STATUS_DIM_ID as integer) as WHOLE_CLAIM_STATUS_DIM_ID,
ADJ_MM
from FACT_CLAIM
where ADJUD_DATE like '%T%' and trim(length(ADJUD_DATE))> 9 ;
--Rows impacted : 13,575,207

/* Rows impact ---  114,665,864 */
create or replace table FACT_CLAIM_M1
as
select
cast(ADJUD_DATE as date) as ADJUD_DATE,
ALLOWED_AMT,
AUTH_NUMBER,
cast(round(BILL_TYPE_DIM_ID) as integer) as BILL_TYPE_DIM_ID,
BILLED_AMT,
case when CALC_ADMITS='0E-10' then '0' else CALC_ADMITS end as CALC_ADMITS,
case when CALC_DAYS='0E-10' then '0' else CALC_DAYS end as CALC_DAYS,
case when CALC_PROCEDURES='0E-10' then '0' else CALC_PROCEDURES end as CALC_PROCEDURES,
case when CALC_UNITS='0E-10' then '0' else CALC_UNITS end as CALC_UNITS,
case when CALC_VISITS='0E-10' then '0' else CALC_VISITS end as CALC_VISITS,
CLAIM_NUMBER,
cast(CLAIM_STATUS_DIM_ID as integer) as CLAIM_STATUS_DIM_ID,
cast(CLAIM_THRU_DATE as date) as CLAIM_THRU_DATE,
cast(CLAIM_TYPE_DIM_ID as integer) as CLAIM_TYPE_DIM_ID,
cast(CLASS_DIM_ID as integer) as CLASS_DIM_ID,
cast(COMPANY_DIM_ID as integer) as COMPANY_DIM_ID,
cast(CONVERTED_FROM_DIM_ID as integer) as CONVERTED_FROM_DIM_ID,
COPAYMENT_1_AMT ,
COPAYMENT_2_AMT,
cast(COS_STL_4_DIM_ID as integer) as COS_STL_4_DIM_ID,
cast(CPT_CODE_DIM_ID as integer) as CPT_CODE_DIM_ID,
cast(CPT_MODIFIER_DIM_ID as integer) as CPT_MODIFIER_DIM_ID,
cast(DETAIL_SVC_DATE as date) as DETAIL_SVC_DATE,
cast(DIAGNOSIS_1_DIM_ID as integer) as DIAGNOSIS_1_DIM_ID,
cast(DRG_CODE_DIM_ID as integer) as DRG_CODE_DIM_ID,
cast(LINE_NUMBER as integer) as LINE_NUMBER,
cast(MEMB_DIM_ID as integer) as MEMB_DIM_ID,
MEMBER_AGE,
NET_AMT,
NOT_COVERED_AMT,
OTHER_CARRIER_AMT,
PAID_NET_AMT,
cast(PLACE_OF_SVC_1_DIM_ID as integer) as PLACE_OF_SVC_1_DIM_ID,
cast(PLAN_DIM_ID as integer) as PLAN_DIM_ID,
cast(POST_DATE as date) as POST_DATE,
cast(PRIMARY_SVC_DATE as date) as  PRIMARY_SVC_DATE,
cast(PROV_DIM_ID as integer) as PROV_DIM_ID,
cast(PROV_SPEC_DIM_ID as integer) as PROV_SPEC_DIM_ID,
cast(PROV_TYPE_DIM_ID as integer) as PROV_TYPE_DIM_ID,
cast(PROVIDER_PAR_DIM_ID as integer) as PROVIDER_PAR_DIM_ID,
QUANTITY,
cast(REVENUE_CODE_DIM_ID as integer) as REVENUE_CODE_DIM_ID,
cast(SEQ_CLAIM_ID as integer) as SEQ_CLAIM_ID,
SUB_LINE_CODE,
cast(SVC_TO_DATE as date) as SVC_TO_DATE,
cast (VEND_DIM_ID as integer) as VEND_DIM_ID,
cast (WHOLE_CLAIM_STATUS_DIM_ID as integer) as WHOLE_CLAIM_STATUS_DIM_ID,
ADJ_MM
from FACT_CLAIM
where
CLAIM_NUMBER IN (select distinct CLAIM_NUMBER from FACT_CLAIM where trim(ADJUD_DATE) <> '00:00:00'
and trim(length(ADJUD_DATE))=9 and CLAIM_NUMBER not in (select distinct claim_number from FACT_CLAIM_M))  ;

