USE ROLE AZU_DWS_ECT_DEV_OBH_DP_ETL_SC_F_RL;
USE WAREHOUSE LOAD_WH;
USE DATABASE ECT_DEV_OBH_DP_DB;
USE SCHEMA ECT_DEV_OBH_DP_DB.ETL;

put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_10.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_11.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_12.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_13.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_14.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_15.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_16.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_17.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_18.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_19.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_1.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_20.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_21.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_22.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_23.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_24.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_25.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_26.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_27.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_28.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_29.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_2.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_30.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_31.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_32.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_33.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_34.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_35.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_36.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_37.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_38.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_39.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_3.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_40.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_41.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_42.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_43.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_44.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_45.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_46.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_4.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_5.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_6.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_7.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_8.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
put file:///mapr/datalake/optum/optuminsight/p_hp2/prd/developer/p_jars/Data/CSV/FACT_CLAIM_2021_01_split/FACT_CLAIM_2021_01_split_9.csv @TCOC.FACT_MY_CSV_STAGE overwrite=TRUE auto_compress=true PARALLEL = 99;
!quit;
