CREATE TABLE IF NOT EXISTS FOUNDATION.OCM_OBHDP_LOAD_TIME (
PROC_NAME VARCHAR(16777216),
OCM_TABLE_NAME VARCHAR(16777216),
LAST_LOAD_TIMESTAMP TIMESTAMP_NTZ(9)
);
COMMENT ON COLUMN FOUNDATION.OCM_OBHDP_LOAD_TIME.PROC_NAME IS 'procedure name respective to load timestamp';
COMMENT ON COLUMN FOUNDATION.OCM_OBHDP_LOAD_TIME.OCM_TABLE_NAME IS 'table name respective to load timestamp';
COMMENT ON COLUMN FOUNDATION.OCM_OBHDP_LOAD_TIME.LAST_LOAD_TIMESTAMP IS 'max value of load time stamp of respective table';