-- PKorrapa - 2022-03-15
-- Before executing the clone creation, make sure OBH_DP.PHRM_DRG_CLM table is not empty!
CREATE OR REPLACE TABLE OBH_DP.PHRM_DRG_CLM_DM CLONE OBH_DP.PHRM_DRG_CLM;

create or replace view ECT_STG_OBH_DP_DB.TCOC.PHRM_DRG_CLM(
	PHRM_DRG_CLM_SYS_ID COMMENT 'Drug Claim System Identifier: Data warehouse system generated key',
	PHRM_COPAY_AMT COMMENT 'Copay Amount: The fixed amount the member pays for a specific service as defined in their benefit plan.',
	PHRM_DED_AMT COMMENT 'The set amount a member pays for services until they reach a specified limit (usually defined on an annual basis). After the limit is reached, the member payment for services changes (often insurance pays 100% of the cost of services).',
	PHRM_DSPNS_FEE_AMT COMMENT 'Dispensing Fee Amount: Amount the pharmacy charged to fill the prescription.',
	PHRM_INGR_CST_AMT COMMENT 'Ingredient Cost Amount: Ingredient cost of the drug.',
	PHRM_PD_AMT COMMENT 'Paid Amount: The amount the pharmacy is reimbursed. Also referred to as the net amount.',
	PHRM_CHK_DT COMMENT 'Check Date: Part of the unique natural key that identifies the claim. The date that appears on the check for claims payment.',
	PHRM_FILL_DT COMMENT 'Fill Date: Date the prescription was filled by the pharmacy.',
	PHRM_DAY_SPL_CNT COMMENT 'Days Supply Count: Estimated number of days the drug supply should last for the patient if taken as prescribed.',
	PHRM_DSPNS_AS_WRT_CD COMMENT 'Dispense as Written Code: Identifies if a prescription was filled as written or altered by Pharmacy, Physician or Member.',
	PHRM_NDC_CD COMMENT 'NDC Code: The unique code that identifies a drug product as defined by the National Drug Data File (all drug products regulated by the FDA must use an NDC).',
	PHRM_FST_FILL_IND_CD COMMENT 'First Fill Indicator Code: Indicates if this is the first time a prescription is being filled. N=No U=Unknown Y=Yes',
	PHRM_FRMLRY_IND_CD COMMENT 'Formulary Indicator Code: Indicates if the drug being dispensed is on the formulary list or not. N=No Space=Unknown Y=Yes',
	PHRM_FRMLRY_TYP_CD COMMENT 'Formulary Type Code: Type of formulary used to pay a claim. For example, open, closed, etc.',
	PHRM_FRMLRY_TYP_DESC COMMENT 'Formulary Type Code Desc: Describes Type of formulary used to pay a claim. For example, open, closed, etc.',
	PHRM_MAIL_ORDR_IND_CD COMMENT 'Mail Order Indicator Code: Indicates if the type of pharmacy utilized to fill the prescription was Mail Order. (N=No, Y=Yes, U=Unknown)',
	PHRM_PRSC_RFL_NBR COMMENT 'Prescription Refill Number: Indicates if this is the first, second, or subsequent refill for the prescription.',
	PHRM_QTY_CNT COMMENT 'Quantity Count: Quantity of drug dispensed in metric units.',
	PHRM_IN_NTWK_CD COMMENT 'Pharmacy In Network Indicator Code: Indicates if the prescription was filled by a contracted pharmacy. Y=Yes, N=No, U=Unknown',
	PHRM_NBR COMMENT 'May be the NABP Number. A number assigned by the National Council for Prescription Drug Programs (NCPDP) to uniquely identify a pharmacy. Or, could be an ID defined by the client/submitter that uniquely identifies a provider in the source system.',
	PHRM_NPI_PROV_ID COMMENT 'A number assigned to uniquely identify a pharmacy. May be used in place of the NABP Number.',
	PHRM_PRSC_NPI_PROV_ID COMMENT 'This is the unique NPI number assigned to the prescribing physician.',
	PHRM_PROV_DEA_NBR COMMENT 'Provider DEA Number: An identifier assigned by Federal DEA (Drug Enforcement Agency) to a physician, authorizing him/her to prescribe medications. The first two positions are alpha and the last 9 positions are numeric.',
	PHRM_ACCT_ID COMMENT 'An Rx Solutions value within Carrier Id that is a further break down of the PacifiCare business into various categories such as by state or funding or other breakdown.',
	PHRM_CARR_ID COMMENT 'An Rx Solutions value that identifies the various PacifiCare businesses that they process claims for.',
	PHRM_COB_CD COMMENT 'Indicates what type of other insurance the member has.',
	PHRM_COB_DESC COMMENT 'Describes what type of other insurance the member has.',
	PHRM_DRG_CLM_ALT_ID COMMENT 'Provider Alternate Identifier: system id or natual (business) id which can identify a provider in a specific source.',
	MBR_ALT_ID COMMENT 'EDW concatenate of source natural member columns to create member key',
	PROV_ALT_ID COMMENT 'EDW concatenate of source natural provider columns to create provider key',
	CUST_SEG_NBR COMMENT 'Galaxy Customer Segment Number: The number assigned to an entity that has purchased products and/or services from UHG. For COSMOS this equates to Site + Group.',
	TRAN_CD COMMENT 'For Pharmacy Claims only, Transaction Code is part of the claim natural key, when the value is populated.',
	SRC_REC_CD COMMENT 'The source code representing the initial input system for a given record.',
	REC_CRT_DT COMMENT 'The create date of a record into the table.',
	REC_UPD_DT COMMENT 'The update date of a record into the table.',
	MBR_BTH_DT COMMENT 'The member or claimant date of birth',
	MBR_FST_NM COMMENT 'The member or claimant first name',
	MBR_LST_NM COMMENT 'The member or claimant last name',
	MBR_ZIP_CD COMMENT 'The claimant or member 5-digit US Postal ZIP Code.',
	PHRM_AUTH_RFL_CNT COMMENT 'The number of authorized refills for the prescribing physician.',
	PHRM_PRSCN_WRT_DT COMMENT 'Date the provider wrote the prescription. Default Value: 1/1/1900',
	SBSCR_NBR COMMENT 'The source system subscriber number.',
	MEDCD_ID COMMENT 'Unique Identifier assigned by CMS for an individual with Community & State [C&S] coverage',
	MEDCR_ID COMMENT 'Unique Identifier assigned by CMS for an individual with Medicare & Retirement [M&R] coverage',
	MBR_GDR_CD COMMENT 'A code identifying the sex of the member.',
	PHRM_DIAG_CD COMMENT 'IDC-9 (International Classification of Disease, 9th Revision, Clinical Modication) as entered on the claim (without NUMBER point). IDC-9-CM is designed for the classification of morbidity and mortality information for statistical purposes and for the indexing of hospital records by disease and operations, for data storage retrieval. ID-9-CM is an accepted national standard for coding diagnostic and disease information.',
	PHRM_PRSC_NBR COMMENT 'Prescription Number: The number assigned to the prescription by the supplying vendor or the provider prescribing number.',
	SRC_DRG_CLM_TYP COMMENT 'Describes the DRUG Claim type, values include PHARM, DENTAL, UBH-RX, N/A and UNK.',
	DERIV_OBH_FINC_LIAB COMMENT 'When the claim is behavioral finance paid then it is True else False.',
	SRC_CUST_CD COMMENT 'Represents the UHC Community and State Company created codes for every plan used in the Data Warehouse.',
	SRC_CUST_NM COMMENT 'Represents the long description of the UHC Community and State Company created codes.',
	SRC_MBR_ID COMMENT 'the Unique identifier like Diamond_id for the individual assgined within a sourceSystem like SMART. This field is used to tie all member records for the same individual together irrespective of the source system or line of business.',
	OBH_SCR_RL_LST COMMENT 'Contains the list of security tags for the ROW_LEVEL Security.',
	CLM_SRC_MBR_ACCT_NBR COMMENT 'ClientAccountNumber(forFacetsandPBHthisistheGroupID)',
	CLM_TRANS_SBMT_AMT COMMENT 'The dollar amount the provider requested to be reimbursed for the service they provided. This amount is what was entered into the source system and is also referred to as the claimed amount or the source charge amount.',
	CLM_TRANS_THER_CLASS_DESC COMMENT 'Description for therapeutic classification. i.e. Brand name in NDC table = Tylenol Cold and Flu Severe, SPEC description is NON - Narc Antitus - 1st Gen anthist-Decon-Analges, AHFS description is Antitussives, GNRC description is Cough/Cold preparations, Medco description is Decongestant/Antihistamines and STD description is Cold and Cough preparations.',
	CLM_TRANS_PRDCT_TYP_DESC COMMENT 'A text description rollup of plan benefits, such as: Commercial, Medicare, Medicaid. Valid Values: Commercial, Medicaid, Medicare, U. Default Values: U',
	IMDM_ID COMMENT 'Unique Identifier assigned to an individual by enterprise individual master data management [iMDM EID]',
    PERS_SYS_ID Comment 'Unique Person Identifier generated with in EDW',
	PHRM_EPIM_PROV_ID COMMENT 'Identifier assigned by the Enterprise Provider Identity Management [EPIM] to the Pharmacy/Facility that issued the Drug',
	PHRM_PRSC_EPIM_PROV_ID COMMENT 'Identifier assigned by the Enterprise Provider Identity Management [EPIM] to the Provider that prescribed the Drug based on NPI',
	PHRM_DEA_EPIM_PROV_ID COMMENT 'Identifier assigned by the Enterprise Provider Identity Management [EPIM] to the Provider that prescribed the Drug based on DEA',
	SF_INSERT_DATETIME COMMENT 'Indicates the timestamp when the record was inserted the record in Snowflake. Defaulted to Current timestamp',
	SF_UPDATE_DATETIME COMMENT 'Indicates the timestamp when the record was updated the record in Snowflake. Defaulted to Current timestamp',
	SF_PROCESS_ID COMMENT 'Identifies the process which inserted/updated the record in Snowflake.'
) as SELECT
PHRM_DRG_CLM_SYS_ID,
PHRM_COPAY_AMT,
PHRM_DED_AMT,
PHRM_DSPNS_FEE_AMT,
PHRM_INGR_CST_AMT,
PHRM_PD_AMT,
PHRM_CHK_DT,
PHRM_FILL_DT,
PHRM_DAY_SPL_CNT,
PHRM_DSPNS_AS_WRT_CD,
PHRM_NDC_CD,
PHRM_FST_FILL_IND_CD,
PHRM_FRMLRY_IND_CD,
PHRM_FRMLRY_TYP_CD,
PHRM_FRMLRY_TYP_DESC,
PHRM_MAIL_ORDR_IND_CD,
PHRM_PRSC_RFL_NBR,
PHRM_QTY_CNT,
PHRM_IN_NTWK_CD,
PHRM_NBR,
PHRM_NPI_PROV_ID,
PHRM_PRSC_NPI_PROV_ID,
PHRM_PROV_DEA_NBR,
PHRM_ACCT_ID,
PHRM_CARR_ID,
PHRM_COB_CD,
PHRM_COB_DESC,
PHRM_DRG_CLM_ALT_ID,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MBR_ALT_ID ELSE '' END MBR_ALT_ID,
PROV_ALT_ID,
CUST_SEG_NBR,
TRAN_CD,
SRC_REC_CD,
REC_CRT_DT,
REC_UPD_DT,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MBR_BTH_DT ELSE '1800-01-01' END MBR_BTH_DT,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MBR_FST_NM ELSE '' END MBR_FST_NM,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MBR_LST_NM ELSE '' END MBR_LST_NM,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MBR_ZIP_CD ELSE '' END MBR_ZIP_CD,
PHRM_AUTH_RFL_CNT,
PHRM_PRSCN_WRT_DT,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN SBSCR_NBR ELSE '' END SBSCR_NBR,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MEDCD_ID ELSE '' END MEDCD_ID,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MEDCR_ID ELSE '' END MEDCR_ID,
CASE WHEN CURRENT_ROLE() LIKE ('%_OBHDPSAS_OPTUM_ROLE') THEN MBR_GDR_CD ELSE '' END MBR_GDR_CD,
PHRM_DIAG_CD,
PHRM_PRSC_NBR,
SRC_DRG_CLM_TYP,
DERIV_OBH_FINC_LIAB,
SRC_CUST_CD,
SRC_CUST_NM,
SRC_MBR_ID,
OBH_SCR_RL_LST,
CLM_SRC_MBR_ACCT_NBR,
CLM_TRANS_SBMT_AMT,
CLM_TRANS_THER_CLASS_DESC,
CLM_TRANS_PRDCT_TYP_DESC,
IMDM_ID,
PERS_SYS_ID,
PHRM_EPIM_PROV_ID,
PHRM_PRSC_EPIM_PROV_ID,
PHRM_DEA_EPIM_PROV_ID,
SF_INSERT_DATETIME,
SF_UPDATE_DATETIME,
SF_PROCESS_ID
FROM OBH_DP.PHRM_DRG_CLM_DM;