CREATE OR REPLACE TABLE COMPACT.IMDM_EDW_INDV_KEY_DM CLONE COMPACT.IMDM_EDW_INDV_KEY;
CREATE OR REPLACE VIEW TCOC.IMDM_EDW_INDV_KEY(
	INDV_KEY_VAL,
	INDV_KEY_TYP_REF_DESC,
	CREAT_DTTM,
	CHG_DTTM,
	CREAT_SYS_REF_CD,
	CHG_SYS_REF_CD,
	DATA_SECUR_RULE_LIST,
	IMDM_SURRG_KEY,
	IMDM_ID,
	DW_SYS_REF_CD,
	DW_CREAT_DTTM,
	DW_CHG_DTTM,
	SF_INSERT_DATETIME,
	SF_UPDATE_DATETIME,
	SF_PROCESS_ID
) as SELECT DISTINCT
CASE WHEN CURRENT_ROLE() LIKE ANY ('%_OBHDPSAS_OPTUM_ROLE','%_DEBBY_POON_OPTUM_ROLE') THEN INDV_KEY_VAL ELSE '' END AS INDV_KEY_VAL,
INDV_KEY_TYP_REF_DESC,
CREAT_DTTM,
CHG_DTTM,
CREAT_SYS_REF_CD,
CHG_SYS_REF_CD,
DATA_SECUR_RULE_LIST,
CASE WHEN CURRENT_ROLE() LIKE ANY ('%_OBHDPSAS_OPTUM_ROLE','%_DEBBY_POON_OPTUM_ROLE') THEN IMDM_SURRG_KEY ELSE '' END AS IMDM_SURRG_KEY,
INDV_SRC_ID AS IMDM_ID,
DW_SYS_REF_CD,
DW_CREAT_DTTM,
DW_CHG_DTTM,
SF_INSERT_DATETIME,
SF_UPDATE_DATETIME,
SF_PROCESS_ID
FROM COMPACT.IMDM_EDW_INDV_KEY_DM;