CREATE TASK IF NOT EXISTS ETL.CMPCT_IMDM_INDV_LD
  WAREHOUSE = ECT_DEV_OBH_DP_LOAD_WH
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  USER_TASK_TIMEOUT_MS = 36000000
  COMMENT = 'Task to Trigger COMPACT IMDM_INDV table load'
  AFTER ETL.CMPCT_IMDM_EDW_INDV_KEY_LD
AS
  call ETL.DBA_MERGE_IMDM_INDV('COMPACT.IMDM_EDW_INDV_KEY', 'COMPACT.IMDM_INDV', 'Historical Load');



ALTER TASK ETL.CMPCT_IMDM_INDV_LD RESUME ;