CREATE TASK IF NOT EXISTS ETL.ETL_IMDM_INDV_CHNG_LD
  WAREHOUSE = ECT_DEV_OBH_DP_LOAD_WH
  SCHEDULE = 'USING CRON 0 20 * * * America/Chicago'
  //SCHEDULE = '{ USING CRON <expr> <time_zone> }'
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  USER_TASK_TIMEOUT_MS = 36000000
  COMMENT = 'Task to Trigger ETL IMDM_INDV_CHNG table load'
AS
  CALL ETL.DBA_MERGE_IMDM_INDV_CHNG() ;



ALTER TASK ETL.ETL_IMDM_INDV_CHNG_LD RESUME ;