USE ROLE AZU_DWS_ECT_DEV_OBH_DP_ETL_SC_F_RL;
USE WAREHOUSE LOAD_WH;
USE DATABASE ECT_DEV_OBH_DP_DB;
USE SCHEMA ECT_DEV_OBH_DP_DB.ETL;

CREATE OR REPLACE TABLE
    DIM_COMPANY
    (
        CLAIM_TYPE_DIM_ID INTEGER,
        CLAIM_TYPE VARCHAR(8),
        CLAIM_TYPE_DESC VARCHAR(30)
    );
/**********************************************************************/
DROP TABLE
    DRG_CODE;
/* DRG_CODE*/
DROP TABLE
    DIM_DRG_CODE;
CREATE TABLE
    DIM_DRG_CODE
    (
        DRG_CODE_DIM_ID VARCHAR(100),
        DRG_CODE VARCHAR(100),
        DRG_CODE_SHORT_DESC VARCHAR(100),
        DRG_CODE_MDC_CODE VARCHAR(100),
        DW_INSERT_DATETIME VARCHAR(100),
        DW_UPDATE_DATETIME VARCHAR(100),
        DRG_CODE_CLASS VARCHAR(100),
        DRG_CODE_TYPE VARCHAR(100),
        DRG_CODE_LONG_DESC VARCHAR(300)
    );
LS @MY_CSV_STAGE;
SELECT
    COUNT(1)
FROM
    DIM_DRG_CODE;
SELECT
    *
FROM
    DRG_CODE;
COPY INTO DIM_DRG_CODE FROM @MY_CSV_STAGE/_DIM_DRG_CODE__202103151608.CSV.GZ FILE_FORMAT=
MYCSVFORMAT ON_ERROR = CONTINUE;
/**********************************************************************/
/*DIM_GEOGRAPHY*/
CREATE TABLE
    DIM_GEOGRAPHY
    (
        ZIP_CODE VARCHAR(255),
        AREA VARCHAR(255),
        COUNTY VARCHAR(255),
        STATE VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        GEOGRAPHY_DIM_ID VARCHAR(255),
        GEOGRAPHY_STATE_DIM_ID VARCHAR(255),
        STATE_DESC VARCHAR(255),
        GEOGRAPHY_COUNTY_DIM_ID VARCHAR(255),
        COUNTY_DESC VARCHAR(255),
        CITY_DESC VARCHAR(255),
        AREA_DESC VARCHAR(255),
        GEOGRAPHY_REGION_DIM_ID VARCHAR(255),
        REGION VARCHAR(255),
        REGION_DESC VARCHAR(255),
        GEOGRAPHY_AREA_DIM_ID VARCHAR(255),
        ZIP_LATITUDE VARCHAR(255),
        ZIP_LONGITUDE VARCHAR(255)
    );
COPY INTO DIM_GEOGRAPHY FROM @MY_CSV_STAGE/_DIM_GEOGRAPHY__202103151608.CSV.GZ FILE_FORMAT=
MYCSVFORMAT ON_ERROR = CONTINUE;
SELECT
    COUNT(1)
FROM
    DIM_GEOGRAPHY;
    /**********************************************************************/
/*_DIM_PLACE_OF_SVC__202103151713*/
CREATE TABLE
    DIM_PLACE_OF_SVC
    (
        PLACE_OF_SVC_DIM_ID VARCHAR(255),
        PLACE_OF_SVC_CODE VARCHAR(255),
        PLACE_OF_SVC_DESC VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        PLACE_OF_SVC_SUMM_CD VARCHAR(255)
    );
COPY INTO DIM_PLACE_OF_SVC FROM @MY_CSV_STAGE/_DIM_PLACE_OF_SVC__202103151713.CSV.GZ FILE_FORMAT=
MYCSVFORMAT ON_ERROR = CONTINUE;
/**********************************************************************/
/*DIM_PLAN*/
CREATE TABLE
    DIM_PLAN
    (
        PLAN_DIM_ID VARCHAR(255),
        PLAN_CODE VARCHAR(255),
        PLAN_DESC VARCHAR(255),
        PLAN_STANDARD_FLAG VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        ETL_COMPANY_DIM_ID VARCHAR(255),
        PLAN_GEOGRAPHY_COUNTY_DIM_ID VARCHAR(255),
        COUNTY VARCHAR(255),
        COUNTY_DESC VARCHAR(255),
        STATE VARCHAR(255),
        STATE_DESC VARCHAR(255),
        HCFA_COUNTY VARCHAR(255),
        HCFA_COUNTY_DESC VARCHAR(255),
        STATE_PROGRAM_CODE_1_DIM_ID VARCHAR(255),
        STATE_PROGRAM_CODE_2_DIM_ID VARCHAR(255)
    );
COPY INTO DIM_PLAN FROM @MY_CSV_STAGE/_DIM_PLAN__202103151713.CSV.GZ FILE_FORMAT=MYCSVFORMAT
ON_ERROR = CONTINUE;
SELECT
    COUNT(1)
FROM
    DIM_PLAN;
    /**********************************************************************/
/*_DIM_PROCEDURE_CODE__202103151713*/
CREATE TABLE
    DIM_PROCEDURE_CODE
    (
        PROCEDURE_DIM_ID VARCHAR(255),
        PROCEDURE_CODE VARCHAR(255),
        PROCEDURE_CODE_SHORT_DESC VARCHAR(255),
        PRIMARY_GROUPING VARCHAR(255),
        SECONDARY_GROUPING VARCHAR(255),
        PRCD_REV_INP_OUTP_IND VARCHAR(255),
        ER_FLAG VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        ASC_GROUPER VARCHAR(255),
        REVENUE_CAT_LVL_2_DIM_ID VARCHAR(255),
        REVENUE_CAT_LVL_1_DIM_ID VARCHAR(255),
        CPT_CAT_LVL_3_DIM_ID VARCHAR(255),
        CPT_CAT_LVL_2_DIM_ID VARCHAR(255),
        CPT_CAT_LVL_1_DIM_ID VARCHAR(255),
        PROCEDURE_CODE_LONG_DESC VARCHAR(255),
        PROCEDURE_CODE_EFF_DATE VARCHAR(255),
        PROCEDURE_CODE_TERM_DATE VARCHAR(255),
        CODE_TYPE VARCHAR(255)
    );
COPY INTO DIM_PROCEDURE_CODE FROM @MY_CSV_STAGE/_DIM_PROCEDURE_CODE__202103151713.CSV.GZ
FILE_FORMAT=MYCSVFORMAT ON_ERROR = CONTINUE;
/**********************************************************************/
/*_DIM_PROCEDURE_MODIFIER__202103151713*/
CREATE TABLE
    DIM_PROCEDURE_MODIFIER
    (
        MODIFIER_DIM_ID VARCHAR(255),
        MODIFIER_CODE VARCHAR(255),
        PROCEDURE_MODIFIER_DESC VARCHAR(255),
        ANESTHESIA_IND VARCHAR(255),
        INFORMATIONAL_FLAG VARCHAR(255),
        PROCEDURE_MODIFIER_EFF_DATE VARCHAR(255),
        PROCEDURE_MODIFIER_TERM_DATE VARCHAR(255),
        PRMO_REV_INP_OUTP_IND VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        FINANCIAL_FLAG VARCHAR(255)
    );
COPY INTO DIM_PROCEDURE_MODIFIER FROM @MY_CSV_STAGE/_DIM_PROCEDURE_MODIFIER__202103151713.CSV.GZ
FILE_FORMAT=MYCSVFORMAT ON_ERROR = CONTINUE;
SELECT DISTINCT
    MODIFIER_DIM_ID
FROM
    DIM_PROCEDURE_MODIFIER
WHERE
    MODIFIER_DIM_ID=40299
ORDER BY
    1;
    /**********************************************************************/
/*_DIM_PROVIDER_PAR_STAT__202103151714*/
CREATE TABLE
    DIM_PROVIDER_PAR_STAT
    (
        PROVIDER_PAR_DIM_ID VARCHAR(255),
        PROVIDER_PAR_STAT VARCHAR(255),
        PROVIDER_DESC VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255)
    );
COPY INTO DIM_PROVIDER_PAR_STAT FROM @MY_CSV_STAGE/_DIM_PROVIDER_PAR_STAT__202103151714.CSV.GZ
FILE_FORMAT=MYCSVFORMAT ON_ERROR = CONTINUE;
/**********************************************************************/
/*_DIM_PROVIDER_TYPE__202103151714*/
CREATE TABLE
    DIM_PROVIDER_TYPE
    (
        PROV_TYPE_DIM_ID VARCHAR(255),
        TYPE_OR_SPEC_CODE VARCHAR(255),
        TYPE_OR_SPECIALTY VARCHAR(255),
        PROV_TYPE_SHORT_DESC VARCHAR(255),
        PROV_TYPE_DESC VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        TYPE_OF_SERVICE VARCHAR(255),
        PROV_SPEC_CAT_CODE VARCHAR(255)
    ) ;
COPY INTO DIM_PROVIDER_TYPE FROM @MY_CSV_STAGE/_DIM_PROVIDER_TYPE__202103151714.CSV.GZ
FILE_FORMAT=MYCSVFORMAT
ON_ERROR = CONTINUE;

-------- DIM_BILL_TYPE Table -------------------------
CREATE TABLE
    DIM_BILL_TYPE
    (
        BILL_TYPE_DIM_ID VARCHAR(255),
        BILL_TYPE	VARCHAR(255),
        BILL_TYPE_DESC VARCHAR(255),
        INP_OUTP_IND VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        BILL_TYPE_CAT_LVL_2_DIM_ID VARCHAR(255),
        BILL_TYPE_CAT_LVL_1_DIM_ID VARCHAR(255),
        PLACE_OF_SVC_DIM_ID VARCHAR(255)
    );
--------------------------------------------------------
-------- DIM_CLAIM_STATUS Table ------------------------
CREATE TABLE
    DIM_CLAIM_STATUS
    (
        CLAIM_STATUS_DIM_ID VARCHAR(255),
        CLAIM_STATUS VARCHAR(255),
        CLAIM_STATUS_DESC	VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        CLAIM_STATUS_TYPE_DIM_ID VARCHAR(255),
        CLAIM_STATUS_TYPE VARCHAR(255),
        CLAIM_STATUS_TYPE_DESC VARCHAR(255)
    );
------------------------------------------------------------
-------- DIM_CLAIM_TYPE Table ------------------------------
CREATE TABLE
    DIM_CLAIM_TYPE
    (
        CLAIM_TYPE_DIM_ID VARCHAR(255),
        CLAIM_TYPE VARCHAR(255),
        CLAIM_TYPE_DESC VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255)
    );
------------------------------------------------------------
-------- DIM_CLASS Table -----------------------------------
CREATE TABLE
    DIM_CLASS
    (
        CLASS_DIM_ID VARCHAR(255),
        CLASS_ID VARCHAR(255),
        CLASS_DESC VARCHAR(255),
        GROUP_CODE VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255)
    );
------------------------------------------------------------
-------- DIM_COS_STL_4 Table -------------------------------
CREATE TABLE
    DIM_COS_STL_4
    (
        COS_STL_4_DIM_ID VARCHAR(255),
        COS_STL_4_DESC VARCHAR(255),
        COS_STL_3_DIM_ID VARCHAR(255),
        COS_STL_3_DESC VARCHAR(255),
        COS_STL_2_DIM_ID VARCHAR(255),
        COS_STL_2_DESC VARCHAR(255),
        COS_STL_1_DIM_ID VARCHAR(255),
        COS_STL_1_DESC VARCHAR(255),
        COS_CODE VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        COS_PRIORITY VARCHAR(255),
        UNIT_TYPE VARCHAR(255)
    );
------------------------------------------------------------
-------- DIM_DIAGNOSIS Table -------------------------------
CREATE TABLE
    DIM_DIAGNOSIS
    (
        DIAGNOSIS_DIM_ID VARCHAR(255),
        DIAGNOSIS_CODE VARCHAR(255),
        DIAGNOSIS_SHORT_DESC VARCHAR(255),
        DX_CLASS_1 VARCHAR(255),
        FROM_AGE VARCHAR(255),
        TO_AGE VARCHAR(255),
        PATIENT_GENDER VARCHAR(255),
        TRAUMA_FLAG VARCHAR(255),
        PROCEDURE_CLASS VARCHAR(255),
        DIAGNOSIS_MDC_CODE VARCHAR(255),
        OPER_PROCEDURE_FLAG VARCHAR(255),
        DIAGNOSIS_EFFECTIVE_DATE VARCHAR(255),
        DIAGNOSIS_TERM_DATE VARCHAR(255),
        PRODUCT_SERVICE_ID_QUALIFIER VARCHAR(255),
        DIAGNOSIS_NODECM_CODE VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        DIAG_FIRSTN_DIM_ID VARCHAR(255),
        DIAG_FIRSTN_CODE VARCHAR(255),
        DIAG_FIRSTN_DESC VARCHAR(255),
        DIAG_CAT_LVL_2_DIM_ID VARCHAR(255),
        DIAG_CAT_LVL_1_DIM_ID VARCHAR(255),
        ICD_VER_IND VARCHAR(255),
        CODE_TYPE VARCHAR(255),
        DIAGNOSIS_LONG_DESC VARCHAR(255)
    );
------------------------------------------------------------
-------- DIM_PRODUCT Table ---------------------------------
CREATE TABLE
    DIM_PRODUCT
    (
        PRODUCT_DIM_ID VARCHAR(255),
        PRODUCT_CODE VARCHAR(255),
        PRODUCT_DESC VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255)
    );
------------------------------------------------------------
-------- DIM_PROVIDER Table ---------------------------------
CREATE TABLE
    DIM_PROVIDER
    (
        PROV_DIM_ID	VARCHAR(255),
        SEQ_PROV_ID	VARCHAR(255),
        COMPANY_DIM_ID VARCHAR(255),
        PROVIDER_ID	VARCHAR(255),
        MCAID_ID VARCHAR(255),
        PROV_FIRST_NAME	VARCHAR(255),
        PROV_LAST_NAME VARCHAR(255),
        PROV_MIDDLE_INITIAL	VARCHAR(255),
        PROV_FULL_NAME VARCHAR(255),
        PROV_ADDRESS_LINE_1 VARCHAR(255),
        PROV_ADDRESS_LINE_2 VARCHAR(255),
        PROV_CITY VARCHAR(255),
        PROV_STATE VARCHAR(255),
        PROV_ZIP VARCHAR(255),
        COUNTY VARCHAR(255),
        PHONE_NUMBER VARCHAR(255),
        EXTENSION VARCHAR(255),
        DEA_NBR	VARCHAR(255),
        DEA_ALPHA_NBR VARCHAR(255),
        LANGUAGE_1_DIM_ID VARCHAR(255),
        LANGUAGE_2_DIM_ID VARCHAR(255),
        LANGUAGE_3_DIM_ID VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        GEOGRAPHY_DIM_ID VARCHAR(255),
        GEOGRAPHY_STATE_DIM_ID VARCHAR(255),
        PROV_GEOG_STATE VARCHAR(255),
        PROV_GEOG_STATE_DESC VARCHAR(255),
        GEOGRAPHY_COUNTY_DIM_ID VARCHAR(255),
        PROV_GEOG_COUNTY VARCHAR(255),
        PROV_GEOG_COUNTY_DESC VARCHAR(255),
        DFLT_VEND_DIM_ID VARCHAR(255),
        PROV_GEOG_ZIP VARCHAR(255),
        CONVERTED_FROM_DIM_ID VARCHAR(255),
        NABP_NBR VARCHAR(255),
        PREV_PROVIDER_ID VARCHAR(255),
        MPIN VARCHAR(255),
        UPIN VARCHAR(255),
        NATIONAL_PROVIDER_ID VARCHAR(255),
        PREV_SEQ_PROV_ID VARCHAR(255),
        MAX_ENROLLMENT VARCHAR(255),
        DOB	VARCHAR(255),
        SSN_ID VARCHAR(255),
        PROV_TYPE_DIM_ID VARCHAR(255),
        STATE_PROVIDER_TYPE VARCHAR(255),
        PREV_MCAID_ID VARCHAR(255),
        UNISON_COMMON_ID VARCHAR(255),
        PROV_ENTITY VARCHAR(255),
        CURR_PROV_GROUP_DIM_ID VARCHAR(255),
        TAXONOMY_CODE VARCHAR(255),
        GENDER_DIM_ID VARCHAR(255),
        MULT_LOC_IND VARCHAR(255),
        PROV_FAX VARCHAR(255),
        LANGUAGE_4_DIM_ID VARCHAR(255),
        LANGUAGE_5_DIM_ID VARCHAR(255),
        LANGUAGE_6_DIM_ID VARCHAR(255),
        LANGUAGE_7_DIM_ID VARCHAR(255),
        LANGUAGE_8_DIM_ID VARCHAR(255),
        TAXONOMY_CODE_DIM_ID VARCHAR(255),
        PROV_DEG_CD VARCHAR(255)
    );
------------------------------------------------------------

/* VENDOR TABLE */
// LOAD CSV FILES
CREATE
OR
REPLACE FILE FORMAT MYCSVFORMAT TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1 RECORD_DELIMITER
='\N';
//CREATING LANDING SPACE FOR CSV
CREATE
OR
REPLACE STAGE DIM_VENDOR_STAGE FILE_FORMAT = MYCSVFORMAT;
LS @DIM_VENDOR_STAGE;
/**********************************************************************/

/* ALTER FILE FORMAT*/
ALTER FILE FORMAT
IF EXISTS MYCSVFORMAT SET SKIP_HEADER= 0;
SHOW FILE FORMAT MYCSVFORMAT;

CREATE OR REPLACE TABLE
    DIM_VENDOR
    (
        VEND_DIM_ID VARCHAR(255),
        SEQ_VEND_ID VARCHAR(255),
        VENDOR_ID VARCHAR(255),
        COMPANY_DIM_ID VARCHAR(255),
        SHORT_NAME VARCHAR(255),
        VEND_FULL_NAME VARCHAR(255),
        VENDOR_TYPE VARCHAR(255),
        IRS_TAX_ID VARCHAR(255),
        HOLD_PAYMENT_FLAG VARCHAR(255),
        VEND_ADDRESS_LINE_1 VARCHAR(255),
        VEND_ADDRESS_LINE_2 VARCHAR(255),
        VEND_CITY VARCHAR(255),
        VEND_STATE VARCHAR(255),
        VEND_ZIP VARCHAR(255),
        VEND_COUNTY VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        GEOGRAPHY_DIM_ID VARCHAR(255),
        GEOGRAPHY_STATE_DIM_ID VARCHAR(255),
        VEND_GEOG_STATE VARCHAR(255),
        VEND_GEOG_STATE_DESC VARCHAR(255),
        GEOGRAPHY_COUNTY_DIM_ID VARCHAR(255),
        VEND_GEOG_COUNTY VARCHAR(255),
        VEND_GEOG_COUNTY_DESC VARCHAR(255),
        VEND_GEOG_ZIP VARCHAR(255),
        CONVERTED_FROM_DIM_ID VARCHAR(255),
        TAX_DIM_ID VARCHAR(255)
    );
--3.2.2 LOAD SOME OF THE DATA!
COPY INTO DIM_VENDOR FROM @DIM_VENDOR_STAGE/DIM_VENDOR_CONSAE.GZ FILE_FORMAT=MYCSVFORMAT
ON_ERROR = SKIP_FILE;
SELECT
    *
FROM
    DIM_VENDOR
WHERE
    VEND_DIM_ID='18122226.0000000000';
SELECT
    *
FROM
    DIM_VENDOR
WHERE
    VEND_DIM_ID='VEND_DIM_ID';
DELETE
FROM
    DIM_VENDOR
WHERE
    VEND_DIM_ID='VEND_DIM_ID';

/**********************************************************************/
/* FACT CLAIMS*/
// LOAD CSV FILES
CREATE
OR
REPLACE FILE FORMAT FACT_MYCSVFORMAT TYPE = 'CSV' COMPRESSION = GZIP FIELD_DELIMITER = '|'
SKIP_HEADER = 1 RECORD_DELIMITER='\N';
//CREATING LANDING SPACE FOR CSV
CREATE
OR
REPLACE STAGE FACT_MY_CSV_STAGE FILE_FORMAT = FACT_MYCSVFORMAT;
CREATE TABLE
    FACT_CLAIM_TEST
    (
        ADJUD_DATE VARCHAR(255),
        ALLOWED_AMT VARCHAR(255),
        AUTH_NUMBER VARCHAR(255),
        BILL_TYPE_DIM_ID VARCHAR(255),
        BILLED_AMT VARCHAR(255),
        CALC_ADMITS VARCHAR(255),
        CALC_DAYS VARCHAR(255),
        CALC_PROCEDURES VARCHAR(255),
        CALC_UNITS VARCHAR(255),
        CALC_VISITS VARCHAR(255),
        CLAIM_NUMBER VARCHAR(255),
        CLAIM_STATUS_DIM_ID VARCHAR(255),
        CLAIM_THRU_DATE VARCHAR(255),
        CLAIM_TYPE_DIM_ID VARCHAR(255),
        CLASS_DIM_ID VARCHAR(255),
        COMPANY_DIM_ID VARCHAR(255),
        CONVERTED_FROM_DIM_ID VARCHAR(255),
        COPAYMENT_1_AMT VARCHAR(255),
        COPAYMENT_2_AMT VARCHAR(255),
        COS_STL_4_DIM_ID VARCHAR(255),
        CPT_CODE_DIM_ID VARCHAR(255),
        CPT_MODIFIER_DIM_ID VARCHAR(255),
        DETAIL_SVC_DATE VARCHAR(255),
        DIAGNOSIS_1_DIM_ID VARCHAR(255),
        DRG_CODE_DIM_ID VARCHAR(255),
        LINE_NUMBER VARCHAR(255),
        MEMB_DIM_ID VARCHAR(255),
        MEMBER_AGE VARCHAR(255),
        NET_AMT VARCHAR(255),
        NOT_COVERED_AMT VARCHAR(255),
        OTHER_CARRIER_AMT VARCHAR(255),
        PAID_NET_AMT VARCHAR(255),
        PLACE_OF_SVC_1_DIM_ID VARCHAR(255),
        PLAN_DIM_ID VARCHAR(255),
        POST_DATE VARCHAR(255),
        PRIMARY_SVC_DATE VARCHAR(255),
        PROV_DIM_ID VARCHAR(255),
        PROV_SPEC_DIM_ID VARCHAR(255),
        PROV_TYPE_DIM_ID VARCHAR(255),
        PROVIDER_PAR_DIM_ID VARCHAR(255),
        QUANTITY VARCHAR(255),
        REVENUE_CODE_DIM_ID VARCHAR(255),
        SEQ_CLAIM_ID VARCHAR(255),
        SUB_LINE_CODE VARCHAR(255),
        SVC_TO_DATE VARCHAR(255),
        VEND_DIM_ID VARCHAR(255),
        WHOLE_CLAIM_STATUS_DIM_ID VARCHAR(255),
        ADJ_MM VARCHAR(255)
    );
LS @FACT_MY_CSV_STAGE;
COPY INTO DIM_VENDOR FROM @FACT_MY_CSV_STAGE/ FILE_FORMAT=MYCSVFORMAT ON_ERROR = SKIP_FILE;
/**********************************************************************/
/* MEMBER_PHI*/
LS @MEMBER_HASH_STAGE;
CREATE
OR
REPLACE STAGE MEMBER_HASH_STAGE FILE_FORMAT = MEMBER_HASH;
SELECT
    COUNT(1)
FROM
    DIM_MEMBER;
CREATE OR REPLACE TABLE
    DIM_MEMBER
    (
        MEMB_DIM_ID VARCHAR(255),
        SEQ_MEMB_ID VARCHAR(255),
        PERSON_NUMBER VARCHAR(255),
        COMPANY_DIM_ID VARCHAR(255),
        SEQ_SUBS_ID VARCHAR(255),
        SUBSCRIBER_ID VARCHAR(255),
        MEMB_ELIG_STATUS VARCHAR(255),
        DOB VARCHAR(255),
        DOD VARCHAR(255),
        GENDER VARCHAR(255),
        ETHNIC VARCHAR(255),
        SOCIAL_SEC_NO VARCHAR(255),
        MEMB_FIRST_NAME VARCHAR(255),
        MEMB_MIDDLE_INITIAL VARCHAR(255),
        MEMB_LAST_NAME VARCHAR(255),
        MEMB_ADDRESS_LINE_1 VARCHAR(255),
        MEMB_ADDRESS_LINE_2 VARCHAR(255),
        MEMB_CITY VARCHAR(255),
        MEMB_STATE VARCHAR(255),
        MEMB_ZIP VARCHAR(255),
        HOME_PHONE_NUMBER VARCHAR(255),
        BUS_PHONE_NUMBER VARCHAR(255),
        DIAMOND_ID VARCHAR(255),
        ORIGINAL_EFFECTIVE_DATE VARCHAR(255),
        DW_INSERT_DATETIME VARCHAR(255),
        DW_UPDATE_DATETIME VARCHAR(255),
        GEOGRAPHY_STATE_DIM_ID VARCHAR(255),
        GENDER_DIM_ID VARCHAR(255),
        GENDER_DESC VARCHAR(255),
        CURR_PCP_DIM_ID VARCHAR(255),
        GEOGRAPHY_DIM_ID VARCHAR(255),
        MEMB_GEOG_ZIP VARCHAR(255),
        MEMB_GEOG_STATE VARCHAR(255),
        MEMB_GEOG_STATE_DESC VARCHAR(255),
        CONVERTED_FROM_DIM_ID VARCHAR(255),
        MEDICARE_NO VARCHAR(255),
        MEDICAID_NO VARCHAR(255),
        CASE_ID VARCHAR(255),
        CURR_CASE_MANAGER_DIM_ID VARCHAR(255),
        CURR_COMORBIDITY_CNT VARCHAR(255),
        PREV_SUBSCRIBER_ID VARCHAR(255),
        PREV_SEQ_MEMB_ID VARCHAR(255),
        MC_PERSONAL_CARE_SPECIALIST VARCHAR(255),
        LANGUAGE_DIM_ID VARCHAR(255),
        IPRO_RISK_SCORE VARCHAR(255),
        RISK_SCORE_3MO VARCHAR(255),
        PRETOTDL VARCHAR(255),
        PRETOTDL3M VARCHAR(255),
        RISK_SCORE_AGESEX VARCHAR(255),
        RISK_SCORE_ACTUARIAL VARCHAR(255),
        RISK_SCORE_LAB VARCHAR(255),
        RISK_SCORE_PRG VARCHAR(255),
        VERSION_DATE VARCHAR(255),
        GROUP_DIM_ID VARCHAR(255),
        MCARE_DUAL_ENROLLED_FLAG VARCHAR(255),
        RES_PARTY_FIRST_NAME VARCHAR(255),
        RES_PARTY_LAST_NAME VARCHAR(255),
        RES_PARTY_ADDR1 VARCHAR(255),
        RES_PARTY_ADDR2 VARCHAR(255),
        RES_PARTY_ADDR3 VARCHAR(255),
        RES_PARTY_CITY VARCHAR(255),
        RES_PARTY_STATE VARCHAR(255),
        RES_PARTY_ZIP VARCHAR(255),
        RES_PARTY_GEO_DIM_ID VARCHAR(255),
        HCR_IND_DIM_ID VARCHAR(255),
        RECENT_TERM_DT VARCHAR(255),
        MEMB_ADDR_MAIL_DIM_ID VARCHAR(255),
        CELL_PHONE_NUMBER VARCHAR(255),
        WORK_PHONE_NUMBER VARCHAR(255),
        TERM_REASON_DIM_ID VARCHAR(255),
        MEDICARE_DUAL_FLAG_DIM_ID VARCHAR(255),
        ETHNIC_DIM_ID VARCHAR(255),
        QUALIFY_DATE VARCHAR(255),
        RES_PARTY_MID_INIT VARCHAR(255),
        RES_PARTY_PHONE VARCHAR(255),
        RES_PARTY_EMAIL VARCHAR(255),
        RES_PARTY_LAST_EFF_DATE VARCHAR(255),
        RES_PARTY_LAST_TERM_DATE VARCHAR(255),
        RES_PARTY_ID VARCHAR(255),
        MOTHER_MEMB_DIM_ID VARCHAR(255),
        HOMELESS_FLAG_DIM_ID VARCHAR(255),
        FAM_RELATIONSHIP VARCHAR(255),
        FAM_LINK_ID VARCHAR(255),
        IEX_MEMB_ID VARCHAR(255)
    );
COPY INTO DIM_MEMBER FROM @MEMBER_HASH_STAGE/ FILE_FORMAT=MEMBER_HASH ON_ERROR = SKIP_FILE;
/* LOAD ERROR FILES*/
COPY INTO DIM_MEMBER FROM @MEMBER_HASH_STAGE/DIM_MEMBER_21.CSV.GZ FILE_FORMAT=MEMBER_HASH ON_ERROR
= SKIP_FILE;
COPY INTO DIM_MEMBER FROM @MEMBER_HASH_STAGE/DIM_MEMBER_164.CSV.GZ FILE_FORMAT=MEMBER_HASH ON_ERROR
= SKIP_FILE;
COPY INTO DIM_MEMBER FROM @MEMBER_HASH_STAGE/DIM_MEMBER_106.CSV.GZ FILE_FORMAT=MEMBER_HASH ON_ERROR
= SKIP_FILE;
COPY INTO DIM_MEMBER FROM @MEMBER_HASH_STAGE/DIM_MEMBER_134.CSV.GZ FILE_FORMAT=MEMBER_HASH ON_ERROR
= SKIP_FILE;
/* VALIDATE ERROR FILE LOAD INTO DIM_MEMBER*/
SELECT
    COUNT(*)
FROM
    DIM_MEMBER;
SELECT
    TOP 20 *
FROM
    DIM_MEMBER
WHERE
    LENGTH(DOB) > 4;
DROP TABLE
    MEMBER_HASH;
/* LIST ALL THE FILE */
LS @MEMBER_HASH_STAGE/;
/* REMOVE LOADE FILE FROM STAGE */
REMOVE @TCOC.MEMBER_HASH_STAGE PATTERN='.*.CSV.GZ';
SELECT
    TABLE_SCHEMA AS SCHEMA,
    SUM(BYTES)   AS BYTES
FROM
    INFORMATION_SCHEMA.TABLES
GROUP BY
    SCHEMA;
SELECT
    *
FROM
    INFORMATION_SCHEMA.TABLE_STORAGE_METRICS;

/**********************************************************************/
