# Author: Mary Jasline Vinodh
# Date: 04/13/2022
# Description: Compare a data set from compact tables in Snowflake against Foundation tables in Snowflake, document the differences

import cx_Oracle
import pandas as pd
import snowflake.connector

sf_conn = snowflake.connector.connect(
    user='your-username',
    role='your-role',
    warehouse = 'your-warehouse',
    database = 'your-database',
    schema = 'FOUNDATION',
    account='your-account',
    authenticator='externalbrowser'
)

sf_conn1 = snowflake.connector.connect(
    user='your-username',
    role='your-role',
    warehouse = 'your-warehouse',
    database = 'your-database',
    schema = 'COMPACT',
    account='your-account',
    authenticator='externalbrowser'
)

diff_path = 'C:/Users/your-folder/Documents/Data_Profiles/'
tgt_tb_name = 'CLM_TRANS_SRVC_LN'
tgt_schema_name = 'FOUNDATION'


def execute_compare(query1, query2, yearn, monthn, dayn):
    try:

        s1 = pd.read_sql(query1, con=sf_conn1)
        s2 = pd.read_sql(query2, con=sf_conn)

        s1 = s1.replace([None], [''], regex=True)
        s2 = s2.replace([None], [''], regex=True)

        s1 = s1.fillna('')
        s2 = s2.fillna('')

        df_diff2 = pd.concat([s2, s1], keys=['Snowflake', 'Snowflake']).drop_duplicates(keep=False)

        if (df_diff2.size > 0):
            df_diff2.to_csv(diff_path + tgt_tb_name + '_' + yearn + '_' + monthn + '_' + dayn + '_Diffs.csv')


    except Exception as e:
        print(e, e.args)
        pass


# update these 4 values to target specific dates by year, month and d, where "d" = Day of the month to start validation
# and endday = the day of the month to validate (up-to-this-day), example: validate every day from 8-11-2021 through 8-15-2021
yearNumber = 2022
month = 1
day = 1
endday = 1
# you can increase the amount of records to validate per day with the next value, but I found 2000 is the sweet spot where
# performance is not greatly affected, yet the amount of records is high enough for accuracy
rowcomparison = '2000'
try:

    while day <= endday:
        try:
            print('generating report for ' + 'CLM_TRANS_SRVC_LN' + ' ' + str(yearNumber) + ' ' + str(month) + ' ' + str(
                day))
            q1 = "SELECT " + " CONCAT(COF.CONVERTED_FROM, CMP.COMPANY_CODE, CLM.CLAIM_NUMBER, CLM.LINE_NUMBER,TRIM(CLM.SUB_LINE_CODE)) CLM_TRANS_SYS_ID," \
                             "CLM.CLAIM_NUMBER CLM_AUD_SRC_ID,COF.CONVERTED_FROM CLM_AUD_SRC_SYS_CD,CLM.CLAIM_NUMBER as CLM_AUD_NBR,TO_CHAR(CLM.LINE_NUMBER) CLM_AUD_LN_NBR," \
                             "TRIM(CLM.SUB_LINE_CODE) CLM_AUD_TRANS_SEQ_NBR,CLM.AUTH_NUMBER CLM_SRC_AUTH_NBR, LIB.LINE_OF_BUSINESS_DESC CLM_SRC_MBR_ACCT_NBR,MMB.FAM_LINK_ID CLM_SRC_MBR_FAM_ID," \
                             " CASE WHEN COF.CONVERTED_FROM = \'CSP' AND MMB.GENDER_DESC ='FEMALE' THEN 'F' WHEN COF.CONVERTED_FROM = 'CSP' AND MMB.GENDER_DESC = 'MALE' THEN 'M' WHEN COF.CONVERTED_FROM = 'CSP' AND MMB.GENDER_DESC = 'UNKNOWN' THEN 'U' ELSE MMB.GENDER_DESC END  AS CLM_SRC_MBR_GDR_CD," \
                             "PLN.PLAN_CODE CLM_SRC_MBR_GRP_ID,PFA.MARKET CLM_SRC_MBR_MKT_DERIV_NBR,CASE WHEN COF.CONVERTED_FROM = 'CSP' THEN 'Y' ELSE NULL END CLM_SRC_MBR_NON_UHG_EE_FLG," \
                             "SRP.SOURCE_PRODUCT_CODE CLM_SRC_MBR_PLN_ID,SRP.SOURCE_PRODUCT_CODE CLM_SRC_MBR_PRDCT_CD,CASE WHEN COF.CONVERTED_FROM = 'CSP' THEN MMB.FAM_RELATIONSHIP ELSE NULL END CLM_SRC_MBR_REL_CD,MMB.SUBSCRIBER_ID CLM_SRC_MBR_SBSCR_ID," \
                             "TO_CHAR(MMB.SEQ_MEMB_ID) CLM_SRC_MBR_SYS_ID,PRV.PROV_CITY CLM_SRC_PROV_SRVC_CTY_NM,PRV.PROV_STATE CLM_SRC_PROV_SRVC_ST_CD,PRV.PROVIDER_ID CLM_SRC_PROV_SYS_ID," \
                             "ADJ.AUTO_ADJUD_FLAG_DESC CLM_TRANS_ADJ_CD,CO1.COS_STL_1_DESC CLM_TRANS_CLM_FM_TYP_CD," \
                             "DI1.DIAGNOSIS_NODECM_CODE CLM_TRANS_DIAG_1_CD,CT11.DIAG_CAT_LVL_1_DESC CLM_TRANS_DIAG_1_CD_CATGY_LVL_1_DESC," \
                             "ED1.DIAG_DERIV_TYP_CD CLM_TRANS_DIAG_1_CD_TYP_CD,DI2.DIAGNOSIS_NODECM_CODE CLM_TRANS_DIAG_2_CD," \
                             "CT21.DIAG_CAT_LVL_1_DESC CLM_TRANS_DIAG_2_CD_CATGY_LVL_1_DESC,ED2.DIAG_DERIV_TYP_CD CLM_TRANS_DIAG_2_CD_TYP_CD," \
                             "DI3.DIAGNOSIS_NODECM_CODE CLM_TRANS_DIAG_3_CD,CT31.DIAG_CAT_LVL_1_DESC CLM_TRANS_DIAG_3_CD_CATGY_LVL_1_DESC," \
                             "ED3.DIAG_DERIV_TYP_CD CLM_TRANS_DIAG_3_CD_TYP_CD,DI4.DIAGNOSIS_NODECM_CODE CLM_TRANS_DIAG_4_CD," \
                             "CT41.DIAG_CAT_LVL_1_DESC CLM_TRANS_DIAG_4_CD_CATGY_LVL_1_DESC,ED4.DIAG_DERIV_TYP_CD CLM_TRANS_DIAG_4_CD_TYP_CD," \
                             "DI5.DIAGNOSIS_NODECM_CODE CLM_TRANS_DIAG_5_CD,CT51.DIAG_CAT_LVL_1_DESC CLM_TRANS_DIAG_5_CD_CATGY_LVL_1_DESC," \
                             "ED5.DIAG_DERIV_TYP_CD CLM_TRANS_DIAG_5_CD_TYP_CD,ED1.MH_SA_CD CLM_TRANS_DIAG_MH_SA_CD," \
                             "CASE WHEN ED1.MH_SA_CD = 'SA' OR  ED2.MH_SA_CD = 'SA' OR  ED3.MH_SA_CD = 'SA' OR  ED4.MH_SA_CD = 'SA' OR  ED5.MH_SA_CD = 'SA' THEN 'Y' ELSE 'N' END CLM_TRANS_DIAG_SBSTNC_ABUS_FLG,CRL.CARE_LEVEL_DESC CLM_TRANS_DLOC_TXT," \
                             "CRL.CARE_LEVEL_CODE CLM_TRANS_DLOC_SEQ_NBR," \
                             "BIT.INP_OUTP_IND CLM_TRANS_DLOC_CATGY_TXT,CLM.ADJUD_DATE CLM_TRANS_DT_ADJD_DT,CLM.DIAMOND_INSERT_DATE CLM_TRANS_DT_ENT_DT,CLM.POST_DATE CLM_TRANS_DT_PD_DT," \
                             "CLM.DATE_RECEIVED CLM_TRANS_DT_RCVD_DT,CLM.POST_DATE CLM_TRANS_DT_PST_DT,CLM.DETAIL_SVC_DATE CLM_TRANS_DT_SRVC_FROM_DT,CLM.SVC_TO_DATE CLM_TRANS_DT_SRVC_THRU_DT," \
                             "BT1.BILL_TYPE_CAT_LVL_1_DESC CLM_TRANS_LVL_OF_SRVC_DERIV_CD,BT1.BILL_TYPE_CAT_LVL_1_SHORT_DESC CLM_TRANS_LVL_OF_SRVC_SRC_CD," \
                             "TRUNC(CLM.MEMBER_AGE) CLM_TRANS_MBR_IN_YR_AGE,SVC.PLACE_OF_SVC_CODE CLM_TRANS_PL_OF_SRVC_AMA_CD," \
                             "PMO.MODIFIER_CODE CLM_TRANS_PROC_MOD_CD,CASE WHEN CLM.REVENUE_CODE_DIM_ID > 0 THEN REV.CODE_TYPE ELSE PRC.CODE_TYPE END CLM_TRANS_PROC_TYP_CD," \
                             "CTR.TAX_ID CLM_SRC_PROV_TAX_ID_NBR,PRV.PROV_ZIP CLM_SRC_PROV_SRVC_ZIP_CD,PRV.NATIONAL_PROVIDER_ID CLM_SRC_PROV_CLM_NPI_ID," \
                             "WCS.WHOLE_CLAIM_STATUS CLM_TRANS_RSN_TYP_CD,DI1.DIAGNOSIS_NODECM_CODE CLM_TRANS_CLM_PRI_DIAG_CD,CLM.ACTUAL_ADMISSION_DATE CLM_TRANS_DT_ADMIT_DT," \
                             "CLM.ADMIT_TYPE CLM_TRANS_ADMIT_TYP_CD,ADS.ADMIT_SOURCE_CODE  CLM_TRANS_ADMIT_SRC_CD," \
                             "CLM.PRIMARY_SVC_DATE CLM_TRANS_DT_CLM_FST_SRVC_DT,CLM.CLAIM_THRU_DATE CLM_TRANS_DT_CLM_LST_SRVC_DT," \
                             "BIT.BILL_TYPE CLM_TRANS_BILL_TYP_CD,CLM.PATIENT_STATUS CLM_TRANS_DSCHRG_STS_CD,DRG.DRG_CODE CLM_TRANS_SYS_DIAG_REL_GRP_CD," \
                             "DRG.DRG_CODE CLM_TRANS_ENT_DIAG_REL_GRP_CD,EOB.REASON_DESC CLM_TRANS_CLM_LVL_RSN_CD_DESC,EOB.REASON_CODE CLM_TRANS_EOB_RSN_CD_DESC," \
                             "CLM.AUTH_NUMBER CLM_TRANS_AUTH_NBR,CLM.RX_SUPPLY_DAYS CLM_TRANS_SUPP_ORDR_IND,VEN.VEND_FULL_NAME CLM_SRC_PROV_PAYE_NM," \
                             "COALESCE(ED1.DIAG_DERIV_DESC, DI1.DIAGNOSIS_LONG_DESC) CLM_TRANS_DIAG_1_CD_DESC," \
                             "COALESCE(ED2.DIAG_DERIV_DESC, DI2.DIAGNOSIS_LONG_DESC) CLM_TRANS_DIAG_2_CD_DESC,COALESCE(ED3.DIAG_DERIV_DESC, DI3.DIAGNOSIS_LONG_DESC) CLM_TRANS_DIAG_3_CD_DESC," \
                             "COALESCE(ED4.DIAG_DERIV_DESC, DI4.DIAGNOSIS_LONG_DESC) CLM_TRANS_DIAG_4_CD_DESC,COALESCE(ED5.DIAG_DERIV_DESC, DI5.DIAGNOSIS_LONG_DESC) CLM_TRANS_DIAG_5_CD_DESC," \
                             "PRC.PROCEDURE_CODE CLM_TRANS_PROC_CD,PRC.PROCEDURE_CODE_SHORT_DESC CLM_TRANS_PROC_DESC," \
                             "ED1.ICD_DIAG_TYP_CD ICD_DIAG_TYP_CD,CASE WHEN CLM.ALLOWED_REASON_DIM_ID > 0 THEN ALLOW.REASON_DESC ELSE NOTC.REASON_DESC END CLM_TRANS_RSN_DESC," \
                             "COALESCE(ED1.DSM_TYP_CD, DI1.CODE_TYPE) CLM_TRANS_DIAG_1_DSM_TYP_CD,COALESCE(ED2.DSM_TYP_CD, DI2.CODE_TYPE) CLM_TRANS_DIAG_2_DSM_TYP_CD," \
                             "COALESCE(ED3.DSM_TYP_CD, DI3.CODE_TYPE) CLM_TRANS_DIAG_3_DSM_TYP_CD,COALESCE(ED4.DSM_TYP_CD, DI4.CODE_TYPE) CLM_TRANS_DIAG_4_DSM_TYP_CD," \
                             "COALESCE(ED5.DSM_TYP_CD, DI5.CODE_TYPE) CLM_TRANS_DIAG_5_DSM_TYP_CD," \
                             "EOB.REASON_CODE CLM_TRANS_CLM_LVL_RSN_CD,PM2.MODIFIER_CODE CLM_TRANS_PROC_MOD_2_CD,PM3.MODIFIER_CODE CLM_TRANS_PROC_MOD_3_CD," \
                             "PM4.MODIFIER_CODE CLM_TRANS_PROC_MOD_4_CD,REV.PROCEDURE_CODE CLM_TRANS_RVNU_CD," \
                             "REV.PROCEDURE_CODE_LONG_DESC CLM_TRANS_RVNU_DESC,PRC.PROCEDURE_CODE CLM_TRANS_SEC_PROC_CD," \
                             "PRC.PROCEDURE_CODE_SHORT_DESC CLM_TRANS_SEC_PROC_DESC,PRC.CODE_TYPE CLM_TRANS_SEC_PROC_TYP_CD," \
                             "CLT.CLAIM_TYPE SRC_FINC_LIAB_CD,CASE WHEN CLM.CLAIM_TYPE_DIM_ID IN (6,7,8) THEN 'TRUE' ELSE 'FALSE' END DERIV_OBH_FINC_LIAB," \
                             "PRV.NATIONAL_PROVIDER_ID CLM_SRC_PROV_CLM_SRVC_NPI_ID,CLM.REF_PROVIDER_NPI CLM_SRC_PROV_CLM_REF_NPI_ID," \
                             "CLM.SRC_SERVICE_NPI CLM_SRC_PROV_CLM_FAC_NPI_ID,PRV.NATIONAL_PROVIDER_ID CLM_SRC_PROV_CLM_RNDR_NPI_ID," \
                             "CLM.SRC_BILLING_NPI CLM_SRC_PROV_CLM_BIL_NPI_ID,TO_CHAR(CLM.PROVIDER_NPI) CLM_SRC_PROV_CLM_PAYE_NPI_ID," \
                             "CLM.SRC_ADMITTING_NPI CLM_SRC_PROV_CLM_ADMIT_NPI_ID,TO_CHAR(CLM.ATT_PROV_NPI) CLM_SRC_PROV_CLM_ATD_NPI_ID," \
                             "CASE WHEN CLM.ALLOWED_REASON_DIM_ID > 0 THEN ALLOW.REASON_CODE ELSE NOTC.REASON_CODE END CLM_TRANS_RSN_CD," \
                             "PAG.PROV_AGREEMENT_ID CLM_TRANS_AGRMNT_ID,PAG.AGREEMENT_DESC CLM_TRANS_AGRMNT_DESC," \
                             "WCS.WHOLE_CLAIM_STATUS_DESC	CLM_TRANS_RSN_TYP_DESC,CLT.CLAIM_TYPE_DESC SRC_FINC_LIAB_DESC," \
                             "COALESCE(ED1.DIAG_CATGY_DERIV_DESC, CT12.DIAG_CAT_LVL_2_DESC) CLM_TRANS_DIAG_1_CD_CATGY_LVL_2_DESC," \
                             "COALESCE(ED2.DIAG_CATGY_DERIV_DESC, CT22.DIAG_CAT_LVL_2_DESC) CLM_TRANS_DIAG_2_CD_CATGY_LVL_2_DESC," \
                             "COALESCE(ED3.DIAG_CATGY_DERIV_DESC, CT32.DIAG_CAT_LVL_2_DESC) CLM_TRANS_DIAG_3_CD_CATGY_LVL_2_DESC," \
                             "COALESCE(ED4.DIAG_CATGY_DERIV_DESC, CT42.DIAG_CAT_LVL_2_DESC) CLM_TRANS_DIAG_4_CD_CATGY_LVL_2_DESC," \
                             "COALESCE(ED5.DIAG_CATGY_DERIV_DESC, CT52.DIAG_CAT_LVL_2_DESC) CLM_TRANS_DIAG_5_CD_CATGY_LVL_2_DESC," \
                             "TO_CHAR(CLM.MEMB_DIM_ID) MBR_SYS_ID,NULL PERS_SYS_ID,PLN.PLAN_CODE  PKG_SYS_ID," \
                             "CLM.ALLOWED_AMT CLM_TRANS_ALLW_AMT,CLM.ALLOWED_AMT CLM_TRANS_ALLW_DERIV_AMT,CLM.COPAYMENT_1_AMT CLM_TRANS_COB_AMT," \
                             "CLM.COPAYMENT_2_AMT CLM_TRANS_COINS_AMT,CLM.ALLOWED_AMT CLM_TRANS_CONTR_AMT,CLM.COPAYMENT_1_AMT CLM_TRANS_COPAY_AMT," \
                             "CLM.DEDUCTIBLE_AMT CLM_TRANS_DED_AMT,CLM.NOT_COVERED_AMT CLM_TRANS_DSALLW_AMT,CLM.DISCOUNT_AMT CLM_TRANS_DSCNT_AMT," \
                             "CLM.COPAYMENT_2_AMT CLM_TRANS_MBR_RESP_AMT,CLM.PAID_NET_AMT CLM_TRANS_PD_AMT,CLM.WITHHOLD_AMT CLM_TRANS_RSRV_AMT," \
                             "CLM.BILLED_AMT CLM_TRANS_SBMT_AMT,CLM.QUANTITY CLM_TRANS_ALLWD_QTY,CLM.BILLED_QUANTITY CLM_TRANS_BILL_QTY," \
                             "CLM.CALC_VISITS CLM_TRANS_COV_VST_CNT,CLM.CALC_DAYS CLM_TRANS_COV_DAYS_CNT,CLM.CALC_UNITS CLM_TRANS_SRVC_UNT_CNT," \
                             "CLM.CALC_PROCEDURES CLM_TRANS_PROC_CNT,CLM.CALC_ADMITS CLM_TRANS_ALLWD_ADMTS," \
                             "CMP.COMPANY_CODE SRC_CUST_CD,CMP.COMPANY_DESC SRC_CUST_NM,AHFS.AHFS_THER_CLASS_CODE CLM_TRANS_THER_CLASS_CD," \
                             "AHFS.AHFS_THER_CLASS_DESC CLM_TRANS_THER_CLASS_DESC,PLPRG.PROGRAM_CODE CLM_TRANS_PKG_CD,PLPRG.PROGRAM_DESC CLM_TRANS_PKG_NM," \
                             "CLSS.CLASS_ID CLM_TRANS_MKT_PKG_CD,CLSS.CLASS_DESC CLM_TRANS_MKT_PKG_DESC,CLSSPLN.CLASS_PLAN_ID CLM_TRANS_PLAN_CD," \
                             "CLSSPLN.CLASS_PLAN_DESC CLM_TRANS_PLAN_DESC,LOBTYP.LINE_OF_BUSINESS_TYPE_DESC CLM_TRANS_PRDCT_TYP_DESC," \
                             "PLN.PLAN_DESC CLM_SRC_MBR_GRP_NAME,SVC.PLACE_OF_SVC_DESC CLM_TRANS_PL_OF_SRVC_AMA_DESC," \
                             "VEN.VENDOR_TYPE CLM_SRC_PROV_PAYE_TYP,VEN.IRS_TAX_ID CLM_SRC_PROV_PAYE_TAX_ID," \
                             "PMO.PROCEDURE_MODIFIER_DESC CLM_TRANS_PROC_MOD_DESC,PM2.PROCEDURE_MODIFIER_DESC CLM_TRANS_PROC_MOD_2_DESC," \
                             "PM3.PROCEDURE_MODIFIER_DESC CLM_TRANS_PROC_MOD_3_DESC,PM4.PROCEDURE_MODIFIER_DESC CLM_TRANS_PROC_MOD_4_DESC," \
                             "BIT.BILL_TYPE_DESC CLM_TRANS_BILL_TYP_DESC," \
                             "DRG.DRG_CODE_SHORT_DESC CLM_TRANS_SYS_DIAG_REL_GRP_DESC,NDC.NDC_CODE CLM_TRANS_NDC_CD," \
                             "NDC.GENERIC_NAME CLM_TRANS_NDC_GNRC_NM,CO1.COS_CODE CLM_TRANS_COS_CD," \
                             "CO1.COS_STL_1_DESC CLM_TRANS_COS_LVL1_DESC,CO1.COS_STL_2_DESC CLM_TRANS_COS_LVL2_DESC," \
                             "CO1.COS_STL_3_DESC CLM_TRANS_COS_LVL3_DESC,CO1.COS_STL_4_DESC CLM_TRANS_COS_LVL4_DESC," \
                             "PARST.PROVIDER_PAR_STAT SRC_PROV_NTWK_CD,PARST.PROVIDER_DESC SRC_PROV_NTWK_DESC," \
                             "CLMST.CLAIM_STATUS CLM_SRVC_LN_STS_CD,CLMST.CLAIM_STATUS_DESC CLM_SRVC_LN_STS_DESC," \
                             "CATLVL1.CPT_CAT_LVL_1_DESC CLM_TRANS_PROC_CTGY_LVL_1_DESC,CATLVL2.CPT_CAT_LVL_2_DESC CLM_TRANS_PROC_CTGY_LVL_2_DESC," \
                             "CATLVL3.CPT_CAT_LVL_3_DESC CLM_TRANS_PROC_CTGY_LVL_3_DESC,MMB.DIAMOND_ID SRC_MBR_ID,MMB.MEDICAID_NO MEDCD_ID,MMB.MEDICARE_NO MEDCR_ID" \
                             " FROM COMPACT.FACT_CLAIM CLM " \
                             " LEFT JOIN COMPACT.DIM_COMPANY CMP ON CLM.COMPANY_DIM_ID = CMP.COMPANY_DIM_ID   LEFT JOIN COMPACT.DIM_CONVERTED_FROM COF ON COF.CONVERTED_FROM_DIM_ID = CLM.CONVERTED_FROM_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_LINE_OF_BUSINESS LIB ON CLM.LINE_OF_BUSINESS_DIM_ID = LIB.LINE_OF_BUSINESS_DIM_ID  LEFT JOIN COMPACT.DIM_MEMBER MMB ON  CLM.MEMB_DIM_ID = MMB.MEMB_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_PLAN PLN ON PLN.PLAN_DIM_ID = CLM.PLAN_DIM_ID AND CLM.COMPANY_DIM_ID = PLN.ETL_COMPANY_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_PROVIDER PRV ON PRV.PROV_DIM_ID = CLM.PROV_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROVIDER_FACILITY PFA ON PRV.MPIN = PFA.MPIN AND PRV.PROV_GEOG_ZIP = PFA.ZIP " \
                             " LEFT JOIN COMPACT.DIM_SOURCE_PRODUCT SRP ON SRP.SOURCE_PRODUCT_DIM_ID = CLM.SOURCE_PRODUCT_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_AUTO_ADJUD_FLAG ADJ ON ADJ.AUTO_ADJUD_FLAG_DIM_ID = CLM.AUTO_ADJUD_FLAG_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_DIAGNOSIS DI1 ON CLM.DIAGNOSIS_1_DIM_ID = DI1.DIAGNOSIS_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_1 CT11 ON DI1.DIAG_CAT_LVL_1_DIM_ID = CT11.DIAG_CAT_LVL_1_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_2 CT12 ON DI1.DIAG_CAT_LVL_2_DIM_ID = CT12.DIAG_CAT_LVL_2_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAGNOSIS DI2 ON CLM.DIAGNOSIS_2_DIM_ID = DI2.DIAGNOSIS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_1 CT21 ON DI2.DIAG_CAT_LVL_1_DIM_ID = CT21.DIAG_CAT_LVL_1_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_2 CT22 ON DI2.DIAG_CAT_LVL_2_DIM_ID = CT22.DIAG_CAT_LVL_2_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAGNOSIS DI3 ON CLM.DIAGNOSIS_3_DIM_ID = DI3.DIAGNOSIS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_1 CT31 ON DI3.DIAG_CAT_LVL_1_DIM_ID = CT31.DIAG_CAT_LVL_1_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_2 CT32 ON DI3.DIAG_CAT_LVL_2_DIM_ID = CT32.DIAG_CAT_LVL_2_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAGNOSIS DI4 ON CLM.DIAGNOSIS_4_DIM_ID = DI4.DIAGNOSIS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_1 CT41 ON DI4.DIAG_CAT_LVL_1_DIM_ID = CT41.DIAG_CAT_LVL_1_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_2 CT42 ON DI4.DIAG_CAT_LVL_2_DIM_ID = CT42.DIAG_CAT_LVL_2_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAGNOSIS DI5 ON CLM.DIAGNOSIS_5_DIM_ID = DI5.DIAGNOSIS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_1 CT51 ON DI5.DIAG_CAT_LVL_1_DIM_ID = CT51.DIAG_CAT_LVL_1_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_DIAG_CAT_LVL_2 CT52 ON DI5.DIAG_CAT_LVL_2_DIM_ID = CT52.DIAG_CAT_LVL_2_DIM_ID" \
                             " LEFT JOIN FOUNDATION.EDW_TB_DIAG_DEDUP ED1 ON DI1.DIAGNOSIS_NODECM_CODE = ED1.DIAG_CD" \
                             " LEFT JOIN FOUNDATION.EDW_TB_DIAG_DEDUP ED2 ON DI2.DIAGNOSIS_NODECM_CODE = ED2.DIAG_CD" \
                             " LEFT JOIN FOUNDATION.EDW_TB_DIAG_DEDUP ED3 ON DI3.DIAGNOSIS_NODECM_CODE = ED3.DIAG_CD" \
                             " LEFT JOIN FOUNDATION.EDW_TB_DIAG_DEDUP ED4 ON DI4.DIAGNOSIS_NODECM_CODE = ED4.DIAG_CD" \
                             " LEFT JOIN FOUNDATION.EDW_TB_DIAG_DEDUP ED5 ON DI5.DIAGNOSIS_NODECM_CODE = ED5.DIAG_CD " \
                             " LEFT JOIN COMPACT.DIM_COS_STL_4 CO1 ON CO1.COS_STL_4_DIM_ID = CLM.COS_STL_4_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_CARE_LEVEL CRL ON CLM.CARE_LEVEL_DIM_ID = CRL.CARE_LEVEL_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_CLAIM_TYPE CLT ON CLM.CLAIM_TYPE_DIM_ID = CLT.CLAIM_TYPE_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_BILL_TYPE BIT ON CLM.BILL_TYPE_DIM_ID = BIT.BILL_TYPE_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_PLACE_OF_SVC SVC ON CLM.PLACE_OF_SVC_1_DIM_ID = SVC.PLACE_OF_SVC_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_BILL_TYPE_CAT_LVL_1 BT1 ON BT1.BILL_TYPE_CAT_LVL_1_DIM_ID = BIT.BILL_TYPE_CAT_LVL_1_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_DRG_CODE DRG ON CLM.DRG_CODE_DIM_ID = DRG.DRG_CODE_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_PROCEDURE_CODE REV ON CLM.REVENUE_CODE_DIM_ID = REV.PROCEDURE_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROCEDURE_CODE PRC ON CLM.CPT_CODE_DIM_ID = PRC.PROCEDURE_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_REASON_CODE ALLOW ON CLM.ALLOWED_REASON_DIM_ID = ALLOW.REASON_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_REASON_CODE NOTC ON CLM.NOT_COVERED_REASON_DIM_ID = NOTC.REASON_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_REASON_CODE EOB ON CLM.EOB_DIM_ID = EOB.REASON_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROCEDURE_MODIFIER PMO ON CLM.CPT_MODIFIER_DIM_ID = PMO.MODIFIER_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROCEDURE_MODIFIER PM2 ON CLM.CPT_MODIFIER_2_DIM_ID = PM2.MODIFIER_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROCEDURE_MODIFIER PM3 ON CLM.CPT_MODIFIER_3_DIM_ID = PM3.MODIFIER_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROCEDURE_MODIFIER PM4 ON CLM.CPT_MODIFIER_4_DIM_ID = PM4.MODIFIER_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_ADMIT_SOURCE ADS ON ADS.ADMIT_SOURCE_DIM_ID = CLM.ADMIT_SOURCE_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROVIDER_CONTRACT CTR  ON CLM.CONTRACT_DIM_ID = CTR.CONTRACT_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_WHOLE_CLAIM_STATUS WCS ON WCS.WHOLE_CLAIM_STATUS_DIM_ID = CLM.WHOLE_CLAIM_STATUS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_NDC_CODE NDC ON CLM.NDC_CODE_DIM_ID = NDC.NDC_CODE_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_VENDOR VEN ON VEN.VEND_DIM_ID = CLM.VEND_DIM_ID " \
                             " LEFT JOIN COMPACT.DIM_PROV_AGREEMENT  PAG ON CTR.PROV_AGREEMENT_DIM_ID = PAG.PROV_AGREEMENT_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_AHFS_THER_CLASS_CODE AHFS ON NDC.AHFS_THER_CLASS_DIM_ID = AHFS.AHFS_THER_CLASS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PLAN_LOB PLB  ON CLM.PLAN_LOB_DIM_ID = PLB.PLAN_LOB_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_LINE_OF_BUSINESS LOB ON PLB.LINE_OF_BUSINESS_DIM_ID = LOB.LINE_OF_BUSINESS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_LINE_OF_BUSINESS_TYPE LOBTYP ON LOB.LINE_OF_BUSINESS_TYPE_DIM_ID = LOBTYP.LINE_OF_BUSINESS_TYPE_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PLAN_PROGRAM PLPRG ON PLB.PLAN_PROGRAM_DIM_ID = PLPRG.PLAN_PROGRAM_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_CLASS CLSS ON CLM.CLASS_DIM_ID = CLSS.CLASS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_CLASS_PLAN CLSSPLN ON CLM.CLASS_PLAN_DIM_ID = CLSSPLN.CLASS_PLAN_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_PROVIDER_PAR_STAT PARST ON PARST.PROVIDER_PAR_DIM_ID = CLM.PROVIDER_PAR_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_CLAIM_STATUS CLMST ON CLMST.CLAIM_STATUS_DIM_ID = CLM.CLAIM_STATUS_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_CPT_CAT_LVL_1 CATLVL1 ON PRC.CPT_CAT_LVL_1_DIM_ID = CATLVL1.CPT_CAT_LVL_1_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_CPT_CAT_LVL_2 CATLVL2 ON PRC.CPT_CAT_LVL_2_DIM_ID = CATLVL2.CPT_CAT_LVL_2_DIM_ID" \
                             " LEFT JOIN COMPACT.DIM_CPT_CAT_LVL_3 CATLVL3 ON PRC.CPT_CAT_LVL_3_DIM_ID = CATLVL3.CPT_CAT_LVL_3_DIM_ID" \
                             " WHERE CLM.CLAIM_TYPE_DIM_ID not in (3,8) and EXTRACT(YEAR FROM DETAIL_SVC_DATE) = " \
                 + str(yearNumber) + " AND EXTRACT(MONTH FROM DETAIL_SVC_DATE) = " + str(month) \
                 + " AND EXTRACT(DAY FROM DETAIL_SVC_DATE) = " + str(day) \
                 + " ORDER BY CLM.CLAIM_NUMBER,CLM.LINE_NUMBER,CLM.SUB_LINE_CODE FETCH FIRST " + rowcomparison + ' ROWS ONLY'

            q2 = 'SELECT CLM_TRANS_SYS_ID ,CLM_AUD_SRC_ID,CLM_AUD_SRC_SYS_CD,CLM_AUD_NBR,CLM_AUD_LN_NBR,CLM_AUD_TRANS_SEQ_NBR,CLM_SRC_AUTH_NBR,' \
                 'CLM_SRC_MBR_ACCT_NBR,CLM_SRC_MBR_FAM_ID,CLM_SRC_MBR_GDR_CD,CLM_SRC_MBR_GRP_ID,CLM_SRC_MBR_MKT_DERIV_NBR,CLM_SRC_MBR_NON_UHG_EE_FLG,' \
                 'CLM_SRC_MBR_PLN_ID,CLM_SRC_MBR_PRDCT_CD,CLM_SRC_MBR_REL_CD,' \
                 'CLM_SRC_MBR_SBSCR_ID,CLM_SRC_MBR_SYS_ID,CLM_SRC_PROV_SRVC_CTY_NM,CLM_SRC_PROV_SRVC_ST_CD,CLM_SRC_PROV_SYS_ID,' \
                 'CLM_TRANS_ADJ_CD,CLM_TRANS_CLM_FM_TYP_CD,CLM_TRANS_DIAG_1_CD,CLM_TRANS_DIAG_1_CD_CATGY_LVL_1_DESC,CLM_TRANS_DIAG_1_CD_TYP_CD,' \
                 'CLM_TRANS_DIAG_2_CD,CLM_TRANS_DIAG_2_CD_CATGY_LVL_1_DESC,' \
                 'CLM_TRANS_DIAG_2_CD_TYP_CD,CLM_TRANS_DIAG_3_CD,CLM_TRANS_DIAG_3_CD_CATGY_LVL_1_DESC,CLM_TRANS_DIAG_3_CD_TYP_CD,CLM_TRANS_DIAG_4_CD,CLM_TRANS_DIAG_4_CD_CATGY_LVL_1_DESC,CLM_TRANS_DIAG_4_CD_TYP_CD,' \
                 'CLM_TRANS_DIAG_5_CD,CLM_TRANS_DIAG_5_CD_CATGY_LVL_1_DESC,CLM_TRANS_DIAG_5_CD_TYP_CD,CLM_TRANS_DIAG_MH_SA_CD,CLM_TRANS_DIAG_SBSTNC_ABUS_FLG,CLM_TRANS_DLOC_TXT,CLM_TRANS_DLOC_SEQ_NBR,CLM_TRANS_DLOC_CATGY_TXT ,CLM_TRANS_DT_ADJD_DT,' \
                 'CLM_TRANS_DT_ENT_DT,CLM_TRANS_DT_PD_DT,CLM_TRANS_DT_RCVD_DT,CLM_TRANS_DT_PST_DT,CLM_TRANS_DT_SRVC_FROM_DT,CLM_TRANS_DT_SRVC_THRU_DT,' \
                 'CLM_TRANS_LVL_OF_SRVC_DERIV_CD,CLM_TRANS_LVL_OF_SRVC_SRC_CD,CLM_TRANS_MBR_IN_YR_AGE,CLM_TRANS_PL_OF_SRVC_AMA_CD,' \
                 'CLM_TRANS_PROC_MOD_CD,CLM_TRANS_PROC_TYP_CD,CLM_SRC_PROV_TAX_ID_NBR,CLM_SRC_PROV_SRVC_ZIP_CD,CLM_SRC_PROV_CLM_NPI_ID,' \
                 'CLM_TRANS_RSN_TYP_CD,CLM_TRANS_CLM_PRI_DIAG_CD,CLM_TRANS_DT_ADMIT_DT,CLM_TRANS_ADMIT_TYP_CD,CLM_TRANS_ADMIT_SRC_CD,' \
                 'CLM_TRANS_DT_CLM_FST_SRVC_DT,CLM_TRANS_DT_CLM_LST_SRVC_DT,CLM_TRANS_BILL_TYP_CD,' \
                 'CLM_TRANS_DSCHRG_STS_CD,CLM_TRANS_SYS_DIAG_REL_GRP_CD,CLM_TRANS_ENT_DIAG_REL_GRP_CD,' \
                 'CLM_TRANS_CLM_LVL_RSN_CD_DESC, CLM_TRANS_EOB_RSN_CD_DESC,CLM_TRANS_AUTH_NBR,' \
                 'CLM_TRANS_SUPP_ORDR_IND,CLM_SRC_PROV_PAYE_NM,CLM_TRANS_DIAG_1_CD_DESC,' \
                 'CLM_TRANS_DIAG_2_CD_DESC,CLM_TRANS_DIAG_3_CD_DESC,CLM_TRANS_DIAG_4_CD_DESC,' \
                 'CLM_TRANS_DIAG_5_CD_DESC,CLM_TRANS_PROC_CD,CLM_TRANS_PROC_DESC,' \
                 'ICD_DIAG_TYP_CD,CLM_TRANS_RSN_DESC,CLM_TRANS_DIAG_1_DSM_TYP_CD,' \
                 'CLM_TRANS_DIAG_2_DSM_TYP_CD,CLM_TRANS_DIAG_3_DSM_TYP_CD,CLM_TRANS_DIAG_4_DSM_TYP_CD,' \
                 'CLM_TRANS_DIAG_5_DSM_TYP_CD,CLM_TRANS_CLM_LVL_RSN_CD,CLM_TRANS_PROC_MOD_2_CD,' \
                 'CLM_TRANS_PROC_MOD_3_CD,CLM_TRANS_PROC_MOD_4_CD,CLM_TRANS_RVNU_CD,' \
                 'CLM_TRANS_RVNU_DESC,CLM_TRANS_SEC_PROC_CD,CLM_TRANS_SEC_PROC_DESC,' \
                 'CLM_TRANS_SEC_PROC_TYP_CD,SRC_FINC_LIAB_CD,DERIV_OBH_FINC_LIAB,' \
                 'CLM_SRC_PROV_CLM_SRVC_NPI_ID,CLM_SRC_PROV_CLM_REF_NPI_ID,CLM_SRC_PROV_CLM_FAC_NPI_ID,' \
                 'CLM_SRC_PROV_CLM_RNDR_NPI_ID,CLM_SRC_PROV_CLM_BIL_NPI_ID,CLM_SRC_PROV_CLM_PAYE_NPI_ID,' \
                 'CLM_SRC_PROV_CLM_ADMIT_NPI_ID,CLM_SRC_PROV_CLM_ATD_NPI_ID,CLM_TRANS_RSN_CD,' \
                 'CLM_TRANS_AGRMNT_ID,CLM_TRANS_AGRMNT_DESC,CLM_TRANS_RSN_TYP_DESC,' \
                 'SRC_FINC_LIAB_DESC,CLM_TRANS_DIAG_1_CD_CATGY_LVL_2_DESC,CLM_TRANS_DIAG_2_CD_CATGY_LVL_2_DESC,' \
                 'CLM_TRANS_DIAG_3_CD_CATGY_LVL_2_DESC,CLM_TRANS_DIAG_4_CD_CATGY_LVL_2_DESC,CLM_TRANS_DIAG_5_CD_CATGY_LVL_2_DESC,' \
                 'MBR_SYS_ID,PERS_SYS_ID,PKG_SYS_ID,' \
                 'CLM_TRANS_ALLW_AMT,CLM_TRANS_ALLW_DERIV_AMT,CLM_TRANS_COB_AMT,CLM_TRANS_COINS_AMT,' \
                 'CLM_TRANS_CONTR_AMT,CLM_TRANS_COPAY_AMT,CLM_TRANS_DED_AMT,CLM_TRANS_DSALLW_AMT,' \
                 'CLM_TRANS_DSCNT_AMT,CLM_TRANS_MBR_RESP_AMT,CLM_TRANS_PD_AMT,CLM_TRANS_RSRV_AMT,' \
                 'CLM_TRANS_SBMT_AMT,CLM_TRANS_ALLWD_QTY,CLM_TRANS_BILL_QTY,CLM_TRANS_COV_VST_CNT,' \
                 'CLM_TRANS_COV_DAYS_CNT,CLM_TRANS_SRVC_UNT_CNT,CLM_TRANS_PROC_CNT,CLM_TRANS_ALLWD_ADMTS,' \
                 'SRC_CUST_CD,SRC_CUST_NM,CLM_TRANS_THER_CLASS_CD,CLM_TRANS_THER_CLASS_DESC,CLM_TRANS_PKG_CD,' \
                 'CLM_TRANS_PKG_NM,CLM_TRANS_MKT_PKG_CD,CLM_TRANS_MKT_PKG_DESC,CLM_TRANS_PLAN_CD,' \
                 'CLM_TRANS_PLAN_DESC,CLM_TRANS_PRDCT_TYP_DESC,CLM_SRC_MBR_GRP_NAME,CLM_TRANS_PL_OF_SRVC_AMA_DESC,' \
                 'CLM_SRC_PROV_PAYE_TYP,CLM_SRC_PROV_PAYE_TAX_ID,CLM_TRANS_PROC_MOD_DESC,CLM_TRANS_PROC_MOD_2_DESC,' \
                 'CLM_TRANS_PROC_MOD_3_DESC,CLM_TRANS_PROC_MOD_4_DESC,CLM_TRANS_BILL_TYP_DESC,' \
                 'CLM_TRANS_SYS_DIAG_REL_GRP_DESC,CLM_TRANS_NDC_CD,CLM_TRANS_NDC_GNRC_NM,CLM_TRANS_COS_CD,' \
                 'CLM_TRANS_COS_LVL1_DESC,CLM_TRANS_COS_LVL2_DESC,CLM_TRANS_COS_LVL3_DESC,CLM_TRANS_COS_LVL4_DESC,' \
                 'SRC_PROV_NTWK_CD,SRC_PROV_NTWK_DESC,CLM_SRVC_LN_STS_CD,CLM_SRVC_LN_STS_DESC,CLM_TRANS_PROC_CTGY_LVL_1_DESC,' \
                 'CLM_TRANS_PROC_CTGY_LVL_2_DESC,CLM_TRANS_PROC_CTGY_LVL_3_DESC,SRC_MBR_ID,MEDCD_ID,MEDCR_ID' \
                 '  FROM ' + tgt_schema_name + '.' + \
                 tgt_tb_name + ' WHERE EXTRACT(YEAR FROM CLM_TRANS_DT_SRVC_FROM_DT) = ' \
                 + str(yearNumber) + ' AND EXTRACT(MONTH FROM CLM_TRANS_DT_SRVC_FROM_DT) = ' + str(month) \
                 + ' AND EXTRACT(DAY FROM CLM_TRANS_DT_SRVC_FROM_DT) = ' + str(day) \
                 + ' ORDER BY  CLM_AUD_SRC_ID,CLM_AUD_LN_NBR,CLM_AUD_TRANS_SEQ_NBR FETCH FIRST ' + rowcomparison + ' ROWS ONLY'
            execute_compare(q1, q2, str(yearNumber), str(month), str(day))
        except Exception as e:
            print(e, e.args)
            pass
        day += 1
except Exception as e:
    print(e, e.args)
    pass
finally:
    sf_conn.close()
    sf_conn1.close()
