CREATE TASK IF NOT EXISTS COMPACT.SMART_DATA_REFRESH
  WAREHOUSE = ECT_PRD_OBH_DP_LOAD_WH
  SCHEDULE = 'USING CRON 0 2 * * 2,4 America/Chicago'
  //SCHEDULE = '{ USING CRON <expr> <time_zone> }'
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  USER_TASK_TIMEOUT_MS = 36000000
  COMMENT = 'Task to Trigger Procedure SMART_DATA_REFRESH to create clones'
AS
  CALL COMPACT.SMART_DATA_REFRESH();

  ALTER TASK COMPACT.SMART_DATA_REFRESH RESUME ;