CREATE TASK IF NOT EXISTS ETL.FND_CLM_TRANS_SRVC_LN_ALL_COS_LD
  WAREHOUSE = ECT_PRD_OBH_DP_LOAD_WH
  SCHEDULE = 'USING CRON 0 2 * * 1,2,3,4,5, America/Chicago'
  //SCHEDULE = '{ USING CRON <expr> <time_zone> }'
  ALLOW_OVERLAPPING_EXECUTION = FALSE
  USER_TASK_TIMEOUT_MS = 36000000
  COMMENT = 'Task to Trigger Foundation CLM_TRANS_SRVC_LN_ALL table load for COSMOS from EDW'
AS
  CALL LOAD_EDW_OBHDP_CLAIMS_COS();



ALTER TASK ETL.FND_CLM_TRANS_SRVC_LN_ALL_COS_LD RESUME ;
