CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_PROVIDER_QUALIFIER_L (
    PROV_QUALIFIER_DIM_ID VARCHAR(50),
    PROV_ID_QUALIFIER VARCHAR(3),
    PROV_ID_QUALIFIER_DESC VARCHAR(50),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_PROV_QUALIFIER_DIM_ID PRIMARY KEY (PROV_QUALIFIER_DIM_ID)
);
