CREATE TABLE IF NOT EXISTS ETL.UNET_GALAXY_MHSA_CODE_L
    (
        MHSA_CD VARCHAR(1) NOT NULL,
        MHSA_DESC VARCHAR(25) NOT NULL,
        UPDT_USER_ID VARCHAR(8) NOT NULL,
        LOAD_DT DATE NOT NULL,
        UPDT_DT DATE NOT NULL,
        CONSTRAINT PK_MHSA_CD PRIMARY KEY (MHSA_CD) not enforced
    );

