CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_SOURCE_PRODUCT_L (
	SOURCE_PRODUCT_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_SOURCE_PRODUCT_DIM_ID PRIMARY KEY,
	SOURCE_PRODUCT_CODE VARCHAR(20) NOT NULL,
	SOURCE_PRODUCT_DESC VARCHAR(70) NOT NULL,
	CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
	DW_INSERT_DATETIME VARCHAR(35) NOT NULL,
	DW_UPDATE_DATETIME VARCHAR(35) NOT NULL,
    CONSTRAINT UK_DIM_SOURCE_PRODUCT_CODE_CONVERTED_FROM UNIQUE (SOURCE_PRODUCT_CODE,CONVERTED_FROM_DIM_ID)
);
