CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_DATE_QUARTER_L (
    QUARTER_DIM_ID VARCHAR(50) NOT NULL,
	QUARTER_DESC VARCHAR(8),
	CAL_YEAR_QUARTER VARCHAR(50),
	YEAR_DIM_ID VARCHAR(50),
	YEAR_NBR VARCHAR(50),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	QUARTER_BEGIN_DATE VARCHAR(35),
	QUARTER_END_DATE VARCHAR(35),
	YEAR_BEGIN_DATE VARCHAR(35),
	YEAR_END_DATE VARCHAR(35),
	CURR_QUARTER_IND VARCHAR(50),
	CONSTRAINT PK_SMART_DIM_DATE_QUARTER_ETL PRIMARY KEY (QUARTER_DIM_ID)
);
