CREATE TABLE IF NOT EXISTS ETL.UNET_GALAXY_CLAIM_ORIGINATION_CODE_L
	     (
	        CLM_ORIG_CD VARCHAR(2) NOT NULL,
	        CLM_ORIG_DESC VARCHAR(50) NOT NULL,
	        UPDT_USER_ID VARCHAR(8) NOT NULL,
	        LOAD_DT DATE NOT NULL,
	        UPDT_DT DATE NOT NULL,
	        CONSTRAINT PK_CLM_ORIG_CD PRIMARY KEY (CLM_ORIG_CD) not enforced
	    );