CREATE TABLE IF NOT EXISTS ETL.EDW_TB_DIM_ORG_SALE_CHNL_L (
    SALE_CHNL_SYS_ID VARCHAR(4),
    SALE_CHNL_NM VARCHAR(64),
    REC_CRT_DTTM VARCHAR(26),
    REC_UPDT_DTTM VARCHAR(26),
    CONSTRAINT PK_EDW_TB_DIM_ORG_SALE_CHNL_ETL PRIMARY KEY (SALE_CHNL_SYS_ID)
);
