CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_THERAPEUTIC_GROUP_L (
    RX_THERAPEUTIC_GROUP_DIM_ID VARCHAR(50),
    RX_THERAPEUTIC_GROUP_IND VARCHAR(3),
    RX_THERAPEUTIC_GROUP_IND_DESC VARCHAR(30),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_RX_THERAPEUTIC_GROUP_DIM_ID PRIMARY KEY (RX_THERAPEUTIC_GROUP_DIM_ID)
);
