CREATE TABLE IF NOT EXISTS ETL.EDW_TB_PRV_PROVIDER_ALT_L(
	PROV_ALT_SYS_ID VARCHAR(10) NOT NULL,
	PROV_SYS_ID VARCHAR(10) NOT NULL,
	SRC_PROV_TAX_ID varchar(9) NULL,
	SRC_REC_CRT_DTTM VARCHAR(26) NULL,
	SRC_REC_CRT_USER_ID VARCHAR(15) NULL,
	SRC_REC_UPDT_DTTM VARCHAR(26) NULL,
	SRC_REC_UPDT_USER_ID VARCHAR(15) NULL,
	REC_CRT_DTTM VARCHAR(26) NOT NULL,
	REC_UPDT_DTTM VARCHAR(26) NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
	BTCH_LOAD_DT VARCHAR(26) NOT NULL,
	PROV_ALT_ID varchar(100) NULL,
	CONSTRAINT EDW_TB_PRV_PROVIDER_ALT_SYS PRIMARY KEY(PROV_ALT_SYS_ID)
);