CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CLAIM_TYPE_L (
CLAIM_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_CLAIM_TYPE_DIM_ID PRIMARY KEY,
CLAIM_TYPE VARCHAR(8) NOT NULL CONSTRAINT UK_DIM_CLAIM_TYPE_CLAIM_TYPE UNIQUE,
CLAIM_TYPE_DESC VARCHAR(30),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);
