CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RATE_TYPE_L (
	RATE_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_RATE_TYPE_DIM_ID PRIMARY KEY,
	RATE_TYPE_CODE VARCHAR(4) NOT NULL,
	RATE_TYPE_DESC VARCHAR(255) NOT NULL,
	CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	CONSTRAINT UK_DIM_RATE_TYPE_CODE_CONVERTED UNIQUE (RATE_TYPE_CODE,CONVERTED_FROM_DIM_ID)
);
