CREATE TABLE IF NOT EXISTS ETL.EDW_TB_PRV_PRAC_ALT_L(
	PRAC_ALT_SYS_ID VARCHAR(10) NOT NULL,
	PRAC_SYS_ID VARCHAR(10) NOT NULL,
	PRAC_ALT_ID varchar(20) NULL,
	SRC_REC_CRT_DTTM VARCHAR(26) NULL,
	SRC_REC_CRT_USER_ID VARCHAR(15) NULL,
	SRC_REC_UPDT_DTTM VARCHAR(26) NULL,
	SRC_REC_UPDT_USER_ID VARCHAR(15) NULL,
	REC_CRT_DTTM VARCHAR(26) NOT NULL,
	REC_UPDT_DTTM VARCHAR(26) NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
	BTCH_LOAD_DT VARCHAR(26) NOT NULL,
	CONSTRAINT PK_TB_PRV_PRAC_ALT_SYS PRIMARY KEY(PRAC_ALT_SYS_ID)
);