CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROV_CRED_TYPE_L (
PROV_CRED_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROV_CRED_TYPE_DIM_ID PRIMARY KEY,
PROV_CRED_TYPE VARCHAR(10) NOT NULL,
PROV_CRED_TYPE_DESC VARCHAR(100) NOT NULL,
CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
CONSTRAINT UK_DIM_PROV_CRED_TYPE_CONV_FROM UNIQUE (PROV_CRED_TYPE,CONVERTED_FROM_DIM_ID)
);
