CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_FEE_SCHEDULE_L (
	FEE_SCHEDULE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_FEE_SCHEDULE_DIM_ID_ PRIMARY KEY,
	FEE_SCHEDULE_CODE VARCHAR(70) NOT NULL CONSTRAINT UK_DIM_FEE_SCHEDULE_FEE_SCHEDULE_CODE UNIQUE,
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);
