CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CPT_CAT_LVL_3_L (
	CPT_CAT_LVL_3_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_CPT_CAT_LVL_3_DIM_ID PRIMARY KEY,
	CPT_CAT_LVL_3_DESC VARCHAR(500),
	CPT_CAT_LVL_2_DIM_ID VARCHAR(50),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	CPT_CAT_LVL_3_SHORT_DESC VARCHAR(25)
);
