CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_COST_DETERMIN_BASIC_L (
    COST_DETERMIN_BASIC_DIM_ID VARCHAR(50),
    COST_DETERMIN_BASIC	VARCHAR(3),
    COST_DETERMIN_BASIC_DESC VARCHAR(60),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_COST_DETERMIN_BASIC_DIM_ID PRIMARY KEY (COST_DETERMIN_BASIC_DIM_ID)
);
