CREATE TABLE IF NOT EXISTS ETL.SMART_PATIENT_INDEX_L (
    INDEX_VALUE VARCHAR(200) NOT NULL,
	INDEX_ID VARCHAR(50) NOT NULL,
	PATIENT_ID VARCHAR(50) NOT NULL,
	DISPLAY_VALUE VARCHAR(200) NOT NULL,
	CREATED_ON VARCHAR(35) NOT NULL,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	UPDATED_ON VARCHAR(35),
	DELETED_BY VARCHAR(50),
	DELETED_ON VARCHAR(35),
	PATIENT_INDEX_IDNTY VARCHAR(50) NOT NULL CONSTRAINT PK_PATIENT_INDX_ID PRIMARY KEY,
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
	);