CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PLAN_PROGRAM_TYPE_L (
PLAN_PROGRAM_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PLAN_PROGRAM_TYPE_DIM_ID PRIMARY KEY,
PROGRAM_TYPE_CODE VARCHAR(6) NOT NULL,
PROGRAM_TYPE_DESC VARCHAR(30),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
MEDICARE_DUAL_FLAG_DIM_ID VARCHAR(50),
CONSTRAINT UK_DIM_PLAN_PROGRAM_TYPE_CODE UNIQUE (PROGRAM_TYPE_CODE)
);

