CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_DRG_CODE_L (
DRG_CODE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_DRG_CODE_DIM_ID PRIMARY KEY,
DRG_CODE VARCHAR(6) NOT NULL,
DRG_CODE_SHORT_DESC VARCHAR(30),
DRG_CODE_MDC_CODE VARCHAR(2),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
DRG_CODE_CLASS VARCHAR(4),
DRG_CODE_TYPE VARCHAR(10),
DRG_CODE_LONG_DESC VARCHAR(300),
CONSTRAINT UK_DIM_DRG_CODE_DRG_CODE_CODE_TYPE UNIQUE(DRG_CODE,DRG_CODE_TYPE)
);
