CREATE TABLE IF NOT EXISTS ETL.SMART_PROGRAM_STATUS_L (
	PROGRAM_STATUS_ID VARCHAR(50) NOT NULL CONSTRAINT PK_PROGRAM_STATUS_ID PRIMARY KEY,
	PROGRAM_STATUS_NAME VARCHAR(1000) NOT NULL,
	IS_ACTIVE VARCHAR(50),
	CREATED_BY VARCHAR(50),
	CREATED_ON VARCHAR(35),
	UPDATED_BY VARCHAR(50),
	UPDATED_ON VARCHAR(35),
	DELETED_BY VARCHAR(50),
	DELETED_ON VARCHAR(35),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);