CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_UNCLEAN_FLAG_L
    (
        UNCLEAN_FLAG_DIM_ID VARCHAR(50) NOT NULL,
        UNCLEAN_FLAG_DESC VARCHAR(30),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_DIM_UNCLN_FLG PRIMARY KEY (UNCLEAN_FLAG_DIM_ID)
    );
