CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_BILLING_ACCT_L (
    RX_BILLING_ACCT_DIM_ID VARCHAR(50),
    LINE_OF_BUSINESS_DIM_ID	VARCHAR(22),
    ACCOUNT_NO VARCHAR(10),
    COMPANY_DIM_ID VARCHAR(22),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_RX_BILLING_ACCT_DIM_ID PRIMARY KEY (RX_BILLING_ACCT_DIM_ID)
);
