-- ECT_DEV_OBH_DP_DB.ETL.DBA_MERGE_META definition

CREATE OR REPLACE TABLE ETL.DBA_MERGE_META (
	SOURCE_SCHEMA_TABLE_NAME VARCHAR(128) NOT NULL,
	TARGET_SCHEMA_TABLE_NAME VARCHAR(128),
	STM_HIST_MERGE VARCHAR(100000),
	SF_LAST_UPDATED TIMESTAMP_NTZ(9),
	CONSTRAINT UK_ETL_DBA_MERGE_META_TARGET UNIQUE (TARGET_SCHEMA_TABLE_NAME),
	CONSTRAINT PK_ETL_DBA_MERGE_META_SOURCE PRIMARY KEY (SOURCE_SCHEMA_TABLE_NAME)
);
