CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_GROUP_L (
	GROUP_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_GROUP_DIM_ID PRIMARY KEY,
	GROUP_ID VARCHAR(10) NOT NULL CONSTRAINT UK_DIM_GROUP_DIM_GROUP_ID UNIQUE,
	GROUP_SHORT_NAME VARCHAR(80),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	SEQ_GROUP_ID VARCHAR(50),
	COMPANY_DIM_ID VARCHAR(50),
	CONSTRAINT UK_DIM_GROUP_SEQ_GROUP_ID_COMPANY_DIM_ID UNIQUE (SEQ_GROUP_ID,COMPANY_DIM_ID)
);
