CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_DIAG_CAT_LVL_1_L (
	DIAG_CAT_LVL_1_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_DIAG_CAT_LVL_1 PRIMARY KEY,
	DIAG_CAT_LVL_1_DESC VARCHAR(100),
	DIAG_CAT_LVL_1_SHORT_DESC VARCHAR(25),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);
