CREATE TABLE IF NOT EXISTS ETL.EDW_AUTH_EXTRACT_L (
    MBR_SYS_ID VARCHAR(4),
    PERS_SYS_ID VARCHAR(4),
    AUTH_EFF_DT VARCHAR(91),
    AUTH_CRT_DT VARCHAR(91),
    AUTH_PRSD_EFF_DT VARCHAR(91),
    ELIG_ST_ABBR_CD VARCHAR(2),
    ACSS_DESC VARCHAR(12),
    CHRT_TYP_DESC VARCHAR(12)
);
