CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_FORMULARY_IND_L
    (
        RX_FORMULARY_IND_DIM_ID VARCHAR(50) NOT NULL,
        RX_FORMULARY_IND VARCHAR(1) NOT NULL,
        RX_FORMULARY_IND_DESC VARCHAR(25),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_DIM_RX_FRMLRY_IND PRIMARY KEY (RX_FORMULARY_IND_DIM_ID)
    );
