CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PLAN_LOB_L (
	PLAN_LOB_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PLAN_LOB_DIM_ID PRIMARY KEY,
	LINE_OF_BUSINESS_DIM_ID VARCHAR(50) NOT NULL,
	PLAN_DIM_ID VARCHAR(50) NOT NULL,
	PLAN_PROGRAM_DIM_ID VARCHAR(50) NOT NULL,
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	PPC_FLAG VARCHAR(1),
	SOURCE_PRODUCT_DIM_ID VARCHAR(50) NOT NULL,
	CLASS_DIM_ID VARCHAR(50) NOT NULL,
	CLASS_PLAN_DIM_ID VARCHAR(50) NOT NULL,
	CONSTRAINT UK_DIM_PLAN_LOB_PLAN_BUSINESS_CLASS_PROD UNIQUE (PLAN_DIM_ID,LINE_OF_BUSINESS_DIM_ID,CLASS_PLAN_DIM_ID,CLASS_DIM_ID,SOURCE_PRODUCT_DIM_ID)
);
