CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_MEDICARE_TYPE_L (
	MEDICARE_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_MEDICARE_TYPE_DIM_ID PRIMARY KEY,
	MEDICARE_TYPE VARCHAR(3) NOT NULL,
	MEDICARE_IND VARCHAR(1),
	MEDICARE_TYPE_DESC VARCHAR(100),
	MEDICARE_GROUP_DIM_ID VARCHAR(50) NOT NULL,
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	GROUP_DIM_ID VARCHAR(50) NOT NULL,
	CONSTRAINT UK_DIM_MEDICARE_TYPE_MEDICARE_TYPE_GROUP_DIM_ID UNIQUE (MEDICARE_TYPE,GROUP_DIM_ID)
);
