CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_OTHER_COVERAGE_CODE_L (
    OTHER_COVERAGE_CODE_DIM_ID VARCHAR(50),
    OTHER_COVERAGE_CODE VARCHAR(3),
    OTHER_COVERAGE_CODE_DESC VARCHAR(60),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_OTHER_COVERAGE_CODE_DIM_ID PRIMARY KEY (OTHER_COVERAGE_CODE_DIM_ID)
);
