CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_TYPE_L (
PROV_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROVIDER_TYPE_DIM_ID PRIMARY KEY,
TYPE_OR_SPEC_CODE VARCHAR(10) NOT NULL,
TYPE_OR_SPECIALTY VARCHAR(1),
PROV_TYPE_SHORT_DESC VARCHAR(15),
PROV_TYPE_DESC VARCHAR(60),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
TYPE_OF_SERVICE VARCHAR(3),
PROV_SPEC_CAT_CODE VARCHAR(50),
CONSTRAINT UK_DIM_PROVIDER_TYPE_TYPE_OR_SPEC_CODE_SPECIALTY UNIQUE (TYPE_OR_SPEC_CODE,TYPE_OR_SPECIALTY)
);
