CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_COS_STL_1_L (
COS_STL_1_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_COS_STL_1_DIM_ID PRIMARY KEY,
COS_STL_1_DESC  VARCHAR(20),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);

