CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_CONTRACT_TYPE_L (
CONTRACT_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROVIDER_CONTRACT_TYPE_DIM_ID PRIMARY KEY,
CONTRACT_TYPE VARCHAR(1) NOT NULL,
CONTRACT_TYPE_DESC VARCHAR(20),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);

