CREATE TABLE IF NOT EXISTS ETL.EPIM_PROVIDER_TELECOM_L
(
EPIM_IDENTIFIER	VARCHAR(255),
HCP_HCO_INDICATOR	VARCHAR(255),
NPI	VARCHAR(255),
ASSOCIATION_RESOURCE_CPDE	VARCHAR(255),
TELECOM_VALUE	VARCHAR(255),
TELECOM_USE_CODE	VARCHAR(255),
TELECOM_SYSTEM_CODE	VARCHAR(255),
TELECOM_USETYPE_CODE	VARCHAR(255),
TELECOM_USETYPE_TEXT	VARCHAR(255),
PERIOD_START	VARCHAR(255),
EPIM_LAST_UPDATED_DTTM	VARCHAR(255),
AUDIT_CREATE_DATE	VARCHAR(255)
);
