CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_ADMIT_SOURCE_L (
	ADMIT_SOURCE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_ADMIT_SOURCE_DIM_ID PRIMARY KEY,
	ADMIT_SOURCE_CODE VARCHAR(6) NOT NULL,
	ADMIT_SOURCE_DESC VARCHAR(30),
	ADMIT_CLASS VARCHAR(1),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	CONSTRAINT UK_DIM_ADMIT_SOURCE_SOURCE_CODE_ADMIT_CLASS UNIQUE (ADMIT_SOURCE_CODE,ADMIT_CLASS)
);
