CREATE TABLE IF NOT EXISTS ETL.EPIM_ORGANIZATION_CONTACT_L
(
EPIM_IDENTIFIER	VARCHAR(255),
HCP_HCO_INDICATOR	VARCHAR(255),
NPI	VARCHAR(255),
CONTACT_PURPOSE_CODE	VARCHAR(255),
CONTACT_PURPOSE_SYSTEM	VARCHAR(255),
CONTACT_PURPOSE_CODE_DISPLAY	VARCHAR(255),
CONTACT_PURPOSE_CODE_TEXT	VARCHAR(255),
CONTACT_NAME_USE_CODE	VARCHAR(255),
CONTACT_FAMILY_NAME	VARCHAR(255),
CONTACT_GIVEN_NAME	VARCHAR(255),
CONTACT_NAME_PREFIX	VARCHAR(255),
CONTACT_NAME_SUFFIX	VARCHAR(255),
EPIM_LAST_UPDATED_DTTM	VARCHAR(255),
AUDIT_CREATE_DATE	VARCHAR(255)
);
