CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_GENERIC_BRAND_IND_L
    (
        RX_GENERIC_BRAND_IND_DIM_ID VARCHAR(50) NOT NULL,
        RX_GENERIC_BRAND_IND VARCHAR(1) NOT NULL,
        RX_GENERIC_BRAND_IND_DESC VARCHAR(100),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_DIM_RX_GRC_BRD_IND PRIMARY KEY (RX_GENERIC_BRAND_IND_DIM_ID)
    );
