CREATE TABLE IF NOT EXISTS ETL.EDW_TB_CUST_ACCT_ORG_SALE_CHNL_XREF_L (
	SALE_CHNL_SYS_ID VARCHAR(10) NOT NULL,
	ACCT_SYS_ID VARCHAR(10) NOT NULL,
	REC_ACTV_FLG VARCHAR(1) NOT NULL,
	REC_CRT_DTTM VARCHAR(26)NOT NULL,
	REC_UPDT_DTTM VARCHAR(26)NOT NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
	CONSTRAINT PK_TB_CUST_ACCT_ORG_SALE_CHNL_XREF PRIMARY KEY (SALE_CHNL_SYS_ID,ACCT_SYS_ID)
);
