CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_BILL_TYPE_L (
BILL_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_BILL_TYPE_DIM_ID PRIMARY KEY,
BILL_TYPE VARCHAR(3) NOT NULL CONSTRAINT UK_DIM_BILL_TYPE_BILL_TYPE UNIQUE,
BILL_TYPE_DESC VARCHAR(60),
INP_OUTP_IND VARCHAR(1),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
BILL_TYPE_CAT_LVL_2_DIM_ID VARCHAR(50) NOT NULL,
BILL_TYPE_CAT_LVL_1_DIM_ID VARCHAR(50) NOT NULL,
PLACE_OF_SVC_DIM_ID VARCHAR(50) NOT NULL
);

