CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RATECELL_RATE_L 
(
        RTCL_RATE_DIM_ID VARCHAR(50) NOT NULL,
        RTCL_DIM_ID VARCHAR(50) NOT NULL,
        RTCL_MONTH VARCHAR(35) NOT NULL,
        RATE VARCHAR(50) NOT NULL,
        DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
        RTCL_GME VARCHAR(50),
        RTCL_PAE VARCHAR(50),
        RTCL_RISK_ADJ_RATE_SCORE VARCHAR(50),
        MONTH_DIM_ID VARCHAR(50) NOT NULL,
        RTCL_CODE_DESC VARCHAR(200),
        CONSTRAINT PK_RTCL_RT_DIM_ID PRIMARY KEY (RTCL_RATE_DIM_ID),
        CONSTRAINT UK_DIM_RTCL_RT_DIM_MNTH UNIQUE (RTCL_DIM_ID, RTCL_MONTH)
    );
