CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_NETWORK_L (
NETWORK_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_NETWORK_DIM_ID PRIMARY KEY,
NETWORK_ID  VARCHAR(15),
NETWORK_DESC  VARCHAR(20),
COMPANY_DIM_ID VARCHAR(50) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);
