CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RATECELL_REGION_L
(
        RTCL_REGION_DIM_ID VARCHAR(50) NOT NULL,
        COMPANY_DIM_ID VARCHAR(50) NOT NULL,
        RTCL_STATE VARCHAR(2) NOT NULL,
        RTCL_REGION_CODE VARCHAR(20),
        RTCL_REGION_NAME VARCHAR(30),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_RTCL_RG_DIM_ID PRIMARY KEY (RTCL_REGION_DIM_ID)
    );
