CREATE TABLE IF NOT EXISTS ETL.EDW_TB_MEM_MBR_ALT_L (
MBR_ALT_SYS_ID VARCHAR(10) NOT NULL,
MBR_SYS_ID VARCHAR(10) NULL,
MBR_ALT_ID VARCHAR(50) NULL,
MBR_ALT_ID_SRC_FLG VARCHAR(1) NOT NULL,
SRC_REC_CRT_DTTM VARCHAR(26) NULL,
SRC_REC_CRT_USER_ID VARCHAR(15) NULL,
SRC_REC_UPDT_DTTM VARCHAR(26) NULL,
SRC_REC_UPDT_USER_ID VARCHAR(15) NULL,
REC_CRT_DTTM VARCHAR(26) NOT NULL,
REC_UPDT_DTTM VARCHAR(26) NOT NULL,
REC_XTRCT_SRC_CD VARCHAR(4) NOT NULL,
REC_INPUT_SRC_CD VARCHAR(4) NOT NULL,
BTCH_LOAD_DT VARCHAR(26) NOT NULL,
CONSTRAINT TB_MEM_MBR_ALT_SYS PRIMARY KEY (MBR_ALT_SYS_ID)
);