CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_EOB_IND_L (
	EOB_IND_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_EOB_IND_DIM_ID PRIMARY KEY,
	EOB_IND_DESC VARCHAR(20),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);
