CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_PLAN_DRUG_STATUS_L (
    PLAN_DRUG_STATUS_DIM_ID VARCHAR(50),
    PLAN_DRUG_STATUS VARCHAR(3),
    PLAN_DRUG_STATUS_DESC VARCHAR(50),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_PLAN_DRUG_STATUS_DIM_ID PRIMARY KEY (PLAN_DRUG_STATUS_DIM_ID)
);
