CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PLAN_L (
PLAN_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PLAN_DIM_ID PRIMARY KEY,
PLAN_CODE VARCHAR(20) NOT NULL,
PLAN_DESC VARCHAR(240) NOT NULL,
PLAN_STANDARD_FLAG VARCHAR(1) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
ETL_COMPANY_DIM_ID VARCHAR(50) NOT NULL,
PLAN_GEOGRAPHY_COUNTY_DIM_ID VARCHAR(50),
COUNTY VARCHAR(5),
COUNTY_DESC VARCHAR(25),
STATE VARCHAR(6),
STATE_DESC VARCHAR(20),
HCFA_COUNTY VARCHAR(4),
HCFA_COUNTY_DESC VARCHAR(30),
STATE_PROGRAM_CODE_1_DIM_ID VARCHAR(50) NOT NULL,
STATE_PROGRAM_CODE_2_DIM_ID VARCHAR(50) NOT NULL,
CONSTRAINT UK_DIM_PLAN_PLAN_CODE_ETL_COMPANY UNIQUE (PLAN_CODE,ETL_COMPANY_DIM_ID)
);
