CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CLASS_L (
CLASS_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_CLASS_DIM_ID PRIMARY KEY,
CLASS_ID VARCHAR(10) NOT NULL,
CLASS_DESC VARCHAR(200) NOT NULL,
GROUP_CODE VARCHAR(8) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
CONSTRAINT UK_DIM_CLASS_ID_CLASS_ID_GROUP_CODE UNIQUE (CLASS_ID, GROUP_CODE)
);
