-- ECT_DEV_OBH_DP_DB.ETL.DBA_PROCESS_LOG definition
CREATE OR REPLACE TABLE ETL.DBA_PROCESS_LOG (
	DBA_LOAD_LOG_ID VARCHAR(36) NOT NULL,
	TABLE_SOURCE VARCHAR(128),
	TABLE_TARGET VARCHAR(128),
	PROCESS_DESCRIPTION VARCHAR(50),
	ROWCOUNT_SOURCE NUMBER(38,0),
	ROWCOUNT_TARGET NUMBER(38,0),
	LOAD_START TIMESTAMP_NTZ(9),
	LOAD_END TIMESTAMP_NTZ(9),
	SF_INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	INSERTED_COUNT INTEGER NULL,
	UPDATED_COUNT INTEGER NULL,
	DELETED_COUNT INTEGER NULL DEFAULT 0
);
