CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_COMPOUND_CODE_L (
    COMPOUND_CODE_DIM_ID VARCHAR(50),
    COMPOUND_CODE VARCHAR(3),
    COMPOUND_CODE_DESC VARCHAR(50),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_COMPOUND_CODE_DIM_ID PRIMARY KEY (COMPOUND_CODE_DIM_ID)
);
