CREATE TABLE IF NOT EXISTS ETL.EDW_STAR_EXCLUSION_RULE_FAILURES_L (
	CLINICAL_REVIEW_ID NUMBER(11) NOT NULL,
	REASON_CODE varchar(3) NOT NULL,
	CREATE_DATE_TIME DATETIME NOT NULL,
	UPDATE_DATE_TIME DATETIME NOT NULL,
	CONSTRAINT PK_STAR_EXCLUSION_RULE_FAILURES PRIMARY KEY (CLINICAL_REVIEW_ID,REASON_CODE)
);
