CREATE TABLE IF NOT EXISTS ETL.EPIM_PROVIDER_NAME_L
(
EPIM_IDENTIFIER VARCHAR(255),
HCP_HCO_INDICATOR VARCHAR(255),
RESOURCE_TYPE VARCHAR(255),
NPI VARCHAR(255),
PROVIDER_ACTIVE_INDICATOR VARCHAR(255),
NAME_USE_CODE VARCHAR(255),
FAMILY_NAME VARCHAR(255),
GIVEN_NAME VARCHAR(255),
NAME VARCHAR(255),
GENDER VARCHAR(255),
BIRTH_DATE VARCHAR(255),
DECEASED VARCHAR(255),
SOURCE_SYSTEM_CODE VARCHAR(255),
EPIM_LAST_UPDATED_DTTM VARCHAR(255),
AUDIT_CREATE_DATE VARCHAR(255)
);
