CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_COS_STL_4_L (
COS_STL_4_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_COS_STL_4_DIM_ID PRIMARY KEY,
COS_STL_4_DESC VARCHAR(40),
COS_STL_3_DIM_ID VARCHAR(50) NOT NULL,
COS_STL_3_DESC VARCHAR(20),
COS_STL_2_DIM_ID VARCHAR(50) NOT NULL,
COS_STL_2_DESC VARCHAR(20),
COS_STL_1_DIM_ID VARCHAR(50) NOT NULL,
COS_STL_1_DESC VARCHAR(20),
COS_CODE VARCHAR(4) NOT NULL CONSTRAINT UK_DIM_COS_STL_4_COS_CODE UNIQUE,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
COS_PRIORITY VARCHAR(11),
UNIT_TYPE VARCHAR(1)
);
