CREATE TABLE IF NOT EXISTS ETL.EDW_TB_DIM_MBR_UNMASK_UHC_L (
    MBR_SYS_ID VARCHAR(10),
    ELIG_ADR_LN_1_TXT VARCHAR(50),
    ELIG_ADR_LN_2_TXT VARCHAR(40),
    MAIL_ADR_LN_1_TXT VARCHAR(50),
    MAIL_ADR_LN_2_TXT VARCHAR(40),
    MBR_NM_FST_TXT VARCHAR(35),
    MBR_NM_LST_TXT VARCHAR(35),
    SBSCR_NM_FST_TXT VARCHAR(35),
    SBSCR_NM_LST_TXT VARCHAR(35)
);
