CREATE TABLE IF NOT EXISTS ETL.DBA_VALIDATION_COUNTS(
SRC_SYSTEM VARCHAR(60) NOT NULL,
SRC_SCHEMA VARCHAR(20) NOT NULL,
SRC_TABLE  VARCHAR(60) NOT NULL,
SRC_COUNT  NUMBER NOT NULL,
DBA_LOAD_LOG_ID VARCHAR(36) NULL,
EXTRACT_DT DATETIME DEFAULT CURRENT_TIMESTAMP()
);
