CREATE TABLE IF NOT EXISTS ETL.EPIM_PROVIDER_ADDRESSES_L
(
EPIM_IDENTIFIER VARCHAR(255),
HCP_HCO_INDICATOR VARCHAR(255),
NPI VARCHAR(255),
ASSOCIATION_RESOURCE_CODE VARCHAR(255),
SOURCE_SYSTEM_CODE VARCHAR(255),
ADDRESS_IDENTIFIER VARCHAR(255),
ADDRESSTYPE_CODE VARCHAR(255),
ADDRESS_USE_CODE VARCHAR(255),
ADDRESS_USETYPE_CODE VARCHAR(255),
ADDRESS_USETYPE_CODE_TEXT VARCHAR(255),
LINE_TEXT VARCHAR(255),
RANK VARCHAR(255),
CITY_NAME VARCHAR(255),
DISTRICT_NAME VARCHAR(255),
STATE_CODE VARCHAR(255),
POSTAL_CODE VARCHAR(255),
LATITUDE VARCHAR(255),
LONGITUDE VARCHAR(255),
EPIM_LAST_UPDATED_DTTM VARCHAR(255),
AUDIT_CREATE_DATE VARCHAR(255)
);
