CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_APPROVED_COST_SOURCE_L (
    APPROVED_COST_SOURCE_DIM_ID	VARCHAR(50),
    APPROVED_COST_SOURCE VARCHAR(15),
    APPROVED_COST_SOURCE_DESC VARCHAR(50),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_APPROVED_COST_SOURCE_DIM_ID PRIMARY KEY (APPROVED_COST_SOURCE_DIM_ID)
);
