CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_PAR_STAT_L (
PROVIDER_PAR_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROVIDER_PAR_STAT_DIM_ID PRIMARY KEY,
PROVIDER_PAR_STAT VARCHAR(1) NOT NULL,
PROVIDER_DESC VARCHAR(20),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);
