CREATE TABLE  IF NOT EXISTS ETL.EDW_TB_FCT_MBR_ELIG_L (
    SALE_CHNL_SYS_ID VARCHAR(10),
    GRP_SYS_ID VARCHAR(10),
    PKG_SYS_ID VARCHAR(10),
    MBR_SYS_ID VARCHAR(10),
    PERS_SYS_ID VARCHAR(10),
    CARE_MGT_MKT_SYS_ID VARCHAR(10),
    ZIP_CD_SYS_ID VARCHAR(10),
    MBR_ELIG_SYS_ID VARCHAR(10),
    CAL_DT_SYS_ID VARCHAR(10),
    RPT_CUST_SYS_ID VARCHAR(10),
    MBR_ELIG_OCCUR_CNT VARCHAR(10),
    REC_CRT_DTTM VARCHAR(26),
    REC_UPDT_DTTM VARCHAR(26),
    CONSTRAINT PK_EDW_TB_FCT_MBR_ELIG_ETL PRIMARY KEY (ZIP_CD_SYS_ID, SALE_CHNL_SYS_ID, GRP_SYS_ID, PKG_SYS_ID,
    MBR_SYS_ID, PERS_SYS_ID, CARE_MGT_MKT_SYS_ID, MBR_ELIG_SYS_ID, CAL_DT_SYS_ID)
);
