CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_LANGUAGE_L (
LANGUAGE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_LANGUAGE_DIM_ID PRIMARY KEY,
LANGUAGE_CODE VARCHAR(5) NOT NULL,
LANGUAGE_DESC VARCHAR(30),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
CONSTRAINT UK_DIM_LANGUAGE_LANGUAGE_CODE_CONV_FROM UNIQUE (LANGUAGE_CODE,CONVERTED_FROM_DIM_ID)
);
