CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CARE_LEVEL_L (
CARE_LEVEL_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_CARE_LELVEL_DIM_ID PRIMARY KEY,
CARE_LEVEL_CODE  VARCHAR(17) NOT NULL,
CARE_LEVEL_DESC  VARCHAR(32) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);

