CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_OTC_CODE_L (
    RX_OTC_CODE_DIM_ID VARCHAR(50),
    RX_OTC_CODE VARCHAR(3),
    RX_OTC_CODE_DESC VARCHAR(30),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_RX_OTC_CODE_DIM_ID PRIMARY KEY (RX_OTC_CODE_DIM_ID)
);
