CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_LINE_OF_BUSINESS_TYPE_L (
	LINE_OF_BUSINESS_TYPE_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_LINE_OF_BUSINESS_TYPE_DIM_ID PRIMARY KEY,
	LINE_OF_BUSINESS_TYPE_DESC VARCHAR(8),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);
