CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_COSMOS_CUST_SEG_L (
	COSMOS_CUST_SEG_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_COSMOS_CUST_SEG_DIM_ID PRIMARY KEY,
	COSMOS_CUST_SEG VARCHAR(9) NOT NULL CONSTRAINT UK_DIM_COSMOS_CUST_SEG_COSMOS_CUST_SEG UNIQUE,
	COSMOS_CUST_SEG_DESC VARCHAR(120),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	COMPANY_DIM_ID VARCHAR(50) NOT NULL,
	LEGAL_ENTITY VARCHAR(10),
	FIN_PRODUCT VARCHAR(10)
);
