CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PLAN_PROGRAM_L (
    PLAN_PROGRAM_DIM_ID VARCHAR(22),
    PROGRAM_CODE VARCHAR(16),
    PROGRAM_DESC VARCHAR(30),
    COMPANY_DIM_ID VARCHAR(22),
    DW_INSERT_DATETIME VARCHAR(26),
    DW_UPDATE_DATETIME VARCHAR(26),
    PLAN_PROGRAM_TYPE_DIM_ID VARCHAR(22),
    PROGRAM_TYPE_CODE VARCHAR(6),
    PROGRAM_TYPE_DESC VARCHAR(30),
    CONSTRAINT PK_SMART_DIM_PLAN_PROGRAM_ETL PRIMARY KEY (PLAN_PROGRAM_DIM_ID),
    CONSTRAINT UK_DIM_PLAN_PROGRAM_CODE_COMPANY UNIQUE (PROGRAM_CODE,COMPANY_DIM_ID)
);
