CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_FLAG_INDICATOR_L (
    FLAG_DIM_ID	VARCHAR(50),
    FLAG_IND VARCHAR(3),
    FLAG_IND_DESCRIPTION VARCHAR(30),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    FLAG_TYPE VARCHAR(50),
    CONSTRAINT PK_FLAG_DIM_ID PRIMARY KEY (FLAG_DIM_ID)
);
