CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CONVERTED_FROM_L
    (
        CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
        CONVERTED_FROM VARCHAR(8) NOT NULL,
        CONVERTED_FROM_DESC VARCHAR(60),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONVERTED_FROM_TYPE VARCHAR(1),
        CONSTRAINT PK_DIM_CNVRTD_FRM PRIMARY KEY (CONVERTED_FROM_DIM_ID)
    );


