CREATE TABLE IF NOT EXISTS ETL.SMART_BENF_PLAN_PROG_L (
	BEN_PLAN_PROG_ID VARCHAR(50) NOT NULL CONSTRAINT PK_BEN_PLAN_PROG_ID PRIMARY KEY,
	BENEFIT_PLAN_ID VARCHAR(50) NOT NULL,
	BENEFIT_PROGRAM_ID VARCHAR(50) NOT NULL,
	START_DATE VARCHAR(35),
	END_DATE VARCHAR(35),
	HAS_EXPIRED VARCHAR(50),
	IS_ACTIVE VARCHAR(50),
	CREATED_ON VARCHAR(35),
	DELETED_BY VARCHAR(50),
	DELETED_ON VARCHAR(35),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	UPDATED_ON VARCHAR(35),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);