CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROCEDURE_MODIFIER_L (
MODIFIER_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROCEDURE_MODIFIER_DIM_ID PRIMARY KEY,
MODIFIER_CODE VARCHAR(3) NOT NULL CONSTRAINT UK_DIM_PROCEDURE_MODIFIER_MODIFIER_CODE UNIQUE,
PROCEDURE_MODIFIER_DESC VARCHAR(60),
ANESTHESIA_IND VARCHAR(1),
INFORMATIONAL_FLAG VARCHAR(1),
PROCEDURE_MODIFIER_EFF_DATE VARCHAR(35),
PROCEDURE_MODIFIER_TERM_DATE VARCHAR(35),
PRMO_REV_INP_OUTP_IND VARCHAR(1),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
FINANCIAL_FLAG VARCHAR(1)
);
