CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_PRIORAUTH_QUALIFIER_L (
    RX_PRIORAUTH_QUALIFIER_DIM_ID VARCHAR(50),
    RX_PRIOR_AUTH_QUALIFIER VARCHAR(3),
    RX_PRIOR_AUTH_QUALIFIER_DESC VARCHAR(40),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PKRX_PRIORAUTH_QUALIFIER_DIM_ID PRIMARY KEY (RX_PRIORAUTH_QUALIFIER_DIM_ID)
);
