CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_WHOLE_CLAIM_STATUS_L
    (
        WHOLE_CLAIM_STATUS_DIM_ID VARCHAR(50) NOT NULL,
        WHOLE_CLAIM_STATUS VARCHAR(1) NOT NULL,
        WHOLE_CLAIM_STATUS_DESC VARCHAR(20),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_DIM_WHLE_CLM_STS PRIMARY KEY (WHOLE_CLAIM_STATUS_DIM_ID)
    );
