CREATE TABLE IF NOT EXISTS ETL.EPIM_PROVIDER_IDENTIFIER_BY_NPI_L
(
EPIM_IDENTIFIER VARCHAR(255),
NPI VARCHAR(255),
HCP_HCO_INDICATOR VARCHAR(255),
IDENTIFIER VARCHAR(255),
IDENTIFIER_TYPE_CODE VARCHAR(255),
IDENTIFIER_SOURCE_SYSTEM_CODE VARCHAR(255),
IDENTIFIER_TYPE_CODE_TEXT VARCHAR(255),
IDENTIFIER_USE_CODE VARCHAR(255),
IDENTIFIER_CHARACTERISTIC_NAME VARCHAR(255),
IDENTIFIER_CHARACTERISTIC_VALUE VARCHAR(255),
PERIOD_START_DATE VARCHAR(255),
PERIOD_END_DATE VARCHAR(255),
ASSIGNER_ORGANIZATION_NAME VARCHAR(255),
ASSIGNER_ORGANIZATION_IDENTIFIER VARCHAR(255),
PROVIDER_ACTIVE_INDICATOR VARCHAR(255),
EPIM_LAST_UPDATED_DTTM VARCHAR(255),
AUDIT_CREATE_DATE VARCHAR(255)
);
