CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_CREDENTIAL_L (
PROV_CRED_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROVIDER_CREDENTIAL_DIM_ID PRIMARY KEY,
COMPANY_DIM_ID VARCHAR(50) NOT NULL,
PROV_DIM_ID VARCHAR(50) NOT NULL,
PROV_CRED_TYPE_DIM_ID VARCHAR(50) NOT NULL,
CRED_SEQ_NO VARCHAR(50) NOT NULL,
CRED_VALUE_1 VARCHAR(15),
CRED_VALUE_2 VARCHAR(50),
EFFECTIVE_DATE VARCHAR(35),
TERM_DATE VARCHAR(35),
CRED_STATE VARCHAR(2),
CRED_PAR_IND VARCHAR(2),
CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35) NOT NULL,
DW_UPDATE_DATETIME VARCHAR(35) NOT NULL,
CONSTRAINT UK_DIM_PROVIDER_CREDENTIAL_IDS_CONVERTED UNIQUE (COMPANY_DIM_ID,PROV_DIM_ID,PROV_CRED_TYPE_DIM_ID,CRED_SEQ_NO,CONVERTED_FROM_DIM_ID)
);
