CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_LINE_OF_BUSINESS_L (
	LINE_OF_BUSINESS_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_LINE_OF_BUSINESS_DIM_ID PRIMARY KEY,
	LINE_OF_BUSINESS VARCHAR(5) NOT NULL CONSTRAINT UK_DIM_LINE_OF_BUSINESS_BUSINESS UNIQUE,
	LINE_OF_BUSINESS_DESC VARCHAR(30),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	LINE_OF_BUSINESS_TYPE_DIM_ID VARCHAR(50),
	RECORD_STATUS_DIM_ID VARCHAR(50)
);
