CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_REASON_CODE_L
(
        REASON_DIM_ID VARCHAR(50) NOT NULL,
        REASON_CODE VARCHAR(12) NOT NULL,
        REASON_CODE_TYPE VARCHAR(2) NOT NULL,
        COMPANY_DIM_ID VARCHAR(50) NOT NULL,
        REASON_DESC VARCHAR(60),
        REASON_STANDARD_FLAG VARCHAR(1),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        REASON_GROUP_DIM_ID VARCHAR(50) NOT NULL,
        CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
        REASON_CODE_TYPE_DIM_ID VARCHAR(50) NOT NULL,
        CONSTRAINT PK_RSN_CD PRIMARY KEY (REASON_DIM_ID),
        CONSTRAINT UK_DIM_RSN_CD UNIQUE (REASON_CODE, REASON_CODE_TYPE,
        COMPANY_DIM_ID, CONVERTED_FROM_DIM_ID)
    );
