CREATE TABLE IF NOT EXISTS ETL.EDW_TB_CUS_GRP_L (
	GRP_SYS_ID VARCHAR(10) NOT NULL,
	ACCT_SYS_ID VARCHAR(10) NULL,
	GRP_NM VARCHAR(128) NULL,
	GRP_TMLN_EFF_DTTM VARCHAR(26) NULL,
	GRP_TMLN_EXPIR_DTTM VARCHAR(26) NULL,
	SRC_REC_CRT_DTTM VARCHAR(26) NULL,
	SRC_REC_UPDT_DTTM VARCHAR(26) NULL,
	SRC_REC_CRT_USER_ID VARCHAR(15) NULL,
	SRC_REC_UPDT_USER_ID VARCHAR(15) NULL,
	REC_CRT_DTTM VARCHAR(26) NULL,
	REC_UPDT_DTTM VARCHAR(26) NULL,
	REC_XTRCT_SRC_CD VARCHAR(4) NULL,
	REC_INPUT_SRC_CD VARCHAR(4) NULL,
	BTCH_LOAD_DT VARCHAR(26) NULL,
	CONSTRAINT PK_TB_CUS_GRP PRIMARY KEY (GRP_SYS_ID)
);
