CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_SPECIALTY_L (
PROV_DIM_ID VARCHAR(50) NOT NULL,
PRIMARY_SPECIALTY_FLAG VARCHAR(1),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
PROV_SPEC_DIM_ID VARCHAR(50) NOT NULL,
CONSTRAINT PK_DIM_PROVIDER_SPECIALTY_DIM_ID PRIMARY KEY (PROV_DIM_ID,PROV_SPEC_DIM_ID)
);


