CREATE TABLE IF NOT EXISTS ETL.EDW_TB_AMA_POS_L(
	POS_SYS_ID VARCHAR(10) NOT NULL,
	POS_ID varchar(2) NULL,
	POS_DESC varchar(50) NULL,
	POS_DERIV_CATGY varchar(64) NULL,
	SRC_REC_USER_ID varchar(15) NULL,
	REC_DEL_FLG varchar(1) NULL,
	REC_CRT_DTTM VARCHAR(26) NOT NULL,
	REC_UPD_DTTM VARCHAR(26) NOT NULL,
	REC_XTRCT_SRC_CD varchar(4) NOT NULL,
	REC_INPUT_SRC_CD varchar(4) NOT NULL,
	BTCH_LOAD_DT VARCHAR(26) NOT NULL,
	CONSTRAINT TB_AMA_POS_SYS PRIMARY KEY(POS_SYS_ID)
);