CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_DATE_YEAR_L (
    YEAR_DIM_ID VARCHAR(50) NOT NULL,
	YEAR_NBR VARCHAR(50),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	YEAR_BEGIN_DATE VARCHAR(35),
	YEAR_END_DATE VARCHAR(35),
	CURR_YEAR_IND VARCHAR(50),
	CONSTRAINT PK_SMART_DIM_DATE_YEAR_ETL PRIMARY KEY (YEAR_DIM_ID)
);
