CREATE TABLE IF NOT EXISTS ETL.EPIM_PROVIDER_QUALIFICATION_L
(
EPIM_IDENTIFIER VARCHAR(255),
HCP_HCO_INDICATOR VARCHAR(255),
NPI VARCHAR(255),
QUALIFICATION_CODE VARCHAR(255),
QUALIFICATION_CODE_TEXT VARCHAR(255),
EPIM_LAST_UPDATED_DTTM VARCHAR(255),
AUDIT_CREATE_DATE VARCHAR(255)
);
