CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_IDENT_L (
PROV_DIM_ID VARCHAR(50) NOT NULL,
IDENT_TYPE_DIM_ID VARCHAR(50) NOT NULL,
IDENT_VALUE VARCHAR(100) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
CONSTRAINT PK_DIM_PROVIDER_IDENT_DIM_ID PRIMARY KEY (PROV_DIM_ID,IDENT_TYPE_DIM_ID)
);

