CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_GL_TAG_L (
	GL_TAG_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_GL_TAG_DIM_ID PRIMARY KEY,
	GL_TAG_CODE VARCHAR(6),
	GL_TAG_DESC VARCHAR(25),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);
