CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_PLAN_QUALIFIER_CODE_L (
    PLAN_QUALIFIER_CODE_DIM_ID VARCHAR(50),
    PLAN_QUALIFIER_CODE VARCHAR(10),
    PLAN_QUALIFIER_CODE_DESC VARCHAR(50),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_PLAN_QUALIFIER_CODE_DIM_ID PRIMARY KEY (PLAN_QUALIFIER_CODE_DIM_ID)
);
