CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_PRODUCT_QUALIFIER_L (
    RX_PRODUCT_QUALIFIER_DIM_ID VARCHAR(50),
    RX_PRODUCT_ID_QUALIFIER VARCHAR(3),
    RX_PRODUCT_ID_QUALIFIER_DESC VARCHAR(30),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_RX_PRODUCT_QUALIFIER_DIM_IDRIMARY PRIMARY KEY (RX_PRODUCT_QUALIFIER_DIM_ID)
);
