CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_DISPENSE_AS_WRITTEN_L (
    DISPENSE_AS_WRITTEN_DIM_ID VARCHAR(50),
    DISPENSE_AS_WRITTEN	VARCHAR(3),
    DISPENSE_AS_WRITTEN_DESC VARCHAR(65),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_DISPENSE_AS_WRITTEN_DIM_ID PRIMARY KEY (DISPENSE_AS_WRITTEN_DIM_ID)
);
