CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROV_ADDR_INFO_L (
PROV_ADDR_INFO_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROV_ADDR_INFO_DIM_ID PRIMARY KEY,
COMPANY_DIM_ID VARCHAR(50) NOT NULL,
PROV_DIM_ID VARCHAR(50) NOT NULL,
PROV_ADDR_DIM_ID VARCHAR(50) NOT NULL,
PROV_ADDR_ID VARCHAR(12) NOT NULL,
PROV_ADDR_SUB_ID VARCHAR(3) NOT NULL,
EFFECTIVE_DATE VARCHAR(35) NOT NULL,
INFO_CODE_TYPE_DIM_ID VARCHAR(50) NOT NULL,
INFO_CODE_DIM_ID VARCHAR(50) NOT NULL,
INFO_VALUE VARCHAR(100),
CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35) NOT NULL,
DW_UPDATE_DATETIME VARCHAR(35) NOT NULL,
CONSTRAINT UK_DIM_PROV_ADDR_INFO_DIM_IDS_EFFECTIVE UNIQUE (COMPANY_DIM_ID,PROV_DIM_ID,PROV_ADDR_ID,PROV_ADDR_SUB_ID,EFFECTIVE_DATE,INFO_CODE_TYPE_DIM_ID,INFO_CODE_DIM_ID,CONVERTED_FROM_DIM_ID)
);

