CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CLASS_PLAN_L (
CLASS_PLAN_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_CLASS_PLAN_DIM_ID PRIMARY KEY,
CLASS_PLAN_ID VARCHAR(10) NOT NULL CONSTRAINT UK_DIM_CLASS_PLAN_CLASS_PLAN_ID UNIQUE,
CLASS_PLAN_DESC VARCHAR(70) NOT NULL,
DW_INSERT_DATETIME VARCHAR(35) NOT NULL,
DW_UPDATE_DATETIME VARCHAR(35) NOT NULL

);
