CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_AHFS_THER_CLASS_CODE_L (
	AHFS_THER_CLASS_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_AHFS_THER_CLASS_CODE_DIM_ID PRIMARY KEY,
	AHFS_THER_CLASS_CODE VARCHAR(8) CONSTRAINT UK_DIM_AHFS_THER_CLASS_CODE_CLASS_CODE UNIQUE,
	AHFS_THER_CLASS_DESC VARCHAR(100),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);
