CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PRODUCT_L (
PRODUCT_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PRODUCT_DIM_ID PRIMARY KEY,
PRODUCT_CODE VARCHAR(7) NOT NULL CONSTRAINT UK_DIM_PRODUCT_PRODUCT_CODE UNIQUE,
PRODUCT_DESC VARCHAR(35),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);
