-- ECT_DEV_OBH_DP_DB.ETL.DBA_ERROR_LOG definition

CREATE OR REPLACE TABLE ETL.DBA_ERROR_LOG (
	ERROR_CODE NUMBER(38,0),
	PROC_NAME VARCHAR(128),
	ERROR_STATE VARCHAR(128),
	ERROR_MESSAGE VARCHAR(2000),
	STACKTRACE VARCHAR(2000),
	ERROR_DATETIME TIMESTAMP_NTZ(9)
);
