CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_IO_FLAG_L (
IO_FLAG_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_IO_FLAG_DIM_ID PRIMARY KEY,
IO_FLAG_DESC  VARCHAR(30),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35)
);

