CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_CLIENT_TYPE_L (
    RX_CLIENT_TYPE_DIM_ID VARCHAR(50),
    RX_CLIENT_TYPE VARCHAR(3),
    RX_CLINET_TYPE_DESC VARCHAR(40),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_RX_CLIENT_TYPE_DIM_ID PRIMARY KEY (RX_CLIENT_TYPE_DIM_ID)
);
