CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_COMPANY_L (
COMPANY_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_COMPANY_DIM_ID PRIMARY KEY,
COMPANY_CODE VARCHAR(5) NOT NULL CONSTRAINT UK_DIM_COMPANY_COMPANY_CODE UNIQUE,
COMPANY_DESC VARCHAR(30),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
CORPORATE_DIM_ID VARCHAR(50),
DIVISION_DIM_ID VARCHAR(50),
REGION_DIM_ID VARCHAR(50),
GEOGRAPHY_STATE_DIM_ID VARCHAR(50),
RECORD_STATUS_DIM_ID VARCHAR(50)
);
