CREATE TABLE IF NOT EXISTS ETL.EPIM_PROVIDER_SANCTIONS_L
(
EPIM_IDENTIFIER VARCHAR(255),
HCP_HCO_INDICATOR VARCHAR(255),
NPI VARCHAR(255),
SANCTION_IDENTIFIER_VALUE VARCHAR(255),
SANCTION_IDENTIFIER_USE_CODE VARCHAR(255),
SANCTION_IDENTIFIER_TYPE_CODE VARCHAR(255),
SANCTION_IDENTIFIER_PERIOD_END_DATE VARCHAR(255),
SANCTION_IDENTIFIER_PERIOD_START_DATE VARCHAR(255),
SANCTION_ASSIGNER_NAME VARCHAR(255),
SANCTION_PERIOD_START_DATE VARCHAR(255),
SANCTION_PERIOD_END_DATE VARCHAR(255),
SANCTION_EXCLUSION_TYPE VARCHAR(255),
SANCTION_EXCLUSION_STATE VARCHAR(255),
SANCTION_SUBJECT_ID VARCHAR(255),
SANCTION_RESOURCE_TYPE VARCHAR(255),
SANCTION_WAIVER_INDICATOR VARCHAR(255),
EPIM_LAST_UPDATED_DTTM VARCHAR(255),
AUDIT_CREATE_DATE VARCHAR(255)
);
