CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_CLAIM_STATUS_L (
CLAIM_STATUS_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_CLAIM_STATUS_DIM_ID PRIMARY KEY,
CLAIM_STATUS VARCHAR(1) NOT NULL CONSTRAINT UK_DIM_CLAIM_STATUS_CLAIM_STATUS UNIQUE,
CLAIM_STATUS_DESC VARCHAR(30),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
CLAIM_STATUS_TYPE_DIM_ID VARCHAR(50) NOT NULL,
CLAIM_STATUS_TYPE VARCHAR(1) NOT NULL,
CLAIM_STATUS_TYPE_DESC VARCHAR(20)
);

