CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PLACE_OF_SVC_L (
PLACE_OF_SVC_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PLACE_OF_SVC_DIM_ID PRIMARY KEY,
PLACE_OF_SVC_CODE VARCHAR(6) NOT NULL CONSTRAINT UK_DIM_PLACE_OF_SVC_PLACE_OF_SVC_CODE UNIQUE,
PLACE_OF_SVC_DESC VARCHAR(60),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
PLACE_OF_SVC_SUMM_CD VARCHAR(1) NOT NULL
);
