CREATE TABLE IF NOT EXISTS ETL.SMART_INTERNAL_PROGRAM_REASON_L (
	PROGRAM_REASON_ID VARCHAR(50) NOT NULL CONSTRAINT PK_INTERNAL_PROG_REASON_ID PRIMARY KEY,
	REASON_DESCRIPTION VARCHAR(5000),
	PROGRAM_STATUS_ID VARCHAR(50),
	CREATED_ON VARCHAR(35),
	CREATED_BY VARCHAR(50),
	IS_ACTIVE VARCHAR(50),
	DELETED_BY VARCHAR(50),
	DELETED_ON VARCHAR(35),
	UPDATED_BY VARCHAR(50),
	UPDATED_ON VARCHAR(35),
	REASON_TYPE VARCHAR(100),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35)
);