CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RATECELL_CATEGORY_L
(
        RTCL_CATEGORY_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_RTCL_CATEGORY_DIM_ID PRIMARY KEY,
        RTCL_CATEGORY_CODE VARCHAR(10),
        RTCL_CATEGORY_DESC VARCHAR(50),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35)
);
