CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_GPI_L (
    RX_GPI_DIM_ID VARCHAR(50),
    GPI VARCHAR(30),
    GPI_DESC VARCHAR(100),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_RX_GPI_DIM_ID PRIMARY KEY (RX_GPI_DIM_ID)
);
