CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_REASON_CODE_GROUP_L
    (
        REASON_GROUP_DIM_ID VARCHAR(35) NOT NULL,
        REASON_GROUP_CODE VARCHAR(10),
        REASON_GROUP_TYPE VARCHAR(2),
        REASON_CODE_GROUP_DESC VARCHAR(30),
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
        CONSTRAINT PK_DIM_RSN_CD_GRP_DIM_ID PRIMARY KEY (REASON_GROUP_DIM_ID),
        CONSTRAINT UK_RSN_CD_GRP_CD_GRP_TYP UNIQUE (REASON_GROUP_CODE, REASON_GROUP_TYPE)
    );
