CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_REFILL_CODE_L (
    REFILL_CODE_DIM_ID VARCHAR(50),
    REFILL_CODE VARCHAR(3),
    REFILL_CODE_DESC VARCHAR(30),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_REFILL_CODE_DIM_ID PRIMARY KEY (REFILL_CODE_DIM_ID)
);
