CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROV_AGREEMENT_L (
	PROV_AGREEMENT_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROV_AGREEMENT_DIM_ID PRIMARY KEY,
	PROV_AGREEMENT_ID VARCHAR(20),
	EFFECTIVE_DATE VARCHAR(35),
	TERM_DATE VARCHAR(35),
	AGREEMENT_DESC VARCHAR(70),
	AGREEMENT_TYPE VARCHAR(4),
	DW_INSERT_DATETIME VARCHAR(35) NOT NULL,
	DW_UPDATE_DATETIME VARCHAR(35) NOT NULL,
	RECORD_STATUS_DIM_ID VARCHAR(50) NOT NULL,
	CONSTRAINT UK_DIM_PROV_AGREEMENT_AGREEMENT_ID_EFFECTIVE_DATE UNIQUE (PROV_AGREEMENT_ID,EFFECTIVE_DATE)
);
