CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_RX_PAYMENT_TYPE_L (
    PAYMENT_TYPE_DIM_ID VARCHAR(50),
    PAYMENT_TYPE VARCHAR(3),
    PAYMENT_TYPE_DESC VARCHAR(30),
    DW_INSERT_DATETIME VARCHAR(35),
    DW_UPDATE_DATETIME VARCHAR(35),
    CONSTRAINT PK_PAYMENT_TYPE_DIM_ID PRIMARY KEY (PAYMENT_TYPE_DIM_ID)
);
