CREATE TABLE IF NOT EXISTS
    ETL.SMART_DIM_ETHNIC_CODE_L
    (
        ETHNIC_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_ETHNIC_DIM_ID PRIMARY KEY,
        ETHNIC_CODE VARCHAR(10) NOT NULL,
        ETHNIC_CODE_DESC VARCHAR(100),
        CONVERTED_FROM_DIM_ID VARCHAR(50) NOT NULL,
        DW_INSERT_DATETIME VARCHAR(35),
        DW_UPDATE_DATETIME VARCHAR(35),
      CONSTRAINT UK_DIM_ETHNIC_CODE_CONVERTED_FROM UNIQUE (ETHNIC_CODE, CONVERTED_FROM_DIM_ID)
    );