CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_PROVIDER_CONTRACT_L (
CONTRACT_DIM_ID VARCHAR(50) NOT NULL CONSTRAINT PK_DIM_PROVIDER_CONTRACT_DIM_ID PRIMARY KEY,
PROV_DIM_ID VARCHAR(50) NOT NULL,
SEQ_PROV_CONTRACT VARCHAR(50) NOT NULL,
CONTRACT_TYPE VARCHAR(1) NOT NULL,
PROV_CONTRACT_LINE_OF_BUSINESS  VARCHAR(5),
PANEL_ID  VARCHAR(5),
PROV_CONTRACT_EFFECTIVE_DATE VARCHAR(35) NOT NULL,
PROV_CONTRACT_TERM_DATE VARCHAR(35),
TERM_REASON  VARCHAR(5),
PCP_FLAG VARCHAR(1),
TAX_ID  VARCHAR(15),
DW_INSERT_DATETIME VARCHAR(35),
DW_UPDATE_DATETIME VARCHAR(35),
VEND_DIM_ID VARCHAR(50) NOT NULL,
CONTRACT_TYPE_DIM_ID VARCHAR(50) NOT NULL,
CONTRACT_TYPE_DESC  VARCHAR(20),
CONT_LINE_OF_BUSINESS_DIM_ID VARCHAR(50) NOT NULL,
PROVIDER_PAR_DIM_ID VARCHAR(50) NOT NULL,
PROV_CONTRACT_ID  VARCHAR(40),
NETWORK_DIM_ID VARCHAR(50) NOT NULL,
CONVERTED_FROM_DIM_ID VARCHAR(50),
RECORD_STATUS_DIM_ID VARCHAR(50),
ACC_NEW_PAT_IND  VARCHAR(1),
PROV_AGREEMENT_DIM_ID VARCHAR(50) NOT NULL,
CONSTRAINT UK_DIM_PROVIDER_CONTRACT_DIM_ID_SEQ_CONTRACT UNIQUE (PROV_DIM_ID,SEQ_PROV_CONTRACT)
);


