CREATE TABLE IF NOT EXISTS ETL.SMART_DIM_SDA_L (
    SDA_DIM_ID VARCHAR(50) NOT NULL,
	SDA_CODE VARCHAR(100),
	SDA_DESC VARCHAR(100),
	COMPANY_DIM_ID VARCHAR(50),
	DW_INSERT_DATETIME VARCHAR(35),
	DW_UPDATE_DATETIME VARCHAR(35),
	CONVERTED_FROM_DIM_ID VARCHAR(50),
CONSTRAINT PK_SMART_DIM_SDA_ETL PRIMARY KEY (SDA_DIM_ID)
);
