CREATE  OR REPLACE PROCEDURE ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_FCT_CLM_TRANS_HIS_LOAD_PROC()
RETURNS VARCHAR
LANGUAGE javascript
COMMENT='Loads the data to intermediate OCM_FCT_CLM_TRANS FOUNDATION table from OCM tables'
EXECUTE as caller
AS
$$

var sql_OCM_FCT_CLM_TRANS_trunc_command = "DELETE FROM ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_FCT_CLM_TRANS";

var sql_OCM_FCT_CLM_TRANS_insert_command = "INSERT INTO ECT_DEV_OBH_DP_DB.FOUNDATION.OCM_FCT_CLM_TRANS(CLM_TRANS_SYS_ID,CLM_AUD_LN_NBR,CLM_AUD_NBR,CLM_TRANS_ALLW_AMT,CLM_TRANS_COINS_AMT,CLM_TRANS_COPAY_AMT,CLM_TRANS_DED_AMT,CLM_TRANS_DSCNT_AMT,CLM_TRANS_MBR_RESP_AMT,CLM_TRANS_PD_AMT,CLM_TRANS_UNIT_CNT,CLM_TRANS_SBMT_AMT) SELECT DISTINCT SRVCLN.DW_CLM_SRVC_LN_REC_ID, CASE WHEN LENGTH(SRVCLN.CLM_SRVC_LN_ID)=1 THEN CONCAT('00', SRVCLN.CLM_SRVC_LN_ID) WHEN LENGTH(SRVCLN.CLM_SRVC_LN_ID)=2 THEN CONCAT('0', SRVCLN.CLM_SRVC_LN_ID) ELSE SRVCLN.CLM_SRVC_LN_ID END,SPLIT_PART(SRVCLN.CLM_TRANS_ID, ':' , 2), SRVCLN.ALLW_LN_AMT, SRVCLN.BEN_COINS_LN_AMT, SRVCLN.BEN_COPAY_LN_AMT, SRVCLN.DED_LN_AMT, SRVCLN.DSCNT_LN_AMT, SRVCLN.MBR_RESP_LN_AMT, SRVCLN.NET_PD_LN_AMT,SRVCLN.SRVC_UNIT_CNT, TRANS.TOT_BIL_CHRG_AMT FROM ECT_DEV_CLAIMS_DB.FOUNDATION.DW_CLM_SRVC_LN AS SRVCLN INNER JOIN ECT_DEV_CLAIMS_DB.FOUNDATION.DW_CLM_TRANS AS TRANS ON SRVCLN.CLM_TRANS_ID = TRANS.CLM_TRANS_ID WHERE SRVCLN.CLM_SRC_SYS_CD='COS'";

try {
snowflake.execute (
          {sqlText: sql_OCM_FCT_CLM_TRANS_trunc_command}
    );
snowflake.execute (
          {sqlText: sql_OCM_FCT_CLM_TRANS_insert_command}
    );
return "Succeeded.";   // Return a success/error indicator.
}
catch (err)  {
  return "Failed: " + err;   // Return a success/error indicator.
}

$$;
