CREATE TABLE IF NOT EXISTS OBH_DP.PHRM_DRG_CLM CLUSTER BY (LEFT(PHRM_DRG_CLM_SYS_ID,7))(
	PHRM_DRG_CLM_SYS_ID VARCHAR(100) DEFAULT '-1' NOT NULL CONSTRAINT PK_PHRM_DRG_CLM_SYS_ID PRIMARY KEY comment 'Drug Claim System Identifier: Data warehouse system generated key',
	PHRM_COPAY_AMT NUMBER(10,2) NULL comment 'Copay Amount: The fixed amount the member pays for a specific service as defined in their benefit plan.',
	PHRM_DED_AMT NUMBER(10,2) NULL comment 'The set amount a member pays for services until they reach a specified limit (usually defined on an annual basis). After the limit is reached, the member payment for services changes (often insurance pays 100% of the cost of services).',
	PHRM_DSPNS_FEE_AMT NUMBER(10,2) NULL comment 'Dispensing Fee Amount: Amount the pharmacy charged to fill the prescription.',
	PHRM_INGR_CST_AMT NUMBER(10,2) NULL comment 'Ingredient Cost Amount: Ingredient cost of the drug.',
	PHRM_PD_AMT NUMBER(10,2) NULL comment 'Paid Amount: The amount the pharmacy is reimbursed. Also referred to as the net amount.',
	PHRM_CHK_DT date NULL comment 'Check Date: Part of the unique natural key that identifies the claim. The date that appears on the check for claims payment.',
	PHRM_FILL_DT date NULL comment 'Fill Date: Date the prescription was filled by the pharmacy.',
	PHRM_DAY_SPL_CNT NUMBER NULL comment 'Days Supply Count: Estimated number of days the drug supply should last for the patient if taken as prescribed.',
	PHRM_DSPNS_AS_WRT_CD char(1) NULL comment 'Dispense as Written Code: Identifies if a prescription was filled as written or altered by Pharmacy, Physician or Member.',
	PHRM_NDC_CD varchar(60) NULL comment 'NDC Code: The unique code that identifies a drug product as defined by the National Drug Data File (all drug products regulated by the FDA must use an NDC).',
	PHRM_FST_FILL_IND_CD char(1) NULL comment 'First Fill Indicator Code: Indicates if this is the first time a prescription is being filled. N=No U=Unknown Y=Yes',
	PHRM_FRMLRY_IND_CD char(1) NULL comment 'Formulary Indicator Code: Indicates if the drug being dispensed is on the formulary list or not. N=No Space=Unknown Y=Yes',
	PHRM_FRMLRY_TYP_CD varchar(10) NULL comment 'Formulary Type Code: Type of formulary used to pay a claim. For example, open, closed, etc.',
	PHRM_FRMLRY_TYP_DESC varchar(60) NULL comment 'Formulary Type Code Desc: Describes Type of formulary used to pay a claim. For example, open, closed, etc.',
	PHRM_MAIL_ORDR_IND_CD char(1) NULL comment 'Mail Order Indicator Code: Indicates if the type of pharmacy utilized to fill the prescription was Mail Order. (N=No, Y=Yes, U=Unknown)',
	PHRM_PRSC_RFL_NBR varchar(3) NULL comment 'Prescription Refill Number: Indicates if this is the first, second, or subsequent refill for the prescription.',
	PHRM_QTY_CNT NUMBER(13,3) NULL comment 'Quantity Count: Quantity of drug dispensed in metric units.',
	PHRM_IN_NTWK_CD char(1) NULL comment 'Pharmacy In Network Indicator Code: Indicates if the prescription was filled by a contracted pharmacy. Y=Yes, N=No, U=Unknown',
	PHRM_NBR varchar(24) NULL comment 'May be the NABP Number. A number assigned by the National Council for Prescription Drug Programs (NCPDP) to uniquely identify a pharmacy. Or, could be an ID defined by the client/submitter that uniquely identifies a provider in the source system.',
	PHRM_NPI_PROV_ID varchar(10) NULL comment 'A number assigned to uniquely identify a pharmacy. May be used in place of the NABP Number.',
	PHRM_PRSC_NPI_PROV_ID varchar(10) NULL comment 'This is the unique NPI number assigned to the prescribing physician.',
	PHRM_PROV_DEA_NBR varchar(25) NULL comment 'Provider DEA Number: An identifier assigned by Federal DEA (Drug Enforcement Agency) to a physician, authorizing him/her to prescribe medications. The first two positions are alpha and the last 9 positions are numeric.',
	PHRM_ACCT_ID varchar(24) NULL comment 'An Rx Solutions value within Carrier Id that is a further break down of the PacifiCare business into various categories such as by state or funding or other breakdown.',
	PHRM_CARR_ID varchar(24) NULL comment 'An Rx Solutions value that identifies the various PacifiCare businesses that they process claims for.',
	PHRM_COB_CD VARCHAR(3) NULL comment 'Indicates what type of other insurance the member has.',
	PHRM_COB_DESC VARCHAR(60) NULL comment 'Describes what type of other insurance the member has.',
	PHRM_DRG_CLM_ALT_ID varchar(100) NOT NULL comment 'Provider Alternate Identifier: system id or natual (business) id which can identify a provider in a specific source.',
	MBR_ALT_ID varchar(50) NULL comment 'EDW concatenate of source natural member columns to create member key',
	PROV_ALT_ID varchar(24) NULL comment 'EDW concatenate of source natural provider columns to create provider key',
	CUST_SEG_NBR varchar(20) NULL comment 'Galaxy Customer Segment Number: The number assigned to an entity that has purchased products and/or services from UHG. For COSMOS this equates to Site + Group.',
	TRAN_CD varchar(2) NULL comment 'For Pharmacy Claims only, Transaction Code is part of the claim natural key, when the value is populated.',
	SRC_REC_CD varchar(8) NULL comment 'The source code representing the initial input system for a given record.',
	REC_CRT_DT date NULL comment 'The create date of a record into the table.',
	REC_UPD_DT date NULL comment 'The update date of a record into the table.',
	MBR_BTH_DT date NULL comment 'The member or claimant date of birth',
	MBR_FST_NM varchar(50) NULL comment 'The member or claimant first name',
	MBR_LST_NM varchar(50) NULL comment 'The member or claimant last name',
	MBR_ZIP_CD varchar(5) NULL comment 'The claimant or member 5-digit US Postal ZIP Code.',
	PHRM_AUTH_RFL_CNT NUMBER NULL comment 'The number of authorized refills for the prescribing physician.',
	PHRM_PRSCN_WRT_DT date NULL comment 'Date the provider wrote the prescription. Default Value: 1/1/1900',
	SBSCR_NBR varchar(20) NULL comment 'The source system subscriber number.',
        MEDCD_ID VARCHAR(20) NULL COMMENT 'Identifier assigned by CMS for a individual enrolled in Community & State [C&S] coverage.',
	MEDCR_ID VARCHAR(20) NULL COMMENT 'Identifier assigned by CMS for a individual enrolled in Medicare & Retirement [M&R] coverage.',
	MBR_GDR_CD varchar(1) NULL comment 'A code identifying the sex of the member.',
	PHRM_DIAG_CD varchar(25) NULL comment 'IDC-9 (International Classification of Disease, 9th Revision, Clinical Modication) as entered on the claim (without NUMBER point). IDC-9-CM is designed for the classification of morbidity and mortality information for statistical purposes and for the indexing of hospital records by disease and operations, for data storage retrieval. ID-9-CM is an accepted national standard for coding diagnostic and disease information.',
	PHRM_PRSC_NBR varchar(15) NULL comment 'Prescription Number: The number assigned to the prescription by the supplying vendor or the provider prescribing number.',
	SRC_DRG_CLM_TYP VARCHAR(30) NULL comment 'Describes the DRUG Claim type, values include PHARM, DENTAL, UBH-RX, N/A and UNK.',
	DERIV_OBH_FINC_LIAB VARCHAR(5) NULL comment 'When the claim is behavioral finance paid then it is True else False.',
	SRC_CUST_CD VARCHAR(5) NULL comment 'Represents the UHC Community and State Company created codes for every plan used in the Data Warehouse.',
	SRC_CUST_NM VARCHAR(30) NULL comment 'Represents the long description of the UHC Community and State Company created codes.',
	SRC_MBR_ID VARCHAR(12) NULL comment 'the Unique identifier like Diamond_id for the individual assgined within a sourceSystem like SMART. This field is used to tie all member records for the same individual together irrespective of the source system or line of business.',
	IMDM_ID VARCHAR(12) DEFAULT '-1' NOT NULL comment 'This is the unique identifier [EID] assigned to the individual/member in the enterprise individual master data management [IMDM] system.',
	PHRM_PRSC_EPIM_PROV_ID VARCHAR(255) DEFAULT '-1' NOT NULL comment 'This is the unique identifier assigned to the prescribing physician in the enterprise provider identity management [EPIM] system.',
	PERS_SYS_ID VARCHAR(100) NOT NULL DEFAULT '-1' COMMENT 'Person System Identifier: Data warehouse system generated key',
	PHRM_EPIM_PROV_ID VARCHAR(255) COMMENT 'Identifier assigned by the Enterprise Provider Identity Management [EPIM] to the Pharmacy/Facility that issued the Drug',
	PHRM_DEA_EPIM_PROV_ID VARCHAR(255) COMMENT 'Identifier assigned by the Enterprise Provider Identity Management [EPIM] to the Provider that prescribed the Drug based on DEA',							
	OBH_SCR_RL_LST VARIANT NULL comment 'Contains the list of security tags for the ROW_LEVEL Security.',
	CLM_SRC_MBR_ACCT_NBR VARCHAR(30) NULL comment 'ClientAccountNumber(forFacetsandPBHthisistheGroupID)',
    CLM_TRANS_SBMT_AMT NUMBER(18,2) NULL comment 'The dollar amount the provider requested to be reimbursed for the service they provided. This amount is what was entered into the source system and is also referred to as the claimed amount or the source charge amount.',
    CLM_TRANS_THER_CLASS_DESC VARCHAR(100) NULL comment 'Description for therapeutic classification. i.e. Brand name in NDC table = Tylenol Cold and Flu Severe, SPEC description is NON - Narc Antitus - 1st Gen anthist-Decon-Analges, AHFS description is Antitussives, GNRC description is Cough/Cold preparations, Medco description is Decongestant/Antihistamines and STD description is Cold and Cough preparations.',
    CLM_TRANS_PRDCT_TYP_DESC VARCHAR(8) NULL comment 'A text description rollup of plan benefits, such as: Commercial, Medicare, Medicaid. Valid Values: Commercial, Medicaid, Medicare, U. Default Values: U',
 	SF_INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP NOT NULL comment 'Indicates the timestamp when the record was inserted the record in Snowflake. Defaulted to Current timestamp',
	SF_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP NOT NULL comment 'Indicates the timestamp when the record was updated the record in Snowflake. Defaulted to Current timestamp',
	SF_PROCESS_ID VARCHAR(36) comment 'Identifies the process which inserted/updated the record in Snowflake.'
) COMMENT ='Drug Claim: This table contains pharmacy claims for specific types of drugs that are identified as psychotropic drugs.The list of drugs selected for this table is based on Therapuetic Class, or individual NDC code.  A separate user table is defined for identifying which therapuetic classes and/or NDC codes should be selected for inclusion in this table.';
