CREATE OR REPLACE MATERIALIZED VIEW NORTHSTAR.NS_MEMBER_DATATABLE_MATERIALIZED_VIEW AS
SELECT *
FROM NORTHSTAR.NS_MEMBER_DATATABLE
WHERE (CARE_COORDINATOR_FIRST_NAME IS NOT NULL AND CARE_COORDINATOR_LAST_NAME IS NOT NULL AND
       CARE_COORDINATOR_EMAIL IS NOT NULL AND CARE_COORDINATOR_PHONE IS NOT NULL)
  AND UPPER(ACCOUNTABLE_ENTITY) = 'CARE NAVIGATION'
  AND UPPER(AE_PROGRAM_STATUS) != 'CLOSED'
  AND UPPER(SEGMENTATION) = 'HIGH ACUITY';