CREATE TABLE IF NOT EXISTS NORTHSTAR.NS_AE_DATA_EXTRACTION
(
MEM_BENF_PROG_ID VARCHAR(50),
ALTRUISTA_ID VARCHAR(50),
LOB  VARCHAR(18),
BENEFIT_PLAN VARCHAR(30),
PROGRAM_NAME VARCHAR(34),
START_DATE DATE,
END_DATE DATE,
PROGRAM_REFERRAL_SOURCE VARCHAR(50),
PROGRAM_STATUS VARCHAR(50),
PROGRAM_STATUS_DESC VARCHAR(100),
create_dttm DATE
);