CREATE TABLE IF NOT EXISTS NORTHSTAR.CONFIG_LMT_LOBS(
STATE VARCHAR(2),
STATE_DIM_ID NUMBER(38,0),
LOB_DIM_ID NUMBER(38,0),
Plan_IPRO VARCHAR(10),
PLAN_DESC VARCHAR(100),
DETAILS VARCHAR(100),
AGE NUMBER(3,0),
FLAG VARCHAR(1)
);
